pkg/component/component.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/odo/cli/preference/set.go, pkg/odo/cli/preference/unset.go, pkg/odo/cli/preference/view.go, pkg/preference/machine_output.go, pkg/preference/preference.go, pkg/preference/preference_test.go, tests/integration/generic_test.go
/kind feature
Fixes part of #3110 as per @mik-dass https://github.com/openshift/odo/issues/2877#issuecomment-627821138 
CI should not fail with build timeout error
=> Expose oc build timeout in preference

README.adoc
Signed-off-by: Yana Hontyk <yhontyk@redhat.com>
[skip ci]
Updates broken URLs in the README
=> Update URLs. [skip ci]

docs/public/secure-registry.adoc
/area devfile
This PR is secure registry docs includes:
- Introduction to secure registry
- Steps for adding secure registry
Related issue: https://github.com/openshift/odo/issues/2893
=> Docs: secure registry docs

scripts/openshiftci-presubmit-all-tests.sh
Debugging the failure on 4.5 cluster multistage test infra.
Debugging purpose.
Fixes NA
NA
=> Enabling verbose only for Integration test

tests/integration/devfile/cmd_devfile_url_test.go
/kind bug
Fixes the project creation failure for devfile url test
Fixes #3603 
project should get created on kubernetes as well as openshift.
=> Fixing project create on both kubernetes and openshift for devfile url test

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
/kind feature
Release 1.2.4
N/A
N/A
N/A
=> Release 1.2.4

rpms/openshift-odo.spec
/kind bug
Our internal release system requires all the following variables /
information in the spec in order to do a s390x release. This if
statement has been removed so we may be correctly build our internal
build.
N/A
N/A
N/A
=> Fix building RPM

rpms/openshift-odo.spec
/kind bug
Package name in our internal git repository / brew is changed from
openshift-odo to just `odo`
N/A
N/A
N/A
=> Fix package name

pkg/util/util.go, pkg/util/util_test.go
during debug, found it's hard to know which folder is really empty or has files
add those logs to help further debug/development
=> Add more logs when the folder is not empty

tests/integration/devfile/cmd_devfile_create_test.go
/kind cleanup
Just customise and remove duplicate tests.
Fixes - Part of #3385 
`make test-cmd-devfile-create` should run successfully.
=> Customise and cleanup create test

Makefile, docs/dev/test-architecture-s390x.adoc, scripts/configure-installer-tests-cluster-s390x.sh, scripts/openshiftci-presubmit-all-tests.sh
Enable upstream CI on s390x arch.
Fixes #2876 
We setup OCP on IBM Z. For every PR, we download the code from upstream and run the scripts/openshiftci-presubmit-all-tests.sh to trigger CI tests.
=> CI support for IBM Z

tests/integration/devfile/cmd_devfile_debug_test.go
/kind cleanup
$SUBJECT
Fixes - Part of #3385
Run `make test-cmd-devfile-debug` should pass.
=> Clean up and customise debug test

pkg/odo/cli/component/create.go
show project download info at UI
Fixes #3508 
`odo create  --starter nodejs`
=> show project download info at UI

pkg/devfile/parser/data/2.0.0/devfileJsonSchema200.go, pkg/devfile/parser/data/2.0.0/types.go, tests/examples/source/devfiles/nodejs/devfile-with-debugrun.yaml, tests/examples/source/devfiles/nodejs/devfile-with-invalid-volmount.yaml, tests/examples/source/devfiles/nodejs/devfile-with-multiple-defaults.yaml, tests/examples/source/devfiles/nodejs/devfile-with-post-start.yaml, tests/examples/source/devfiles/nodejs/devfile-with-volume-components.yaml, tests/examples/source/devfiles/nodejs/devfile-with-volumes.yaml, tests/examples/source/devfiles/nodejs/devfile-without-devbuild.yaml, tests/examples/source/devfiles/nodejs/devfile-without-devinit.yaml, tests/examples/source/devfiles/nodejs/devfile.yaml, tests/examples/source/devfiles/nodejs/devfileCompositeCommands.yaml, tests/examples/source/devfiles/nodejs/devfileCompositeCommandsParallel.yaml, tests/examples/source/devfiles/nodejs/devfileCompositeNonExistent.yaml, tests/examples/source/devfiles/nodejs/devfileCompositeRun.yaml, tests/examples/source/devfiles/nodejs/devfileNestedCompCommands.yaml, tests/examples/source/devfiles/nodejs/devfileSourceMapping.yaml, tests/examples/source/devfiles/openliberty/devfile-with-multi-layer-parent.yaml, tests/examples/source/devfiles/springboot/devfile-with-metadataname-foobar.yaml, tests/examples/source/devfiles/springboot/devfile.yaml, tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/docker/cmd_docker_devfile_push_test.go, tests/integration/devfile/utils/utils.go
/kind feature
Update devfile schema to unblock some issues.
New in Schema: Apply, endpoint changes, starter project, description of volume mounts are new changes in the schema.
This PR updates the schema and go structs here pkg/devfile/parser/data/2.0.0/types.go, we are not using go structs from here Directly we consume from pkg/devfile/parser/data/common/types.go, issue stakeholders can update corresponding struct  accordingly.
Fixes #?
=> Update devfile schema

docs/proposals/file-sync-location.md
/kind design
Adds a design proposal doc for modifying the file sync location functionality in odo, as we decided on last Thursday's meeting to do that first. 
See https://github.com/openshift/odo/issues/3494 and https://github.com/openshift/odo/issues/3581 for some background
N/A 
N/A
=> Add proposal for updating the file sync location

tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/integration/devfile/cmd_devfile_push_test.go
/kind bug
Fixes GetPVCSize(). 
Fixes NA
All the tests should pass.
=> Fixes GetPVCSize() for the cli helpers.

index.md
Updates the asciinema demo on the index page
=> Updates asciinema demo

pkg/util/util.go
> /kind bug
> /kind design
/kind flake
>
> [skip ci]
There is an increase of timeouts in our CIs due to slow networking (either on CI side, or GitHub side).
This increases timeout to work around that.
Fixes https://github.com/openshift/odo/issues/3667
=> increase ResponseHeaderTimeout

pkg/devfile/adapters/common/utils.go
/kind feature
Updates to 1.1.5 odo-init-image.
N/A
N/A
N/A
=> Update to 1.1.5 image

docs/public/installing-odo.adoc
[skip ci]
Adds installation documentation rather than using the downstream
documentation from https://docs.openshift.com/container-platform/4.5/cli_reference/developer_cli_odo/installing-odo.html
N/A
N/A
N/A
=> Add installation documentation

chosen-docs/openshift-docs/configuring-the-odo-cli.md, chosen-docs/openshift-docs/creating-a-multicomponent-application-with-odo.md, chosen-docs/openshift-docs/creating-a-single-component-application-with-odo.md, chosen-docs/openshift-docs/creating-an-application-with-a-database.md, chosen-docs/openshift-docs/debugging-applications-in-odo.md, chosen-docs/openshift-docs/managing-environment-variables-in-odo.md, chosen-docs/openshift-docs/odo-architecture.md, chosen-docs/openshift-docs/odo-cli-reference.md, chosen-docs/openshift-docs/understanding-odo.md, chosen-docs/openshift-docs/using-sample-applications.md, chosen-docs/upstream/deploying-a-devfile-using-odo.md, docs/configuring-the-odo-cli.md, docs/creating-a-multicomponent-application-with-odo.md, docs/creating-a-single-component-application-with-odo.md, docs/creating-an-application-with-a-database.md, docs/debugging-applications-in-odo.md, docs/deploying-a-devfile-using-odo.md, docs/managing-environment-variables-in-odo.md, docs/odo-architecture.md, docs/odo-cli-reference.md, docs/understanding-odo.md, docs/using-sample-applications.md
=> Update grid navigation

Makefile, pkg/devfile/adapters/docker/component/utils.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/utils/utils.go, pkg/devfile/parser/context/schema.go, pkg/odo/cli/component/delete.go, pkg/odo/cli/service/create.go, tests/integration/cmd_url_test.go
Update golangci-lint to latest version and fix some linting errors.
Small code simplification
=> Update golangci-lint to latest version and fix some linting errors

pkg/util/util.go, pkg/util/util_test.go
/kind bug
Fixes issues with unzipping files on Windows
Fixes #3296 
- `odo create nodejs --downloadSource` 
- Verify that the project is cloned in current dir and not under a dir like `odo-devfiles-nodejs-ex-*`
- This should be tested on Windows and non-Windows platforms.
=> Fix project unzip function on Windows

index.md
Unfortunately the last one was archived. So had to update it.
=> Update asciinema recording

.travis.yml
https://github.com/openshift/odo/issues/3714
=> Remove docker tests

tests/integration/project/cmd_project_test.go
missing test
Adding missing flag integration test coverage for project command
Fixes NA
```make test-cmd-project```
=> Get only project name

.travis.yml
/kind cleanup
#3714
Fixes NA
No docker test target should run on travis CI
=> Docker test target clean up

tests/integration/devfile/cmd_devfile_catalog_test.go
/kind cleanup
Removes the duplicates from test script
Fixes - Part of #3385
`make test-cmd-devfile-catalog` should pass.
=> Removing duplicates from devfile catalog test

index.md
Updates the index page to include information regarding not just
OpenShift but Kubernetes too
=> Updates the index page to include info regarding k8s

docs/configuring-the-odo-cli.md, docs/creating-a-multicomponent-application-with-odo.md, docs/creating-a-single-component-application-with-odo.md, docs/creating-an-application-with-a-database.md, docs/debugging-applications-in-odo.md, docs/installing-odo.md, docs/managing-environment-variables-in-odo.md, docs/odo-cli-reference.md, docs/using-sample-applications.md
Syncs the documentation against the current master documents
=> Sync documenation against master

pkg/odo/cli/project/get.go, tests/integration/project/cmd_project_test.go
/kind design
Fixes #?
`odo project get -o json`
=> Add json format output to project get

.github/PULL_REQUEST_TEMPLATE.md, docs/dev/test-architecture.adoc, tests/template/template_cleantest_test.go
Proper test guidelines has been updated and also linked to the PR template
Fixes #3687 
=> Test guidelines updated to write proper tests and avoid duplicates

docs/creating-a-multicomponent-application-with-odo.md, docs/creating-an-application-with-a-database.md
[skip ci]
Fixes https://github.com/openshift/odo/issues/3707
=> wrong commands in the odo.dev docs

docs/public/understanding-odo.adoc
[skip ci]
update documents for s390x arch support.
Fixes #3725 
=> Update documents for s390x arch.

scripts/configure-installer-tests-cluster-s390x.sh
/kind bug
/kind feature
Make the same change with PR #3737 
=> Applying secret to namespace for authenticated registry for s390x

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bumping odo version to 1.2.5 -> 1.2.6

tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/cmd_devfile_test_test.go
=> consolidated some integration tests

docs/file-reference/index.md
[skip ci]
Update devfile reference index for starter projects
Fixes #?
=> Update doc for starter project

pkg/devfile/adapters/common/command_simple.go, pkg/devfile/adapters/common/command_supervisor.go, pkg/devfile/adapters/common/generic.go, pkg/devfile/adapters/common/types.go, pkg/devfile/adapters/common/utils.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/parser/context/schema_test.go, pkg/devfile/parser/data/2.0.0/devfileJsonSchema200.go, pkg/devfile/parser/data/2.0.0/types.go, pkg/devfile/parser/data/common/types.go, tests/examples/source/devfiles/nodejs/devfile-with-hotReload.yaml, tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/utils/utils.go
/kind feature
Adds Support for `hotReloadCapable` field, it is a replacement of attribute `restart:false`.
This PR also fixes a bug while switching mode from debug to run.
Fixes #3548 
Fixes #3784
=> Add support for hot reload commands

pkg/devfile/adapters/common/utils.go, pkg/devfile/adapters/common/utils_test.go, pkg/odo/cli/storage/create.go, pkg/odo/cli/storage/list.go, pkg/odo/cli/storage/list_test.go, pkg/storage/storage.go, pkg/storage/storage_test.go, pkg/storage/types.go, pkg/testingutil/containers.go, pkg/testingutil/devfile.go, pkg/testingutil/pods.go, tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/cmd_devfile_storage_test.go
/kind feature
It adds `odo storage list` command for devfile volumes
Fixes #3704 
TBA
=> Adds list command of storage for devfile v2

scripts/configure-installer-tests-cluster-ppc64le.sh
/kind bug
/kind feature
Make the same change with PR #3737 and PR #3802 
=> Applying secret to namespace for authenticated registry for ppc64le

pkg/kclient/deployments.go, pkg/kclient/pods.go, pkg/occlient/occlient.go
/kind flake
Log Deployment and Pod status.
This will make it easier to debug issues like 
https://github.com/openshift/odo/issues/3256
https://github.com/openshift/odo/issues/2877
Because we will see a  reason why Deployment or Pod is failing
=> Logging of Deployment and Pod statuses

tests/integration/generic_test.go
/kind bug
Fix the failed integration/generic testcase for "when executing odo version command"
Fixes #3757 
=> Update regex for OdoVersion in integration/generic test.

pkg/devfile/parser/context/context.go, pkg/devfile/parser/writer.go, pkg/occlient/utils.go, pkg/odo/cli/utils/convert.go, pkg/sync/adapter.go, tests/integration/component.go
/kind feature
s2i to devfile conversion test was dependent on odo-init-image release, the image containing required changes has been released, I missed to enable the integration test.
Fixes #?
=> Enable integration test for s2i to devfile conversion

.travis.yml
/kind feature
/kind flake
To analyze flake #3731. Changes are done as per the request - https://github.com/openshift/odo/issues/3731#issuecomment-684787903
Fixes NA, this pr will add memory information in travis log. We need to merge this into master so that flake #3731 next occurrence will be analyze with more inputs.
VM memory information should be printed in travis log
=> Add debug to analyze flake on travis CI

docs/creating-a-multicomponent-application-with-odo.md, docs/creating-a-single-component-application-with-odo.md, docs/creating-an-application-with-a-database.md, docs/debugging-applications-in-odo.md, docs/deploying-a-devfile-using-odo.md, docs/operator-hub.md, docs/understanding-odo.md, file-reference/index.html, slate/source/index.html.md
Synchronizes the documentation
=> Synchronize documentation against the site

tests/integration/devfile/cmd_devfile_push_test.go
=> Fix test failure caused by updating springboot devfile

docs/public/community.adoc, docs/public/deploying-a-devfile-using-odo.adoc, docs/public/operator-hub.adoc
[skip ci]
Signed-off-by: Yana Hontyk <yhontyk@redhat.com>
[skip ci]
Small docs bugfixes.  
Fixes https://github.com/openshift/odo/issues/3868
=> Update commands ouputs in docs.

docs/public/installing-odo.adoc
[skip ci]
Updates the installation page to showcase the beta
N/A
=> Update installation page to indicate beta-1

tests/examples/source/devfiles/springboot/devfile-with-metadataname-foobar.yaml, tests/examples/source/devfiles/springboot/devfile.yaml, tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/utils/utils.go
=> Update springboot devfile

docs/odo-cli-reference.md
[skip ci]
Update the CLI reference.
Fixes https://github.com/openshift/odo/issues/3870
=> Update CLI reference.

docs/file-reference/index.md, docs/public/debugging-using-devfile.adoc, docs/public/using-devfile-lifecycle-events.adoc
Updates docs to use the new schema changes for components and commands
Fixes #3925
Check if all the docs are updated to the new schema.
=> Updates docs to use the new schema changes for commands and components

docs/public/s2i-to-devfile.adoc
[skip ci]
Document to convert s2i to devfile components.
Fixes #3749
=> Document for s2i to devfile conversion

chosen-docs/upstream/debugging-using-devfile.md, docs/community.md, docs/debugging-using-devfile.md, docs/deploying-a-devfile-using-odo.md, docs/odo-cli-reference.md, file-reference/index.html, index.md, slate/source/index.html.md
Updates the debugging documentation to point to devfile debugging rather
than the current downstream OpenShift doc.
=> Synchronize documentation / debuging doc

chosen-docs/upstream/s2i-to-devfile.md, docs/s2i-to-devfile.md, index.md
Adds s2i to devfile doc to website
=> Add s2i to devfile documentation to website

chosen-docs/upstream/deploying-a-devfile-using-odo.md, index.md
Updates the front page index cards of the odo.dev site
=> Update index cards

docs/public/installing-odo.adoc
[skip ci]
- Adds instructions on how to install the VSCode Plugin
- Remove references to old version of odo
Closes https://github.com/openshift/odo/issues/3970
=> Add instructions on how to install VSCode plugin

pkg/devfile/parser/context/apiVersion_test.go
/kind cleanup
Migrate api-version test to devfileV2
Fixes #3794 
=> apiVersion test migrated to devfileV2

docs/deploying-a-devfile-using-odo.md, docs/installing-odo.md
Updates the documentation on the main site / synchronizes
=> Synchronize site documentation

docs/blog/template.md
[skip ci]
This is a preliminary change in order to get a blog directory added /
blog posts out
N/A
N/A
=> Adds a blog folder

Dockerfile.rhel, scripts/rpm-prepare.sh
/kind feature
Release 2.0.0 of odo
N/A
N/A
N/A
=> Release 2.0.0

scripts/configure-installer-tests-cluster-s390x.sh
/kind bug
Make the same change with #3939 
=> Update s2i image for the library change on s390x plaftorm.

README.adoc
[skip ci]
Updates the README with an updated asciinema showing Devfile not S2I.
N/A
N/A
=> Update asciinema on the README

docs/file-reference/index.md
Signed-off-by: Maysun J Faisal <maysunaneek@gmail.com>
[skip ci]
- updates the index doc with the master changes
- fixed broken links
Fixes N/A
=> Index Doc Update - Volume, Composite Cmd

rpms/openshift-odo.spec
> /kind bug
> /kind design
> /kind flake
>
> [skip ci]
Fixes #?
=> Fixing issues with RPMS

docs/blog/2020-09-24-odo-200-ga-release.md
[skip ci]
Adds a blog post which will go live on September 23rd regarding the
2.0.0 release.
N/A
N/A
=> Add blog post regarding 2.0.0 GA release

docs/public/debugging-using-devfile.adoc
[skip ci]
Updates the debugging documentation with more information with example
output as well as a link to VSCode debugging tools
Closes https://github.com/openshift/odo/issues/3971
=> Update the debugging documentation

docs/blog/2020-09-24-odo-200-ga-release.md, docs/public/installing-odo.adoc
[skip ci]
- Updates the installation page so that includes links to the latest
install
- Updates the blog post (minor issue with headline)
N/A
N/A
=> Update the installation page and blog

_posts/2020-09-24-odo-200-ga-release.md, docs/community.md, docs/creating-a-single-component-application-with-odo.md, docs/debugging-using-devfile.md, docs/installing-odo.md, docs/odo-cli-reference.md, docs/operator-hub.md, file-reference/index.html, scripts/sync.sh, slate/source/index.html.md
Synchronizes the site and publishes the blog / updated installation page
=> Synchronizes the site + publishes the blog

_config.yml
Very minor change to the index page / title of odo.dev
=> Minor change to index title

docs/public/operator-hub.adoc
[skip ci]
Before this fix, everything below "Installing an Operator" looked like
its child on odo.dev website. This commit fixes it.
Fixes NA (fixed based on what I observed on odo.dev website)
=> Fixes sections in Opreator Hub documentation

docs/public/installing-odo.adoc
[skip ci]
Since the odo CI on Z for master has passed for all covered tests, The latest version installation should be added to doc for users of odo on IBM Z.
Fixes #3913 
=> Update doc to support installation on IBM Z for the latest version.[skip ci]

docs/public/installing-odo.adoc
[skip ci]
Since the odo CI on Power for master has passed for all covered tests, The latest version installation should be added to doc for users of odo on IBM Power. Similar to PR #4040 
Fixes #?
=> Update doc to support installation on IBM Power for the latest version.[skip ci]

docs/public/using-storage.adoc
It adds a document about the usage of storage commands.
Fixes #3761
Check if the document is correct, clear and easy to understand.
=> Adds a document regarding the usage of storage commands.

README.md, default.md
Updates and adds documentation on how to deploy something to the site.
=> Add instructons on how to edit / deploy something using the site

README.md
=> Link error

scripts/configure-installer-tests-cluster-s390x.sh
/kind bug
There is configured imagestreams for s390x arch . Since the library has updates the files, we need to update it to work well.
Fixes #?
=> Update configure-installer-tests-cluster-s390x.sh script to import right imagestream for tests.

chosen-docs/upstream/secure-registry.md, chosen-docs/upstream/using-devfile-lifecycle-events.md, chosen-docs/upstream/using-storage.md, docs/creating-a-multicomponent-application-with-odo.md, docs/odo-architecture.md, docs/secure-registry.md, docs/using-devfile-lifecycle-events.md, docs/using-storage.md, index.md
=> Add secure registry, storage and lifecycle docs

_posts/2020-09-24-odo-200-ga-release.md
[skip ci]
It removes the extra i in front of https.
=> Fix link to Devfile documentation

docs/public/secure-registry.adoc
[skip ci]
Updates the documentation to align with other docs such as "deploying a
devfile using odo".
This document had a few spelling / grammar errors as well as incorrect
headlines being used / steps.
N/A
N/A
=> Update secure registry documentation

README.md, site-readme.txt
Adds instructions on how to tarball the site when doing a release.
=> Add instructions on tarballing the site

Dockerfile.rhel, openshift-ci/build-root/Dockerfile, openshift-ci/build-root/Dockerfile.travislogin, scripts/rpm-prepare.sh
> [skip ci]
Currently the prow is failing, seems like golang 1.13 was deprecated.
=> Updating golang version to 1.15

README.adoc, docs/public/community.adoc
[skip ci]
Adds updated documentation to the README and Community pages with
regards to the new Slack channel.
N/A
N/A
N/A
=> Add links to new Kubernetes Slack

Dockerfile.rhel, openshift-ci/build-root/Dockerfile, openshift-ci/build-root/Dockerfile.travislogin, scripts/rpm-prepare.sh
=> Revert "Updating golang version to 1.15"

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
/kind feature
Releases 2.0.1 of odo
N/A
N/A
N/A
=> Release 2.0.1 of odo

docs/blog/2020-09-24-odo-200-ga-release.md, docs/blog/2020-10-28-odo-201-release.md
[skip ci]
Adds 2.0.1 changelog blog post
N/A
N/A
N/A
=> Add 2.0.1 changelog blog post

docs/blog/2020-10-28-odo-201-release.md
[skip ci]
Publishes 2.0.1 blog post immediately
Fixes #?
=> Publish blog post

README.md, _posts/2020-10-28-odo-201-release.md, docs/community.md, docs/deploying-a-devfile-using-odo.md, docs/s2i-to-devfile.md, docs/secure-registry.md
=> Publish new blog post + update README

docs/blog/2020-10-28-odo-201-release.md
[skip ci]
Fix incorrect markdown on the blog post
NA
=> Fix blog post

_posts/2020-10-28-odo-201-release.md
Updates a minor error in the blog documentation
=> Update blog again

docs/public/deploying-a-devfile-using-odo.adoc
[skip ci]
Fixes the heading
N/A
N/A
N/A
=> Changes headings for deploying your first devfile

docs/deploying-a-devfile-using-odo.md
=> Update the headings on devfile deploy page

docs/dev/development.adoc
[skip ci]
Updates the release notes
N/A
N/A
N/A
_Based on work of @cdrage _
=> Update release notes

scripts/configure-installer-tests-cluster-ppc64le.sh
/kind bug
To update the required s2i imagestream for nodejs and java application om IBM Power.
=> Update required s2i imagestreams for nodejs and java on IBM Power

README.adoc
[skip ci]
Add Roadmap in the readme
Fixes https://github.com/openshift/odo/issues/4083
=> Add Roadmap for the next 3 milestones in the Readme

scripts/openshiftci-periodic-tests.sh, scripts/openshiftci-presubmit-all-tests.sh, tests/e2escenarios/e2escenarios_suite_test.go, tests/helper/reporter/junitReporter.go, tests/integration/debug/debug_suite_test.go, tests/integration/devfile/debug/debug_suite_test.go, tests/integration/devfile/devfile_suite_test.go, tests/integration/devfile/docker/docker_suite_test.go, tests/integration/integration_suite_test.go, tests/integration/loginlogout/loginlogout_suite_test.go, tests/integration/project/project_suite_test.go, tests/integration/servicecatalog/servicecatalog_suite_test.go
/kind 
This PR will enable jUnit test report generation
Fixes #4137
=> Junit test report generation

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bumping odo version v2.0.1 -> v2.0.2

OWNERS
Add @kadel, @adisky & @mik-dass to owners
=> Add Tomas, Aditi and Mrinal to owners

docs/deploying-a-devfile-using-odo.md, docs/operator-hub.md
This PR adds OpenLiberty documentation added in #4119 and warning message added for Operator installation in #4282.
=> OpenLiberrty documentation and Operator installation warning

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bumping odo version v2.0.2 -> v2.0.3

chosen-docs/upstream/install-service-binding-operator.md, docs/configuring-the-odo-cli.md, docs/creating-a-multicomponent-application-with-odo.md, docs/creating-a-single-component-application-with-odo.md, docs/creating-an-application-with-a-database.md, docs/install-service-binding-operator.md, docs/odo-architecture.md, docs/operator-hub.md, docs/operators-on-minikube.md, index.md
[skip ci]
[skip ci]
Syncs the documentation for odo.dev website
Fixes NA
=> More documentation on Operators and small fixes

index.md
=> Fix incorrect link for Operators on minikube

docs/install-service-binding-operator.md
=> Update docs to install SBO from OperatorHub.io

pkg/component/component.go
Modifies block comment to reflect what the code actually does. Issue #2847 does mention to code repetition but it's not exactly the same code, both blocks iterate over different object so merging them implies some work currently not necessary.
Fixes #2847
=> Changed block comment to reflect what the code actually does.

pkg/kclient/kclient.go, pkg/odo/cli/component/common_link.go, pkg/odo/cli/component/link.go, pkg/odo/cli/component/unlink.go, pkg/odo/cli/service/create.go
/kind bug
Remove isResourceSupported call from command intialization
Fixes #4046 
- Disconnect with the openshift/k8s cluster
- Run any odo command without changes 
- Run any odo command with  applying this PR
Observe the significant time difference between the output returned by odo
=> Fix odo hang when cluster is unreachable 

docs/installing-odo.md
=> Update installing odo on Windows section

OWNERS
/kind cleanup
Remove Aditi from gh-pages
=> remove aditi from gh-pages

OWNERS, pkg/devfile/OWNERS
=> Removes Aditi from the OWNERS files

tests/integration/operatorhub/cmd_service_test.go
It separates an edge case of tests into its own spec.
Fixes #4301
Test should pass. Especially for #4063.
=> Separates test into its own spec

scripts/configure-cluster/common/auth.sh, scripts/configure-cluster/common/kubeconfigandadmin.sh, scripts/configure-cluster/common/kubeconfigreset.sh, scripts/configure-cluster/common/test-htpasswd, scripts/configure-installer-tests-cluster-ppc64le.sh, scripts/configure-installer-tests-cluster-s390x.sh, scripts/configure-installer-tests-cluster.sh
/kind code-refactor
This is the second phase of the refactor of the configure the cluster. Again. Nothing the flow should be broken
=> Configure-installer script refactor part 2

pkg/envinfo/envinfo.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/delete.go, tests/integration/devfile/cmd_devfile_delete_test.go
> /kind bug
Fixes https://github.com/openshift/odo/issues/4262
=> set UserCreatedDevfile: true in envInfo and check on delete --all

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bumping odo version from v2.0.3 to v2.0.4

docs/dev/development.adoc
> [skip ci]
we dont necessarily need to clone odo in GOPATH so changing that
No issue
=> removing information on mandate to clone go in GOPATH

scripts/configure-installer-tests-cluster-s390x.sh
> /kind bug
This removes the getting secret step for my project .
Fixes #?
=> Remove the unused step in configure-installer-tests-cluster-s390x.sh.

scripts/openshiftci-periodic-tests.sh, scripts/openshiftci-presubmit-all-tests.sh, scripts/openshiftci-presubmit-unittests.sh
/kind bug
**What does does this PR do / why we need it**: This will fix the report generation on periodic jobs 
Fixes #?
=> $ARTIFACTS_DIR  is set by platform

scripts/openshiftci-e2e-4x-psi-tests.sh
The script will be updated in the prow psi poc pr
after openshift ci prow config has been updated with
new job for psi
=> Adding psi prow script placeholder.

docs/public/deploying-a-devfile-using-odo.adoc
[skip ci]
Though this is real basic, getting started info it doesn't include the most basic steps required for having odo leverage the ingress on a basic kubernetes setup like minikube.   
=> Elaborate on minikube, ingress, nip.io setup

docs/dev/development.adoc
The PR mainly fixes the release script `bump-version.sh` link.
Fixes #?
=> Fix release script link

docs/debugging-applications-in-odo.md, docs/deploying-a-devfile-using-odo.md, docs/operator-hub.md
Updates the site odo.dev based on recent changes to docs in the master branch.
Fixes NA
=> Updates to 'odo watch' and Operator docs

tests/e2escenarios/e2e_images_test.go
Unblock CI and fix the failure https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-odo-master-v4.5-integration-e2e-periodic/1358928787923800064#1:build-log.txt%3A779 
Fixes 
`make test-e2e-images` should pass
=> Fixing wrong project passed to the component

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
=> Buming odo version for release

OWNERS
Adds @valaparthvi to reviewers of odo.
=> Adds Parthvi to reviewers of odo

docs/public/install-service-binding-operator.adoc
**What does  this PR do / why we need it**:
This PR documents how to enable OLM on Kubernetes (minikube and otherwise). 
Fixes #? NA
=> Document how to enable OLM on Kubernetes

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bumping odo version v2.0.5 -> v2.0.6

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
This is to get a fix to an important issue that was fixed recently
=> Bumping version to v2.0.7

pkg/devfile/convert/convert.go, pkg/odo/cli/utils/convert.go
Refactoring convert code so it can be used outside utils package. This helps towards https://github.com/openshift/odo/issues/4281
partly https://github.com/openshift/odo/issues/4281
everything should work the same
=> Refactoring convert code so it can be used outside utils package

pkg/odo/cli/component/create.go, tests/integration/devfile/cmd_devfile_create_test.go
/kind bug
see $SUBJECT
Fixes https://github.com/openshift/odo/issues/4354
```
odo create nodejs <- this should fail now, before it wasn't
```
=> fixed odo create allowed  to run multiple times in same dir

docs/public/deploying-java-app-with-database.adoc, docs/public/installing-and-onfiguring-minikube-environment.adoc
[skip ci]
Adds Java+DB on minikube guide to docs, based on @dharmit doc https://github.com/dharmit/application-stack-samples/blob/minikube-readme/jpa/README-minikube.md 
Fixes https://github.com/openshift/odo/issues/4116
I edited the original doc slightly to match the general structure of the docs and made a few changes to the style/wording.
=> Java+DB docs [skip ci]

chosen-docs/upstream/deploying-java-app-with-database.md, chosen-docs/upstream/install-service-binding-operator.md, chosen-docs/upstream/installing-and-onfiguring-minikube-environment.md, docs/deploying-java-app-with-database.md, docs/install-service-binding-operator.md, docs/installing-and-onfiguring-minikube-environment.md, docs/odo-cli-reference.md, index.md
Updates the odo.dev website to use latest updates to the documentation 
Fixes NA
=> Add docs for java+database example

tests/integration/devfile/utils/utils.go
/kind cleanup
Fixes #https://github.com/openshift/odo/pull/4521#discussion_r595946977
- Tests should pass.
=> Removes occurrence of docker from utils.go

scripts/minici-presubmit-all-tests.sh, scripts/minikube-minishift-all-tests.sh, scripts/minikube-minishift-setup-env.sh
/kind bug
Temporary fix for https://github.com/openshift/odo/issues/4523
Fixes #?
kuberenetes job should not be blocked on parameter thing
=> Passing minikube and minishift parameter using env

scripts/minici-presubmit-all-tests.sh, scripts/minikube-minishift-all-tests.sh, scripts/minikube-minishift-setup-env.sh
Add quotes to arguments to ci-firewall request to ensure args are treaded as part of the script.
Fixes #4523 
=> Fixing argument issue on minikube and minishift psi tests

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bumping odo version v2.0.7 -> v2.0.8

pkg/segment/segment.go, pkg/segment/segment_test.go
This PR changes AnonymousId to UserID so that odo data can be synchronized with data from other projects.
Fixes #4571 
Send some data to Segment and check if `UserId` appears in the response.
=> Use UserId instead of AnonymousId while sending telemetry data

Makefile, pkg/segment/segment.go
=> Updating segment variable= dev key as default overrideable with ldflags

docs/public/install-service-binding-operator.adoc
Updates odo docs for SBO installation
Fixes #4559
=> Update documentation for SBO installation

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bumping odo version to v2.1.0

docs/creating-a-multicomponent-application-with-odo.md, docs/install-service-binding-operator.md, docs/odo-architecture.md, docs/sample-applications.md
Adds docs for SBO 0.6.0 installation and other minor fixes
Fixes NA
=> SBO 0.6.0 and minor fixes

scripts/minici-presubmit-all-tests.sh, scripts/minikube-minishift-setup-env.sh
Just updating current exchange flag value for minikube
Fixes #4287 
kubernetes test should run successfully.
=> Adding exchange for minikube and minishift

pkg/odo/cli/env/view.go, tests/integration/devfile/cmd_devfile_env_test.go
/kind bug
see SUBJECT
Fixes https://github.com/openshift/odo/issues/4574
=> add Application in the odo env view standard output

scripts/minici-presubmit-all-tests.sh
Upgrading ci-firewall to v0.1.1 so that it can use retryloop feature
Fixes #?
=> Upgrade ci-firewall version to v0.1.1

scripts/configure-cluster/common/auth.sh, scripts/configure-cluster/common/kubeconfigandadmin.sh
=> Adding inseucre skip to cluster configure commands

scripts/openshiftci-e2e-4x-psi-tests.sh
I wanted to run test on jenkins with latest ci-firewall version
Fixes part - #4606 
=> Upgrading ci-firewall version for linix

.github/ISSUE_TEMPLATE/UserStory.md
NA
It asks "Epic" information for creating a "User Story" because Epics are high level items that can have a bunch of User Stories. And Epics are what are tracked by Milestones. 
Fixes NA
=> Require "Epic" for a user story

scripts/minici-presubmit-all-tests.sh, scripts/openshiftci-e2e-4x-psi-tests.sh
=> Updating main-branch

OWNERS
$subject
Need it since Parthvi's contributing to the project for some time now and it would help if her PRs had "approved" label set automatically just like every other dev's PRs.
Fixes NA
=> Adds Parthvi to top level OWNERS

scripts/configure-installer-tests-cluster-ppc64le.sh, scripts/openshiftci-presubmit-all-tests.sh
To enable the operator-hub testing on Power architecture.
Fixes #?
This commits enable the operator-hub testing on Power architecture.
=> Enabling operator-hub test for Power.

docs/public/operator-hub.adoc, docs/public/operators-on-minikube.adoc
[skip ci]
Fixes broken relative links.  
Also updated link to old v0.3.0 SBO.  
@dharmit  not sure if we want to link to a specific newer one or just the homepage (which is what I did).
N/A
=> Adjust SBO link and fix broken relative links to other articles

OWNERS
=> Adds Parthvi to OWNERS of gh-pages branch

pkg/catalog/catalog.go, pkg/util/httpcache.go, pkg/util/httpcache_test.go
/kind bug
When there is an issue unmarshalling the github registry index, we invalidate the cache and retry.
Fixes https://github.com/openshift/odo/issues/4566
=> invalidate the cache if there is an error

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bumping odo version v2.1.0 -> v2.2.0

OWNERS
Changes in Makefile or `openshift/release` repo PR does not allow @prietyc123 to approve 
Fixes NA
=> Adds Priti to OWNERS

.github/PULL_REQUEST_TEMPLATE.md, Changelog.md
Documentation changes: Please include [skip ci] in your commit message as well
[skip ci]
We want to do manual changelog management for better release notes.
Action item in retro
=> Add changelog and github issue template

pkg/odo/cli/catalog/describe/interface.go, pkg/odo/cli/catalog/describe/operator_backend.go, pkg/odo/cli/catalog/describe/service.go, pkg/odo/cli/catalog/describe/service_catalog_backend.go, pkg/service/cr_description.go, tests/integration/operatorhub/cmd_service_test.go
/kind feature
see $SUBJECT
Fixes https://github.com/openshift/odo/issues/2615
Try 
```
odo catalog describe service etcdoperator.v0.9.4/EtcdCluster        
odo catalog describe service etcdoperator.v0.9.4/EtcdCluster -o json
```
=> odo catalog describe service for operators

docs/public/breaking-changes-in-odo-2.2.adoc
[skip ci]
see $SUBJECT
No issue
=> typo in breaking changes doc

docs/dev/development.adoc
[skip ci]
Fixes some minor typos in the development documentation
=> Fix some typos in development doc

scripts/openshiftci-e2e-4x-psi-tests.sh
This PR fixes CI-firewall requestor command in test script
=> fixing ci-firewall command

docs/public/operator-hub.adoc
[skip ci]
see $SUBJECT
No issue
Try the links
=> Resolve broken links in main doc

Makefile
[skip ci]
Add a `make help` command, extracting comments from Makefile (inspired by https://github.com/kubernetes/website/blob/master/Makefile)
N/A
=> Add make help

README.md, chosen-docs/upstream/breaking-changes-in-odo-2.2.md, docs/breaking-changes-in-odo-2.2.md, docs/operator-hub.md, docs/sample-applications.md, index.md
[skip ci]
see $SUBJECT
No issue
=> fix doc instruction readme, add some helpers and built breaking-changes-2.2 doc

scripts/openshiftci-e2e-4x-psi-tests.sh
/area testing
This PR updates script to use main branch for PSI tests
=> Update test script to use main branch for PSI test

docs/deploying-java-app-with-database.md
Updates docs to comply with changes related to `_` and `.`.
Fixes #?
=> Fix SB annotations (#4714)

tests/e2escenarios/e2e_devfile_test.go
This pr will avoid docker rate limit issue in e2e test. Explained https://github.com/openshift/odo/issues/4606#issuecomment-838232142
Fixes part - #4606
`make test-e2e-all` should run successfully on PSI
=> Remove devfile images needs image pull from docker

scripts/minici-presubmit-all-tests.sh, scripts/minikube-minishift-all-tests.sh, scripts/minikube-minishift-setup-env.sh
/kind feature
PRs will start running on long running minikube vm
Fixes partially #4675 
kubernetes job should run on long running VM, created on psi
=> Modify minikube script for long running cluster

tests/integration/cmd_pref_config_test.go
/kind cleanup
This PR cleans some duplicity from the code, fixes typo and makes tests verbose.
Fixes #?
=> Remove duplicity and make tests verbose

Changelog.md
[skip ci]
It updates the Changelog.md with the mention of PR https://github.com/openshift/odo/pull/4588.
Fixes NA
- Verify the change log file.
=> Updates the Changelog.md with the mention of PR https://github.com/openshift/odo/pull/4588

.gitignore, chosen-docs/upstream/using-devfile-odo.dev.push.path-attribute.md, docs/sample-applications.md, docs/using-devfile-odo.dev.push.path-attribute.md, index.md
=> Adds docs for dev.push.path attribute

pkg/util/util.go
/kind bug
TempDir created in case of subDir was not getting closed properly
due to missing close() action resulting in failure during whne we
attempted to delete anything in tmpdir. So close() is now added
with deference and code is wrapped in anonymous func to ensure
close() happens before deletion attempt.
Fixes #4727 
without permission denied error
On windows system
```bash
$ make bin
go build -mod=vendor -ldflags="-X github.com/openshift/odo/pkg/version.GITCOMMIT=3196871ac" cmd/odo/odo.go
$ mkdir prj
$ cd prj
$ cp -avrf …
```
=> Adding tempdir close defer to prevent unclosed tmpdir

chosen-docs/upstream/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.md, chosen-docs/upstream/deploying-a-devfile-using-odo.md, docs/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.md, docs/deploying-a-devfile-using-odo.md, docs/sample-applications.md, index.md
[skip ci]
To introduce how to use defiles on IBM Z & Power for clients.
=> Add doc to introduce how to use devfile on Z & Power.

tests/helper/helper_cli.go, tests/helper/helper_generic.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/integration/devfile/cmd_devfile_delete_test.go
=> Debug flaky test

README.adoc
remove travis-ci badge
[skip ci]
=> Update README.adoc - remove travis-ci badge

OWNERS, tests/OWNERS
@feloy is proving to be one of the most productive team members
=> add feloy as top-level approver and anandrkskd as reviewer and tests approver

.github/PULL_REQUEST_TEMPLATE.md, pkg/util/util.go
/kind cleanup
see $SUBJECT
Fixes https://github.com/openshift/odo/issues/4734
~~- [ ] Update changelog~~ 
=> remove [skip CI] from PR template

Changelog.md, pkg/service/service.go, tests/integration/operatorhub/cmd_service_test.go
=> odo push can deploy new services when some services are already deployed

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bumping odo version

Changelog.md
This PR adds information about important features, tests, documentation and bug fixes for the new release.
Fixes #?
=> Add changelogs

scripts/minici-presubmit-all-tests.sh, scripts/openshiftci-e2e-4x-psi-tests.sh
$SUBJECT
Fixes #?
Test should run fine on the latest version.
=> Updating CI Firewall version to v0.1.2

docs/public/operators-on-minikube.adoc
This PR fixes wrong URL and typos with the install-operator-on-minikube doc.
Fixes #4824
=> Fix URL and typos with install-operator-on-minikube doc

scripts/minikube-minishift-setup-env.sh
=> Fixing GOPATH and GOBIN in minikube and minishift scripts

pkg/odo/cli/catalog/describe/operator_backend.go, pkg/odo/cli/catalog/describe/service.go, pkg/service/types.go, tests/integration/operatorhub/cmd_service_test.go
/kind feature
see $SUBJECT
Fixes https://github.com/openshift/odo/issues/4796
Install an operator of your liking
```
odo catalog describe service postgresql-operator.v0.1.1/Database --example
apiVersion: postgresql.dev4devs.com/v1alpha1
kind: Database
metadata:
name: database
spec:
databaseCpu: 30m
databaseCpuLimit: 60m
databaseMemoryLimit: 512Mi
databaseMemoryRequest: 128Mi
databaseName: example
databaseNameKeyEnvVar: POSTGRESQL_DATABASE
databasePassword: postgres
databasePasswordKeyEnvVar: POSTGRESQL_PASSWORD
databaseStorageRequest: 1Gi
databaseUser: postgres
databaseUserKeyEnvVar: POSTGRESQL_USER …
```
=> odo catalog describe service <operator> --example

Makefile
Runs the Operator Hub integration tests in parallel and not serially, as it is not necessary anymore.
=> Run operator hub tests in parallel

tests/integration/operatorhub/cmd_service_test.go
- Remove two nesting levels in operatorhub integration tests
- Change all JustBeforeEach/JustAfterEach with BeforeEach/AfterEach
=> Remove nesting levels in operatorhub integration tests

tests/integration/cmd_app_test.go
Demo to refactor app integration tests
=> app tests refactored

Changelog.md
=> update changelog with `odo service create` feature changes

pkg/odo/cli/catalog/describe/operator_backend.go
/kind design
/area UX
>
> Documentation changes: CI will automatically skip test runs if it is a doc related change.
Currently the operators service parameters are listed as a long list of parameters.
<details>
<summary>old format</summary>
```
▶ odo catalog describe service postgresql-operator.v0.1.1/Database           
Kind: Database
Version: v1alpha1
Description: Database is the Schema for the the Database Database API
Parameters:
Path   Display
- Path: awsAccessKeyId
DisplayName: AWS S3 accessKey/token ID
Description: 'Key ID of AWS S3 storage. Default Value: nil Required to …
```
=> format service parameters as a table

pkg/util/file_indexer.go
Correct incorrect comment introduced in #2660
Fixes #4468
=> Correct ioutil.WriteFile comment about os.Create

pkg/application/application.go, pkg/application/doc.go, pkg/project/doc.go, pkg/project/project.go
=> Some doc on app / project packages

Makefile, tests/integration/project/cmd_project_test.go
Refactor tests in `project/cmd_project_test.go` file
=> Refactor project command tests

tests/integration/component.go
Refactoring of s2i component integration tests
=> Refactor component tests

docs/public/deploying-a-devfile-using-odo.adoc
[skip ci]
URL truncation was fixed slightly breaking the doc.
**NOTE:**  Probably will keep this as a draft until I can update it to account for:
https://github.com/openshift/odo/pull/4567
since that might change the output a bit.   Or maybe not but this is a reminder to think about that.
Follow through the https://odo.dev/docs/deploying-a-devfile-using-odo/#deploying-an-open-liberty-application-to-an-openshift--kubernetes-cluster  instructions on a minikube cluster.
=> Update URL in doc

tests/integration/cmd_storage_test.go
Refactor tests in tests/integration/cmd_storage_test.go  file
=> refactor cmd-storage test

Changelog.md
=> Fix Changelog

Changelog.md, Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bumping version of odo for release

pkg/kclient/fake/ingress.go, pkg/url/kubernetes_test.go, pkg/url/status_test.go, pkg/url/types.go, pkg/url/url.go, pkg/url/url_test.go
/kind task
See topic
Fixes #4865
unit tests in url package should not be broken
=> Migrating URL unit tests to use networking v1 ingress

Changelog.md, pkg/odo/cli/component/create.go, pkg/odo/cli/component/delete.go
/kind bug
This PR updates the help example for `odo create` and `odo delete`.
1. `odo create -h` is missing example for `--app` and `--project` and it should mention the use of `--s2i` flags for `--git` and `--binary` examples.
2. `odo delete -h` is missing a lot of examples.
Fixes #4903 
Run `odo create --help` and `odo delete --help` to see the difference.
```shell
➜  odo git:(main) ✗ odo delete --help
...
...
Examples:
odo delete
odo delete frontend
odo delete --all
odo delete --context ./frontend
odo delete --context ./frontend --all
odo delete frontend --app myapp --project …
```
=> Update component create and delete help examples

OWNERS, docs/OWNERS, pkg/debug/OWNERS, pkg/devfile/OWNERS
Used a one-liner while learning, so I'm not sure if it removes references from all places. Here's the one-liner I used:
```sh
$ find . -iname "*OWNERS*" -not -path "./vendor/*" | xargs sed -i '/girishramnani/d'
```
=> Removes Girish from OWNERS files

tests/integration/devfile/cmd_devfile_catalog_test.go, tests/integration/devfile/cmd_devfile_config_test.go
https://github.com/openshift/odo/issues/4741
=> Refactor devfile catalog and config integration tests

tests/integration/operatorhub/cmd_link_test.go
/kind bug
This test should pass when #4905  is merged and this PR is rebased on main
Fixes #4917 
=> Test storage + link

Changelog.md, scripts/configure-cluster/common/setup-operators.sh, scripts/openshiftci-Nightly-SBO-tests.sh
/kind feature
/area testing
Setup Operator script such that we run test nightly on SBO master and also CI script to trigger the job
Fixes part of -  #4942 
Fixes part of -  #4955 
`make test-operator-hub` should be setup to run on nightly
=> Nightly CI and Operator Setup script

Changelog.md, Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bumping odo version before release

website/package-lock.json, website/package.json
Ran `npm audit fix` as suggested by the npm tooling itself.
=> Updated npm modules for Dependabot warnings

Changelog.md
=> Adds missing # to a Changelog entry

.github/PULL_REQUEST_TEMPLATE.md
=> Updating pr template

Changelog.md, Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bumping odo version v2.2.4 -> v2.3.0

pkg/storage/kubernetes.go, pkg/storage/kubernetes_test.go, pkg/testingutil/deployments.go
/kind bug
/kind design
It uses the deployment while listing and storage from the cluster.
Fixes #4917 
- All tests should pass.
=> Uses the deployment while listing storage from the cluster

Changelog.md, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter_test.go, pkg/devfile/adapters/kubernetes/component/status_test.go, tests/helper/helper_cli.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/helper/helper_run.go, tests/integration/devfile/cmd_devfile_storage_test.go
/kind bug
It fixes the ephemeral storage mount issue.
Fixes NA
- Trigger `odo preference set ephemeral false -f`
- Create and push a odo component `odo create nodejs` and `odo push`
- Check the created deployment, the volume `odo-projects` should have a persistent volume claim which points to the newly created source pvc for the component.
=> Fixes ephemeral storage mount issue

tests/helper/helper_oc.go
/area testing
This PR fixes failure due to `1 min timeout` for IBMCloud  openshift cluster.
Fixes #5034
=> Increasing timeout from 1min to 5min for PodsShuouldBeRunning

scripts/openshiftci-e2e-4x-psi-tests_win_mac.sh, scripts/run_script_e2e.sh, scripts/setup_script_e2e.sh
/kind feature
This PR adds script to run tests on Ibm cloud 
Fixes - part of #4412
Fixes - part of #4408
=> add PSI and IBM cloud to the script for test

pkg/component/component_full_description.go
/kind bug
This PR fixes output of `odo describe --context /path`for windows
Fixes #? NA
=> fix Filepath to use / for odo describe --context /path for windows

pkg/odo/cli/service/create.go, pkg/odo/cli/service/delete.go, pkg/odo/cli/service/describe.go, pkg/odo/cli/service/interface.go, pkg/odo/cli/service/list_operator.go, pkg/odo/cli/service/list_operator_test.go, pkg/odo/cli/service/operator_backend.go, pkg/odo/cli/service/service.go, pkg/odo/cli/service/utils.go, tests/integration/operatorhub/cmd_service_test.go, website/docs/command-reference/json-output.md
/kind feature
- `odo service create -o json`
- `odo service decribe -o json`
- `odo service describe`
Fixes #2784
=> odo service create/describe -o json

scripts/openshiftci-e2e-4x-psi-tests_win_mac.sh, scripts/run_script_e2e.sh
/kind tests
This PR fixes the script for jobs for windows and mac
Fixes: N/A
=> resolve CI job script error

scripts/minici-presubmit-all-tests.sh
/kind tests
JOB_NAME for running tests in IBM Cloud Cluster was incorrect
Fixes #?
=> fixed JOB_NAME

pkg/odo/cli/component/create.go, tests/integration/devfile/cmd_devfile_create_test.go
=> Delete devfile when creation fails

docs/website/docs/using-odo/create-url.md, docs/website/docs/using-odo/url.md
$subject
Fixes part of #4895 
Doc preview at - https://deploy-preview-5191--odo-docusaurus-preview.netlify.app/docs/using-odo/url
=> Document for URL creation using odo

pkg/service/service.go, pkg/service/service_test.go
/kind bug
Fixes #5019 
```
odo service create rhoas-operator.0.9.0/ServiceRegistryConnection
odo push
```
=> Remove metadata.namespace from ALM Examples

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
/kind feature
release bump
nothing should be broken in odo tests or builds
=> Bumping odo version v2.4.1 -> v2.4.2

tests/integration/devfile/cmd_devfile_status_test.go
/kind tests
Refactoring
Fixes #5099 
=> Refactoring test

.ibm/pipelines/functions.sh, .ibm/pipelines/kubernetes-tests.sh, .ibm/pipelines/openshift-tests.sh, .ibm/pipelines/unit-tests.sh
/kind tests
This PR adds scripts to be executed from IBM Pipelines to run unit tests and integration tests on IBM Cloud
=> Scripts for IBM Pipelines

docs/website/docs/using-odo/create-component.md
/kind bug
Fixes doc bug
Fixes #5224
=> Add starter project name in doc

pkg/odo/cli/component/link.go
Fixes incorrect env variables name in example.
Fixes #5175
=> Fix help for `odo link`

pkg/odo/cli/catalog/describe/operator_backend.go
=> Catalog describe service displays info about []object fields

tests/integration/devfile/cmd_dot_devfile_test.go
/kind tests
Add tests for `.devfile.yaml` support
**Which issue(s) this PR fixes**: 
Fixes https://github.com/openshift/odo/issues/5167
=> add tests for .devfile.yaml support

pkg/odo/cli/service/create.go
/kind bug
$subject.
Fixes #? NA
Build the binary and do `odo service create -h`.
=> Corrects service creation help message

tests/integration/devfile/cmd_devfile_watch_test.go
/kind tests
Test refactoring 
Fixes #5161 
=> Incorporated feedback about When statements

scripts/minikube-minishift-setup-env.sh
/kind tests
This PR fixes the failing k8s test. 
Fixes #?
=> setup minikube before env setup

pkg/kclient/fake/ingress.go, pkg/url/kubernetes.go, pkg/url/kubernetes_test.go, pkg/url/url.go, pkg/url/utils.go, pkg/util/util.go
=> Use adler32 into URL name

.ibm/images/Dockerfile, .ibm/pipelines/functions.sh, .ibm/pipelines/kubernetes-tests.sh, .ibm/pipelines/openshift-tests.sh, .ibm/pipelines/unit-tests.sh, Makefile
/kind tests
Modifies the IBM scripts to use a Docker image with preinstalled tools: oc, kubectl, ibmcloud, gh
=> Use an image with pre-installed oc/kubectl/ibmcloud for IBM Pipelines

pkg/catalog/catalog.go, pkg/devfile/adapters/kubernetes/component/podwatcher_test.go, pkg/devfile/adapters/kubernetes/component/status_test.go, pkg/envinfo/storage.go, pkg/kclient/events_test.go, pkg/kclient/ingress.go, pkg/kclient/ingress_test.go, pkg/kclient/pods_test.go, pkg/odo/cli/catalog/list/list.go, pkg/odo/cli/catalog/search/search.go, pkg/odo/cli/component/create_methods.go, pkg/odo/cli/registry/add.go, pkg/odo/cli/ui/common.go, pkg/odo/util/validation/validation_test.go, pkg/odogenerator/ingressgenerator.go, pkg/secret/secret.go, pkg/secret/secret_test.go, pkg/segment/integrations_test.go, pkg/sync/adapter_test.go, pkg/sync/mock/sync.go, pkg/testingutil/fileutils.go, pkg/unions/kubernetes_ingress.go
/kind cleanup
Lints the imports using `goimports`. I was reading through something and did `goimport -l -w pkg/` on odo repo.
I don't know if we need it. Leaving it up to the team to merge or not.
Fixes - NA
=> Fixes done by `goimports -l -w pkg`

docs/website/docusaurus-odo-plugin-segment/README.md, docs/website/docusaurus-odo-plugin-segment/index.js, docs/website/docusaurus-odo-plugin-segment/package-lock.json, docs/website/docusaurus-odo-plugin-segment/package.json, docs/website/docusaurus-odo-plugin-segment/segment.js, docs/website/docusaurus.config.js, docs/website/package-lock.json, docs/website/package.json
/kind feature
This PR adds support for tracking people visiting odo.dev
Fixes #5106 
Run the server locally and check if data is visible on segment. Ensure that the user IP is set to 0.0.0.0.
=> Add support for tracking people visiting odo.dev

tests/integration/devfile/cmd_devfile_registry_test.go
/kind tests
This PR refactors the test to use the new test flow
Fixes #5257 
```
make test-cmd-devfile-registry
```
=> refactor devfile-registry tests

.ibm/pipelines/functions.sh, .ibm/pipelines/kubernetes-tests.sh, .ibm/pipelines/openshift-tests.sh, .ibm/pipelines/unit-tests.sh
/kind tests
This PR adds Status of test execution in ibmcloud test comments on PRs.
Fixes  N/A
=> Add sucess and failure for ibmcloud tests comments

pkg/devfile/adapters/common/utils.go
/kind feature
This PR makes odo use the latest odo-init-image v1.1.11
Fixes #?
=> Use odo-init-image v1.1.11

tests/integration/devfile/cmd_devfile_log_test.go
> /kind tests
Refactoring
Fixes #5258 
=> Refactor cmd_devfile_log_tests.go

docs/website/blog/2021-05-04-breaking-changes-in-odo-2.2.md, docs/website/blog/2021-12-14-odo-v2.4.3.md
=> add blog post about v2.4.3

.ibm/images/Dockerfile, .ibm/pipelines/functions.sh
=> Use odo-robot to post logs to PR

scripts/ansible/kubernetes-cluster/README.md, scripts/configure-cluster/common/setup-operators.sh
Required for operator tests on K8S cluster
Fixes #5232 
=> Update to install OLM for K8S tests

.ibm/pipelines/kubernetes-tests.sh
/kind tests
Runs the operator hub integration tests on the IBM Kubernetes cluster
Fixes #?
=> Run Operator Hub integration tests on IBMKubernetes cluster

tests/integration/devfile/cmd_devfile_test_test.go
/kind cleanup
/kind tests
This PR refactors [devfile test](https://github.com/redhat-developer/odo/blob/main/tests/integration/devfile/cmd_devfile_test_test.go) tests.
Fixes #5303 
`make test-cmd-devfile-test`
=> refactor devfile test test

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
bump version for 2.5.0 release
=> bump to v2.5.0

docs/website/blog/2022-01-14-odo-v2.5.0.md
=> add blog post about 2.5.0 release

OWNERS, docs/OWNERS, docs/website/OWNERS
> /kind bug
> /kind tests
> Feel free to use other [labels](https://github.com/redhat-developer/odo/labels) as needed. However one of the above labels must be present or the PR will not be reviewed. This instruction is for reviewers as well.
Adds myself to OWNERS
N/A
Not needed
Not needed
N/A
=> Add myself to OWNERS group

.github/PULL_REQUEST_TEMPLATE.md
Updates the pull request template / removes the incorrect links
Takes inspiration from: https://raw.githubusercontent.com/kubernetes/kubernetes/master/.github/PULL_REQUEST_TEMPLATE.md
We need it to fix the incorrect links as well as make it easier to
contribute / guidelines
N/A
N/A
N/A
N/A
=> Updates .github/PULL_REQUEST_TEMPLATE.md with new information

docs/website/README.md
> /kind bug
> /kind tests
> Feel free to use other [labels](https://github.com/redhat-developer/odo/labels) as needed. However one of the above labels must be present or the PR will not be reviewed. This instruction is for reviewers as well.
Updates the incorrect link in the website docs directory
N/A
N/A
N/A
N/A
=> Updates incorrect link

scripts/configure-installer-tests-cluster-s390x.sh
/kind bug
For Z, we need to add namespace "nodejs-14" in configure-installer-tests-cluster-s390x.sh refer to configure-installer-tests-cluster.sh. this namespace is used in test cases, so I create this pull request to add it.
Fixes #
=> add namespace in configure-installer-tests-cluster-s390x.sh

docs/website/blog/2022-01-14-odo-v2.5.0.md
adds @dharmit's `--maping` demo
=> blog post for 2.5.0 - add video recording

pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/component/component_kubernetes.go, pkg/devfile/adapters/kubernetes/component/errors.go, pkg/log/status.go, pkg/odo/cli/application/delete.go, pkg/odo/cli/component/delete.go, pkg/odo/cli/service/create.go, tests/integration/devfile/cmd_devfile_delete_test.go
=> [v2 cherrypicking] Undeploy error

docs/website/docs/getting-started/basics.md, docs/website/docs/getting-started/features.md, docs/website/docs/getting-started/installation.md, docs/website/docs/getting-started/quickstart.md
Installation should be listed before quickstart
=> odo.dev: reorder getting-started section

docs/website/blog/2020-09-24-odo-v2.0.0-ga-release.md, docs/website/blog/2020-10-28-odo-v2.0.1-release.md, docs/website/blog/2021-05-04-odo-v2.2.0-breaking-changes.md, docs/website/blog/2021-12-14-odo-v2.4.3.md, docs/website/blog/2022-01-14-odo-v2.5.0.md
Changes:
- Updates the blog posts so it's more consistent with the file names
- Updates the links to avatars so it's more consistent, uses the `.png`
feature of github.com's author image links
- Changes the wording of the "breaking changes" to "backwards
incompatible" which is less harsh and portrays more stability in the odo
software, rather than us breaking things all the time.
N/A
View the site :)
=> Updates blog posts

docs/website/docs/getting-started/basics.md
Updates the concept page with the following changes:
- Changes the header so the definitions appear on the side bar
- Changes the name to Concepts of odo so it matches all the other
documents in the section that start with capitalization / not with the
odo word
- Changes odo to `odo` to emphasize cli tool
- Updates devfile link and other examples
N/A
N/A
=> Update concept page

docs/website/docs/getting-started/cluster-setup/kubernetes.md, docs/website/docs/getting-started/cluster-setup/openshift.md
Updates the documentation for cluster setup with the following:
- Removes trailing sentences / reduces the amount of uneeded sentences
- Organizes the information logically on both k8s and oc pages
- Changes references to `odo` instead of odo
- Grammatical changes
- Updates to links / operator hub version
N/A
N/A
=> Update Cluster Setup documentation

.ibm/pipelines/unit-tests.sh, .ibm/pipelines/validate.sh
/kind tests
By this PR, we will divide unit test running on IBMCloud into unit test and validator to speed up the test. 
Fixes #5282 
=> split unit test into unit test and validate test

docs/website/docs/command-reference/delete.md, docs/website/docs/command-reference/deploy.md, docs/website/docs/command-reference/init.md, docs/website/docs/command-reference/link.md, docs/website/docs/command-reference/registry.md, docs/website/docs/command-reference/service.md, docs/website/docs/command-reference/storage.md
Documentation related to the `odo init` command
=> odo init reference doc

tests/integration/devfile/cmd_devfile_debug_test.go
/kind tests
Test refactoring 
Fixes #5304 
=> Refactor test-cmd-devfile-debug

docs/website/package-lock.json
/kind cleanup
upgrade website dependencies some of them have security issues (detected by GitHub Dependabot)
=> update website dependencies

docs/website/docs/getting-started/features.md, docs/website/docs/intro.md
This PR does the following to the introduction documentation:
- Updates the language used to be more casual / persuasive
- Uses keywords such as cloud engineer rather than architect / better
for SEO
- Focuses more on Kubernetes keywords
- Organizes larger paragraphs
N/A
=> Updates introduction documentation

docs/website/package-lock.json, docs/website/package.json
$subject. Doing it to get rid of Dependabot banner. Not sure if this will suffice.
Fixes #
=> Updated node-forge from 0.10.0 to 1.0.0

.github/workflows/build.yml, sonar-project.properties
fixes SonarCloud integration
/kind tests
=> Fix sonarcloud

docs/website/docs/getting-started/cluster-setup/kubernetes.md, docs/website/docs/getting-started/cluster-setup/openshift.md, docs/website/docs/getting-started/quickstart.md, docs/website/src/pages/index.tsx
This does the following:
- Updates the quickstart guide
- Updates the cluster setup guides with more troubleshooting tips
- Reworks the quickstart guide so it now says "Hands-on Guide", as it's
not exactly a quick start guide anymore... In the future we should add a
quick start guide which could be a simple frontend application
- Still use the "quickstart" link so that no current links break
- The guide reorders the deployment of applications (front end then
backend, then database)
- Explains more to the user what is happening each step
Fixes https://github.com/redhat-developer/odo/issues/5395
Fixes https://github.com/redhat-developer/odo/issues/5375
Fixes …
=> Updates the quickstart and cluster setup guides

pkg/odo/cli/init/init.go, pkg/odo/cli/init/params/types.go
/kind bug
Based on feedback from sprint 213 demo, added clearer error messages and more examples
=> More inline help for odo init

docs/website/src/pages/index.tsx
Fixes the incorrect link on the website that said hands on guide instead
of quickstart.
N/A
N/A
N/A
N/A
N/A
=> Fix quickstart link on the site

tests/integration/cmd_pref_config_test.go
/kind bug
/kind tests
Fixes #5410 
```
export KUBERNETES=true
ginkgo -focus="odo preference and config command tests" tests/integration
```
=> Fix odo running OC specific tests in K8s env

pkg/odo/cli/cli.go
/kind cleanup
This PR:
- Removes the OpenShift references in the main --help page
- Adds an ASCII version of our logo which looks better on the --help
output
- Changes the link to our main website
See the output here!:
```sh
▶ odo --help | head -n 15
__
/  \__     odo is a CLI tool for fast iterative application development
\__/  \    deployed immediately to your kubernetes cluster.
/  \__/    Find more information at https://odo.dev
\__/
Usage:
odo [flags]
odo [command]
Examples:
git clone https://github.com/odo-devfiles/nodejs-ex && cd nodejs-ex
odo push
```
Fixes https://github.com/redhat-developer/odo/issues/5401
**How to test changes …
=> Adds ASCII logo to --help / removes oc references

docs/website/docs/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.md
For Z. we have verified more languages and runtimes refer to https://github.com/devfile/registry/tree/main/stacks. So this PR is to update document https://odo.dev/docs/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power for Z.
All the added type of languages have been verified on OCP-Z.
Fixes #
=> Update devfiles images document for s390x

docs/website/docs/tutorials/deploying-java-app-with-database.md
In doc https://odo.dev/docs/tutorials/deploying-java-app-with-database, due to the [manifest](https://github.com/redhat-developer/odo/tree/main/docs/website/manifests) directory path in the odo code has changed, the yamls in manifest URL should be update.
Fixes #
=> update yaml URL when install postgreSQL on IBM Z and Power

pkg/init/asker/asker_test.go
=> Add test for personalization options

pkg/odo/cli/cli.go, pkg/odo/cli/component/delete.go, pkg/odo/cli/delete/component.go, pkg/odo/cli/delete/delete.go, pkg/odo/genericclioptions/resolve.go, pkg/odo/genericclioptions/runnable.go, pkg/odo/genericclioptions/util.go, tests/integration/devfile/cmd_devfile_create_test.go, tests/integration/devfile/cmd_devfile_delete_test.go, tests/integration/devfile/cmd_devfile_deploy_test.go, tests/integration/devfile/cmd_devfile_push_test.go
/kind feature
This PR creates the common code for issues #5478 and #5479
Fixes partially #5409 
=> Skeleton for odo delete component command

scripts/openshiftci-periodic-tests.sh, tests/examples/source/devfiles/nodejs/devfile-registry.yaml, tests/examples/source/devfiles/python/devfile-registry.yaml, tests/examples/source/devfiles/springboot/devfile-registry.yaml
/kind tests
This PR will update the script used for periodic testing on openshift-ci.
Fixes #5411 
=> Modify periodic test script for v2 branch

docs/website/docs/command-reference/create.md, docs/website/docs/command-reference/delete.md, docs/website/docs/command-reference/deploy.md, docs/website/docs/command-reference/link.md, docs/website/docs/command-reference/registry.md, docs/website/docs/command-reference/service.md, docs/website/docs/command-reference/storage.md, docs/website/docs/getting-started/basics.md, docs/website/docs/getting-started/cluster-setup/kubernetes.md, docs/website/docs/getting-started/cluster-setup/openshift.md, docs/website/docs/getting-started/configure.md, docs/website/docs/getting-started/features.md, docs/website/docs/getting-started/installation.md, docs/website/docs/getting-started/quickstart.md, docs/website/docs/intro.md, docs/website/docs/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.md, docs/website/docs/tutorials/deploying-java-app-with-database.md
The documentation was unfortunately not updated / correct. This PR moves
all the documentation we had in the "3.0.0" folder to 2.5.0 with the
exception of the `odo init` command.
=> Syncs documentation for 2.5.0

pkg/dev/dev.go, pkg/dev/interface.go, pkg/odo/cli/dev/dev.go
/kind cleanup
It implements the callback pattern to use the function implemented at CLI level instead of defining it in business layer
Fixes # NA
=> Use callback and implement watch handler at CLI level

pkg/kclient/kclient.go
/kind feature
We query the REST client *a lot* with `odo`. This increases the QPS and
Burst constants of the client in order to reduce the amount of
"throttling" warnings we get, as well as increase the rate that we can
query the API.
The Kubernetes client-go library is smart in the fact that it retries /
automatically reduces the rate at which are cluster queries are being
done.
Setting the QPS and Burst to high values reduces the amount of time it
takes `odo` to query all resources on the cluster (using `odo list`) as
well as speeds up other aspects of `odo` such as `odo deploy` and `odo
dev`.
N/A …
=> Increase the QPS and Burst constants of the Kubernetes REST client

pkg/odo/cli/deploy/deploy.go, tests/integration/devfile/cmd_dev_test.go, tests/integration/devfile/cmd_devfile_deploy_test.go, tests/integration/devfile/cmd_devfile_init_test.go
/kind bug
/kind tests
Fixes #5544 
=> Test and fix using namespace from env file

.ibm/pipelines/openshift-tests.sh, .ibm/pipelines/windows-test-script.ps1, .ibm/pipelines/windows-test.sh
/kind tests
This PR updates the login process for openshift clusters
Fixes #5501
=> fix openshift login failure

pkg/odo/cli/init/init.go, tests/integration/devfile/cmd_devfile_init_test.go
/kind feature
This PR adds information about `odo deploy` only if the devfile do
wnloaded by `odo init` contains a deploy command.
Fixes #5534
```sh
➜  odo init --name aname --devfile-path /tmp/devfile-deploy.yaml                                                                                                                
✓  Copying devfile from "/tmp/devfile-deploy.yaml" [68123ns]                                                                                                                       
Your new component "aname" is ready in the current directory.
To start editing your component, use …
```
=> condition odo deploy information in odo init output 

scripts/openshiftci-periodic-tests.sh
/kind tests
This PR fixes v2 periodic testing script.
Fixes #
=> fix failing v2 periodic tests

tests/helper/helper_dev.go, tests/integration/devfile/cmd_delete_test.go, tests/integration/devfile/cmd_dev_test.go, tests/integration/devfile/cmd_devfile_list_test.go
/kind tests
This PR abstracts running `odo dev` for integration tests
Fixes #5549 
=> Create DevSession for integration tests

pkg/deploy/deploy.go, pkg/dev/dev.go, pkg/devfile/image/docker_compatible.go, pkg/devfile/image/image.go, pkg/log/status.go, pkg/odo/cli/deploy/deploy.go, pkg/odo/cli/dev/dev.go, pkg/service/service.go, pkg/watch/watch.go
/kind cleanup
Cleans up the experience when using `odo deploy` and `odo dev` by cleaning up the main
output in a more consise manner.
Other changes:
* Updates the log/status.go output for "title" and "info"
* When using `-v` it will show the raw image build / pushing output for debugging purposes.
**UPDATES TO ODO DEPLOY:**
[![asciicast](https://asciinema.org/a/Sde9krmi8jCX0XZzA83UXloIB.svg)](https://asciinema.org/a/Sde9krmi8jCX0XZzA83UXloIB)
**UPDATES TO ODO DEV:**
[![asciicast](https://asciinema.org/a/rhAd0tvzMTje0RpfI6ITTfE7b.svg)](https://asciinema.org/a/rhAd0tvzMTje0RpfI6ITTfE7b)
N/A
Run `odo …
=> Updates the UX/UI experience of odo deploy and odo dev

docs/website/versioned_docs/version-3.0.0/command-reference/delete.md, pkg/odo/cli/delete/component.go
This PR updates documentation for odo delete command reference.
Fixes #5559 
=> Update odo delete component doc

pkg/devfile/image/image.go
/kind cleanup
Updates the backend error message to indicate that Docker or Podman
should be installed.
N/A
=> Updates the backend error messages more clearly

cmd/odo/odo.go, pkg/auth/login.go, pkg/odo/cli/init/init.go
/kind cleanup
Remove all italic output throughout odo with the exception of building
images / pushing images.
Makes all output consistent with `odo dev` and `odo deploy`
N/A
=> Remove italic output throughout odo

pkg/dev/dev.go, pkg/dev/interface.go, pkg/dev/mock.go, pkg/odo/cli/dev/dev.go, tests/integration/devfile/cmd_dev_test.go
/kind bug
This PR makes `odo dev` use the content of `.gitignore` file
Fixes #5581 
Blocked by #5569 to write integration test with `odo dev`
=> Use .gitignore file for odo dev

pkg/kclient/kclient.go
=> Hide warnings for dynamic client

docs/website/docs/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.md, docs/website/versioned_docs/version-3.0.0/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.md
For Z. we have verified latest languages and runtimes refer to https://github.com/devfile/registry/tree/main/stacks. So this PR is to update document https://odo.dev/docs/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power for Z.
All the added type of languages have been verified on OCP-Z.
Fixes #
/area system-PZ
=> Update devfiles' information and used images for s390x

tests/examples/source/devfiles/nodejs/devfile-registry.yaml, tests/examples/source/devfiles/nodejs/devfile-with-link.yaml, tests/examples/source/devfiles/python/devfile-registry.yaml, tests/examples/source/devfiles/springboot/devfile-registry.yaml, tests/integration/devfile/cmd_dot_devfile_test.go, tests/integration/operatorhub/cmd_link_test.go
Add one of the following kinds:
/kind tests
This PR updates the devfile.yaml present in the example dir for tests.
Fixes #
=> update devfiles on v2 branch

tests/e2escenarios/e2e_devfile_test.go, tests/helper/helper_dev.go, tests/helper/helper_non_windows.go, tests/helper/helper_nowindows.go, tests/helper/helper_run.go, tests/helper/helper_windows.go, tests/integration/devfile/cmd_delete_test.go, tests/integration/devfile/cmd_dev_test.go, tests/integration/devfile/cmd_devfile_deploy_test.go, tests/integration/devfile/cmd_devfile_list_test.go
/kind bug
This PR fixes how the odo process is terminated on Windows during integration tests
Fixes #5485 
=> Terminate process on windows

scripts/openshiftci-periodic-tests.sh
/kind tests
This PR fix artifact collection for periodic job on v2
Fixes #
=> fix artifact collection

OWNERS
=> Remove Mrinal and add Armel to OWNERS

tests/helper/helper_dev.go, tests/integration/devfile/cmd_dev_test.go
=> Fix dev integration tests not finishing

tests/examples/source/devfiles/nodejs/devfile-with-pod.yaml
/kind tests
to fix the failing test on periodic tests due to image registry
Fixes https://github.com/redhat-developer/odo/issues/5709
=> update image path, fix test

docs/website/versioned_docs/version-3.0.0/command-reference/describe.md, docs/website/versioned_docs/version-3.0.0/command-reference/json-output.md, pkg/api/component.go, pkg/api/error.go, pkg/api/utils.go, pkg/component/component.go, pkg/component/component_test.go, pkg/component/errors.go, pkg/component/types.go, pkg/machineoutput/types.go, pkg/odo/cli/cli.go, pkg/odo/cli/describe/component.go, pkg/odo/cli/describe/describe.go, pkg/odo/cli/init/init.go, pkg/odo/util/cmdutils.go, pkg/state/interface.go, pkg/state/state.go, pkg/state/state_test.go, tests/integration/devfile/cmd_describe_test.go
/kind feature
Fixes #5660 
Doc preview:
- https://deploy-preview-5720--odo-docusaurus-preview.netlify.app/docs/3.0.0/command-reference/json-output#odo-describe-component--o-json
- https://deploy-preview-5720--odo-docusaurus-preview.netlify.app/docs/3.0.0/command-reference/describe (to be completed as part of #5661)
=> odo describe component -o json

pkg/alizer/alizer.go, pkg/alizer/alizer_test.go, pkg/init/backend/interactive.go, pkg/init/backend/interactive_test.go, pkg/log/status.go, pkg/odo/cli/cli.go, pkg/odo/cli/registry/registry.go, pkg/registry/interface.go, pkg/registry/mock.go, pkg/registry/registry.go, pkg/registry/registry_test.go, pkg/registry/types.go, tests/integration/devfile/cmd_devfile_registry_test.go
/kind feature
This adds the `odo registry` command, to output the details of what's
in the registry.
It also implements the flags:
- `--filter`
- `--devfile`
- `--details`
This can be tested by typing in the `odo registry` command after adding
a registry (you should already have one by default)
part of https://github.com/redhat-developer/odo/issues/5524
`odo registry`
=> Adds odo registry command

docs/website/.gitignore, docs/website/docusaurus.config.js
We have too little content to constitute hiding the sidebars. Similar to
other sites, we disable the expansion and autoexpand when first loading
so users can see all documentation.
N/A
=> Update the site configuration to expand sidebars

docs/website/versioned_docs/version-3.0.0/getting-started/cluster-setup/kubernetes.md, docs/website/versioned_docs/version-3.0.0/getting-started/cluster-setup/openshift.md
Updates the wording for the cluster setup documentation so it says
requirements not prerequisites.
N/A
=> Small update to cluster setup docs

docs/website/versioned_docs/version-3.0.0/command-reference/add-binding.md
This PR adds documentation for `odo add binding`.
Fixes part of #5627 
=> odo add binding documentation

docs/website/versioned_docs/version-3.0.0/command-reference/dev.md
Minor update to the odo dev reference documentation (capitalize the
section, fix the grammar)
Fixes #
=> Minor update to odo dev reference

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bumping odo version to v3.0.0-alpha2

docs/website/versioned_docs/version-3.0.0/getting-started/quickstart.md
This PR adds examples to the odo quickstart guide in order to go into
details with the `odo init`, `odo dev` and `odo deploy` commands.
N/A, part of multiple PR's
related to https://github.com/redhat-developer/odo/issues/5682
=> Redo the quickstart guide to odo 3.0.0

docs/website/versioned_docs/version-3.0.0/command-reference/list-namespace.md, pkg/odo/cli/cli.go, pkg/odo/cli/list/list.go, pkg/odo/cli/list/namespace/namespace.go, tests/integration/cmd_namespace_test.go
/kind feature
This PR adds `odo list namespaces` command
Fixes part of #5525
1. `odo list namespace`
2. `odo list project`
Try the above commands on both OC and K8s cluster.
=> odo list namespace

pkg/kclient/pods.go
=> Execute tar with --no-same-owner

docs/website/versioned_docs/version-3.0.0/user-guides/quickstart.md
Adds a Java Spring Boot example to the quickstart
Closes https://github.com/redhat-developer/odo/issues/5746
=> Adds Java Spring Boot example to quickstart guide

pkg/binding/binding.go, pkg/binding/binding_test.go, pkg/binding/interface.go, pkg/binding/mock.go, pkg/kclient/binding.go, pkg/kclient/deployments.go, pkg/kclient/interface.go, pkg/kclient/mock_Client.go, pkg/odo/cli/add/binding/binding.go, pkg/testingutil/devfile.go
/kind tests
This PR adds unit test cases for pkg/binding/binding.go
Fixes #5627 
=> Add unit test for odo add binding

OWNERS, openshift-ci/build-root/OWNERS, scripts/OWNERS, tests/OWNERS
/kind tests
This PR updates the OWNERS list, updating it with the current team members.
Fixes #
=> Update OWNERS files

docs/website/docusaurus.config.js, docs/website/src/pages/index.tsx
Adds alpha link on the homepage so you can easily go to the quickstart
guide.
Updates the sidebar usage on saying alpha 2 not alpha 1.
N/A
=> Add 3.0.0 link to homepage, and fix alpha title

docs/website/blog/2022-06-14-binding-external-service.md
=> Add blog post about binding an external service

docs/website/versioned_docs/version-3.0.0/user-guides/quickstart.md
An incorrect rebase messed up the quickstart guide, as well as feedback
from users reccomended to remove the CLI portion of the springboot
guide.
=> Fix CLI info regarding Springboot quickstart

docs/website/versioned_docs/version-3.0.0/command-reference/json-output.md, docs/website/versioned_docs/version-3.0.0/command-reference/list-binding.md, pkg/api/binding.go, pkg/api/list.go, pkg/binding/add.go, pkg/binding/binding.go, pkg/binding/binding_test.go, pkg/binding/interface.go, pkg/binding/list.go, pkg/binding/list_test.go, pkg/binding/mock.go, pkg/kclient/binding.go, pkg/kclient/interface.go, pkg/kclient/mock_Client.go, pkg/kclient/operators.go, pkg/odo/cli/list/binding/binding.go, pkg/odo/cli/list/list.go, pkg/odo/cli/ui/table.go, pkg/odo/genericclioptions/context.go, pkg/odo/genericclioptions/context_test.go, pkg/odo/genericclioptions/errors.go, tests/examples/source/devfiles/nodejs/devfile-with-service-binding-files.yaml, tests/integration/devfile/cmd_describe_binding_test.go, tests/integration/devfile/cmd_describe_list_binding_test.go
/kind feature
Add `odo list binding` command
Fixes #5635 
=> odo list binding

tests/integration/devfile/cmd_logs_test.go
/kind tests
Check the conversation since https://github.com/redhat-developer/odo/issues/5622#issuecomment-1160550743.
Fixes #5622
Tests should pass.
=> Check if all Pods are running in odo logs tests

docs/website/versioned_docs/version-3.0.0/command-reference/add-binding.md, docs/website/versioned_docs/version-3.0.0/overview/cluster-setup/kubernetes.md, docs/website/versioned_docs/version-3.0.0/overview/cluster-setup/openshift.md
This PR adds missing documentation on the service binding operator.
Fixes #5757 
https://deploy-preview-5855--odo-docusaurus-preview.netlify.app/docs/3.0.0/command-reference/add-binding#pre-requisites
https://deploy-preview-5855--odo-docusaurus-preview.netlify.app/docs/3.0.0/overview/cluster-setup/kubernetes#installing-the-service-binding-operator
https://deploy-preview-5855--odo-docusaurus-preview.netlify.app/docs/3.0.0/overview/cluster-setup/openshift/#installing-the-service-binding-operator
=> Add missing documentation on SBO installation

.threatmodel/THREAT_MODELING.md, .threatmodel/odo-model.json
Save the Threat Model (defined in json format), and  basic documentation with important links
Fixes #5794 
No tests required
=> adding Threat Model and corresponding md file

docs/website/docs/overview/installation.md, docs/website/docusaurus.config.js, docs/website/versioned_docs/version-2.5.0/getting-started/installation.md
This PR updates the version number in installation docs.
Fixes #
=> Bump odo version in installation docs

docs/website/docs/user-guides/quickstart.md
Adds a link based on the feedback from user testing.
Fixes # N/A
=> Adds link to inner loop to the Quickstart guide

docs/website/docusaurus.config.js
Fixes #6002 
Change to dark mode on the website.
=> Use oceanicNext dark theme for website

docs/website/src/css/custom.css
Updates the website so the index page isn't "shouting" at you with the
bolded text. Changes it to a softer weighted font.
N/A
=> Update site index page with lighter font

docs/website/blog/2022-08-18-odo-v3-beta3.md, docs/website/docs/overview/installation.md
This adds blog post for odo v3.0.0-beta3
Fixes #5906 
=>  Add blog post for v3.0.0-beta3 and update installation docs

pkg/alizer/alizer.go, pkg/alizer/alizer_test.go, pkg/init/backend/alizer.go, pkg/init/backend/interactive.go, pkg/init/backend/interactive_test.go, pkg/init/init.go, tests/integration/interactive_init_test.go
/kind feature
This PR:
* Detects the project name via pom.xml (java), package.json (node.js),
etc. with alizer.
* If the detection fails, default to using the directory name.
Fixes https://github.com/redhat-developer/odo/issues/5847
=> Autodetect project name via Alizer

pkg/component/delete/delete.go
/kind bug
Fixes #6054
Fixes #5797 
=> Ignore notfound error on delete

.ibm/pipelines/windows-test-script.ps1, .ibm/pipelines/windows-test.sh, Makefile, scripts/configure-cluster/common/setup-operators.sh, scripts/openshiftci-presubmit-all-tests.sh, tests/helper/helper_oc.go, tests/integration/interactive_add_binding_test.go
=> fix flake and use operatorhub to install EDB

docs/website/docs/command-reference/json-output.md, pkg/api/preference.go, pkg/odo/cli/preference/view.go, pkg/odo/cli/preference/view_test.go, pkg/preference/implem.go, pkg/preference/machine_output.go, tests/integration/cmd_pref_config_test.go
=> JSON output for preference view

docs/website/docs/command-reference/add-binding.md, pkg/binding/binding.go, scripts/changelog-script.sh
=> Fix broken links to installation guide

docs/website/docusaurus.config.js, docs/website/package.json, docs/website/yarn.lock
There was a mismatch in docusaurus component versions, this can lead to unexpected errors.
While fixing this, I updated Docusaurus to the latest stable version.
Fixes #
=> upgrade to docusaurus 2.1 and fix version mismatch

docs/website/docs/user-guides/advanced/deploy/deploy.md
Use Deploying an Application not Deploying application
Updates correct grammar for title to Deploying an Application
=> Use Deploying an Application not Deploying application

pkg/util/util.go, pkg/util/util_test.go
=> Fix panic when component name is long but not app

tests/integration/cmd_devfile_registry_test.go, tests/integration/interactive_deploy_test.go, tests/integration/interactive_dev_test.go, tests/integration/interactive_init_test.go
/kind tests
/area testing
This PR reverts the changes related to python devfile in integration tests from #6140.
Reason: https://github.com/devfile/registry/pull/125
Fixes part of #6138 
=> Revert devfile python ID

docs/website/docs/overview/_category_.json, docs/website/docs/user-guides/_category_.json, docs/website/docs/user-guides/advanced/_category_.json, docs/website/docs/user-guides/advanced/connecting-a-service.md, docs/website/docs/user-guides/advanced/deploy/_category_.json, docs/website/docs/user-guides/quickstart/_category_.json, docs/website/docusaurus.config.js
This PR adds adjustable collapsible sidebar.
Fixes #6152 
=> Adjust sidebars on odo.dev website

.ibm/pipelines/windows-test-script.ps1, .ibm/pipelines/windows-test.sh, tests/e2escenarios/e2e_devfile_test.go
/kind bug
/kind tests
remove the process of cloning in windows vm, instead we will copy the repo from the test container to VM.
Fixes #6175 
=> Fix Windows tests for PR targeting branches other than `main`

tests/e2escenarios/e2e_devfile_test.go
/kind tests
suspending broken quarkus e2e test, as it's affecting periodic jobs, as well as PRs
This is tracked under **issue** https://github.com/redhat-developer/odo/issues/6181 
Fixes #NA
=> suspend quarkus test

docs/website/docusaurus.config.js
Updates Algolia settings to use the appId and apiKey for the odo project.
=> Update Algolia settings

OWNERS
Removal from OWNERS
/kind cleanup
No longer reviewing / approving the project.
Thanks all for the wonderful years working on `odo`!
N/A
=> Removal from OWNERS

.ibm/pipelines/windows-test-script.ps1, Dockerfile.rhel, pkg/odo/genericclioptions/runnable.go, pkg/segment/context/context.go, pkg/segment/context/context_test.go, pkg/version/version.go, scripts/rpm-prepare.sh, tests/e2escenarios/e2e_devfile_test.go, tests/integration/cmd_devfile_deploy_test.go, tests/integration/cmd_devfile_init_test.go, tests/integration/cmd_devfile_registry_test.go, tests/integration/interactive_deploy_test.go, tests/integration/interactive_dev_test.go, tests/integration/interactive_init_test.go
/kind task
This is a PR to merge the `v3.0.0` tag into the `main` branch.
/hold
Holding to prevent the merge bot from squashing all commits into a single one (and losing the history for unrelated individual commits).
We will need to manually merge this PR by creating an explicit Merge commit after all tests pass.
I've ensured this can be merged by resolving conflicts due to 95a8a58 (already in `main`). So this PR contains changes in the v3.0.0 tag, plus 95a8a58.
ref #6011 
=> Merge `v3.0.0` tag into `main`

tests/e2escenarios/e2e_devfile_test.go
/kind tests
This PR will enable quarkus e2e test.
Fixes #6181 
=> enable quarkus e2e test

docs/website/blog/3.0.0-GA-blog.md
=> odo 3.0.0 GA blog

README.md, docs/website/docs/command-reference/build-images.md, docs/website/docs/command-reference/deploy.md, docs/website/docs/command-reference/list-component.md, docs/website/docs/overview/configure.md, docs/website/docs/user-guides/advanced/deploy/deploy.md, docs/website/docs/user-guides/quickstart/quickstart.md
This PR makes some things that we missed out on that I observed while reviewing downstream.
Fixes #
=> Minor fixes to documentation

tests/integration/cmd_devfile_registry_test.go, tests/integration/interactive_deploy_test.go, tests/integration/interactive_dev_test.go, tests/integration/interactive_init_test.go
=> fix test failure due to devfile-registry 

tests/e2escenarios/e2e_test.go, tests/integration/cmd_devfile_registry_test.go, tests/integration/interactive_deploy_test.go, tests/integration/interactive_dev_test.go, tests/integration/interactive_init_test.go
=> Fix e2e test after registry changes

pkg/remotecmd/kubeexec.go, pkg/remotecmd/kubexec_test.go
/kind bug
/area dev
For some reason, this happened with NodeJS starter projects for example,
where killing the parent pid for the application ('npm start')
would not stop the underlying 'node' process, causing the application
port to still being used.
Given the following process tree for the Node.JS application:
```
default       49  0.0  0.0  11924  2828 ?        Ss   20:23   0:00 /bin/sh -c echo $$ > /opt/odo/.odo_cmd_run.pid && cd ${PROJECT_SOURCE} &&  (npm start) 1>>/proc/1/fd/1 2>>/proc/1/fd/2; echo $? >> /opt/odo/.odo_cmd_run.pid
default       55  1.0  0.0 735940 62956 ?        Sl   20:23   0:00  \_npm start
default       66  0.0  0.0  11928  2760 ?        S    20:23   0:00    \_ sh /tmp/start-c40b5918.sh …
```
=> Fix potential issue preventing application from being restarted correctly by `odo dev`

pkg/odo/genericclioptions/devfile.go, tests/integration/cmd_devfile_list_test.go
=> Set empty component name in context if no devfile exists in the current directory

tests/integration/cmd_devfile_init_test.go
/kind tests
Changes strings to be checked in tests to match what's available in the underlying devfile
Fixes #6291 
Integration tests should pass.
=> Change expecations to match reality

docs/website/docusaurus.config.js
=> Add YouTube link to docs footer

.github/workflows/build-push-ibm-image.yaml, .ibm/images/README
=> Build and push .ibm/images/Dockerfile image

docs/website/docs/command-reference/json-output.md, pkg/api/list.go, pkg/api/project.go, pkg/odo/cli/list/namespace/namespace.go, tests/integration/cmd_namespace_test.go
=> Adds ability to list namespaces in JSON format

OWNERS, docs/OWNERS, docs/website/OWNERS, pkg/service/OWNERS, tests/OWNERS
=> Remove Dharmit from OWNERS files across the repo

OWNERS
Adding Anand as reviewer and approver
=> add anand to owner file as reviewer and approver

tests/integration/cmd_namespace_test.go
/kind tests
this PR fixes flaky tests for `odo list project/namespace -o json`
Fixes #6368 
=> replacing timeout with time interval

docs/website/docs/command-reference/delete-namespace.md, pkg/odo/cli/delete/namespace/namespace.go, tests/helper/helper_oc.go, tests/helper/odo_utils.go, tests/integration/cmd_namespace_test.go
/kind improvement
See https://github.com/redhat-developer/odo/issues/6256#issuecomment-1339630293
Fixes #6256
=> Improve confirmation message for namespace/project deletion

pkg/dev/podmandev/pod.go, pkg/dev/podmandev/pod_test.go, pkg/dev/podmandev/podmandev.go, pkg/dev/podmandev/reconcile.go, pkg/portForward/portForward.go, pkg/util/util.go
=> Get next free port when forwarding ports on podman

.ibm/pipelines/functions.sh
/kind bug
/kind tests
This PR updates the ENV used for passing ODO_ROBOT key value
Fixes #6392 
=> update env name for ODO_ROBOT_KEY

pkg/api/component.go, pkg/api/running-mode.go, pkg/api/running-mode_test.go, pkg/component/component.go, pkg/component/component_test.go, pkg/component/errors.go, pkg/dev/podmandev/pod.go, pkg/dev/podmandev/pod_test.go, pkg/odo/cli/cli.go, pkg/odo/cli/describe/component.go, pkg/odo/cli/describe/describe.go, pkg/podman/pods.go, tests/helper/labels.go, tests/integration/cmd_describe_component_test.go
=> Make `odo describe component` show information about components running on Podman

docs/website/docs/user-guides/quickstart/java.md
=> [docs] Add note to use SpringBoot 2.7

docs/website/docs/user-guides/quickstart/java.md
=> Remove extra caution from Java Quickstart

pkg/alizer/mock.go, pkg/api/binding.go, pkg/binding/binding.go, pkg/binding/list_test.go, pkg/init/asker/mock.go, pkg/kclient/binding.go, pkg/kclient/interface.go, pkg/kclient/mock_Client.go, pkg/odo/cli/describe/binding.go, pkg/odo/cli/list/binding/binding.go, pkg/odo/cli/list/list.go, tests/examples/source/devfiles/nodejs/devfile-with-service-binding-envvars.yaml, tests/integration/cmd_describe_list_binding_test.go
=> Get binding information without cluster connection

.github/workflows/podman-test.yaml, pkg/podman/podman.go, tests/helper/component_interface.go, tests/helper/component_podman.go, tests/integration/cmd_delete_test.go, tests/integration/cmd_dev_test.go
=> Compatibility with podman v3

pkg/util/util.go, pkg/util/util_test.go
=> Fix adding .odo to .gitignore file

tests/helper/component_cluster.go, tests/helper/component_interface.go, tests/helper/component_podman.go, tests/integration/cmd_delete_test.go, tests/integration/cmd_dev_test.go
/kind tests
Fixes partially #6447 
First commits cherry-picked from #6482 
=> Add more tests for odo dev on Podman (1)

pkg/util/file_indexer.go
=> Fix typo with file_indexer.go

pkg/dev/podmandev/reconcile.go, pkg/watch/status.go, tests/integration/cmd_dev_test.go
=> hotReloadCapable recognized on podman

docs/website/docs/user-guides/quickstart/docs-mdx/connecting_to_the_cluster_description.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/initial_source_code_description.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/odo_init_description.mdx, docs/website/docs/user-guides/quickstart/dotnet.md, docs/website/docs/user-guides/quickstart/java.md
/kind bug
This PR adds instructions to create and cd into a new directory before running any odo commands.
Fixes #
=> Add instructions to quickstart guide to create and cd into a directory

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
=> Version bump to 3.6.0

.ibm/pipelines/functions.sh
/kind tests
Status of test is updated in the same message for:
- OpenShift Unauthenticated Tests / OpenShift Tests
- Kubernetes Docs Tests / Kubernetes Tests
=> Fix identification of message on github PR

.github/workflows/podman-test.yaml
=> Run podman tests on 10 nodes

docs/website/blog/2023-01-24-odo-v3.6.0.md
/kind bug
This PR adds a small correction to how container-overrides and pod-overrides attributes can be defined.
Fixes #
=> Correct container-attributes data in release blog

docs/website/static/googlee17e5687b3174050.html
Add verification file to get Google search console for odo.dev, for [feloy] Google account
=> Verification file for Google Search console [feloy]

scripts/OWNERS, tests/OWNERS
=> Adding ritudes user id to tests/OWNERS 

tests/integration/interactive_dev_test.go
/area testing 
Adds the feature to check and ensure if a pod is created and running before any devfile command is run
Fixes #6594 
=> Adding check in odo dev interactive mode for pod/sync to complete 

tests/helper/helper_generic.go, tests/integration/cmd_add_binding_test.go, tests/integration/cmd_devfile_build_images_test.go
/area testing
->It fixes the issue of failing tests due to the display of update notifications in the output.
Fixes #6618 
=> Fix failing tests due to notifications related to update in output

Makefile, scripts/mockgen.sh
Fixes #
1. Remove `mockgen` binary.
```sh
rm $(which mockgen)
```
2. Run the script.
=> Add mockgen installation to the script

pkg/registry/registry.go, pkg/registry/registry_test.go
/kind bug
/area registry
Fixes #6636 
=> Ignore errors that might happen when getting Devfile Registries from the cluster

docs/website/docs/command-reference/docs-mdx/init/registry_list_output.mdx
=> Fix nodejs-react versions on generated doc

Dockerfile.rhel, docs/website/docs/command-reference/docs-mdx/init/devfile_from_any_registry_output.mdx, docs/website/docs/command-reference/docs-mdx/init/devfile_from_specific_registry_output.mdx, docs/website/docs/command-reference/docs-mdx/init/devfile_from_url_output.mdx, docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx, docs/website/docs/command-reference/docs-mdx/init/interactive_mode_empty_directory_output.mdx, docs/website/docs/command-reference/docs-mdx/init/latest_versioned_devfile_output.mdx, docs/website/docs/command-reference/docs-mdx/init/versioned_devfile_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_deploy_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx, pkg/version/version.go, scripts/rpm-prepare.sh
Bumps version to 3.9.0
Related to #6643 
=> Bump version to 3.9.0

docs/website/docs/development/architecture/how-odo-works.md, docs/website/docs/user-guides/advanced/pushing-specific-files.md
/kind feature
Fixes #6461 
Preview:
- https://deploy-preview-6745--odo-docusaurus-preview.netlify.app/docs/overview/configure#ignoring-files-to-synchronize
- https://deploy-preview-6745--odo-docusaurus-preview.netlify.app/docs/development/architecture/how-odo-works#project-sources
=> Document .gitignore and .odoignore usage

Dockerfile.rhel, docs/website/docs/command-reference/docs-mdx/init/devfile_from_any_registry_output.mdx, docs/website/docs/command-reference/docs-mdx/init/devfile_from_specific_registry_output.mdx, docs/website/docs/command-reference/docs-mdx/init/devfile_from_url_output.mdx, docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx, docs/website/docs/command-reference/docs-mdx/init/interactive_mode_empty_directory_output.mdx, docs/website/docs/command-reference/docs-mdx/init/latest_versioned_devfile_output.mdx, docs/website/docs/command-reference/docs-mdx/init/versioned_devfile_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_deploy_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bump version to 3.10.0

docs/proposals/dev-states.md
this documents the refactoring initiated with #6762 and #6771
=> dev states proposal

docs/website/docs/command-reference/docs-mdx/delete-namespace/delete_namespace.mdx, docs/website/docs/command-reference/docs-mdx/delete-namespace/delete_project.mdx, pkg/odo/cli/delete/namespace/namespace.go, pkg/odo/cli/delete/namespace/namespace_test.go
=> Check if namespace exists before the delete confirmation

docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx, pkg/init/backend/alizer.go, pkg/init/init.go, pkg/odo/cli/dev/dev.go, pkg/odo/genericclioptions/runnable.go
Fixes #6780 
TODO: Fix panic on Ctrl+c with `odo dev`
=> Add spinner when determining a devfile using alizer

Dockerfile.rhel, docs/website/docs/command-reference/docs-mdx/init/devfile_from_any_registry_output.mdx, docs/website/docs/command-reference/docs-mdx/init/devfile_from_specific_registry_output.mdx, docs/website/docs/command-reference/docs-mdx/init/devfile_from_url_output.mdx, docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx, docs/website/docs/command-reference/docs-mdx/init/interactive_mode_empty_directory_output.mdx, docs/website/docs/command-reference/docs-mdx/init/latest_versioned_devfile_output.mdx, docs/website/docs/command-reference/docs-mdx/init/versioned_devfile_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_deploy_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bump version to 3.12.0

pkg/odo/cli/preference/view.go, pkg/preference/machine_output.go
=> [UX] Fix default value of ImageRegistry in odo preference view output

pkg/logs/interface.go, pkg/logs/logs.go, pkg/odo/cli/dev/dev.go, pkg/odo/cli/logs/logs.go, tests/helper/helper_dev.go, tests/integration/cmd_logs_test.go
=> odo dev --logs

pkg/odo/cli/apiserver/apiserver.go
=> Add Preference dependency to api-server command

docs/website/docusaurus.config.js, docs/website/src/pages/index.tsx
=> Update home page with Podman

Dockerfile.rhel, docs/website/docs/command-reference/docs-mdx/init/devfile_from_any_registry_output.mdx, docs/website/docs/command-reference/docs-mdx/init/devfile_from_specific_registry_output.mdx, docs/website/docs/command-reference/docs-mdx/init/devfile_from_url_output.mdx, docs/website/docs/command-reference/docs-mdx/init/devfile_with_run-port_output.mdx, docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx, docs/website/docs/command-reference/docs-mdx/init/interactive_mode_empty_directory_output.mdx, docs/website/docs/command-reference/docs-mdx/init/latest_versioned_devfile_output.mdx, docs/website/docs/command-reference/docs-mdx/init/versioned_devfile_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_deploy_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx, pkg/version/version.go, scripts/rpm-prepare.sh
What type of PR is this:
Which issue(s) this PR fixes:
Part of #6879
=> Bump to version 3.13.0

README.md, docs/website/src/pages/index.tsx
=> Update home page preview video with support of Podman

Dockerfile.rhel, docs/website/docs/command-reference/docs-mdx/init/devfile_from_any_registry_output.mdx, docs/website/docs/command-reference/docs-mdx/init/devfile_from_specific_registry_output.mdx, docs/website/docs/command-reference/docs-mdx/init/devfile_from_url_output.mdx, docs/website/docs/command-reference/docs-mdx/init/devfile_with_run-port_output.mdx, docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx, docs/website/docs/command-reference/docs-mdx/init/interactive_mode_empty_directory_output.mdx, docs/website/docs/command-reference/docs-mdx/init/latest_versioned_devfile_output.mdx, docs/website/docs/command-reference/docs-mdx/init/versioned_devfile_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_deploy_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_podman_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_podman_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_podman_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_podman_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bump version to 3.14.0

docs/pm-doc.md
This doc is a **manual** merge of the 3 website pages:
- introduction
- Overview / installation
- User Guides / Quick Start / Developing with Java (Spring Boot)
Section levels have been uniformized between these different pages.
MDX has been processed and Tabs have been inlined. Content of Podman and Kubernetes tabs have been removed.
Fixes #7036
=> Doc for downstream

.github/workflow-data/release-management/blog-post-header.tpl.md, docs/website/blog/2022-07-21-odo-v3-beta2.md, docs/website/blog/2022-08-18-odo-v3-beta3.md, docs/website/blog/2022-09-01-odo-v3-rc1.md, docs/website/blog/2022-09-22-odo-v3-rc2.md, docs/website/blog/2022-11-29-odo-v3.3.0.md, docs/website/blog/2022-12-13-odo-v3.4.0.md, docs/website/blog/2023-01-04-odo-v3.5.0.md, docs/website/blog/2023-01-24-odo-v3.6.0.md, docs/website/blog/2023-02-15-odo-v3.7.0.md, docs/website/blog/2023-03-08-odo-v3.8.0.md, docs/website/blog/2023-04-05-odo-v3.9.0.md, docs/website/blog/2023-05-04-odo-v3.10.0.md, docs/website/blog/2023-06-27-odo-v3.12.0.md, docs/website/blog/2023-07-24-odo-v3.13.0.md, docs/website/blog/2023-08-22-odo-v3.14.0.md, docs/website/docusaurus.config.js
/kind bug
&mdash;
Ideally, we should test that all links in our docs are valid, but this is the scope of https://github.com/redhat-developer/odo/issues/6617.
=> Fix invalid link to installation page from all release blog posts

docs/website/docs/troubleshooting.md
See https://github.com/redhat-developer/odo/issues/7042#issue-1867300520 for more context and https://github.com/redhat-developer/odo/issues/7042#issuecomment-1727256098 for the reason behind this PR.
Fixes #7042 
=> Add troubleshooting explaining how to workaround port forwarding issues with the Podman remote client

.github/workflows/nightly-build.yaml, docs/website/docs/overview/installation.md
=> Generate checksums for nightly binaries

Dockerfile.rhel, docs/website/docs/command-reference/docs-mdx/init/devfile_from_any_registry_output.mdx, docs/website/docs/command-reference/docs-mdx/init/devfile_from_specific_registry_output.mdx, docs/website/docs/command-reference/docs-mdx/init/devfile_from_url_output.mdx, docs/website/docs/command-reference/docs-mdx/init/devfile_with_run-port_output.mdx, docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx, docs/website/docs/command-reference/docs-mdx/init/interactive_mode_empty_directory_output.mdx, docs/website/docs/command-reference/docs-mdx/init/latest_versioned_devfile_output.mdx, docs/website/docs/command-reference/docs-mdx/init/versioned_devfile_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_deploy_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_podman_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_podman_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_podman_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_podman_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx, pkg/version/version.go, scripts/rpm-prepare.sh
Relates to https://github.com/redhat-developer/odo/issues/6882
=> Bump version to 3.16.0

docs/pm-doc.md, docs/website/docs/user-guides/quickstart/java.md
=> Update Java SpringBoot documentation as there is no more limitation on
