docs/proposals/odo-deploy.md
Signed-off-by: Steven Groeger <groeges@uk.ibm.com>
/kind design
[skip ci]
PR updates the design proposal for `odo deploy` to utilise go's text/template format for template variables using within the deployment manifest. This will change the format to {{.PORT}} from just having PORT.
Fixes #?
=> Update `odo deploy` proposal to use go's text/template format for template variables

pkg/devfile/parse.go, pkg/devfile/parser/parse.go, pkg/devfile/parser/types.go, pkg/devfile/validate/components.go, pkg/devfile/validate/components_test.go, pkg/devfile/validate/validate.go, pkg/odo/cli/catalog/describe/component.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/devfile.go, pkg/odo/cli/component/push.go, pkg/odo/cli/component/test.go, pkg/odo/cli/component/watch.go, pkg/odo/cli/url/create.go
>
> [skip ci]
Moved odo specific logic ( validation ) out of devfile/parser package as we need that package to be independent of odo code.
This effort is important because other projects like che/devconsole can use odo's parser without having any dependency on odo.
No issue
=> moved odo specific logic out of devfile/parser package

scripts/openshiftci-presubmit-all-tests.sh, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/integration/component.go
/kind bug
On a successful oc command execution debug log goes to stderr channel. So widening the error check condition to avoid test script false alarm
Fixes #3547
pr https://github.com/openshift/release/pull/9431 should pass
=> Including exit code in stderr verification

pkg/sync/adapter.go
/kind bug
It resets the index for synced files to ensure that all files are synced when a pod is started/restarted or it is force pushed.
Fixes #3479
Instructions are provided on #3479
=> Reset index when force pushed

pkg/odo/cli/url/create.go, pkg/odo/util/validation/validation.go, tests/integration/devfile/cmd_devfile_url_test.go, tests/integration/devfile/docker/cmd_docker_devfile_url_test.go, tests/integration/generic_test.go
/kind bug
This PR improved `odo url create` flow by:
- avoiding to check experimental / docker / devfile mode all the time
- aggregate all validation errors so that they are reported at once instead of forcing the user to re-try the command several times in order to get things right
- add host name validation to avoid creating an invalid URL which would fail during `push`
Fixes #3589 
Before this PR: 
`odo url create --host https://127.0.0.1:60104 --ingress` would work without issue
After this PR:
`odo url create --host https://127.0.0.1:60104 --ingress` would fail with an error notifying the …
=> Improve `odo url create`

pkg/devfile/adapters/docker/component/adapter.go, pkg/devfile/adapters/docker/component/utils.go, pkg/devfile/adapters/kubernetes/component/adapter.go
/kind bug
post start event message gets printed as pre-start and printed also when there are no events.
```
Syncing to component nodejs
✓  Checking files for pushing [749597ns]
✓  Syncing files to the component [183ms]
Executing preStart lifecycle event commands for component nodejs
```
This PR updates from `preStart` to `postStart` and prints the message only when post start event present in devfile
Fixes #
run `odo push`, no event message gets printed if there are no events in devfile and correct event type is printed.
=> Fix post start event logged message

tests/integration/project/cmd_project_test.go
commenting flake test as it was previously
I actually uncommented a test scenario through https://github.com/openshift/odo/pull/3546 which is again hitting the same flake as reported in #2117 (Bot closed it). So commenting the spec again and reopening the issue for triage. 
Fixes NA 
Flake scenario is commented as it was.
=> Commenting project list -o json CI flake

pkg/envinfo/envinfo.go, pkg/envinfo/fake.go, pkg/odo/cli/component/devfile.go, pkg/odo/cli/component/push.go, pkg/watch/watch.go, pkg/watch/watch_test.go, tests/helper/helper_filesystem.go, tests/integration/devfile/cmd_devfile_debug_test.go, tests/integration/devfile/cmd_devfile_url_test.go, tests/integration/devfile/cmd_devfile_watch_test.go, tests/integration/devfile/utils/utils.go
/kind bug
If runMode is debug, odo watch will trigger push with debug settings else it will trigger normal  push.
Fixes #3480 
- Execute `odo push --debug`
- Execute `odo watch` and check if it detects debug mode for pushing files.
- Revert to `odo push` and check if it uses normal mode for pushing files.
=> Adds runMode to env for debugging with odo watch.

pkg/odo/cli/component/update.go
> /kind bug
> /kind design
> /kind flake
>
> [skip ci]
No issue - just noticed
----- ## Before -------
```
Update the source code path of a component
Usage:
odo update [flags]
Examples:
odo update --local ./frontend
odo update --git …
```
=> moved the deprecation warning from examples and moved to long desc

tests/e2escenarios/e2e_images_test.go
/king test
Verify test for private registry images. As per [comment](https://github.com/openshift/odo/issues/2537#issuecomment-635941209) It should work with multistage
Fixes #2537 
It should verify tests for private registry successfully as per [comment](https://github.com/openshift/odo/issues/2537#issuecomment-635941209) 
Run `make test-e2e-images`
=> adding tests to verify the private registry images

pkg/odo/cli/component/common_link.go, pkg/odo/cli/service/create.go, pkg/odo/cli/service/delete.go, pkg/service/service.go, tests/integration/operatorhub/cmd_service_test.go
/kind feature
This PR lets the user create a service named `myservice` when they do something like `odo service create etcdoperator.v0.9.4-clusterwide --crd EtcdCluster myservice`. This wasn't working earlier for Operator Hub backed services
It also does some refactoring of the code in `pkg/odo/cli/service/create.go`. Part of the business logic is moved to `service` package.
Fixes #3180
```sh
$ odo service create etcdoperator.v0.9.4-clusterwide --crd EtcdCluster myservice
$ odo service list
NAME                TYPE                      AGE
myservice            EtcdCluster               4s
```
=> Use the name provided on CLI to create an Operator backed service

docs/dev/logging.adoc, pkg/odo/cli/cli.go
/kind cleanup
This PR removes additional logging flags that are not needed as well as
unused by odo.
So `odo --help` now looks like this:
```sh
Flags:
--complete             Install completion for odo command
--uncomplete           Uninstall completion for odo command
-v, --v Level              Number for the log level verbosity. Level varies from 0 to 9 (default 0).
--vmodule moduleSpec   Comma-separated list of pattern=N settings for file-filtered logging
-y, --y                    Don't prompt user for typing 'yes' when installing completion
```
Fixes …
=> Remove additional / unneeded logging flags

docs/public/operator-hub.adoc, pkg/odo/cli/service/create.go, pkg/service/service.go, tests/integration/operatorhub/cmd_service_test.go
/kind cleanup
This PR changes the `odo service create` command for Operator backed service to make it more user friendly than what it currently is.
Fixes #3594 
```sh
$ odo service create etcdoperator.v0.9.4-clusterwide --crd EtcdCluster
$odo service create etcdoperator.v0.9.4-clusterwide/EtcdCluster
```
=> Makes service create command consistent with how it's done for Service Catalog

pkg/component/component.go, pkg/odo/cli/component/create.go, pkg/odo/cli/config/set.go, pkg/odo/util/validation/validators.go, tests/e2escenarios/e2e_images_test.go, tests/integration/cmd_push_test.go, tests/integration/component.go, tests/integration/devfile/utils/utils.go, tests/integration/generic_test.go
/kind cleanup
Cleans up and remove the memory and cpu flags from `odo create` command.
There parameters can be set using `odo config` command.
#3403 
=> cleanup #3403: removed --memory, --min-memory. --max-memory, --cpu, --min-cpu, --max-cpu flags from 'odo create' command

docs/file-reference/index.md, docs/public/deploying-a-devfile-using-odo.adoc
[skip ci]
TO PREVIEW: Click on: https://charliedrage.com/odo/file-reference/
This PR adds documentation regarding each section of Devfile and what we
support / do not support
N/A
N/A
=> Adds documentation on Devfile file reference

docs/file-reference/index.md
[skip ci]
Updates the file reference documentation to not have the introductory
section and move unsupported features to the bottom.
N/A
N/A
N/A
=> Update file reference documentation

pkg/odo/cli/url/delete.go
> /kind bug
> /kind design
> /kind flake
>
> [skip ci]
The `odo delete` doesn't work in experimental mode on **S2I** components. So this solves that.
No issue. Just observed
```
odo preference set Experimental false
odo preference set …
```
=> make odo delete work on s2i components in experimental mode

tests/helper/helper_kubectl.go, tests/helper/helper_oc.go
/kind bug
Fixes GetRunningPodNameByComponent() to prevent panics like https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/3651/pull-ci-openshift-odo-master-v4.5-integration-e2e/1288802599100747776#1:build-log.txt%3A935
Fixes #NA
=> Fixes GetRunningPodNameByComponent for the CLI runners

pkg/catalog/catalog.go, pkg/odo/cli/catalog/list/components.go
> /kind bug
> /kind design
/kind feature
make odo catalog list components work outside of experimental mode
Works towards experimental mode
```
odo catalog list components 
odo catalog list components -o json
```
both should work with openshift and kube cluster outside of experimental mode
=> make odo catalog list components work outside of experimental mode

pkg/devfile/adapters/common/command.go, pkg/devfile/adapters/common/command_test.go, tests/examples/source/devfiles/nodejs/devfileCompositeInvalidComponent.yaml, tests/integration/devfile/cmd_devfile_push_test.go
/kind bug
This PR fixes an issue with composite commands where exec subcommands are not validated (such as exec commands that reference an invalid component). With this PR, when we recursively validate the command-tree in a composite command, we now make sure to validate any exec commands. 
Composite subcommands were already being validated.
Fixes https://github.com/openshift/odo/issues/3656
1. Run integreation and unit tests
2. Test with sample devfile:
```
metadata:
name: nodejs
version: 1.0.0
projects:
- name: nodejs-starter
git:
location: …
```
=> Validate exec subcommands in a composite

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
/kind feature
Release 1.2.5 of odo
N/A
N/A
N/A
=> Release 1.2.5

pkg/devfile/adapters/docker/component/utils.go
/kind bug
@maysunfaisal found a bug with how we were setting `$PROJECTS_ROOT` in containers when on Docker. This was due to an improper if statement check when setting the env var in the container.
No issue opened, but can open one if needed.
=> Fix typo when setting PROJECTS_ROOT env on docker

docs/dev/experimental-mode.adoc, pkg/component/types.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/push.go, tests/integration/component.go, tests/integration/devfile/cmd_devfile_catalog_test.go, tests/integration/devfile/cmd_devfile_create_test.go
/kind feature
Fixes #3403 
Use the --s2i flag when using `odo create` to force S2i component over a namesake devfile component type.
=> feature #3403 : Added --s2i flag for 'odo create' command

pkg/devfile/adapters/common/command.go, pkg/devfile/adapters/common/command_test.go, pkg/devfile/adapters/common/interface.go, pkg/devfile/adapters/common/utils.go, pkg/devfile/adapters/docker/adapter.go, pkg/devfile/adapters/docker/component/adapter.go, pkg/devfile/adapters/docker/component/adapter_test.go, pkg/devfile/adapters/kubernetes/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter_test.go, pkg/devfile/validate/errors.go, pkg/devfile/validate/events.go, pkg/devfile/validate/events_test.go, pkg/devfile/validate/validate.go, pkg/kclient/errors.go, pkg/kclient/pods.go, pkg/odo/cli/component/delete.go, pkg/odo/cli/component/devfile.go, pkg/testingutil/devfile.go, pkg/testingutil/pods.go, tests/examples/source/devfiles/nodejs/devfile-with-valid-events.yaml, tests/integration/devfile/cmd_devfile_delete_test.go, tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/cmd_devfile_test_test.go, tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
/kind feature
- Executes `preStop` events, if present, before deleting the component
- Minor `odo delete` label/heading changes to reflect addition of preStop feature
- Add show flag to postStart event execution
- Add show flag to delete command on experimental
- Validate devfile events before using them
- Unit & Integration tests
Fixes #3566
Fixes #3632
Fixes #3655
- Add in preStop events to a devfile or you may try with this sample:
```
metadata:
name: nodejs
projects:
- name: nodejs-starter
git:
location: …
```
=> PreStop Event Feature

pkg/machineoutput/registry.go, pkg/odo/cli/registry/list.go, tests/integration/devfile/cmd_devfile_registry_test.go
>
> [skip ci]
Fixes #3659 
add json output method for `registry list` command
`odo registry list -o json`
=> Add Json output for registry output

pkg/watch/watch.go, tests/helper/helper_generic.go, tests/integration/devfile/cmd_devfile_watch_test.go, tests/integration/devfile/utils/utils.go
/kind bug
Disables the watch ticker when delay is set to 0.
Fixes #3439 
- Execute `odo watch --delay 0` on a odo component.
=> Fixes odo watch when delay is set to 0

tests/helper/helper_generic.go, tests/integration/devfile/cmd_devfile_catalog_test.go, tests/integration/devfile/cmd_devfile_create_test.go, tests/integration/devfile/utils/utils.go
/kind bug
/kind cleanup
PR skin s2i image check for kubernetes clusters due to the fact that imagestreams are not there with k8s.
Also code clean up.
Fixes #3713 
`make test-cmd-devfile-catalog` should run on both openshift and kubernetes cluster
=> Skiping s2iItem check on kubernetes cluster

tests/integration/component.go
/kind bug
PR removes the Ruby image component created from the branch ref
Fixes NA
PR - openshift/release#10346 should be unblocked.
Run `make test-cmd-cmp` and `make test-cmd-cmp-sub`
=> Removing the unsupported ruby image test

Makefile, docs/dev/test-architecture-ppc64le.adoc, scripts/configure-installer-tests-cluster-ppc64le.sh, scripts/openshiftci-presubmit-all-tests.sh
/kind feature
Enable upstream CI on ppc64le arch.
This PR is based on similar PR for IBM Z - https://github.com/openshift/odo/pull/3529
We have setup OCP 4.4 on IBM P. We download this ODO code from upstream and run the scripts/openshiftci-presubmit-all-tests.sh to trigger CI tests on IBM P.
=> CI support for ODO on IBM P

scripts/configure-installer-tests-cluster.sh, tests/e2escenarios/e2e_images_test.go
/kind bug
/kind feature
The issue I am facing right now is, pulling registry from registry.redhat.io test fails on ocp cluster 4.2, 4.3 and 4.4 prow periodic job with unauthorized error, however same test passes in ocp 4.5 prow pr job
```
[oc] ! error: Import failed (InternalError): Internal error occurred: Get https://registry.redhat.io/v2/openjdk/openjdk
-11-rhel8/manifests/latest: unauthorized: Please login to the Red Hat Registry using your Customer Portal 
credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
```
So we need to copy the default secret to the namespace
Fixes NA
**How to test changes / …
=> Applying secret to namespace for authenticated registry

scripts/setup-operators.sh
/kind bug
/kind feature
Adding fields to the operators subscription yaml which creates the operators successfully
Fixes #3741 
`make configure-installer-tests-cluster` should run for 4.* cluster including upcoming release
=> Fixing cluster service version issue for operators on 4.6 cluster

pkg/notify/notify.go
/kind cleanup
>
> [skip ci]
Add HTTP response caching to version notifier to reduce the number of requests that odo does to github.com
Fixes #?
=> add caching to version check

pkg/devfile/adapters/common/command_supervisor.go, pkg/devfile/adapters/common/generic.go
stop debug command, if we are running run command and vice versa
/kind bug
to restart any command in supervisord the way is to stop it and start it, in case of `restart:false` we are omitting the stop supervisord command step. It creates a problem when user switch modes during `odo push` (run/debug). This PR updates in case of `restart:false` we stop other command, like if it is `odo push --debug`,  we stop run command. 
Fixes #3738 
=> Stop other commands in case of restart false

.travis.yml, Makefile, pkg/devfile/adapters/common/utils_test.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/storage/utils.go, pkg/devfile/adapters/kubernetes/storage/utils_test.go, pkg/devfile/parser/context/context.go, pkg/devfile/parser/context/fake.go, pkg/devfile/parser/data/1.0.0/components.go, pkg/devfile/parser/data/2.0.0/components.go, pkg/devfile/parser/data/2.0.0/components_test.go, pkg/devfile/parser/data/common/errors.go, pkg/devfile/parser/data/common/types.go, pkg/devfile/parser/data/interface.go, pkg/devfile/parser/writer.go, pkg/devfile/parser/writer_test.go, pkg/kclient/volumes.go, pkg/odo/cli/storage/create.go, pkg/odo/cli/storage/delete.go, pkg/storage/labels/labels.go, pkg/storage/storage.go, pkg/testingutil/devfile.go, tests/helper/helper_cli.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/integration/cmd_storage_test.go, tests/integration/devfile/cmd_devfile_storage_test.go
/kind feature
Adds storage create and delete commands for devfile v2.
part of #3398 
fixes #3641 
- Create a devfile component
- Create a storage for the component `odo storage create <name> --path <path>`
- Check if the new volume was added to the devfile and mounted to all the container components.
- Execute `odo push`  and `oc get pvc` and check if the PVC was created or not.
- Delete the storage `odo storage delete <name> -f`
- Check the volume is removed from the devfile and unmounted from all the container components.
- Execute `odo push`  and `oc get pvc` and check if the PVC was deleted …
=> Adds storage create and delete commands for devfiles.

pkg/devfile/adapters/common/types.go, pkg/odo/cli/component/watch.go, pkg/sync/adapter.go, pkg/sync/adapter_test.go, pkg/util/file_indexer.go, pkg/util/file_indexer_test.go, pkg/watch/watch.go, pkg/watch/watch_test.go, tests/helper/helper_cli.go, tests/helper/helper_filesystem.go, tests/helper/helper_generic.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/helper/helper_run.go, tests/integration/devfile/cmd_devfile_watch_test.go, tests/integration/devfile/utils/utils.go
> /kind bug
- Fix the `odo watch` logic such that if you edit a devfile after watch has started, the changes to the devfile will now be picked up.
- Fix the `odo watch` logic such that it now updates the `.odo/odo-file-index.json` file, allowing it to play well with `odo push` if push is called immediately after watch
- Fix the `odo watch` logic to regenerate and use the file index to detect changes when `odo watch` is first invoked (in a particular session), with all subsequent updates during the session using the watched file list for changes
- Adds integration tests that test the behaviours that were failing in the linked issues
- Adds directory delete retry, with exponential backoff, to the `DeleteDir` test …
=> Watch command should better handle file synchronization/error reporting when push command is invoked before/after the watch

README.adoc, scripts/configure-installer-tests-cluster-s390x.sh, scripts/openshiftci-presubmit-all-tests.sh, tests/e2escenarios/e2e_images_test.go
There are some hard code to import S2I images. These images only support amd64 arch which causes failed on s390x arch.
Fixes #3670 
=> Update e2e supported images test to support s390x arch.

pkg/odo/cli/env/env_test.go
The printing order in printSupportedParameters() is dependent on a for loop over a map which is random in nature. Thus the unit test should not check for a complete match.
Fixes #3755
- Unit test for printSupportedParameters() should pass without flakes.
=> Updates test for printSupportedParameters to fix flake

tests/helper/helper_generic.go, tests/integration/devfile/cmd_devfile_log_test.go
/kind flake
Fixes the flag for `odo log -f` test. This PR updates the test to check the log until expected log is printed and timeout if it doesn't gets logged in specified timeout duration.
Fixes #3610
=> Fix odo log flake

scripts/generate-coverage.sh
/kind bug
support `make test-coverage` for s390x arch
Fixes #3756 
=> Fix the make test-coverage for s390x arch

pkg/devfile/validate/validate.go, tests/integration/devfile/cmd_devfile_push_test.go
/kind cleanup
This PR removes the ability to create v1 devfiles in odo, and adds a validation error when a user tries to use one, as most v1 devfiles no long work with odo (and we have feature parity with v2 devfiles)
```
Johns-MacBook-Pro-3:test johncollier$ odo push
✗  unsupported devfile version. Only devfiles with schema version 2.0.0 are supported
```
Fixes https://github.com/openshift/odo/issues/3621
=> Prevent v1 devfiles from being used

pkg/devfile/adapters/common/exec.go, pkg/devfile/adapters/common/exec_test.go, pkg/sync/adapter.go, pkg/sync/adapter_test.go, tests/helper/helper_generic.go, tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/utils/cmd_devfile_push_test_utils.go
/kind bug
- This PR ensures that if `forcePush` is set during a sync operation, that the sync directory is cleared before updated files are copied to the sync directory. 
- This PR adds a test that verifies the correct behaviour described in the original issue.
Fixes #3460
See issue #3460 for step-by-step reproduction steps.
=> Sync operation within the Push command does not remove deleted/renamed files

pkg/odo/cli/url/list.go, tests/integration/devfile/cmd_devfile_url_test.go
/kind bug
Fixes `odo url list` for s2i components with experimental mode on.
Fixes #3474
- turn on experimental mode
- `odo create nodejs --s2i`
- trigger `odo url create` for both ingress and routes
- `odo url list` should display both the URLs
=> Fixes odo url list for s2i components

openshift-ci/build-root/Dockerfile.travislogin
/kind Feature
we are in process of getting the odo-bot GitHub token injected into prow. So creating a test container from where all these short of operation like travis cli install, travis login... etc will be launched 
Fixes : part of #2540 
Should not break master
```
$ docker run -it registry.svc.ci.openshift.org/openshift/release:golang-1.13
$ yum -y install sudo make wget gcc git httpd-tools ruby ruby-devel gcc-c++ patch \
readline readline-devel zlib zlib-devel libffi-devel openssl-devel make bzip2 \
autoconf automake libtool bison sqlite-devel
$ sudo curl -sSL https://rvm.io/mpapis.asc | …
```
=> Docker test container for travis login

.travis.yml, Makefile
/kind feature
$SUBJECT It was missed in the make target. To run the individual target we need it.
Fixes NA
`make test-plugin-handler` as well as `make test-integration` should run
=> Adding plugin handler test makefile target

pkg/component/component_full_description.go
Signed-off-by: Denis Golovin <dgolovin@redhat.com>
/kind bug
> /kind design
> /kind flake
>
> [skip ci]
make 'odo describe' print out linked components for component
Fixes #3766.
=> Fix describe to print out linked components list

tests/integration/devfile/cmd_devfile_env_test.go
/kind cleanup
clean up devfile env tests and uses dns supported component name 
=> clean up devfile env tests and uses dns supported component name 

pkg/component/component_full_description.go
Signed-off-by: Denis Golovin <dgolovin@redhat.com>
/kind bug
> /kind design
> /kind flake
>
> [skip ci]
Fix odo describe for components with linked services. Adds linked services information to human/machine readable output.
Similar to #3766.
=> Fix odo describe for component with linked services

pkg/odo/cli/cli.go, tests/integration/generic_test.go
/kind bug
> /kind design
> /kind flake
>
> [skip ci]
see $SUBJECT
Fixes https://github.com/openshift/odo/issues/3750
```
odo hello 
```
should only print help once
=> remove showing help twice for incorrect commands

openshift-ci/build-root/Dockerfile.travislogin
/kind bug
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/10942/rehearse-10942-pull-ci-openshift-odo-master-macOS-testmasoshost/1297231399283068928#1:build-log.txt%3A280
Fixes - It will fix the docker build issue for pr https://github.com/openshift/release/pull/10942
pr https://github.com/openshift/release/pull/10942 should not fail with ```error: build error: running 'rvm requirements run' failed with exit code 127```
=> Fixing rvm error and Docker file format for travis login

scripts/setup-operators.sh, tests/integration/operatorhub/cmd_service_test.go
/kind feature
There is no `mongodb-enterprise` operator available on 4.6 cluster build released after 2nd Aug. In Spite of just removing mongodb operator, planned to replace it with `percona-server-mongodb-operator` which is available for all the versions.
Fixes NA but its blocking pr https://github.com/openshift/release/pull/10346
New operator `percona-server-mongodb-operator` should be successfully installed. Also `make test-operator-hub` should pass
=> Replace unstable mongodb-enterprise operator subscription with percona-server-mongodb-operator

pkg/envinfo/envinfo.go, pkg/odo/cli/component/common_link.go, pkg/service/service.go, tests/integration/operatorhub/cmd_service_test.go
/kind feature
Adds support for unlinking a component from an Operator backed service with `odo unlink` command
Fixes #3563
1. Install "Service Binding Operator" on the OpenShift cluster.
1. Create a `nodejs` component using https://github.com/akashshinde/node-todo. Use this devfile for things to work fine:
<details>
```yaml
metadata:
name: nodejs
version: 1.0.0
projects:
- name: nodejs-starter
git:
location: "https://github.com/odo-devfiles/nodejs-ex.git"
components:
- container:
name: runtime
image: registry.access.redhat.com/ubi8/nodejs-12:1-36
memoryLimit: 1024Mi
mountSources: …
```
=> Add support for unlinking component from service

.travis.yml, Makefile, pkg/config/config.go, pkg/config/env_var.go, pkg/config/storage.go, pkg/devfile/parser/configurables.go, pkg/devfile/parser/configurables_test.go, pkg/devfile/parser/data/2.0.0/components.go, pkg/devfile/parser/representation.go, pkg/envinfo/envinfo.go, pkg/odo/cli/config/config.go, pkg/odo/cli/config/set.go, pkg/odo/cli/config/unset.go, pkg/odo/cli/config/view.go, pkg/odo/genericclioptions/context.go, pkg/odo/genericclioptions/context_flags.go, pkg/preference/preference.go, pkg/preference/preference_test.go, tests/integration/cmd_pref_config_test.go, tests/integration/devfile/cmd_devfile_config_test.go
/kind feature
Add `odo config` support for devfile. This command should work outside of experimental mode by default
Fixes https://github.com/openshift/odo/issues/2688
```
odo config set name blah
odo config unset name
odo config set ports 8080,8081
odo config unset port
odo config set --env HI=Hello
odo config set --env DebugPort=5858
odo config unset --env HI
odo config set memory 512Mi
```
=> odo config for devfile

tests/integration/operatorhub/cmd_service_test.go
I don't know. It's pretty sure not a bug! This PR is mainly opened to fix something that's working just fine on developer/QE systems but failing in CI.
This is being done for two reasons:
1) CI is likely slow to link/unlink as observed in
https://github.com/openshift/odo/issues/3834
2) link/unlink require "odo push" for underlying deployment
Fixes #3834
=> Add odo push to link/unlink tests

pkg/odo/cli/component/watch.go
/kind bug
As per the linked issue, `odo watch` is redeploying the application on first use, but shouldn't be. This is because the application name is not set properly in the watch parameters of `pkg/odo/cli/component/watch.go`, which causes the `"app.kubernetes.io/part-of"` label to be incorrectly set to `""` on the watch-initiated deployment.
Since the `part-of` label has (incorrectly) changed (to `""` from `"app"`, for example), the push logic detects this as a deployment change, and performs a redeploy.  This is why the redeploy is occurring. Fixing the application name at the source (`watch.go`) resolves the issue.
Application name is not being set on the watch parameters, which causes the push code to detect …
=> Fix #3841 - odo watch redeploys component during first push 

pkg/util/util.go
=> fix: remove requirement for URL to end with .zip

doks-theme/_layouts/homepage.html
Removes the logos from the index page for Docker / Kubernetes /
OpenShift since we are already neutral / agnostic and Devfile is
compatible with both Kubernetes and OpenShift.
=> Remove logos from index page

docs/public/deploying-a-devfile-using-odo.adoc, pkg/odo/cli/component/create.go, pkg/odo/cli/url/create.go
/kind cleanup
Updates the `--help` in the following way:
- Changes the `odo create --help` usage to a 1-sentence summary similar
to every other command
- Updates our documentation to remove any mention of crc for something
more neutral (example.com) similar to kubectl / kubernetes
documentation, for example: https://kubernetes.io/docs/concepts/services-networking/ingress/
Fixes https://github.com/openshift/odo/issues/3463
`odo create --help`
and
`odo url …
=> Update the help usage for odo create and odo url create

pkg/odo/genericclioptions/context.go
/kind bug
> /kind design
> /kind flake
>
> [skip ci]
Fixes #3829
`odo delete`
=> not provide %s for namespaces in logs

pkg/odo/cli/component/devfile.go, pkg/odo/cli/component/log.go, pkg/odo/cli/component/test.go
> /kind design
> /kind flake
>
> [skip ci]
See title
Fixes #2959 
=> Fixing os.GetWd() usage for getting component name

docs/public/debugging-using-devfile.adoc, docs/public/deploying-a-devfile-using-odo.adoc, docs/public/operator-hub.adoc
[skip ci]
There are outdated portions of our documentation that asks for you to
enable experimental mode before using Devfile or Operator Hub.
Both of those have moved out of experimental mode.
Since our website (https://odo.dev) reflects using the `alpha` release,
we must update the outdated documentation.
N/A
N/A
=> Remove experimental mode from docs

pkg/odo/cli/component/create.go, pkg/odo/cli/component/exec.go, pkg/odo/cli/debug/debug.go, pkg/odo/cli/debug/info.go, pkg/odo/cli/debug/portforward.go, pkg/odo/cli/url/delete.go, tests/integration/devfile/cmd_devfile_debug_test.go, tests/integration/devfile/cmd_devfile_delete_test.go, tests/integration/devfile/cmd_devfile_exec_test.go, tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/cmd_devfile_test_test.go, tests/integration/devfile/cmd_devfile_url_test.go, tests/integration/devfile/cmd_devfile_watch_test.go, tests/integration/devfile/utils/utils.go
/kind bug
/kind cleanup
- only `odo create` needs the devfile flag to copy contents from the specified flag to project dir/context dir devfile.yaml
- devfile is always devfile.yaml, so no point in having a devfile flag for non create commands
- commands listed in the issue do not require --devfile flag
- there were some bugs when using --context and --devfile flags for the command listed, they have been fixed
- updated integration tests
Fixes #3661 
- Run the commands with the devfile flag; it should err out
- Run the commands with the …
=> Remove unnecessary devfile flag and update tests

scripts/cross-compile.sh
- This is a soft requirement for downstream releases
which will need waiver every time, if not done
```
❯ make bin
go build -ldflags="-w -X github.com/openshift/odo/pkg/version.GITCOMMIT=9a32c42a9" cmd/odo/odo.go
❯ objdump --syms ./odo | grep debug
0000000002009460 l     O .rodata	0000000000000014              debugCallFrameTooLarge
000000000045dea0 l     F .text	0000000000000049              debugCall32
000000000045def0 l     F .text	0000000000000049              debugCall64
000000000045df40 l     F .text	000000000000006d              debugCall128
000000000045dfb0 l     F .text	0000000000000070              debugCall256
000000000045e020 l     F .text	0000000000000070              debugCall512
000000000045e090 l     F …
```
=> Updating cross-compile script to produce stripped binaries

scripts/configure-installer-tests-cluster-s390x.sh
/kind bug
The upstream library updates the link for s2i imagestream. There are errors when running odo ci script on OCP/Z.
```
oc annotate istag/wildfly:latest --namespace=openshift tags=builder --overwrite
imagestreamtag.image.openshift.io/wildfly:latest annotated
++ oc apply -n openshift -f https://raw.githubusercontent.com/openshift/library/master/arch/s390x/official/nginx/imagestreams/nginx-rhel7.json
error: unable to read URL "https://raw.githubusercontent.com/openshift/library/master/arch/s390x/official/nginx/imagestreams/nginx-rhel7.json", server reported 404 Not Found, status code=404
```
Fixes #?
**How to test changes / Special notes to the …
=> Update s2i image from library.

pkg/sync/adapter.go, tests/integration/devfile/cmd_devfile_push_test.go
/kind bug
See https://github.com/openshift/odo/issues/3838#issuecomment-682259193
Fixes #3838
See https://github.com/openshift/odo/issues/3838 for test reproduction steps.
=> Fix #3838: Component is left in broken state after redeployment of the pod 

pkg/catalog/catalog.go, pkg/catalog/catalog_test.go, pkg/catalog/types.go, pkg/odo/cli/catalog/list/components.go, pkg/odo/cli/component/create.go, pkg/odo/cli/env/env.go, pkg/odo/cli/env/env_test.go, pkg/odo/cli/registry/list.go
/kind bug
/area devfile
Issue: Currently we concurrently retrieve devfile index file from different registries, which means the order of registry and components in the registry is random depends on the speed and load of each concurrent thread.
This PR implements a new algorithm/data structure to add registry priority for all registries by taking advantage of the nature of the array index so that ensure the correctness registry/component display order (the newly added registry/component has highest priority). More specifically, the PR implements:
- Registry has priority (Newly added registry has the highest priority)
- Display order is correct + still use …
=> Add registry priority to ensure registry/component display order

docs/file-reference/index.md, docs/public/using-devfile-lifecycle-events.adoc, pkg/devfile/adapters/common/utils.go, pkg/devfile/adapters/common/utils_test.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/storage/utils.go, pkg/devfile/adapters/kubernetes/utils/utils.go, pkg/devfile/adapters/kubernetes/utils/utils_test.go, pkg/devfile/parser/data/common/command_helper.go, pkg/devfile/parser/data/common/command_helper_test.go, tests/examples/source/devfiles/nodejs/devfile-with-valid-events.yaml, tests/helper/helper_cli.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/integration/devfile/cmd_devfile_push_test.go
/kind feature
- Implements PreStart feature Issue
- Executes PreStart events as init containers for the odo component pod
- updates docs
Fixes #3565
- Add in `preStart` event to your devfile and check the init containers on the odo component pod
You can also utilize this devfile that I've been using for testing, that has a mixture of exec and composite commands as preStart:
```
metadata:
name: nodejs
projects:
- name: nodejs-starter
git:
location: "https://github.com/odo-devfiles/nodejs-ex.git"
components:
- container:
name: runtime
image: …
```
=> PreStart Feature PR

docs/dev/experimental-mode.adoc, docs/public/deploying-a-devfile-using-odo.adoc
Signed-off-by: John Collier <jcollier@redhat.com>
[skip ci]
A while back, the default devfile stacks were updated to follow a consistent naming scheme (e.g. `java-spring-boot` -> `java-springboot`), but it appears some of the documentation that references the spring boot stack was not updated accordingly.
Fixes https://github.com/openshift/odo/issues/3863
=> Update doc references to spring boot [skip ci]

README.adoc, docs/public/understanding-odo.adoc
[skip ci]
Updates the README to reflect the changes to our default deployment
mechanism to Devfile.
This also links all documentation to the website rather than
docs.openshift.com
Another point is an emphasis of saying "Kubernetes and OpenShift" rather
than "OpenShift and Kubernetes", making Kubernetes more of a first-class
point.
Fixes https://github.com/openshift/odo/issues/3161
N/A. View the documentation.
Signed-off-by: Charlie Drage …
=> Update the README to reflect Devfile

pkg/odo/cli/component/create.go, tests/integration/devfile/cmd_devfile_create_test.go
- --now flag now works with component create with devfiles
- cleaning up the component create a little bit
- adding integration tests for implemented functionality
> /kind bug
> /kind design
/kind feature
> /kind flake
>
> [skip ci]
see above
Fixes #3469 
```
❯ odo create nodejs --now
Experimental mode is enabled, use at your own risk
Validation
✓  Checking …
```
=> Implementing missing --now for component create with devfile

scripts/configure-installer-tests-cluster-ppc64le.sh
/kind bug
Similar to PR #3861 . The upstream library updated the link for s2i imagestreams. There are errors when running odo ci script on OCP/P. Errors of following types are observed. 
```
++ oc apply -n openshift -f https://raw.githubusercontent.com/openshift/library/master/arch/ppc64le/official/nginx/imagestreams/nginx-rhel7.json
error: unable to read URL "https://raw.githubusercontent.com/openshift/library/master/arch/ppc64le/official/nginx/imagestreams/nginx-rhel7.json", server reported 404 Not Found, status code=404
++ oc apply -n openshift -f https://raw.githubusercontent.com/openshift/library/master/arch/ppc64le/official/php/imagestreams/php-rhel7.json
error: unable to read URL …
```
=> Update s2i image from library for ppc64le

docs/dev/logging.adoc, pkg/devfile/adapters/common/command.go, pkg/devfile/adapters/common/exec.go, pkg/devfile/adapters/common/generic.go, pkg/devfile/adapters/common/utils.go, pkg/devfile/adapters/docker/component/adapter.go, pkg/devfile/adapters/docker/component/utils.go, pkg/devfile/adapters/docker/storage/utils.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/storage/utils.go, pkg/devfile/adapters/kubernetes/utils/utils.go, pkg/devfile/parser/context/apiVersion.go, pkg/devfile/parser/context/content.go, pkg/devfile/parser/context/context.go, pkg/devfile/parser/context/schema.go, pkg/devfile/parser/data/helper.go, pkg/devfile/parser/parse.go, pkg/devfile/parser/writer.go, pkg/devfile/validate/events.go, pkg/devfile/validate/validate.go, pkg/kclient/deployments.go, pkg/kclient/namespace.go, pkg/kclient/operators.go, pkg/kclient/pods.go, pkg/lclient/images.go, pkg/occlient/occlient.go, pkg/occlient/utils.go, pkg/occlient/volumes.go
/kind cleanup
This PR updates all debugging information to separate caterogies in
order to make debugging easier.
For example, if we were to want to only output Devfile and experimental debugging
information we would simply do `odo -v 3`.
For fine tuning, one can use `--vmodule "*=3,*=4` to get very specific
debugging outputs.
Fixes https://github.com/openshift/odo/issues/3007
N/A
N/A
To test:
```sh
odo create nodejs --starter
odo push --vmodule "*=3,*=4" -v 0
```
=> Categorizes debugging information

Makefile
>
> [skip ci]
official method using install.sh doesn't support ppc64
Fixes https://github.com/openshift/odo/issues/3891
=> use go get to download gosec

Makefile
/kind cleanup
There is a regression failure with docker tests which has been tracked https://github.com/openshift/odo/issues/3714 . So just commented out the targets from Makefile. 
Fixes NA
=> Makefile docker target clean up

scripts/setup-operators.sh
/kind bug
/kind feature
Operators are unstable with 4.6 cluster which causing our operator tests to get failed. However there is a common change in start csv version for service binding in all over 4.* cluster. This pr should handle those either by just removing the unstable operators or using workarounds like fetching the operators into the cluster.
Fixes NA
`make test-operator-hub` should pass.
=> Sync operators on 4.* cluster

Makefile, rpms/openshift-odo.spec, scripts/openshiftci-presubmit-unittests.sh, scripts/rpm-local-build.sh, scripts/rpm-prepare.sh, scripts/rpm-x86_64-test.sh
/kind cleanup
- downloading deps in rpm build is a big no
- some cleanup
**Changes**:
- rpmspec `Provides` and `Obsoletes` is more specific (this removes warnings as well)
- rpm local build script now uses dist/rpmbuild as topdir
- explicit `GOFLAGS=-mod-vendor` for `make test` in rpm spec (see https://gist.github.com/mohammedzee1000/81382df2c2a0c67411966e55aa5c1dd2) we cannot have deps being pulled in release
- Added rpm testing
=> Cleaning up odo rpm spec and scripts

pkg/preference/preference.go, pkg/preference/preference_test.go
/kind bug
Fix the case where default registry is not initialized when user already has a `preference.yaml` file without devfile registries
Fixes #3940 
1. Manually remove all devfile registries in `preference.yaml` file
2. Run `odo registry list`, `odo catalog list components` and `odo create <component type>`, all commands should work propertly
=> Fix default registry support

pkg/sync/adapter.go, pkg/sync/adapter_test.go, tests/examples/source/devfiles/nodejs/devfile-with-multiple-projects.yaml, tests/examples/source/devfiles/nodejs/devfile-with-projects.yaml, tests/integration/devfile/cmd_devfile_push_test.go
/kind feature
If a single project is present in devfile:
- if project.clonePath is present sync to $PROJECTS_ROOT/clonePath
- if clonePath not set sync to $PROJECTS_ROOT/projectName
if no project or multiple project present in devfile 
- sync to $PROJECTS_ROOT
The value of $PROJECTS_ROOT is determined by `sourceMapping` field in devfile or `PROJECTS_ROOT` env variable. if both are unset default is `/projects`. 
Fixes #3729 
* create nodejs component from file https://github.com/openshift/odo/pull/3907/files#diff-233e1a3be07da905fb5e3d944f1e3398
* verify the source code sync location with `kubectl …
=> Implement clonePath, update source code sync location

pkg/util/util.go, pkg/util/util_test.go
/kind bug
/area devfile
This PR adds more requirements to URL format validation so that gate more invalid registry URLs
Fixes #3451 
Run `odo registry add test <invalid URL>`, for example run `odo registry add test http://$$$$,,,,,@hdjh.hcgcyd `
=> Improve URL format validation

pkg/component/component.go, pkg/kclient/deployments.go, pkg/occlient/occlient.go, pkg/odo/cli/catalog/list/services.go, pkg/odo/cli/component/common_link.go, pkg/odo/cli/component/link.go, pkg/odo/cli/component/unlink.go, pkg/odo/cli/service/create.go, pkg/odo/cli/service/delete.go, pkg/odo/cli/service/list.go, pkg/odo/genericclioptions/context.go, pkg/odo/util/cmdutils.go, tests/integration/cmd_link_unlink_test.go, tests/integration/operatorhub/cmd_service_test.go, tests/integration/servicecatalog/cmd_service_test.go
/kind feature
It moves Operator Hub integration out of experimental mode. We need it for v2.
Fixes #3595 
* Tests should pass.
* If Operators are supported by the cluster (4.x), we ignore service catalog altogether.
* If user's working with 3.x cluster, odo should support Service Catalog (if enabled by the user).
=> Move Operator Hub out of experimental mode

OWNERS
[skip ci]
Add OWNERS file to gh-pages branch, so we can approve PRs
=> Add owners to gh pages

pkg/devfile/adapters/common/command.go, pkg/devfile/adapters/common/command_test.go, pkg/devfile/adapters/common/utils.go, pkg/devfile/adapters/common/utils_test.go, pkg/devfile/parse.go, pkg/devfile/parser/data/2.0.0/components.go, pkg/devfile/parser/data/common/component_helper.go, pkg/devfile/parser/data/common/component_helper_test.go, pkg/devfile/validate/commands.go, pkg/devfile/validate/commands_test.go, pkg/devfile/validate/errors.go, pkg/devfile/validate/events.go, pkg/devfile/validate/events_test.go, pkg/devfile/validate/validate.go, tests/examples/source/devfiles/nodejs/devfile-with-valid-events.yaml, tests/examples/source/devfiles/nodejs/devfileCompositeInvalidComponent.yaml, tests/integration/devfile/cmd_devfile_push_test.go
/kind cleanup
- migrates devfile command validation to validate pkg along with other devfile validation
- devfile commands are now validated anytime we parse devfile and not only during odo push when using the command
- cleaned up some code
- updated unit tests
Fixes #3703 
- Make invalid changes to the devfile command and any odo command that parses the devfile should err out
=> Migrate devfile cmd validation to validate pkg

pkg/odo/cli/utils/convert.go, tests/integration/component.go
/kind bug
update s2i to devfile conversion to not save url info in env.yaml.
https://github.com/openshift/odo/issues/3910
Fixes #?
=> update s2i to devfile conversion as per new url design

pkg/odo/genericclioptions/context.go, pkg/util/file_indexer.go, tests/integration/devfile/cmd_devfile_watch_test.go, tests/integration/devfile/utils/utils.go
Signed-off-by: Maysun J Faisal <maysunaneek@gmail.com>
/kind bug
- previously when we used `--ignore`, `.odoignore`/`.gitignore` was overwritten. Hence if odo index file `.odo/odo-file-index.json` changed due to a file change, it got stuck in an infinite loop
- Similarly, if the local project was a git project, it would build more than once for `.git` changes
- This PR adds `.odo/odo-file-index.json` & `.git` to the list of ignored files when `--ignores` is used
Fixes #3819 
Fixes #3961
`odo watch --ignore some.txt` and create a file in the component directory. It should only build once.
=> Add mandatory file ignores when using --ignore flag

pkg/odo/cli/component/push.go
/kind cleanup
Clarifies the help text for the `-f` / `--force-build` flag in `odo push`, as outlined in https://github.com/openshift/odo/issues/3919
Fixes https://github.com/openshift/odo/issues/3919
=> Clarify description of the force-build flag in help text for odo push

pkg/kclient/pods.go, tests/integration/devfile/cmd_devfile_log_test.go
/kind bug
passes container name for odo log, we are already passing container name for `odo log -f`, It seems it got missed from `odo log` 
Test updated to use springboot multi containers devfile, also refactored test code.
Fixes #3711
=> Fix odo log for multi containers devfile

pkg/occlient/occlient.go, pkg/occlient/occlient_test.go
/kind bug
s2i builder images available on OCP 4.6 has metadata where exposed ports are listed only in `Config` section.
Previously we were incorrectly using Exposed ports from `ContainerConfig`.  
fixes https://github.com/openshift/odo/issues/3882
`odo create nodejs --s2i` on OCP 4.6 used to fail, now it should work. you can check issue for more info
=> s2i component fix: use Config instead of ContainerConfig for port detection

docs/public/community.adoc, docs/public/deploying-a-devfile-using-odo.adoc
[skip ci]
Removes references to deploying via Docker
N/A
N/A
=> Remove references to Docker support

go.mod, go.sum
CI jobs are failing on 
```
go: github.com/openshift/library-go@v0.0.0-20200407165825-2e79bd232e72 requires
bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
```
original bitbucket repo was mercurial. Mercurial support on bitbucket is being deprecated
Fixes https://github.com/openshift/odo/issues/3983
=> vendor: switch location of goautoneg to github

pkg/odo/cli/debug/debug.go, pkg/odo/cli/debug/portforward.go
/kind cleanup
Updates the debug output of `odo debug --help` to the following:
```sh
github.com/openshift/odo  debugging-docs-update ✔                                                                                                                                                                                                                                                                                                                      53m
▶ ./odo debug --help
Debug allows you to remotely debug your application.
Usage:
odo debug [flags]
odo debug [command]
Aliases:
debug, d
Examples:
odo debug port-forward
odo debug port-forward --local-port 5000
odo debug info
Available Commands:
info         Displays debug …
```
=> Update odo debug --help screen

tests/integration/devfile/cmd_devfile_url_test.go
/kind bug
See $SUBJECT
No issue
test should pass
=> add test for odo url create --context flag

pkg/odo/cli/url/create.go, tests/integration/devfile/cmd_devfile_url_test.go
/kind bug
/area devfile
/area url
The `--port` flag should be an optional flag if there is only one port exposed in devfile. 
This PR fixes the regression.
Also created an integration test for the specific case
Fixes #3923 
`make test-cmd-devfile-url`
Manual Test: 
`odo url create` should successfully create an endpoint in devfile
=> 3923- url creation with optional port flag

pkg/odo/cli/component/link.go
/kind bug
It fixes bug wherein `odo link -h` prints same help message for both 3.x & 4.x clusters
Fixes #3992 
Check `odo link -h` by logging into OCP 3.x & 4.x clusters.
=> Prints help message based on backend cluster

pkg/odo/cli/component/link.go, tests/integration/cmd_link_unlink_test.go
/kind cleanup
It removes check for CSV support by a cluster at the time of initialization of `odo link` command.
Fixes #4008 
`odo link -h` should display same message irrespective of the backing cluster being 3.x, 4.x or k8s.
=> Do not check for CSV when initializing odo link command

docs/public/operator-hub.adoc
[skip ci]
Adds more documentation for Operator Hub integration with odo
Fixes #3810 
Read the docs!
=> Document odo and Operator Hub integration

pkg/odo/cli/component/create.go
/kind cleanup
Removed the `Checking devfile compatibility` stage from odo create as it does nothing for the time being.
No issue
```
$$ odo create java tttt
Validation
✗  Checking devfile existence [25365ns]
⚠  Devfile component type java is not supported, please run `odo catalog list components` for a list of supported devfile component types
```
```
$$ odo create java tttt
Validation
✗  Checking devfile existence [22940ns]
✗  Checking devfile compatibility [9417ns]
⚠  Devfile component type ls is not supported, please run `odo catalog list components` for a list of supported devfile component …
```
=> removed some irrelevant steps from odo create and cleanup

go.mod, go.sum
What does does this PR do / why we need it:
`make goget-ginkgo` fails on PSI
```
++ make goget-ginkgo
go: github.com/openshift/library-go@v0.0.0-20200407165825-2e79bd232e72 requires
vbom.ml/util@v0.0.0-20180919145318-efcd4e0f9787: unrecognized import path "vbom.ml/util" (https fetch: Get https://vbom.ml/util?go-get=1: dial tcp: lookup vbom.ml on 10.11.142.1:53: no such host)
GOFLAGS='' go get github.com/onsi/ginkgo/ginkgo@v1.14.0
go: github.com/openshift/library-go@v0.0.0-20200407165825-2e79bd232e72 requires
vbom.ml/util@v0.0.0-20180919145318-efcd4e0f9787: unrecognized import path "vbom.ml/util" (https fetch: Get https://vbom.ml/util?go-get=1: dial tcp: lookup vbom.ml on 10.11.142.1:53: no such host)
make: *** [Makefile:109: goget-ginkgo] …
```
=> replace unrecognised vendor dependency in go mod

pkg/devfile/parser/data/2.0.0/devfileJsonSchema200.go, pkg/devfile/parser/data/common/types.go
Signed-off-by: Stephanie <yangcao@redhat.com>
/kind bug
/area devfile
Our devfile schema and type defined are missing the two optional metadata shown in the devfiles. Which result in the devObj parsed from the devfile missing those optional metadata. 
And modification action to the devfile through odo would lose those metadata in the new devfile. 
Fixes #3968 
create a devfile component, ` odo create nodejs --starter`
create a new url to update the existing devfile, `odo url create --port 4000`
check the updated devfile, should still see those two optional metadata in devfile
=> 3968-add more optional metadata

tests/e2escenarios/e2e_images_test.go
Add missing `--s2i` flag in e2e image test for s2i components
Fixes NA
`make test-e2e-all` should pass successfully.
=> Added missing s2i flag for e2e test

docs/file-reference/index.md, pkg/devfile/adapters/common/utils.go, pkg/devfile/adapters/kubernetes/utils/utils.go, pkg/devfile/adapters/kubernetes/utils/utils_test.go, pkg/devfile/validate/components.go, pkg/devfile/validate/components_test.go, pkg/devfile/validate/errors.go, pkg/sync/adapter.go, pkg/sync/adapter_test.go, pkg/testingutil/devfile.go, tests/examples/source/devfiles/nodejs/devfile-with-multiple-projects.yaml, tests/examples/source/devfiles/nodejs/devfile-with-projects.yaml, tests/helper/helper_cli.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/integration/devfile/cmd_devfile_describe_test.go, tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/utils/utils.go
Signed-off-by: Maysun J Faisal <maysunaneek@gmail.com>
/kind feature
- Introduces an env, `PROJECT_SOURCE` to all component containers that mount sources
- devfile can now use `PROJECT_SOURCE` which holds the project path in a container
- `PROJECT_SOURCE` value depends upon container's `sourceMapping` & project's `clonePath`
- Updated `GetSyncFolder()` logic for devfile containing more than one project ie; the first project is now selected
- New and updated tests
- Updated public docs about env
- `PROJECTS_ROOT` & `PROJECT_SOURCE` are reserved, check https://github.com/devfile/api/issues/132
Fixes #3781 
- push odo component …
=> Save PROJECT_SOURCE for containers mounting source

docs/public/community.adoc
[skip ci]
Fixes minor docs issue in the community doc
N/A
N/A
=> Fix minor docs issue in community page

scripts/configure-installer-tests-cluster-ppc64le.sh, scripts/openshiftci-presubmit-all-tests.sh, tests/e2escenarios/e2e_java_test.go, tests/e2escenarios/e2e_source_test.go
/kind feature
Update integration testcases and e2e testcases for ppc64le support after testing on Power system.
Fixes #?
=> Update integration testcases and e2e testcases for ppc64le support

pkg/odo/cli/component/list.go
/kind bug
`odo list` returns an error when there are no components but `odo list -o json` returns empty lists. Both approach are subjective but we need to make things consistent. Hence we dont return an error now if there are no components
No issue
Everything should work as expected
=> make odo list's output for no components consistent

docs/public/debugging-using-devfile.adoc
Since the local port default of 5858 is hard-coded into odo it seemed fitting to include it in the same VS Code debugger config for emphasis.  
Also the 'debugrun' id doesn't really match anything or have meaning.
Sorry, I missed the "[skip ci]" in the commit message the first time so force pushed over to add it.
**Which issue(s) this PR fixes**:  Seemed too small to open an issue.
Fixes #?
- [X ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)
=> Show debugger config matching default local port 5858

pkg/sync/adapter.go, pkg/watch/watch.go, tests/integration/devfile/utils/utils.go
/kind bug
This PR fixes the deletion of files created during watch.
Fixes #https://github.com/openshift/odo/issues/3438
- Create a odo component and trigger `odo watch`
- Create a file/folder and wait for the push to be completed
- Delete the file/folder and check if the file was removed from the cluster or not.
=> Fix deletion of files and folders created during watch

pkg/odo/cli/component/common_link.go
/kind cleanup
This PR fixes typo and removes the commented code
Fixes NA
=> Fixing typo and cleanup unused code

pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/sync/adapter.go, tests/integration/devfile/cmd_devfile_push_test.go
/kind bug
This PR fixes the `skipping build` message when run mode is switched as a build does get triggered.
Fixes #3929 
- odo create nodejs
- odo push
- odo push --debug
The message `skipping build` shouldn't be displayed.
=> Fixes message indicating no build when run mode is switched

Dockerfile, scripts/sync.sh
Adds a docker container to run the scripts in rather than relying on
locla pandoc / asciidoctor. This removes the need of making sure that
the user has a particular version installed when running the
synchronization script.
=> Add Docker container to run scripts

Makefile
Signed-off-by: John Collier <jcollier@redhat.com>
/kind bug
Ran in to this while trying to add a dependency to odo and realized that `make vendor-update` needs to be updated since odo uses go modules now.
This PR updates the `vendor-update` make target to use `go mod vendor` rather than using `glide up`.
N/A
=> Update vendor-update makefile target

scripts/configure-installer-tests-cluster-ppc64le.sh
/kind bug
There are configured imagestreams for ppc64le arch. Since the library has updated the files, we need to update it to work well with the test suites. Same as PR https://github.com/openshift/odo/pull/4054
Fixes #?
=> Update configure-installer-tests-cluster-ppc64le.sh script to import right imagestream for tests.

pkg/occlient/occlient.go, pkg/occlient/occlient_test.go
/kind bug
We were reading image labels from image metadata from ContainerConfig
Instead, we should read it from Config. Images in 4.6 are build in a slightly different way and s2i specific labels are not present in ContainerConfig struct, only in Config.
Fixes #4015
=> read s2i paths from both Config and ContainerConfig

pkg/devfile/parser/data/2.0.0/components.go, pkg/devfile/parser/types.go, pkg/devfile/parser/types_test.go, tests/examples/source/devfiles/parentSupport/devfile-with-parent-composite.yaml, tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/utils/utils.go
/kind feature
/area devfile
Adds support for overriding composite commands in parent devfiles. Also fixes a bug where parent commands could not be overridden if the parent command contained upper case letters.
Fixes https://github.com/openshift/odo/issues/3759
Sample devfile:
```
metadata:
name: nodejs
version: 1.0.0
parent:
uri: https://raw.githubusercontent.com/openshift/odo/master/tests/examples/source/devfiles/nodejs/devfileCompositeCommands.yaml
commands:
- id: buildAndMkdir
composite:
label: Build and Mkdir
commands:
- createfile
- install
parallel: false
group: 
kind: …
```
=> feat: Allow composite commands to be overridden

pkg/devfile/adapters/common/utils.go, pkg/devfile/adapters/common/utils_test.go, pkg/odo/cli/storage/create.go, pkg/storage/storage.go, pkg/storage/storage_test.go, tests/examples/source/devfiles/nodejs/devfile-with-volume-components.yaml, tests/examples/source/devfiles/nodejs/devfile-with-volumes.yaml, tests/integration/cmd_storage_test.go, tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/cmd_devfile_storage_test.go
Signed-off-by: Maysun J Faisal <maysunaneek@gmail.com>
/kind bug
If vol mount path is absent, it defaults to vol mount name acc to the devfile schema https://devfile.github.io/devfile/api-reference.html
Fixes #4005 
- Comment out the vol mount path in a devfile and push
- Confirm the volume mount path by `oc/kubectl describe pod`
=> Default vol mount path to vol name if absent

tests/helper/helper_filesystem.go, tests/integration/devfile/cmd_devfile_watch_test.go
/kind cleanup
Adds debug flag tests with odo watch which got removed in https://github.com/openshift/odo/pull/4047 by mistake.
Fixes NA
`make test-cmd-devfile-watch` should pass.
=> Added odo watch test with debug flag

pkg/odo/cli/component/create.go, pkg/odo/cli/component/push.go, pkg/odo/cli/component/ui/ui.go
/kind bug
Add explicit warning while using default namespace with odo, component fails due to volume permission issue
I have added warning for `odo push` only as in we want `odo create` to run without cluster access so avoided adding namespace warning in `odo create`
Fixes #4053 #4027 
=> Add warning for default namespace during odo create

pkg/url/url.go, pkg/url/url_test.go, tests/integration/cmd_url_test.go, tests/integration/devfile/cmd_devfile_url_test.go
/kind bug
before doing odo push if there is a url present then we show it as `://` and that's confusing. Resolved it by making it a blank until user pushes.
Fixes https://github.com/openshift/odo/issues/4109
way to reproduce 
```
odo url create --port 3000
odo url list
```
Output:
```
Found the following URLs for component nodejs
NAME STATE URL PORT SECURE KIND
nodejs-3000 Not Pushed :// 3000 false route
```
After fix the url would be blank
=> nit: dont show url as :// in odo url list

scripts/setup-operators.sh, tests/integration/operatorhub/cmd_service_test.go
/kind cleanup
Removing mongodb operator setup due to instability of the operator on 4.* cluster. Fixing the CI failure we are hitting currently.
Fixes NA
`make test-operator-hub` should pass.
=> Removing mongo db operator

scripts/changelog-script.sh
/kind cleanup
Ignores "lifecycle/rotten" issues when generating the changelog
Closes https://github.com/openshift/odo/issues/3192#issuecomment-707521200
N/A
N/A
=> Ignore lifecycle/rotten labels when generating changelog

pkg/odo/cli/component/create.go, tests/integration/component.go, tests/integration/devfile/cmd_devfile_create_test.go
/kind bug
Fixes #4048 , #4018 
Please try out the `odo create` command using all the possible combinations and flags.
=> Refactor: fix s2i flag for odo create

docs/public/deploying-a-devfile-using-odo.adoc
[skip ci]
- Updates the documentation regarding deploying a devfile
- Changes the wording to include Kubernetes first and then OpenShift.
- Moves the tutorial / prerequisites around so Kubernetes is first
- Removes the part regarding CRC and adds it to the OpenShift
prerequisites and the same for Kubernetes with Minishift.
fixes https://github.com/openshift/odo/issues/4113
N/A
=> Update deploying a devfile documentation

docs/dev/experimental-mode.adoc, docs/public/deploying-a-devfile-using-odo.adoc, docs/public/s2i-to-devfile.adoc, pkg/odo/cli/catalog/list/components.go, pkg/odo/cli/component/list.go, tests/integration/devfile/docker/cmd_docker_devfile_catalog_test.go
> /kind bug
> /kind design
> /kind flake
>
> [skip ci]
Renamed `Openshift` to `S2I` in 
- `odo list`
- `odo catalog list components`
This has been done to remove the confusion around "Openshift" components. This looking at the name "Openshift" makes people think that these are the components people need to use to deploy on openshift and they might ignore "Devfile" components. …
=> renamed Openshift to S2I in odo to remove confusion

pkg/odo/cli/catalog/list/services.go, pkg/odo/cli/component/list.go
> /kind bug
> /kind design
> /kind flake
>
> [skip ci]
`odo catalog list services` fails if there are no services templates / CSVs are present, that shouldn't be happening as its an outcome which a user might expect when they just install operatorhub. However this PR doesn't remove the checks for "service catalog" or "operator hub" being installed correctly.
**Which issue(s) this …
=> fix odo catalog list service erroring out when no service templates / CSVs are present

.travis.yml, Makefile
/kind cleanup
link unlink test file target was only for 4.x cluster and there was no test target for same link unlink test file that resides in service- catalog, so I just created seperate target for link unlink service catalog target for 3.11 
Fixes N/A
make test-cmd-link-unlink-4-cluster
make test-cmd-link-unlink-311-cluster
=> Enable link unlink target for 311 servicecatalog test

scripts/configure-installer-tests-cluster-s390x.sh
/kind bug
To update the required s2i imagestream for nodejs and java application.
=> Update required s2i imagestreams for nodejs and java on IBM Z.

pkg/odo/cli/component/create.go
/kind cleanup
see $SUBJECT
No issue
- Before :
```
~ odo create --s2i nodejs --context ./import2
Devfile path: 
Validation
✓  Validating component [429ms]
Please use `odo push` command to create the component with source deployed
```
- After :
```
~ odo create --s2i nodejs --context ./import
Validation
✓  Validating component [429ms]
Please use `odo push` command to create the component with source deployed
```
=> nit: remove the 'Devfile path' log even when using --s2i in odo create --context

docs/file-reference/index.md, pkg/devfile/parser/configurables_test.go, pkg/devfile/parser/data/2.0.0/devfileJsonSchema200.go, pkg/devfile/parser/data/common/types.go, pkg/devfile/parser/parse_test.go, pkg/devfile/parser/types_test.go, pkg/odo/cli/component/create.go, pkg/testingutil/filesystem/default_fs.go, pkg/testingutil/filesystem/fake_fs.go, pkg/testingutil/filesystem/filesystem.go, pkg/util/util.go, pkg/util/util_test.go, tests/examples/source/devfiles/nodejs/devfile-with-subDir.yaml, tests/examples/source/devfiles/springboot/devfile-with-subDir.yaml, tests/integration/devfile/cmd_devfile_create_test.go
/kind feature
Updates schema to change sparseCheckoutDir to subDir and adds support of it for git starter projects.
Fixes #3933 
- Create a devfile with subDir set and place it in a empty folder.
- Run `odo create --starter`
- The starter project's `subDir` content should be downloaded only and the temp folder should be removed.
=> Adds subDir checkout for git components

pkg/component/component_full_description.go, pkg/odo/cli/component/component.go, tests/integration/component.go, tests/integration/devfile/cmd_devfile_create_test.go
/kind bug
Currently we were deciding the type of context ( devfile or s2i ) based on presence of devfile in the working directory which is a problem when user provides `--context`.  For e.g.
- `odo describe --context <s2i-component-dir>` <- this from a directory that has devfile directory would fail as it would initialise a `DevfileContext` that looks for `env.yaml`. 
Fixes https://github.com/openshift/odo/issues/3902
- create a nodejs s2i component - `nodejs2i`
- create a nodejs devfile component - `nodejsdevfile` along side the s2i component so that both sit in the same dir
- now go to the …
=> check if devfile exist in the context folder instead of working directory

pkg/catalog/catalog.go, pkg/devfile/adapters/common/utils.go, pkg/util/util.go, scripts/configure-installer-tests-cluster.sh, tests/e2escenarios/e2e_images_test.go, tests/image-streams/supported-nodejs.json, tests/integration/devfile/utils/utils.go
/kind bug
/kind feature
There is latest nodejs image difference on 4.6 and 4.5 cluster. So, adding `ubi8/nodejs-12` image as supported will unblock enabling odo periodic job on 4.6 cluster.
Fixes #4016 
Latest nodejs image on 4.6 should work fine for odo
=> Adding ubi8/nodejs-12 images as supported

tests/integration/component.go
This PR will fix mac context related issue for test. 
Fixes #3797
=> Fix absolute path for test on macos

pkg/occlient/occlient.go, pkg/storage/storage.go
/kind bug
When creating applications on OpenShift Kubernetes, a (12-factor) best practice is to externalize the configuration in a ConfigMap. When mounting this ConfigMap in the DC, odo is not working anymore because it expects a volume with a PVC. As odo cannot manage ConfigMap yet, we should ignore them (as we ignore empty volume) to  apply best practices while using odo.
This is an alternance for waiting for the [PR2142](https://github.com/openshift/odo/issues/2142) and [PR2601](https://github.com/openshift/odo/issues/2601)
=> Ignore Configmap mounted in DeploymentConfig

pkg/component/component.go
/kind bug
> [skip ci]
I took an educated guess that if getting DC by name fails with not found error then the line below doesn't report it as an error
https://github.com/openshift/odo/blob/a28e37838c5cbaa396f6675fe90a9986168165f5/pkg/component/pushed_component.go#L258
Hence this line paniced
https://github.com/openshift/odo/blob/cabd4a13eea9e8091c2a79962e00c9a8d6f6c070/pkg/component/component.go#L1414
Note - I wasn't able to reproduce this hence took this guess
fixes https://github.com/openshift/odo/issues/4183
**How to test changes / Special notes to …
=> resolve the panic on odo list when the project contains non-odo DCs

scripts/configure-installer-tests-cluster-s390x.sh
/kind bug
/kind feature
Make conformance with PR #4070 
Fixes #4016 
Latest nodejs image on 4.6 should work fine for odo
=> Update configure-installer-tests-cluster-s390x to support nodejs12 e2e test

tests/helper/helper_generic.go
Some PRs are failing with this error
```
Creating a new project: vhgeggwlqs
Running kubectl with args [kubectl create namespace vhgeggwlqs]
[kubectl] namespace/vhgeggwlqs created
Running kubectl with args [kubectl config set-context --current --namespace vhgeggwlqs]
[kubectl] error: open /home/travis/.kube/config.lock: file exists
``` 
Hence resolving this error
https://travis-ci.com/github/openshift/odo/jobs/440575550
Fixes https://github.com/openshift/odo/issues/4190
=> resolve .kube/config.lock: file exists flake

pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/occlient/projects.go, pkg/occlient/projects_test.go, pkg/odo/util/completion/completionhandlers.go, pkg/project/project.go
/kind cleanup
Moves project related code from occlient.go to projects.go
Fixes part of #4093 
- Tests should pass
=> Moves project related code from occlient.go to a new file

docs/public/operator-hub.adoc, docs/public/operators-on-minikube.adoc
[skip ci]
This PR documents steps to install Operators on minikube cluster. We need this to help Kubernetes users get up to speed with installing and working with Operators.
Fixes #4103
=> Document Operator installation on minikube

.travis.yml, Makefile, tests/e2escenarios/e2e_devfile_test.go
Adds end-to-end tests for the devfile debug feature
Fixes #3377
ginkgo -randomizeAllSpecs -slowSpecThreshold=120 -timeout 7200s -nodes=2 -focus="odo devfile support tests" tests/e2escenarios
=> #3377 adding odo devfile support test

pkg/catalog/catalog.go, pkg/odo/cli/catalog/list/services.go, pkg/odo/cli/component/link.go, pkg/odo/cli/component/unlink.go, pkg/odo/cli/service/create.go, pkg/odo/cli/service/delete.go, pkg/odo/cli/service/list.go, pkg/odo/util/cmdutils.go, pkg/service/service.go, tests/integration/operatorhub/cmd_service_test.go
/kind bug
This PR makes sure that odo lists only those Operators that are successfully installed. This success is determined on the basis of the `Phase` of Operator. If the phase evaluates to `Succeeded`, the Operator is considered available to use.
Fixes #4155 & https://bugzilla.redhat.com/show_bug.cgi?id=1889961
This can be better tested on a minikube setup.
```sh
$ minikube start
$ minikube addons enable olm
$ kubectl apply -f https://gist.github.com/dharmit/89079ad3daa7df83b92cc39c499f670f/raw/ea8808fcc6ec876b1c7c1f0838295f21324f3baf/operators.yaml
$ kubectl get csv …
```
=> List only installed Operators; some refactor

scripts/configure-installer-tests-cluster-ppc64le.sh
Update configure-installer-tests-cluster-ppc64le to support nodejs12 e2e test
/kind bug
/kind feature
Make conformance with PR #4070 and #4215
Fixes #4016
Latest nodejs image on 4.6 should work fine for odo
=> Update configure-installer-tests-cluster-ppc64le to support nodejs12 e2e test

tests/integration/operatorhub/cmd_service_test.go
/kind flake
This increased timeout makes sure that `odo catalog list services` being
executed in `JustBeforeEach` gets enough time to check for existence of
two Operators that we're installing in CI to perform our checks.
We need to increase this timeout because it's taking a long time for
`odo catalog list services` to find "successfully installed" Operators
in the newly created namespace even if these Operators are installed at
cluster level, i.e., in the `openshift-operators` namespace.
The increase in the time taken by odo to find this info is mainly
attributed to https://github.com/openshift/odo/pull/4202. I am observing
that even `kubectl get csv` is taking more than usual time to list the
Operators or …
=> Increase timeout for Operator Hub tests

OWNERS
Adding aditi on top level OWNERS file because we need more approvers.
No issues
=> add aditi as approver in top level OWNERS file

pkg/catalog/catalog.go, pkg/devfile/adapters/common/utils.go, scripts/configure-installer-tests-cluster.sh, tests/e2escenarios/e2e_images_test.go
/kind feature
There is latest java image difference on 4.6 and 4.5 cluster. So, adding `ubi8/openjdk-11` image as supported will unblock enabling odo periodic job on 4.6 cluster https://github.com/openshift/odo/issues/4138
Fixes - part of issue https://github.com/openshift/odo/issues/4138
Latest java image on 4.6 should execute successfully for odo
=> Adding the latest java image ubi8/openjdk-11 in odo supported list

pkg/catalog/catalog.go, pkg/catalog/catalog_test.go
/kind bug
see $SUBJECT
Fixes showing `java:latest` as unsupported on openshift 4.6 cluster
Java should show up as supported now on openshift 4.6
=> resolve need for image stream tags to be in order in catalog list

tests/e2escenarios/e2e_images_test.go, tests/helper/helper_oc.go, tests/integration/devfile/utils/utils.go
/kind bug
This PR will Fix image source for E2E test image.
Fixes #3389 
Fixes #4235 
=> windows path seperator fix

docs/dev/development.adoc
[skip ci]
Update the correct link for prow help command
Fixes - comment https://github.com/openshift/odo/pull/4265#issuecomment-735755308
We should be able to see the help commands with the update link.
=> Update the prow help command link

docs/public/deploying-a-devfile-using-odo.adoc
Signed-off-by: Adam Wisniewski <awisniew@us.ibm.com>
[skip ci]
Add's an Open Liberty example to "deploying-a-devfile-using-odo.adoc"
=> Add Open Liberty to devfile doc

pkg/component/component.go, pkg/component/component_test.go, pkg/devfile/adapters/docker/storage/adapter_test.go, pkg/kclient/secrets_test.go, pkg/occlient/occlient_test.go, pkg/odo/cli/cli.go, pkg/project/project_test.go, pkg/testingutil/services.go
/kind cleanup
See $SUBJECT
Cleaning up code
All tests should pass no new functionality was added
=> remove packages imported twice

docs/dev/ci-reference.adoc
/kind cleanup
[skip ci]
Doc - https://github.com/openshift/odo/blob/master/docs/dev/ci-reference.adoc is outdated.
Fixes - Updated https://github.com/openshift/odo/blob/master/docs/dev/ci-reference.adoc
NOTE: I was referring odo ci-reference doc for the current project i am working on and found the [doc](https://github.com/openshift/odo/blob/master/docs/dev/ci-reference.adoc) was referring to template base testing and travis CI snippet was pretty old. 
https://github.com/openshift/odo/blob/master/docs/dev/ci-reference.adoc should be updated as per the recent ci structure used …
=> Update CI reference doc

docs/public/install-service-binding-operator.adoc
[skip ci]
This PR updates the documentation section about installing SBO on minikube/k8s to use the steps mentioned on https://operatorhub.io/operator/service-binding-operator.
Fixes #4299 
=> Update docs to install SBO from OperatorHub.io

pkg/odo/cli/service/list.go, pkg/service/service.go, tests/integration/operatorhub/cmd_service_test.go
/kind bug
It prevents `odo service list` from entirely failing if listing instances of one or a few of the CRs fails.
Fixes #4221 
1. On a CRC system, install etcd Operator and Red Hat OpenShift Pipelines Operator
1. Look for output similar to below:
```sh
$ odo catalog list services
Operators available in the cluster
NAME                                           CRDs
etcdoperator.v0.9.4-clusterwide                EtcdCluster, EtcdBackup, EtcdRestore
redhat-openshift-pipelines-operator.v1.2.1     Config
```
1. Do `odo service list`. We didn't start a service from any CR/Operator yet so you should see …
=> Don't fail the command if listing a CR's instances fails

pkg/kclient/kclient.go
/kind cleanup
All the other clients are initiated in similar manner except
`client.appsClient`. This commit just makes things uniform.
Fixes NA.
Part of #4298 
=> Follow same initialization pattern as other clients

go.sum, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/storage/utils.go, pkg/devfile/adapters/kubernetes/utils/utils.go, pkg/odo/cli/preference/view.go, pkg/preference/preference.go, pkg/storage/labels/labels.go, pkg/storage/storage.go, tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/cmd_devfile_storage_test.go
/kind feature
This PR proposes to create a PVC for odo source code volume, Uptil now we were using emptyDir to store source code.  
It makes PVC as a default option to store source code, If user wants to use `emptyDir` as source code, it can use
`odo preference set ephemeral true`
Fixes #3775
- odo create nodejs --starter
- odo push
- check if it has created source pvc using `oc get pvc` or `kubectl get pvc`
=> Implement PVC for odo source volume

scripts/openshiftci-presubmit-all-tests.sh, tests/integration/cmd_app_test.go
/kind feature
This PR enables the next make target execution even if the the existing one fails. For ex - If `make test-integration` fails It won't fail the overall execution, instead start the next make target execution.
Fixes NA (Interop team has particularly urged for this feature as part of https://github.com/openshift/odo/issues/4223 )
Prow should not fail overall execution. It should try executing the next target if existing one fails.
=> Execute make target consecutively even on failure

pkg/odo/cli/component/create.go, pkg/odo/cli/component/interactive_create.go, tests/helper/helper_run.go, tests/integration/devfile/cmd_devfile_create_test.go
/kind bug
override an env file if found without a devfile on odo create
Fixes https://github.com/openshift/odo/issues/4210
=> override an env file if found without a devfile on odo create

tests/e2escenarios/e2e_images_test.go
This is just a work around untill we get https://github.com/openshift/odo/issues/4347 done
Fixes - Work around
`make test-e2e-images` should pass .
=> Revert centos nodejs tags to older version

pkg/odo/cli/service/create.go, tests/integration/operatorhub/cmd_service_test.go
/kind bug
It fixes a bug which leads to bad UX.
Fixes #4013
Create an Operator backed service without providing a name. You should now see the service name being used from the alm example:
```sh
$ odo service create etcdoperator.v0.9.4-clusterwide/EtcdCluster
Deploying service of type: EtcdCluster
✓  Deploying service [3ms]
✓  Service 'example' was created
Progress of the provisioning will not be reported and might take a long time
You can see the current status by executing 'odo service list'
Optionally, link etcdoperator.v0.9.4-clusterwide to your component by running: 'odo link <component-name>' …
```
=> Output service name when creating Operator backed service

pkg/component/component.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/kclient/pods.go, pkg/kclient/pods_test.go, pkg/odo/cli/component/common_link.go
/kind bug
It removes the hideSpinner parameter from WaitAndGetPodWithEvents().
Fixes NA
- Tests should pass and panic shouldn't occur while collecting events from the pod.
=> Fixes panic while collecting events from the pod.

pkg/catalog/catalog.go, pkg/devfile/adapters/common/utils.go, tests/e2escenarios/e2e_images_test.go
/kind feature
We need to sync with s2i nodejs container centos image. 
Fixes #4347 
Fixes #4278
centos7 nodejs image should work fine for odo.
=> Add centos7 nodejs latest as supported

pkg/preference/preference.go, tests/integration/devfile/cmd_devfile_storage_test.go
> /kind bug
> /kind design
> /kind flake
>
> [skip ci]
For now, it assumes default value for ephemeral 'false'.
In future releases, we might change it 'true'. But for now, we should
play it safe and keep the old behavior. We are not sure about all the
consequences that this can have.
Fixes #?
**How to test changes / …
=> Change default value for ephemral preference

scripts/configure-installer-tests-cluster-s390x.sh
/kind bug
Add same fix with #4206.
Add some fix for importing java imagestream.
Fixes #?
=> Some fix for configure script of s390x.

pkg/catalog/catalog.go, pkg/odo/cli/catalog/list/services.go, pkg/odo/cli/catalog/util/util.go, tests/integration/operatorhub/cmd_service_test.go
This PR refactors the underlying code for `odo catalog list services`. It makes the code more readable.
We need this because odo will be supporting both Operator Hub as well as Service Catalog backends to let users spin up services from. This PR removes `if..else` blocks and various variables that made the code quite confusing.
Fixes NA
Part of #4298
Check output of `odo catalog list services` in following scenarios:
* a fresh minikube cluster with no Operators or Service Catalog enabled
* enable OLM addon (`minikube addons enable olm`) and install some Operator (for example …
=> Refactor catalog list services

tests/examples/source/devfiles/nodejs/devfile-with-no-starterProject.yaml, tests/integration/devfile/cmd_devfile_create_test.go
Fixes test for checking no starter project found and adds a new example devfile with no starter project in it.
Fixes https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/4381/pull-ci-openshift-odo-master-v4.6-integration-e2e/1352533113997103104
- Tests should pass.
=> Fixes test for checking no starter project found

scripts/configure-cluster/common/kubeconfigandadmin.sh
Configure scripts are failing locally.
```
$ make configure-installer-tests-cluster
. ./scripts/configure-installer-tests-cluster.sh
++ LIBDIR=./scripts/configure-cluster
++ LIBCOMMON=./scripts/configure-cluster/common
++ SETUP_OPERATORS=./scripts/configure-cluster/common/setup-operators.sh
++ AUTH_SCRIPT=./scripts/configure-cluster/common/auth.sh
++ KUBEADMIN_SCRIPT=./scripts/configure-cluster/common/kubeconfigandadmin.sh
++ CI_OPERATOR_HUB_PROJECT=ci-operator-hub-project
++ IMAGE_TEST_NAMESPACES='[openjdk-11](https://issues.redhat.com/browse/openjdk-11)-rhel8 nodejs-12-rhel7 nodejs-12 [openjdk-11](https://issues.redhat.com/browse/openjdk-11)'
++ . …
```
=> Fix configure script run locally

pkg/catalog/catalog.go, pkg/odo/cli/catalog/list/services.go
/kind bug
$subject
Fixes #4376
`odo catalog list services` should pass on all the three platforms:
* Kubernetes (minikube)
* OCP 4.x (CRC)
* OCP 3.11 (minishift)
=> Fixes catalog list services for minishift

pkg/component/component.go, pkg/component/component_full_description.go, pkg/component/component_test.go, pkg/config/config.go, pkg/config/fakeConfig.go, pkg/config/storage.go, pkg/config/storage_test.go, pkg/devfile/adapters/common/utils.go, pkg/devfile/adapters/common/utils_test.go, pkg/envinfo/storage.go, pkg/envinfo/storage_test.go, pkg/localConfigProvider/localConfigProvider.go, pkg/localConfigProvider/mock_localConfigProvider.go, pkg/odo/cli/storage/create.go, pkg/odo/cli/storage/delete.go, pkg/odo/cli/utils/convert.go, pkg/odo/util/cmdutils.go, pkg/odo/util/completion/completionhandlers.go, pkg/storage/storage.go, tests/integration/devfile/cmd_devfile_storage_test.go
It adds storage related functions to the localConfigProvider and also refactors the storage create and delete CLI code to use them.
Fixes part of #4298  
- Tests should pass.
=> Refactors storage code for localConfigProvider.

pkg/auth/login.go
/kind bug
The command `odo login` overwrites the current active project/namespace even if a current context is already defined.
https://github.com/openshift/odo/issues/4387
To reproduce the bug:
`odo login`
`odo project create my-project`
`odo project get` --> result: 'my-project'
`odo login`
`odo project get` --> result should be 'my-project'
=> Keeping the current active project/namespace when re-logging in

pkg/catalog/catalog.go, pkg/devfile/adapters/common/utils.go, scripts/configure-installer-tests-cluster.sh, tests/e2escenarios/e2e_images_test.go
/kind feature
There is latest nodejs image difference on ocp latest and upcoming version(4.7). So, adding ubi8/nodejs-14 image as supported will unblock https://github.com/openshift/odo/issues/4280
Fixes #4303 
Latest nodejs image on 4.7 should work fine for odo
=> Adding ubi8/nodejs-14 image as supported

pkg/odo/cli/component/create.go
This PR redefine the "Validation" header into below different headers:
- Devfile Object Validation 
- Devfile Component Name Validation
- Supportability Validation
Also re-phrased ValidateK8sResourceName() spinner so it now reflects what kind of check it performs. 
`odo create` output now looks like:
<p align="center">
</p>
And,
<p align="center">
</p>
Address issue #3924 
Fixes #?
=> Validation spinners refactor

docs/public/deploying-a-devfile-using-odo.adoc, pkg/odo/cli/component/watch.go, pkg/watch/watch.go, pkg/watch/watch_test.go, tests/examples/source/devfiles/nodejs/devfile-with-debugrun.yaml, tests/integration/devfile/cmd_devfile_watch_test.go
/kind feature
It takes the custom debug command from the CLI while trigerring odo watch.
Fixes #4357 
- `odo watch --debug-command <custom debug command>` should work.
=> Adds debug-command flag to odo watch

pkg/devfile/validate/errors.go, pkg/devfile/validate/events.go, pkg/devfile/validate/events_test.go, pkg/devfile/validate/validate.go, tests/examples/source/devfiles/nodejs/devfile-with-preStart.yaml, tests/integration/devfile/cmd_devfile_push_test.go
/kind bug
preStart even is still not clearly defined in Devfile and it is clear how it should be defined. This will make sure that no one is using PreStart event until we have a proper implementation.
Fixes #4187
Create a devfile with the preStart event command
```
events:
preStart:
- some-command
```
=>  Disable preStart event using validations

pkg/odo/cli/component/create.go, tests/integration/devfile/cmd_devfile_create_test.go
/kind bug
Adding condition to check if `project` is a supported resource during `odo create` command, if so, check non-default project is being used. 
Fixes #4309
`odo create` should only error (and exit) with _odo may not work as expected[...]_ when using the default project in an Openshift cluster.
=> adding project resource check before warning about default project usage

tests/e2escenarios/e2e_devfile_test.go
/kind feature
Adding java-maven to be tested in the devfile debug e2e scenarios
Fixes #4162
make test-e2e-devfile
=> Added java-maven to the list of components to be tested

scripts/openshiftci-e2e-4x-psi-tests.sh, scripts/openshiftci-presubmit-all-tests.sh
- 4.6 will now run the old presubmit-all script
- psi will run as 4.6-e2e-4x-psi
=> Renaming entrypoint scripts to use new job

pkg/component/starter_project.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/create_helpers.go, tests/helper/helper_filesystem.go, tests/integration/devfile/cmd_devfile_create_test.go, tests/template/template_cleantest_test.go
/kind bug
`odo create <component_name>  --starter --context <empty_context_dir>`
This PR fixes the failure caused when running the above command. There was no case covering a scenario where a starter project needs to be downloaded for a custom context directory, now there is.
Output - 
```
odo create nodejs --starter --context sub_dir
⚠  odo may not work as expected in a default project, please run the odo component in a non-default project. To create a new project, use `odo project create`.
Devfile Object Validation
✓  Checking devfile existence [24643ns]
✓  Creating a devfile component from registry: DefaultDevfileRegistry [19872ns]
Validation
✓  Validating if devfile name is correct [82590ns]
Starter Project
✓ …
```
=> Make starter project download work with custom context directory

pkg/devfile/adapters/common/command.go, pkg/devfile/adapters/common/command_test.go, pkg/devfile/adapters/common/errors.go
/kind bug
It introduces two error types called NoDefaultForGroup and MoreDefaultForGroup.
Fixes #4363 
- Create a component and remove the `build` kind command from the devfile.
- `odo push` should pass.
=> Fixes no default build command error.

README.adoc
> /kind bug
> /kind design
> /kind flake
>
[skip ci]
Open VSX is an open registry for VS Code extensions. OpenShift Connector is listed there as well.
Fixes #?
=> Adding link to Connector extension on Open VSX

pkg/url/kubernetes.go, pkg/url/url.go, tests/integration/devfile/cmd_devfile_url_test.go
/kind bug
It fixes the URL name cropping issue.
Fixes #4060 #4392 
- Long URL names shouldn't be trimmed and `odo url list` should display the same URL name.
=> Fixes the URL name cropping issue.

pkg/odo/cli/component/create.go, pkg/odo/cli/component/push.go, pkg/odo/genericclioptions/context.go, pkg/odo/genericclioptions/util.go, tests/integration/devfile/cmd_devfile_create_test.go, tests/integration/devfile/cmd_devfile_env_test.go, tests/integration/devfile/cmd_devfile_push_test.go
/kind bug
It also modifies odo push to fill the project name in env.yaml if no project is not found in it.
Fixes #3811 
- `odo create` should work without a cluster.
- `odo create --project <name>` should fill the project name in env.yaml during creation.
- `odo push` should fill the project name in the env.yaml if none was provided during creation.
=> Modifies odo create for devfile components to not require a cluster access.

go.sum, pkg/kclient/operators.go, pkg/odo/cli/component/common_link.go, scripts/configure-cluster/common/setup-operators.sh
This is to be compatible with SBO 0.5.0
Makes odo compatible with SBO 0.5.0
Fixes #4480
4.7 tests should pass
=> Change API & Operator version for Serice Binding Operator

pkg/util/util.go
This makes sure that the extracted files from starter project zip archive have the original permission. 
/kind bug
Fixes #?
add zip file starter project to a devfile
```
starterProjects:
- name: quarkus-ex
zip:
location: "https://code.quarkus.io/d?s=98e.Bqi.tqK.Svz&cn=code.quarkus.io"
```
when odo extracts starter project  `odo create --devfile ../devfile.yaml --starter`  the `mvnw` and `mvnw.cmd`  files should have executable flags
=> Preserve permissions when extracting zip files

scripts/changelog-script.sh
[skip ci]
Looks like the install link changed within the OpenShift doc.
Old: https://docs.openshift.com/container-platform/latest/cli_reference/openshift_developer_cli/installing-odo.html
New: https://docs.openshift.com/container-platform/latest/cli_reference/developer_cli_odo/installing-odo.html
- [X ] Documentation 
- [X ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)
=> Fix install URL link

pkg/odo/cli/preference/set.go, pkg/odo/cli/preference/unset.go, pkg/odo/cli/preference/view.go, pkg/preference/machine_output.go, pkg/preference/preference.go, pkg/preference/preference_test.go, tests/integration/cmd_pref_config_test.go
/kind feature
This PR adds telemetry consent to preference, so that user can set and unset their telemetry preference.
Partly Fixes #1236 
1. `odo preference --help` and check if ConsentTelemetry appears in the help.
2. `odo preference set ConsentTelemetry true` and check if the preference was set correctly.
3. `odo preference unset ConsentTelemetry` and check if the preference was unset.
4. `odo preference view` and check if ConsentTelemetry is present in the output.
Note that this does not yet collect data, this just adds `ConsentTelemetry` to preferences.
=> Add telemetry consent to preference

pkg/odo/genericclioptions/context.go
/kind bug
when we are creating offline context - we are not setting the project which could be a major bug when using any command in non-cluster mode.
No issue
Not sure how to test this
~~ - [ ] Unit test 
=> resolve project not being set in offline context creation

pkg/component/component_full_description.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/describe.go, pkg/odo/cli/component/push.go, pkg/odo/cli/component/watch.go, pkg/odo/cli/url/create.go, pkg/odo/genericclioptions/client.go, pkg/odo/genericclioptions/context.go, tests/integration/devfile/cmd_devfile_create_test.go
/kind bug
It also removes unused parameters from some functions.
Fixes #4507 
- Open the kubeconfig and edit the `server: ` values to a invalid value.
- `odo create` should pass.
=> Fixes odo create when cluster access is limited

pkg/odo/cli/catalog/describe/component.go, tests/integration/devfile/cmd_devfile_catalog_test.go
/kind bug
Fixes https://github.com/openshift/odo/issues/4474
Fixes https://github.com/openshift/odo/issues/4463
run `odo catalog describe component nodejs -o json` 
the output should be a valid json struct (array)
=> fix json in describe component

pkg/odo/cli/component/create.go, tests/integration/devfile/cmd_devfile_create_test.go, tests/integration/devfile/cmd_devfile_watch_test.go, tests/integration/operatorhub/cmd_service_test.go
/kind feature
see $SUBJECT
Fixes https://github.com/openshift/odo/issues/4112
```
mkdir hello
cd hello
odo create nodejs <- should create a component with name `nodejs-hello-<4randomChars>`
odo create nodejs blah <- should create component with name blah
```
=> use default component name if user doesn't provide one in devfile mode

scripts/openshiftci-presubmit-all-tests.sh
> /kind bug
This change enables ODO test-suite to enable devfile integration tests on Power.
Fixes #4290 
Run the test script (scripts/openshiftci-presubmit-all-tests.sh)
> /area system-PZ
=> Add test-integration-devfile tests for ppc64le

scripts/openshiftci-presubmit-all-tests.sh
For the test-integration-devfile, have verified supported on s390x.
> /kind bug
make odo supported on s390x, and including more cases in ci
Fixes #4290 
**Area**
system-PZ
just run the test script
=> Add test-integration-devfile tests for s390x

tests/helper/helper_generic.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/helper/odo_utils.go, tests/integration/devfile/cmd_devfile_debug_test.go
/kind bug
To assist in resolution of  we are prefixing projectNames with the test filename and line number of the test in progress, this way we can identify which tests are leaving projects behind (not getting cleaned up)
Fixes [#4215](https://github.com/openshift/odo/issues/4502) 
make test-integration
during execution check that projects created in the target cluster are prefixed with the test filename and line number
=> Changes to prefix projectNames with test_file_name and line number

pkg/odo/cli/project/create.go, pkg/odo/cli/project/delete.go, pkg/odo/cli/project/set.go
/kind feature
see $SUBJECT
Fixes https://github.com/openshift/odo/issues/4442
```
odo project create -h
Create a new project. This command directly performs actions on the cluster and doesn't require a push.
```
=> show in all project commands help that a push is not required

pkg/preference/preference.go, pkg/preference/preference_test.go
/kind cleanup
This PR just replaces `%s` with `%q` to make errors more readable, and fixes typos in tests.
Fixes #4540
=> Make preference commands errors pretty and fix typos with test

pkg/devfile/adapters/common/interface.go, pkg/devfile/adapters/docker/adapter.go, pkg/devfile/adapters/docker/component/adapter.go, pkg/devfile/adapters/kubernetes/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/occlient/deploymentConfigs.go, pkg/odo/cli/component/devfile.go, pkg/util/util.go, tests/integration/devfile/cmd_devfile_debug_test.go, tests/integration/devfile/cmd_devfile_push_test.go
/kind bug
It waits for 1 sec to check the status and displays the last 20 lines in case of a failure.
Fixes #4197
- Push a component with a invalid run command, it should error out with the last 20 lines of the component's log.
- Repeat the above steps with a invalid debug command and using the `debug` flag during push.
=> Adds a check to error out if the run command didn't start properly.

openshift-ci/build-root/Dockerfile
Fixing ci failure.
```
error: build error: failed to pull image: After retrying 2 times, Pull image still failed due to error: while pulling "docker://registry.svc.ci.openshift.org/openshift/release:golang-1.13" as "registry.svc.ci.openshift.org/openshift/release:golang-1.13": Error initializing source docker://registry.svc.ci.openshift.org/openshift/release:golang-1.13: error pinging docker registry registry.svc.ci.openshift.org: invalid status code from registry 503 (Service Unavailable)
```
Fixes #?
=> Fixing golang image pull error

pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/utils/utils.go, pkg/kclient/deployments.go, pkg/odo/cli/component/common_link.go
/kind bug
Currently, odo assumes that  Secret created by SBO has the same name as ServiceBinding.
This is no longer valid. SBO Secrets have some kind of has as a suffix. 
This PR makes sure that odo detect the correct Secret name from SB definition. 
Fixes #?
=> Get SB secret name from SB

tests/e2escenarios/e2e_images_test.go, tests/helper/helper_oc.go
PR will fix the latest java:8 image import issue on CI.
```
Checking if "imagestreams" resource supported
[odo] I0330 18:55:13.516732   28620 imageStreams.go:98] Found exact image tag match for java:8
[odo]  ✗  unable to find tag 8 for image java
Deleting dir: /tmp/043054859
```
Log details: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/4563/pull-ci-openshift-odo-master-v4.7-integration-e2e/1377069342159540224
Fixes #?
All the tests related to java:8 should pass.
=> Fixing latest image import issue for java 8

scripts/openshiftci-periodic-tests.sh, scripts/openshiftci-presubmit-all-tests-old.sh, scripts/openshiftci-presubmit-all-tests.sh
The telemetry prompt popped up during a test due to the call to `odo
login`. Swap that to use `oc` directly and avoid the prompt.
Fixes #4568
=> Swap login/logout calls from using odo to oc directly

pkg/component/component.go, pkg/devfile/adapters/helper.go, pkg/devfile/adapters/helper_test.go, pkg/devfile/adapters/kubernetes/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter_test.go, pkg/devfile/adapters/kubernetes/component/podwatcher.go, pkg/devfile/adapters/kubernetes/component/podwatcher_test.go, pkg/devfile/adapters/kubernetes/component/status.go, pkg/devfile/adapters/kubernetes/component/status_test.go, pkg/odo/cli/component/common_push.go, pkg/url/url.go, pkg/url/url_test.go
It initializes the kubernetes adapter with a occlient instead of a kubeclient.
Fixes #4562 
- Running the tests with an invalid `KUBECONFIG` for the project should pass.
```
export KUBECONFIG=/tmp/test/asfdasdf
make test
```
=> Modifies newKubernetesAdapter() and others 

pkg/kclient/deployments.go, pkg/odo/cli/component/common_link.go
/kind api-change
/kind bug
Gets rid of the deprecated `SelfLink` attribute of a deployment and uses information available from the underlying cluster instead.
Fixes #4431
Along with OCP 4.6 and 4.7, `odo link` should work fine on OCP 4.8 and minikube started with `minikube start --kubernetes-version=v1.20.2`
=> Decide GVR based on underlying cluster

tests/integration/cmd_pref_config_test.go
Commenting out test that is accidentally sending out telemetry data to production stats.
=> Disable test sending out telemetry

tests/integration/devfile/cmd_devfile_create_test.go
This will resolve test failure on kubernetes cluster
Fixes #4577 
`make test-cmd-devfile-create` should run successfully on openshift and kubernetes both.
=> Separate out openshift specific tests

USAGE_DATA.adoc, pkg/odo/genericclioptions/runnable.go, tests/e2escenarios/e2escenarios_suite_test.go, tests/helper/helper_generic.go, tests/integration/cmd_pref_config_test.go, tests/integration/debug/debug_suite_test.go, tests/integration/devfile/debug/debug_suite_test.go, tests/integration/devfile/devfile_suite_test.go, tests/integration/integration_suite_test.go, tests/integration/loginlogout/loginlogout_suite_test.go, tests/integration/operatorhub/operatorhub_suite_test.go, tests/integration/project/project_suite_test.go, tests/integration/servicecatalog/servicecatalog_suite_test.go, tests/template/template_suite_test.go
/kind cleanup
- introduces `ODO_DISABLE_TELEMETRY ` env variable. When this is set to `true` odo will skip the telemetry question and it won't send any telemetry data out even if `odo preference set consentTelemetry true`.
- sets `ODO_DISABLE_TELEMETRY` in all ginkgo test suites to make sure that no data is sent to telemetry even by accident
- if odo is not executed in terminal (no tty) it won't ask user to consent with telemetry
Partly Fixes #4462 
=> introduce ODO_DISABLE_TELEMETRY and skip telemetry question when there is no tty

tests/e2escenarios/e2e_images_test.go, tests/helper/helper_oc.go
As https://bugzilla.redhat.com/show_bug.cgi?id=1945281 has been fixed. Reverting java:8 image import to default.
```
$ docker pull registry.redhat.io/redhat-openjdk-18/openjdk18-openshift:latest
latest: Pulling from redhat-openjdk-18/openjdk18-openshift
Digest: sha256:42567207376487246d144b3b06e7505cb912aaa0f0d1f0a093097e6cbccaa604
Status: Downloaded newer image for registry.redhat.io/redhat-openjdk-18/openjdk18-openshift:latest
registry.redhat.io/redhat-openjdk-18/openjdk18-openshift:latest
```
Fixes #4598 
All the tests related to java:8 should pass.
=> Revert Java:8 image import to default

.github/PULL_REQUEST_TEMPLATE.md, tests/integration/devfile/cmd_devfile_app_test.go, tests/integration/devfile/cmd_devfile_debug_test.go, tests/integration/devfile/cmd_devfile_delete_test.go, tests/integration/devfile/cmd_devfile_describe_test.go, tests/integration/devfile/cmd_devfile_log_test.go, tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/cmd_devfile_test_test.go, tests/integration/devfile/cmd_devfile_url_test.go, tests/integration/devfile/cmd_devfile_watch_test.go
/kind cleanup
This PR cleans up code that renders the use of `--context` useless.
Fixes #3801
Run the tests fixed by the PR.
=> Cleanup context in devfile integration tests

scripts/configure-installer-tests-cluster-s390x.sh, scripts/openshiftci-presubmit-all-tests.sh
For the operator-hub test cases, have verified supported on s390x.
> /kind bug
make odo supported on s390x, and including operator-hub cases in ci
Fixes #3672 
just run the test script
=> add operator-hub tests to ci for s390x platform

scripts/configure-installer-tests-cluster-s390x.sh
For the java image used in s390x CI script, also need to change refer to #4569.
> /kind bug
Update java image import for s390x platform, change the tag in the oc import-image command.
Fixes #4569 
configure test cluster for s390x 
just run the test script
=> update java image import for s390x platform

pkg/devfile/adapters/helper.go
/kind bug
It fixes kClient namespace in createKubernetesAdapter()
Fixes https://github.com/openshift/odo/issues/4609
- The scenario mentioned in https://github.com/openshift/odo/issues/4609 should pass.
=> Fixes kClient namespace in createKubernetesAdapter()

pkg/segment/segment.go, pkg/segment/segment_test.go
/kind cleanup
This PR removes file-path, if it is present, from telemetry data before it is sent.
Partly Fixes #4462
Run an odo command that is likely to print an error with a file-path and see if it is sanitized properly.
=> Sanitize file-path from telemetry data

scripts/minici-presubmit-all-tests.sh
Minikube jobs are not able to run whole test suite within 2h15min. So increasing the timeout.
Fixes #?
=> Increase Run time for minikube job

pkg/odo/cli/component/devfile.go, pkg/odo/cli/component/list.go, pkg/odo/cli/component/push.go, pkg/odo/cli/component/status.go, pkg/odo/cli/component/test.go, pkg/odo/cli/component/watch.go, pkg/odo/genericclioptions/context.go
/kind cleanup
ParseAndValidate has been deprecated in favour of
ParseDevfileAndValidate
Fixes NA
Test should pass
=> Use ParseDevfileAndValidate instead of ParseAndValidate

scripts/configure-installer-tests-cluster-s390x.sh
Reverting back changes in https://github.com/openshift/odo/pull/4602 as `registry.redhat.io/redhat-openjdk-18/openjdk18-openshift:latest` has been fixed.
Fixes #?
It should run successfully on s390x arch.
=> Revert java import changes for s390x

pkg/odo/cli/component/create.go
Signed-off-by: jingfu wang <jingfwan@redhat.com>
/kind bug
This PR fixes the issue that starter project overrides the devfile stack additional resources in the project root directory. The issue only happens on the case where the devfile stack has additional resources (eg. icon, outer loop configuration). 
Related issues:
1. https://github.com/openshift/odo/issues/4504
2. https://github.com/devfile/api/issues/367
1. Run `odo create nodejs --registry DefaultDevfileRegistry --starter` then verify the nodejs devfile and corresponding resources and starter project can be downloaded from OCI-based public …
=> OCI-based devfile reigstry support patch

go.mod, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/odo/cli/component/devfile.go, pkg/odo/cli/component/push.go, pkg/odo/cli/service/create.go, pkg/odo/cli/service/operator_backend.go, pkg/service/service.go, tests/integration/operatorhub/cmd_service_test.go
/kind feature
This PR ensures that an Opreator backed service is created on the cluster only when user does `odo push` and not when they do `odo service create`.
Fixes part of the scope mentioned in https://github.com/openshift/odo/issues/4160#issuecomment-809366184
Notes:
* This PR is targeted only for `odo service create; odo push` workflow for Operator backed services. Adding labels to the service, deleting service upon doing `odo push` and Service Catalog related changes will come in subsequent PRs after this one is merged. Doing this to break big piece into smaller chunks.
* ~I need to add …
=> Creates service on cluster upon "odo push"

pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/service/service.go
/kind feature
Adds component labels to Operator backed services. We will need this for:
* `odo service list` - to list services that belong to a component. Refer https://github.com/openshift/odo/issues/4160#issuecomment-806678542 for more details.
* `odo service delete` - to delete services from cluster, we will compare the Kubernetes Inlined components in a devfile with the list of services belonging to the component on the cluster
Fixes part of the scope mentioned in https://github.com/openshift/odo/issues/4160#issuecomment-809366184
*Notes*
* There's no integration test on this one because it's not …
=> Adds component labels to Operator backed services

pkg/odo/cli/preference/set.go, pkg/odo/cli/preference/unset.go
This PR refactors the preference examples to use Go templates instead of normal string formatting
Fixes #4654 
```
odo preference --help
odo preference unset --help
```
=> Refactor help examples to use go templates

tests/e2escenarios/e2e_images_test.go
> /kind bug
> [skip ci]
#4518 move two centos cases from only arm64 to all platform, but s390x doesn't support and don't have the centos7 s390x arch image. So we need skip the cases on s390x platform, I reverted the related move changes for #4518.
Fixes #4518 ?
skip two cases for s390x 
just run the test script
=> skip centos7 image test on s390x

pkg/kclient/pods.go, pkg/kclient/pods_test.go, tests/integration/devfile/cmd_devfile_storage_test.go
/kind bug
It adds a check to ignore pods which are marked for deletion.
Fixes #4655 
- Create a storage and push the changes to the component `odo storage create && odo push`
- Delete the component and then list the storage `odo delete -f && odo storage list`.
=> Adds a check to ignore pods which are marked for deletion

tests/helper/helper_cli.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/helper/helper_run.go, tests/integration/devfile/cmd_devfile_storage_test.go
It fixes the storage list integration test for kubernetes clusters.
Fixes https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/4660/pull-ci-openshift-odo-main-psi-kubernetes-integration-e2e/1388053768792182784#1:build-log.txt%3A601
- Tests should pass on kuberenetes clusters.
=> Fixes the storage list integration test for kubernetes clusters

docs/public/breaking-changes-in-odo-2.2.adoc
[skip ci]
see $SUBJECT 
Fixes https://github.com/openshift/odo/issues/4281
=> add breaking changes in odo 2.2 doc

pkg/devfile/convert/convert.go, tests/integration/component.go
After this change the generated devfile would generate a very similar url as new devfiles
Fixes https://github.com/openshift/odo/issues/4621
=> follow devfile like conventions in generated url name to keep url short for --s2i

tests/integration/devfile/cmd_devfile_catalog_test.go, tests/integration/devfile/cmd_devfile_registry_test.go
/kind cleanup
After moving to use OCI-based registry (https://github.com/openshift/odo/pull/4525), devfile tests should be using OCI-based registry as well. 
Related issues:
https://github.com/devfile/api/issues/367
https://github.com/openshift/odo/issues/4504
https://github.com/openshift/odo/pull/4525
This PR is for changing test codes.
=> Update devfile tests with OCI-based registry

scripts/openshiftci-unit-psi-tests_win_mac.sh
kind /failingtest
It fix typo in windows jobs name for unit test
N/A
=> fix typo in unit-test job name for windows

pkg/preference/preference.go
Signed-off-by: jingfu wang <jingfwan@redhat.com>
/kind bug
This PR ensures the OCI-based registry auto migration only migrates the old default registry.
Related issue: https://github.com/openshift/odo/issues/4504
=> Fix OCI-based registry migration

pkg/component/component.go, pkg/devfile/adapters/common/types.go, pkg/devfile/adapters/common/utils.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/sync/adapter.go, pkg/sync/adapter_test.go, pkg/sync/sync.go, pkg/sync/sync_test.go, pkg/util/file_indexer.go, pkg/util/file_indexer_test.go, tests/examples/source/devfiles/nodejs/devfile-with-remote-attributes.yaml, tests/integration/devfile/cmd_devfile_push_test.go
/kind feature
It uses the `dev.odo.push.path` attribute to push only the mentioned files.
Fixes https://github.com/openshift/odo/issues/3132
- Use the attribute `dev.odo.push.path:<local-path>:<remote-path>` in the run command to mark the files/folders which should be pushed inside the container.
- Execute `odo push`
- Use to `kubectl exec` to check if the required file/folders are present inside the container and their location.
=> Adds dev.odo.push.path attribute support for pushing only mentioned files

docs/public/deploying-java-app-with-database.adoc
[skip ci]
SBO behavior has changed and '.' in annotations are no longer converted  to "_" in the secret keys.
We _could_  mention specific versions in the doc but probably OK just to keep tracking the latest.
- [ X] Documentation
=> Fix SB annotations since '.' no longer converted to '_'

scripts/minici-presubmit-all-tests.sh, scripts/openshiftci-e2e-4x-psi-tests.sh, scripts/openshiftci-unit-psi-tests_win_mac.sh
kind /failingtest
This PR adds commands to debug failure experienced in release repo and adds a flag to use jenkinsProject 
=> add --jenkinsProject in PSI test script 

pkg/config/url.go, pkg/envinfo/envinfo.go, pkg/envinfo/url.go, pkg/envinfo/url_test.go, pkg/odo/cli/url/create.go, pkg/odo/genericclioptions/context.go, pkg/util/url_test.go, tests/integration/devfile/cmd_devfile_url_test.go
/kind bug
It also modifies the error messages when no port is provided.
Fixes #4493
- Download a devfile with an existing URL endpoint and no host information should exist on the env file.
- Trigger `odo url create` on a kubernetes cluster.
- The endpoint which came with the devfile should have host information in the env file.
=> Removes invalid endpoints from the devfile on triggering url create.

README.adoc
Signed-off-by: John Collier <jcollier@redhat.com>
[skip ci]
Updates the devfile registry link in the readme from [odo-devfiles/registry](https://github.com/odo-devfiles/registry) to [devfile/registry](https://github.com/devfile/registry), now that the former is no longer used and is archived.
While the registry is hosted at https://registry.devfile.io, I opted to link to the repository instead, as that's the source repository for the devfiles.
N/A
=> [skip ci] Update links to devfile registry in readme

docs/public/using-devfile-odo.dev.push.path-attribute.adoc
[skip ci]
It adds a document regarding the `odo.dev.push.path` related attributes for https://github.com/openshift/odo/pull/4588
Fixes part of #3132 
- The doc should be valid.
=> Adds a document regarding the odo.dev.push.path attributes in the devfile

Changelog.md, docs/public/git-registry-deprecation.adoc, pkg/catalog/catalog.go, pkg/log/status.go, pkg/odo/cli/component/create.go, pkg/odo/cli/registry/add.go, pkg/odo/cli/registry/list.go, pkg/odo/cli/registry/update.go, pkg/odo/cli/registry/util/util.go, pkg/odo/cli/registry/util/util_test.go, tests/integration/devfile/cmd_devfile_registry_test.go
/kind deprecation
This PR adds deprecation warning for git based registries, whever they are created/listed/updated/used
Fixes #4666 
```
❯ odo registry list
NAME                       URL                             SECURE
DefaultDevfileRegistry     https://registry.devfile.io     No
❯ odo create nodejs
Devfile Object Validation
✓  Checking devfile existence [20878ns]
✓  Creating a devfile component from registry: DefaultDevfileRegistry [36812ns]
Validation
✓  Validating if devfile name is correct [46943ns]
Please use `odo push` …
```
=> Adding deprecation warning for git based registries

tests/integration/operatorhub/cmd_service_test.go
This PR fix Operatorhub test to uses CreateNewContext() in the test to compatible with windows.
Fixes https://github.com/openshift/odo/issues/4680
`make test-operator-hub`
=> Fix Operatorhub test to use CreateNewContext()

docs/public/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.adoc
[skip ci]
Since the DefaultDevfileRegistry don't support IBM Z & Power now, we give this doc to show how to use devfile on IBM Z & Power for clients.
=> Add doc to introduce using devfiles on IBM Z & Power.

docs/dev/development.adoc, scripts/changelog-script.sh
Updates dev docs with updated release process of using changelog.md instead of github changelog generator and updates script to generate baseline release notes
```
❯ sh scripts/changelog-script.sh v2.1.0 v2.2.0
The changelog is located at: /tmp/changelog
❯ cat /tmp/changelog
[Full Changelog](https://github.com/openshift/odo/compare/v2.1.0...v2.2.0)
-- COPY CONTENT FROM Changelog.md here --
To install odo, follow our installation guide at [docs.openshift.com](https://docs.openshift.com/container-platform/latest/cli_reference/developer_cli_odo/installing-odo.html)
After each release, binaries are …
```
=> Updating docs and changelog script for updated release process

Changelog.md, pkg/util/util.go
/kind bug
We were using os specific method to join path for kubeconfig, using `filepath.Join` instead. Also we are not ignoring error from homedir function anymore also.
No issue
=> use filepath Join instead of / while constructing kubeconfig path

pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/odo/cli/component/devfile.go, pkg/util/util.go, pkg/util/util_test.go, tests/helper/helper_cli.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/helper/helper_run.go, tests/integration/devfile/cmd_devfile_push_test.go
/kind feature
It adds the annotation `app.openshift.io/vcs-uri` to the deployment.
Fixes #4544 
- Create a component using `odo create` and trigger `odo push` on a directory in which `git` has been initialized and a remote named `origin` is present.
- Check if the annotation `app.openshift.io/vcs-uri` is present with the value which is to the fetch URL of the `origin` remote.
- If the directory is not a `git` directory, the above annotation should be empty.
=> Adds the annotation app.openshift.io/vcs-uri to deployments

README.adoc
Wrong version for nodejs devfile stack.
The image the devfile pulls for nodejs is version 14 and not version 12.
https://github.com/devfile/registry/pull/32
=> [skip ci] Fixed README typo for nodejs devfile version

Changelog.md, pkg/envinfo/envinfo.go, pkg/envinfo/envinfo_test.go, pkg/odo/cli/component/common_link.go, pkg/odo/cli/component/link.go, tests/integration/cmd_link_unlink_test.go, tests/integration/operatorhub/cmd_service_test.go
Fixes #4693 
**TODO**
On a cluster with some Operator backed services installed (for example etcdoperator.v0.9.4-clusterwide):
```
$ odo create nodejs 
$ odo service create etcdoperator.v0.9.4-clusterwide/EtcdCluster myetcd
$ odo push
$ odo link EtcdCluster/myetcd --name myetcd-config
$ oc get servicebinding myetcd-config
$ odo unlink EtcdCluster/myetcd
$ odo link EtcdCluster/myetcd --name myetcd-config --bind-as-files
$ oc get servicebinding myetcd-config -o …
```
=> Custom link names and bindAsFiles option for SB

tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/debug/debug_suite_test.go, tests/integration/devfile/devfile_suite_test.go
/kind cleanup
Use staging devfile registry for integration test with devfile. Using a production registry would result in unnecessary overload.
Fixes https://github.com/openshift/odo/issues/4639
=> Use staging devfile registry for integration tests

tests/integration/devfile/debug/debug_suite_test.go
/kind cleanup
Use staging devfile registry for devfile debug suite test similar to https://github.com/openshift/odo/pull/4752
Fixes #4639
=> Use staging registry for devfile debug suite test

pkg/segment/segment.go, pkg/segment/segment_test.go
/kind bug
This PR sanitizes some more data that might have some potential PII data.
Fixes part of #4462 
Running unit tests should be fine or perhaps test with data that potentially contains personal data.
=> Sanitize Telemetry data

scripts/openshiftci-e2e-4x-psi-tests.sh, scripts/openshiftci-unit-psi-tests_win_mac.sh
As the successful unit test takes usually 10 min, so waiting for more than 20min does not make sense.
Fixes part of - #4789 
unit test for windows and macOS should not wait more than 20 min if it is supposed to fail
=> Reducing timeout for windows and macOS unit test to 20m

Makefile
When running ginkgo on CI, we want to use vendor dependencies instead of trying to download the dependencies.
Because ginkgo is building itself the tests suite from source, we need to pass it `-mod=vendor` flag, or it will try to build the tests suite by downloading deps.
In `v4.7-integration-e2e` environment, we get the error:
```
ginkgo  -mod=vendor -randomizeAllSpecs -slowSpecThreshold=120 -timeout 14400s -nodes=2 tests/integration/ 
Failed to compile integration:               
go test: mod flag may be set only once       
```
This error happens when running the previous command with `GOFLAGS="-mod=vendor"`:
```
$ GOFLAGS="-mod=vendor" go run -mod=vendor github.com/onsi/ginkgo/ginkgo …
```
=> ginkgo checksum error on CI

tests/helper/helper_oc.go, tests/integration/operatorhub/cmd_service_test.go
This PR refactors the code of the Operator Hub integration tests.
- `Context` describes a state of the cluster, and `JustBeforeEach` checks/wait that the state is ready
- `When` describes the execution of a command or other action **with side-effect** by the user, `JustBeforeEach` contains the execution of the command, `JustAfterEach` contains the counterpart of this command if necessary
- `It` checks the expectations after the last command executed. For readibility, `It` can contain commands executed by the user if these commands have no side-effect (commands failing, lists, describes, etc)
To add a test in this flow, a developer has to follow the Context/When tree to place its tests at the …
=> Refactor OperatorHub integration tests

pkg/odo/genericclioptions/runnable.go, tests/e2escenarios/e2e_java_test.go, tests/integration/component.go, tests/integration/devfile/cmd_devfile_delete_test.go
/kind cleanup
1. Add validity checks for the delete command as mentioned in issue https://github.com/openshift/odo/issues/4451#issuecomment-783431524
2. Add tests for validity checks
3. Add missing test cases for issue #4451 
4. Refactor tests with the new testbook approach
Fixes #4451
=> Refactor devfile delete tests and add validity checks for delete command

pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/kclient/services.go, pkg/odo/cli/component/common_link.go, tests/integration/operatorhub/cmd_service_test.go
/kind feature
It adds the ability to link one devfile component to another devfile component.
Fixes #3423 
- Create two devfile components. 
```
mkdir frontend-dir
mkdir backend-dir
odo create nodejs frontend --context frontend-dir
odo push --context frontend-dir
odo create nodejs backend --context backend-dir
odo push --context backend-dir
```
- Execute `odo link <component-name-1>` from the directory of `<component-name-0>`.
```
odo link backend --context frontend-dir
```
- Check if a `servicebinding` resource has been generated successfully or not.
- A secret should be mentioned in the …
=> Adds ability to link one devfile component to another

pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/utils/utils.go, pkg/devfile/adapters/kubernetes/utils/utils_test.go
Signed-off-by: Stephanie <yangcao@redhat.com>
/kind cleanup
This PR removes GetPreStartInitContainers from odo util:
1. should use generator from library to get initcontainers
2. odo currently does not support PreStart and apply commands
https://github.com/openshift/odo/blob/a54cfd86da993560768c7aae1a8fd1a1c017b833/pkg/devfile/validate/events.go#L5-L14
Fixes #?
=> remove getInitContainer from odo

scripts/minikube-minishift-all-tests.sh, scripts/minikube-minishift-setup-env.sh
kubeconfig fails finding config file, if minikube is already running on the VM. And thats why we don't have long running minikube on VM. It also unblock us for executing concurrent builds on jenkins.
Fixes #4826 
`minikube` job should run successfully.
=> Fix kubeconfig issue when minikube already running on VM

pkg/service/service.go
/kind bug
It fixes push on 3.11 clusters
Fixes #4830 
`odo push` should work on all supported cluster types including 3.11.
=> Fixes push when csv support is not present on the cluster

scripts/minikube-minishift-setup-env.sh
Fix test failure if `kubelet` gets stopped somehow https://github.com/openshift/odo/pull/4661#issuecomment-864912787 
```
$ minikube status
minikube
type: Control Plane
host: Running
kubelet: Stopped
apiserver: Stopped
kubeconfig: Configured
```
Fixes #?
minikube should run test successfully.
=> Fix minikube tests if kubelet gets stopped

scripts/minikube-minishift-setup-env.sh
We have some failure on minikube. Might be due to `kubelet` stopped working so often. However `minikube status` results on vm and pr runs contradict.
Minikube status on prs:
```
minikube status
[ssh:Fedora-32-minikube] ++ mkStatus='* There is no local cluster named "minikube"
++ minikube start --vm-driver=docker --container-runtime=docker
[ssh:Fedora-32-minikube] * minikube 1.21.0 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.21.0
[ssh:Fedora-32-minikube] * To disable this notice, run: 'minikube config set WantUpdateNotification false'
Unable to restart cluster, will reset it: getting k8s client: client config: client config: context "minikube" does not exist
``` …
=> Fix minikube failures on pr

docs/dev/test-architecture.adoc, tests/helper/helper_run.go, tests/integration/devfile/debug/debug_suite_test.go, tests/integration/devfile/devfile_suite_test.go, tests/integration/operatorhub/cmd_service_test.go, tests/integration/project/cmd_project_test.go
This PR will remove old helper functions mentioned below
- CmdShouldRunAndTerminate
- CmdShouldFail
- CmdShouldPass
- CmdShouldFailWithRetry
- CmdShouldRunWithTimeout
Fixes #4517
=> Remove cmd helper functions

Makefile
Run the parallel ginkgo tests on 4 nodes (instead of 2 previously).
The non-parallel tests are still running on a single node.
=> Set 4 nodes for ginkgo tests

pkg/devfile/devfile.go, tests/examples/source/devfiles/nodejs/devfile-variables.yaml, tests/integration/devfile/cmd_devfile_create_test.go, tests/integration/devfile/cmd_devfile_list_test.go, tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/utils/utils.go
/area testing
add integration test to verify that variables have been added in devfile 2.1.0 are working properly 
This also updates structure of devfile push tests.
At a core level, there are 6 main test groups
- verify devfile push works  - generic tests, that don't fit other categories
- verify files are correctly synced
- verify devfile volume components work
- verify command executions
- using OpenShift cluster
- using Kubernetes cluster
Fixes #4589
`cmd_devfile_push_test.go` diff is pretty much unreadable. 
When reviewing it might be easier to check the whole file here …
=> add integration tests for devfile 2.1.0 and refactor devfile push tests

scripts/openshiftci-presubmit-unittests.sh
This PR disable tests for rpm builds on unit tests
Fixes #?
=> disable rpm-build test from unit test

Changelog.md, pkg/kclient/fakeclient.go, pkg/kclient/ingress.go, pkg/kclient/ingress_test.go, pkg/kclient/kclient.go, pkg/odogenerator/ingressgenerator.go, pkg/unions/kubernetes_ingress.go, pkg/url/kubernetes.go, pkg/url/types.go, pkg/url/url.go
/kind task
This is part 2 of the move from extensions v1beta1 ingress to networking v1 ingress
Fixes #4592 
```bash
> odo create nodejs
Devfile Object Validation
✓  Checking devfile existence [93840ns]
✓  Creating a devfile component from registry: DefaultDevfileRegistry [159109ns]
Validation
✓  Validating if devfile name is correct [137914ns]
Please use `odo push` command to create the component with source deployed
> odo url create ingress-3001 --port 3001 --host com --protocol https --ingress --secure
✓  URL ingress-3001 created for component: nodejs-nodejs-ex-kfga
To apply the URL configuration …
```
=> Updating create, delete and get to newer networking v1 extension v1 union functions

Changelog.md, pkg/component/component.go, pkg/component/component_full_description.go, pkg/component/component_test.go, pkg/component/pushed_component.go, pkg/component/types.go, pkg/kclient/deployments.go, pkg/odo/cli/component/delete.go, pkg/odo/util/cmdutils.go, pkg/odo/util/completion/completionhandlers.go, pkg/service/service.go, tests/integration/operatorhub/cmd_link_test.go
/kind feature
> Unused code relative to "linked components" has been removed, because it was detecting the linked components using the old way (based on labels and annotations instead of ServiceBindingRequests):
>
> ```
> componentName, containsComponentLabel := secret.Labels[componentlabels.ComponentLabel]
> 		if containsComponentLabel {
> 			if port, ok := secret.Annotations[kclient.ComponentPortAnnotationName]; ok {
> 				linkedComponents[componentName] = append(linkedComponents[componentName], port)
> 			}
> 		}
> ```
>
> Issue #4871  tracks the update of this behaviour with the new way to create links (with ServiceBindings).
Fixes #3734 
**How to test changes / Special notes to …
=> Add linked service information in odo describe

Changelog.md, pkg/odo/cli/component/create.go, pkg/odo/cli/component/push.go, pkg/odo/cli/project/create.go, pkg/odo/cli/project/set.go, pkg/odo/genericclioptions/runnable.go, pkg/segment/context/context.go, pkg/segment/context/context_test.go, pkg/segment/segment.go, pkg/segment/segment_test.go
/kind cleanup
The changes introduced with this PR will add properties to telemetry context only if telemetry is enabled.
Fixes part of #4462 
There isn't much to test here, except you can disable telemetry and check if the data is added to contextual property with debugger.
=> Add telemetry contextual properties if it is enabled

pkg/component/pushed_component.go, pkg/debug/portforward.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/kclient/errors.go, pkg/kclient/fake/ingress.go, pkg/kclient/pods.go, pkg/kclient/services.go, pkg/kclient/services_test.go, pkg/odo/cli/component/common_link.go, pkg/odo/cli/component/devfile.go, pkg/storage/kubernetes.go, pkg/storage/kubernetes_test.go, pkg/storage/storage.go, pkg/storage/storage_test.go, pkg/testingutil/pods.go, pkg/testingutil/services.go, pkg/url/kubernetes.go, pkg/url/kubernetes_test.go, pkg/url/url.go, pkg/util/util.go, pkg/util/util_test.go, tests/integration/devfile/cmd_devfile_app_test.go, tests/integration/operatorhub/cmd_service_test.go
/kind bug
/kind design
Fixes #4550 
Create two components with the same name in different apps
- `odo create nodejs <component-name> --app app --context <directory of the first component>`
- `odo create springboot <component-name> --app app1 --context <directory of the second component>`
- Trigger `odo push` for the both the components
- `oc get service` should list both the services
- `oc get deployments` should list both the deployments
- Check the list output for `odo list --app app` and `odo list --app app1`.
=> Renames the service name to include the app name

pkg/odo/cli/component/devfile.go, pkg/odo/cli/config/set.go, pkg/odo/cli/config/unset.go, pkg/odo/genericclioptions/context.go, tests/integration/cmd_pref_config_test.go
/kind bug
[see title]
Fixes #4594
With now flag
```bash
> odo create nodejs
...
> odo push
Validation
✓  Validating the devfile [164372ns]
Updating services
✓  Services and Links are in sync with the cluster, no changes are required
Creating Kubernetes resources for component nodejs-nodejs-ex-odtu
✓  Waiting for component to start [7s]
✓  Waiting for component to start [427ms]
Applying URL changes
✓  URL http-3000: http://http-3000-nodejs-nodejs-ex-odtu-uv.apps.testocp47.psiodo.net/ created
Syncing to component nodejs-nodejs-ex-odtu
✓ …
```
=> Fixing now implementation for config set and unset in devfile

pkg/testingutil/configs.go
/kind bug
This PR cleanup the dangling dirs created when we run unit tests
Fixes https://github.com/openshift/odo/issues/4817
=> delete dangling dir created by unit-tests

tests/examples/source/devfiles/nodejs/devfile-with-link.yaml, tests/integration/operatorhub/cmd_link_test.go, tests/integration/operatorhub/cmd_service_test.go
/kind flake
During the execution of the tests, you can check that all pod started by the tests have set a **Memory Request**, and that the system memory allocated is not exhausted by examining the output of `kubectl describe node`:
```
$ kubectl describe node <worker-node>
[...]
Namespace                                   Name                                                             CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
---------                                   ----                                                             ------------  ----------  ---------------  -------------  ---
cmd-link-test99ggn                          cmp-hwbaqb-app-fdc5f8b95-vfc8t                                   0 (0%)        0 (0%)      300M (1%) …
```
=> Limits memory requests to deploy more components

rpms/openshift-odo.spec
- This makes it possible to override golang version based on
availability in build system of rpm
=> Enabling override of required golang in rpm

sonar-project.properties
/kind feature
This PR adds config file for Sonar Cloud Code Analysis so that we can track any changes to its configuration instead of manually doing it from the website.
Current config - 
1. - [x] Analyze source code from cmd and pkg directory.
1. - [x] Exclude any (unit)test file.
2. - [x] Analyze test code from tests directory.
3. - [x] Exclude analyzing any files under vendor directory.
4. - [x] Ignore the "Define a constant instead of duplicating this literal" rule for test files. See code smells in test files [here](https://sonarcloud.io/project/issues?id=openshift_odo&resolved=false).
Fixes part of #4879 
**How to test changes / Special notes to the …
=> Add Sonar Cloud config file: sonar-project.properties

Changelog.md, pkg/kclient/pods.go
/kind bug
`WaitAndGetPodWithEvents` now waits for an event with a Phase different from the expected one before to start the Spinner. This way, the spinner is only displayed when the pod is not in the expected phase.
Fixes #4362 
=> Do not display "Waiting for component to start" twice

pkg/component/starter_project.go, tests/integration/devfile/cmd_devfile_create_test.go
/kind bug
It modifies the error message to list the available starters.
Fixes #4481 
- Trigger `odo create --starter=<invalid-starter-name> nodejs`
- The error message should show the names of the available starters.
=> Modifies the error message to list the available starters

pkg/devfile/convert/convert.go, tests/integration/component.go
/kind bug
This PR adds user-provided component name to devfile metadata for normal component creation and language to devfile metadata for s2i creation.
Fixes #4816
1. Create a s2i component and check if `.metadata.language` and  `.metadata.projectType` is set properly in the devfile.yaml. `odo create --s2i nodejs mynodecomp`.
=> Add language and projectType metadata in devfile for s2i components

pkg/preference/preference.go, website/docs/getting-started/configure.md
This PR adds documentation for global odo configuration.
Fixes part of #4894
```
$ cd website/docs
$ npm install # this command installs dependencies required to create the website
$ npm run start
```
=> Add documentation for global configuration

website/docs/getting-started/installation.md
This PR adds odo installation docs.
Fixes part of #4894
```
$ cd website/docs
$ npm install # this command installs dependencies required to create the website
$ npm run start
Go to Getting Started > Installations
```
=> Add odo installation docs

scripts/openshiftci-periodic-tests.sh
/kind feature
This pr allows other suites to atleast run, even if one suite fails. If there is any failure build automatically failed because of that but atleast entire test suite runs on periodic job
Fixes #?NA
All the test suite should run as part of periodic job
=> Do not cancel the whole execution if one of the test suite fails

Changelog.md, Makefile, pkg/odo/cli/component/list.go, tests/integration/component.go, tests/integration/devfile/cmd_devfile_list_test.go
/kind feature
It adds a column in odo list output to indicate which components are created by odo.
Fixes #4808
- Deploy some components in the same and different apps.
- `odo list`, `odo list --app <app-name>` && `odo list --all-apps` should display a column indicating which components are managed by odo.
Example output:
```
$ odo list --all-apps 
APP         NAME                         PROJECT     TYPE       STATE      MANAGED BY ODO
new-app     nodejs-nodejs-basic-ummk     blah        nodejs     Pushed     No
```
=> Adds a column in odo list output to indicate components created by odo

Changelog.md, pkg/odo/cli/component/link.go, tests/integration/cmd_link_unlink_test.go
/kind cleanup
odo link had an outdated description
commands supports linking two devfile components
=> odo link: fix command description

scripts/openshiftci-Nightly-SBO-tests.sh, scripts/openshiftci-periodic-tests.sh, scripts/openshiftci-presubmit-all-tests.sh
This PR will fix nightly test build failure for reports path https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-odo-main-v4.8-operatorhub-integration-nightly/1423433739802775552#1:build-log.txt%3A535
As we only run operator hub tests on nightly. It generates reports under `tests` directory and we are searching into current `odo` directory currently. Hence it error out with `no such file or directory`
Fixes #? 
Nightly test should not fail.
=> Fix reports directory for operatorhub nightly tests

Changelog.md, pkg/odo/cli/component/create.go, pkg/odo/cli/component/push.go, tests/integration/component.go
/kind deprecation
This PR adds deprecation warning for S2I components on create and push.
Fixes #4951
1. `odo create --help`: Run the help command and see deprecation notes for s2i, ref, git, and binary flags.
2. `odo create --s2i python mypy`
3. `odo create nodejs --s2i --git https://github.com/openshift/nodejs-ex.git` ; `odo push`
4. `touch sample.jar; odo create --s2i --binary sample.jar` ; `odo push`
**Note**: The deprecation warning message is not in its best state, I would appreciate if reviewers can suggest a better guidance  to the users regarding the next step.
=> Add deprecation warnings for s2i components

Changelog.md, website/OWNERS, website/docs/command-reference/catalog.md, website/docs/command-reference/component.md, website/docs/command-reference/env.md, website/docs/command-reference/login.md, website/docs/command-reference/project.md, website/docs/command-reference/storage.md, website/docs/command-reference/url.md, website/docs/using-odo/create-component.md
what: $subject
why: because it helps users new to odo
Fixes part of #4895
=> Documents steps for component creation

pkg/odo/cli/service/operator_backend.go, tests/integration/operatorhub/cmd_service_test.go
/kind bug
It fixes the usage of service create command with parameters and dry-run flag.
Fixes #4813 and #4913 
- Running service create with the `--dry-run` flag and user provided parameters e.g `odo service create postgresql-operator.v0.1.1/Database -p databaseName=mydb -p databaseUser=user -p databasePassword=pass --dry-run` should display
```
apiVersion: postgresql.dev4devs.com/v1alpha1
kind: Database
metadata:
name: database
spec:
databaseName: mydb
databasePassword: pass
databaseUser: user
```
=> Fixes the usage of service create command with parameters and dry-run flag

OWNERS, tests/OWNERS
/kind cleanup
To ensure right folks get selected by the bot for reviews
Fixes - NA
=> Removed QE members from top-level reviewers

website/docs/architecture/_category_.json, website/docs/architecture/secure-registry.md, website/docs/contributing/_category_.json, website/docs/tutorials/_category_.json, website/docs/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.md, website/docs/tutorials/deploying-java-app-with-database.md, website/docs/tutorials/deploying-your-first-devfile.md
1. Adds a tutorials section to the doc website
2. Adds docs which are copy-pasted from the old website.
1. https://odo.dev/docs/deploying-java-app-with-database/ - Refer to the unpublished changes from https://github.com/openshift/odo/pull/4923 for review.
2.  https://odo.dev/docs/deploying-a-devfile-using-odo-on-IBM-Z-and-Power - Content about introduction to devfile and relation between odo and devfile were duplicated, so that has been removed.
3. Adds placeholder for
1. website/docs/architecture/secure-registry.md
2. website/docs/tutorials/deploying-your-first-devfile.md
Fixes part of #4894 
**How to test changes / Special notes to …
=> Add Tutorials section to doc website

pkg/odo/genericclioptions/runnable.go, pkg/segment/context/context.go, pkg/segment/segment.go, pkg/util/util.go
/kind feature
This PR allows sending telemetry data for odo push on user interrupt.
Fixes #4929 
```sh
odo preference set consenttelemetry true -f
odo create java-openliberty myproject --starter
odo push     <- interrupt the program
Ctrl^C
```
See if telemetry data was sent to Segment.
Sample telemetry data - 
```
map[string]interface{}{
"clusterType": "kubernetes",
"componentType": "docker",
"duration(ms)": 995,
"error": "User quit.",
"error-type": "*errors.fundamental",
"success": false,
"tty": true,
"version": "odo v2.2.3 (2e661bf71)",
}
```
=> Send telemetry data on user interrupt

sonar-project.properties
/kind cleanup
This PR adds a new sonar rule to exclude all the files under tests/integration from the "duplicated string literals" error.
[See example](https://sonarcloud.io/project/issues?id=openshift_odo&open=AXsVq_A1ATb_4uWKYpVu&pullRequest=4927&resolved=false&types=CODE_SMELL).
Fixes #?
I am not sure if we can test it at the moment, we'll only know if this works once it is merged in.
=> Add sonar rule to ignore 'duplicated string literals' error on test files

pkg/odo/cli/service/list.go
/kind bug
Fixes typo in `odo service list` output
Fixes N/A
Run `odo service list` when no services are created in devfile.
=> Fix typo when there are no services

pkg/odo/cli/component/create.go
/kind bug
This PR fixes the missing default project value while creating a component interactively,
Fixes #?
_**Deleted KUBECONFIG**_:
1. `mv $HOME/.kube/config $HOME/.kube/movedConfig`
2. `odo create` - After entering component type and name, check if the current project shows up in while entering the project value, in this case it should be an empty string.
```sh
$ odo create
? Which devfile component type do you wish to create  [Use arrows to move, ent? Which devfile component type do you wish to create java-maven
? What do you wish to name the new devfile component java-maven
? What project do you …
```
=> Display default project value while creating a component interactively

pkg/odo/cli/service/list_operator.go, pkg/odo/cli/service/list_operator_test.go, pkg/service/service.go, pkg/service/service_test.go, tests/integration/operatorhub/cmd_service_test.go
=> List all services in JSON output

pkg/component/component.go, pkg/component/component_test.go, pkg/component/labels/labels.go, pkg/component/pushed_component.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter_test.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/create_helpers.go, pkg/odo/cli/component/list.go, pkg/odo/cli/component/push.go, pkg/testingutil/deployments.go, tests/examples/source/devfiles/nodejs/devfile.yaml, tests/examples/source/devfiles/springboot/devfile-with-missing-projectType-and-language-metadata.yaml, tests/examples/source/devfiles/springboot/devfile-with-missing-projectType-metadata.yaml, tests/helper/helper_generic.go, tests/helper/odo_utils.go, tests/integration/component.go, tests/integration/devfile/cmd_devfile_create_test.go, tests/integration/devfile/cmd_devfile_describe_test.go, tests/integration/devfile/cmd_devfile_list_test.go
/kind bug
1. Set the correct component name in the devfile metadata.
2. In case a devfile is already present and user runs `odo create`, name the component to what is present in the devfile and not the dir name. If the `.metadata.name` is not present or if the devfile is not accessible, only then name the component to context dir name.
2. List and Describe to show the `.metadata.projectType` or `.metadata.Language` as the component type, if neither of them are available, it sets the type to `Not available`.
2. Add tests, and modify existing tests.
4. Move `GetComponentTypeFromMetadata` from `create_helpers.go` to `component.go`  so that the function can be used in both the files without any …
=> Set correct component name in the devfile metadata

pkg/segment/segment.go
/kind bug
This will make sure that we identify every user,
not just those for which we created anonymousId.
User can already have anonymousId assigned by other tools like crc or
vscode plugins.
Before this odo did not send identify event for those users. This created
a situation where we were missing some information about those users.
More info about this in https://github.com/openshift/odo/issues/4994#issuecomment-902606879
=> Send Identify event with every Track event

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
version bump before release
**Changelog draft:**
[Full Changelog](https://github.com/openshift/odo/compare/v2.3.0...v2.3.1)
**Features/Enhancements:**
- Get parameters information of operator backed services from Kubernetes OpenAPI spec [\#5020](https://github.com/openshift/odo/pull/5020) ([feloy](https://github.com/feloy))
- Send telemetry data on user interrupt [\#4963](https://github.com/openshift/odo/pull/4963) ([valaparthvi](https://github.com/valaparthvi))
- Refactor machine output code [\#4948](https://github.com/openshift/odo/pull/4948) ([feloy](https://github.com/feloy))
**Bugs:**
- Send Identify event with every Track event [\#5040](https://github.com/openshift/odo/pull/5040) ([kadel](https://github.com/kadel))
- Fix clusterwide permission issues …
=> release v2.3.1

scripts/changelog-script.sh
/kind cleanup
Now it is not required to install `github_changelog_generator` on your system to generate changelog.
=> add logic to run github_changelog_generator in container

tests/helper/helper_generic.go, tests/integration/devfile/cmd_devfile_debug_test.go
/kind tests
This pr will remove the `tmp` directory debug test data leftover and also a workaround for https://github.com/openshift/odo/issues/5037 in tests
Fixes #?
`make test-cmd-devfile-storage` should not throw error in https://github.com/openshift/odo/issues/5037
=> Debug test file cleanup left over

pkg/devfile/convert/convert.go, pkg/storage/kubernetes.go, pkg/storage/kubernetes_test.go, pkg/storage/storage.go, pkg/testingutil/deployments.go, tests/integration/cmd_create_s2i_test.go, tests/integration/cmd_storage_test.go
/kind bug
This PR:
- mounts persistent volumes in /opt/app-root and the deployments directory 
- adds a preStart event to the devfile, to create an initContainer that copies original files in /opt/app-root into the persistent volume
Fixes #4623 
```
$ oc apply -n openshift -f https://raw.githubusercontent.com/openshift/library/master/arch/x86_64/community/wildfly/imagestreams/wildfly-centos7.json
$ odo create --s2i wildfly
$ odo push
```
or
```
$ odo create --s2i nodejs
$ odo push
```
=> Mount persistent volumes for S2I images

tests/integration/devfile/utils/utils.go
/kind flake
This Pr fixes flake for odo watch test 
Fixes #5044
=> repeated check for deleted dir in odo watch test

tests/e2escenarios/e2e_devfile_test.go, tests/helper/helper_generic.go, tests/integration/devfile/cmd_devfile_app_test.go, tests/integration/devfile/cmd_devfile_catalog_test.go, tests/integration/devfile/cmd_devfile_config_test.go, tests/integration/devfile/cmd_devfile_create_test.go, tests/integration/devfile/cmd_devfile_debug_test.go, tests/integration/devfile/cmd_devfile_delete_test.go, tests/integration/devfile/cmd_devfile_describe_test.go, tests/integration/devfile/cmd_devfile_env_test.go, tests/integration/devfile/cmd_devfile_exec_test.go, tests/integration/devfile/cmd_devfile_list_test.go, tests/integration/devfile/cmd_devfile_log_test.go, tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/cmd_devfile_registry_test.go, tests/integration/devfile/cmd_devfile_status_test.go, tests/integration/devfile/cmd_devfile_storage_test.go, tests/integration/devfile/cmd_devfile_test_test.go, tests/integration/devfile/cmd_devfile_url_test.go, tests/integration/devfile/cmd_devfile_watch_test.go, tests/integration/devfile/debug/debug_suite_test.go
/kind tests
Sets up odo to use staging registry in the `CommonBeforeEach` so that we don't need to set it again each time.
Fixes #5056 
CI should pass.
=> Set odo to use staging registry in `CommonBeforeEach`

docs/public/operator-hub.adoc, pkg/component/component_full_description.go, pkg/devfile/adapters/common/utils.go, pkg/devfile/adapters/common/utils_test.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/odo/cli/component/common_link.go, pkg/odo/cli/component/create_helpers.go, pkg/odo/cli/component/delete.go, pkg/odo/cli/component/describe.go, pkg/odo/cli/component/link.go, pkg/odo/cli/service/create.go, pkg/odo/cli/service/list_operator.go, pkg/odo/cli/service/operator_backend.go, pkg/service/link.go, pkg/service/service.go, pkg/service/service_test.go, tests/integration/operatorhub/cmd_link_test.go, tests/integration/operatorhub/cmd_service_test.go
/kind feature
It modifies the usage of service create, link and unlink by using separate files for Kubernetes resources.
Fixes #4886 
- TBA
=> Modifies the usage of service create, link and unlink by using separate files for Kubernetes resources

pkg/odo/cli/component/common_link.go, pkg/odo/cli/component/link.go, pkg/odo/cli/component/unlink.go
/kind cleanup
See title
Fixes #4889 
WIP
=> Removing unused flags in link command

pkg/segment/segment.go
/kind feature
$subject
Fixes part of #4994
Segment data should contain the timezone information in the format "UTC +0530", "UTC 0000", etc.
=> Add timezone information to Telemetry data

pkg/devfile/adapters/common/interface.go, pkg/devfile/adapters/kubernetes/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter.go, tests/integration/devfile/cmd_devfile_push_test.go
/kind bug
`odo push` checks that the component is running on the container. If not, it starts it
Fixes #4822
=> Restart command when stopped on odo push

website/docs/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.md
> /kind bug
> /kind tests
> Feel free to use other [labels](https://github.com/openshift/odo/labels) as needed. However one of the above labels must be present or the PR will not be reviewed. This instruction is for reviewers as well.
In doc: https://odo.dev/docs/tutorials/deploying-a-devfile-using-odo-on-ibm-z-and-power/#deploying-your-first-devfile-on-ibm-z--power, DefaultDevfileRegistry use old link https://github.com/odo-devfiles/registry, need update it to https://registry.devfile.io/viewer 
Fixes #?
**PR …
=> Update DefaultDevfileRegistry link in IBM-Z and Power doc

pkg/kclient/operators.go, scripts/configure-cluster/common/setup-operators.sh, tests/integration/cmd_link_unlink_test.go, tests/integration/operatorhub/cmd_link_test.go, tests/integration/operatorhub/cmd_service_test.go
/kind feature
This PR: 
- does not detect the installed Servivce Binding Operator and uses the Service Binding Library in any case.
- removes the script to install the SBO in the cluster
- disable integration tests relative to SBO usage
Fixes #5084 
=> Do not use Service Binding Operator

pkg/catalog/catalog.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/odo/cli/component/common_link.go, pkg/odo/cli/component/common_push.go, pkg/odo/cli/component/component.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/devfile.go, pkg/odo/cli/component/get.go, pkg/odo/cli/component/link.go, pkg/odo/cli/component/list.go, pkg/odo/cli/preference/view.go, pkg/odo/cli/registry/delete.go, pkg/odo/cli/registry/list.go, pkg/odo/cli/registry/update.go, pkg/odo/cli/registry/util/util.go, pkg/odo/cli/registry/util/util_test.go, pkg/odo/genericclioptions/context.go, pkg/odo/genericclioptions/flag.go, pkg/odo/genericclioptions/localprovider.go, pkg/odo/genericclioptions/resolve.go, pkg/odo/genericclioptions/runnable.go, pkg/odo/genericclioptions/util.go, pkg/odo/util/cmdutils.go
=> remove abrubt os.Exit calls

pkg/odo/cli/config/view.go, tests/integration/cmd_pref_config_test.go
/kind bug
Current `odo config view` fails if we run this command in a dir not containing devfile. 
This PR fixes `odo config view` command for any directory not containing devfile.
Fixes #?
Steps to test changes
```
make install
cd /path/to/dir
odo config view
```
How to Reproduce the failure
```
neo@matrix [11:07:42 PM] [~/work/demo] 
-> % ls    
nodejs-ex
neo@matrix [11:07:43 PM] [~/work/demo] 
-> % odo config view
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 …
```
=> Fix odo config view

docs/website/docs/command-reference/link.md, pkg/odo/cli/component/common_link.go, pkg/odo/cli/component/link.go, pkg/odo/cli/service/create.go, pkg/odo/util/cmdutils.go, pkg/odo/util/cmdutils_test.go, tests/examples/operators/redis.yaml, tests/integration/operatorhub/cmd_link_test.go, tests/integration/operatorhub/cmd_service_test.go
- Sticking to SBO library v0.9.0 because the feature can be implemented
using it just fine.
- ~Docs doesn't cover `--bind-as-files`. I would prefer to keep it in a
separate PR.~ `--bind-as-files` docs e8dfa50.
- Added `id` field to the ServiceBinding resource created by odo and it
defaults to same name as that of service's. No option to change the
`id` itself.
- Removed a hyphen from the `redis.yaml` file because it caused `odo
push` for a link using the `--map` flag to fail due to it.
/kind feature
$subject. We need it for the users to be able to inject custom binding data while linking
Fixes #4937  …
=> Adds mapping support to odo link

pkg/odo/genericclioptions/runnable.go
This is still aligned with our Data Collection Policy (https://developers.redhat.com/article/tool-data-collection)
Telemetry is not enabled by default. Just the preselected answer is now Y instead of N.
/kind feature
=> Default to Y when asking to opt in for telemetry

tests/integration/devfile/cmd_devfile_storage_test.go
/kind tests
This PR refactors the test to use the new test flow
Fixes #5211 
=> refactor devfile storage test

.ibm/pipelines/functions.sh, .ibm/pipelines/kubernetes-tests.sh, .ibm/pipelines/openshift-tests.sh
/kind tests
Cleanup namespaces from cluster before to run tests from IBM Pipelines. The script removes all tests namespaces (not only old ones), as we run 1 pipeline only at a time
Fixes #?
=> Cleanup tests namespaces before to run tests

docs/website/docs/command-reference/create.md, docs/website/docs/command-reference/delete.md, docs/website/docs/command-reference/flags.md, pkg/devfile/adapters/common/apply.go, pkg/devfile/adapters/common/command.go, pkg/devfile/adapters/common/command_apply.go, pkg/devfile/adapters/common/command_composite.go, pkg/devfile/adapters/common/command_parallel_composite.go, pkg/devfile/adapters/common/command_simple.go, pkg/devfile/adapters/common/command_supervisor.go, pkg/devfile/adapters/common/generic.go, pkg/devfile/adapters/common/interface.go, pkg/devfile/adapters/kubernetes/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter_test.go, pkg/devfile/adapters/kubernetes/component/component.go, pkg/devfile/adapters/kubernetes/component/component_image.go, pkg/devfile/adapters/kubernetes/component/component_kubernetes.go, pkg/odo/cli/component/delete.go, pkg/odo/cli/component/devfile.go, pkg/service/service.go, tests/integration/devfile/cmd_devfile_delete_test.go, tests/integration/devfile/cmd_devfile_deploy_test.go
/kind feature
This PR deletes the outerloop resources deployed with `odo deploy`
Fixes #5246 
```sh
mkdir /tmp/abc; cd /tmp/abc
export ODOPATH=/home/pvala/go/src/github.com/redhat-developer/odo
cp -r $ODOPATH/tests/examples/source/nodejs/* . 
cp $ODOPATH/tests/examples/source/devfiles/nodejs/devfile-deploy.yaml devfile.yaml
odo create
odo deploy
```
Next, try the following commands:
1. `odo delete --deploy`
2. `odo delete`
3. `odo delete -af`
TODO:
1. Add documentation for `odo delete --deploy`
2. Add klog logs
3. Remove the unused `GetDeployCommand`
=> Delete outerloop resources with undeploy

pkg/odo/cli/component/create_methods.go
/kind bug
This PR fixes the panic caused while using odo create interactively with a disconnected cluster
Fixes #5283 
1. Set the current-context to "".
2. `odo create`
Recreate the above steps on main branch to see the panic.
=> Fix panic with interactive odo create when talking to a disconnected cluster

scripts/changelog-script.sh
/kind bug
We need it so that changelog script doesn't fail
Fixes - NA
* Generate a GH token for your account from https://github.com/settings/tokens
* Export it using `export GITHUB_TOKEN=<your-token>`
* `cd scripts`
* Try generating changelog using `./changelog-script.sh 2.4.3 main`.
=> `s/openshift/redhat-developer` in changelog script

pkg/odo/cli/component/common_push.go, pkg/odo/cli/component/push.go, pkg/odo/cli/deploy/deploy.go, pkg/odo/cmdline/cobra.go, tests/integration/devfile/cmd_devfile_deploy_test.go
=> Allow odo deploy without envfile

rpms/openshift-odo.spec
fixes old path to github.com/openshift in rpm spec
=> fix wrong path in rpm SPEC

docs/website/blog/2022-01-14-odo-v2.5.0.md
I merged the original blog post by accident :-/  (https://github.com/redhat-developer/odo/pull/5349)
This fixes some of the style errors and typos.
=> fix typos and style in 2.5.0 blog post

pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/kclient/pods.go, tests/helper/helper_cli.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/integration/devfile/cmd_devfile_push_test.go
/kind bug
Refer issue being fixed
Fixes #5041 
Refer issue description of original issue for steps to test changes.
=> odo push recreates the pod if scaled to 0

pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/component/component_kubernetes.go, pkg/devfile/adapters/kubernetes/component/errors.go, pkg/log/status.go, pkg/odo/cli/application/delete.go, pkg/odo/cli/component/delete.go, pkg/odo/cli/service/create.go, tests/integration/devfile/cmd_devfile_delete_test.go
/kind bug
This PR adds more verbosity to un-deploy while executing odo delete -af.
Fixes #5321 
```sh
odo create nodejs --starter nodejs-starter
odo push
odo delete -af
```
Output:
```sh
➜ odo delete -fa 
Un-deploying the Kubernetes Deployment
✗  no kubernetes component to un-deploy
Gathering information for component nodejs-abc-jtmy
✗  Checking status for component [5ms]
⚠  pod not found for the selector: app.kubernetes.io/instance=nodejs-abc-jtmy,app.kubernetes.io/part-of=app
Deleting local config
✓  Successfully deleted env file
✓  Successfully deleted devfile.yaml file
```
=> Add more verbosity to undeploy

docs/website/docs/getting-started/installation.md
Updates the installation page with the following:
- Reorganizes some wording with regards to where changes of the release
are, architectures, etc.
- Moves the IDE portion into a separate section so it's better to
navigate via the sidebar
- Moves the "building from source" to the CLI Binary part as it relates
to CLI rather than IDE
EDIT:
More updates!
- Changes to the installation page to favour tabbed installation pages instead of the script that we previously used
- Steps to verify the downloaded binary with the SHA-256 sum
- Removed section from Windows with regards to setting `PATH` as it is forever changing. Recent Windows 10 update has changed the location. Windows 11 is different. Windows 7/8 …
=> Update installation page

pkg/odo/cli/url/create.go
/kind feature
This adds the --hostname alias to the `odo url create` command since
similar tools such as `oc` use `--hostname` to create routes, and thus
a user may accidently enter --hostname instead.
This PR also reorganized the help usage so it's more inline with
"building up" on each example.
Fixes https://github.com/redhat-developer/odo/issues/5379
N/A
N/A
N/A
=> Add --hostname alias to odo url create

pkg/component/component_full_description.go, pkg/envinfo/storage.go, pkg/storage/kubernetes.go, pkg/storage/kubernetes_test.go, pkg/url/kubernetes.go, pkg/url/kubernetes_test.go, pkg/url/status_test.go, tests/integration/devfile/cmd_devfile_describe_test.go
/kind bug
This PR fixes the panic caused when running odo describe without the context directory.
Fixes #5245
```sh
odo create nodejs mynode --app myapp --project myproject
odo push
<cd outside the context directory>
odo describe mynode --app myapp --project myproject
```
=> Fix odo describe panic without the context directory

.ibm/pipelines/kubernetes-tests.sh, .ibm/pipelines/openshift-tests.sh
/kind tests
Minor changes to use Service IDs and clusters in the developer QE account
For both kubernetes and openshift:
Breaks current login command to first login, then select region:
`ibmcloud login --apikey "${API_KEY}" -r "${IBM_REGION}"`
v
`ibmcloud login --apikey "${API_KEY}"`
`ibmcloud target -r "${IBM_REGION}"`
For Openshift:
Added downloading of kubeconfig (noted that when using Service IDs it requires kubeconfig before oc login)
Added oc login command
Fixes #
=> minor changes to use service IDs and clusters in the Developer QE account

.ibm/pipelines/windows-test.sh
/kind tests
We have running windows tests running, but it override the comment from openshift tests on PR. This PR will fix it. 
Fixes #5300 
=> fix comment override for windows test

go.mod, go.sum, pkg/devfile/adapters/kubernetes/component/adapter.go, vendor/github.com/devfile/library/pkg/devfile/generator/generators.go, vendor/github.com/devfile/library/pkg/devfile/generator/utils.go, vendor/modules.txt
/kind cleanup
Sets replicas using devfile library. We need it as we have pushed the necessary change in devfile library, and now odo just needs to use it.
Fixes #5347
Tests should pass.
=> Set replicas using devfile library

pkg/odo/cli/cli.go
=> Remove registry command from top level commands

go.mod, go.sum, pkg/init/asker/asker.go, pkg/init/asker/interface.go, pkg/init/asker/mock.go, pkg/init/backend/alizer.go, pkg/init/backend/flags.go, pkg/init/backend/interactive.go, pkg/init/backend/interactive_test.go, pkg/init/backend/interface.go, pkg/init/backend/mock.go, pkg/init/init.go, pkg/init/interface.go, pkg/init/mock.go, pkg/init/registry/mock.go, pkg/odo/cli/init/init.go, vendor/github.com/devfile/library/pkg/devfile/parser/configurables.go, vendor/github.com/devfile/library/pkg/devfile/parser/data/interface.go, vendor/github.com/devfile/library/pkg/devfile/parser/data/mock_interface.go, vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/containers.go, vendor/github.com/devfile/library/pkg/testingutil/filesystem/default_fs.go, vendor/github.com/devfile/library/pkg/testingutil/filesystem/fake_fs.go, vendor/github.com/devfile/library/pkg/testingutil/filesystem/filesystem.go, vendor/github.com/devfile/library/pkg/testingutil/filesystem/singleton.go, vendor/github.com/devfile/library/pkg/testingutil/filesystem/watcher.go, vendor/modules.txt
/kind feature
This PR allows user to personalize their devfile by adding/removing port, and environment variable.
Fixes #5423 
=> Personalize devfile

pkg/devfile/adapters/kubernetes/component/adapter.go, tests/examples/source/devfiles/nodejs/devfile-with-two-deploy-commands.yaml, tests/integration/devfile/cmd_devfile_deploy_test.go
=> Non-default deploy commands do not break running the default one

.ibm/pipelines/windows-test-script.ps1
/kind tests
Added API_KEY_QE property to login to clusters in the IBM Cloud QE account. Will continue to use API_KEY to login to developer for log storage bucket, So now we need to login twice, first to QE account for cleanup and to connect to clusters and then to Developer account to upload logs
No related issue
Fixes #5419 
=> Pipeline changes to use clusters in QE account

pkg/kclient/all.go, pkg/kclient/interface.go, pkg/kclient/mock_Client.go
with specific labels (to be used by "odo list" and "odo delete component")
/kind feature
This PR adds a GetAllResourcesFromSelector, function thats searches all recources of any kind in the cluster
This function is intended to be used at least in `odo list` and `odo delete component`
The code comes 99% from https://github.com/ahmetb/kubectl-tree
=> GetAllResourcesFromSelector to retrieve resources of all kinds 

pkg/kclient/all.go
/kind bug
This PR fixes the `GetAllResourcesFromSelector` function to not fail when some resource is not allowed to be listed, but only skip it.
=> Do not fail on no right to list some resource

tests/helper/helper_interactive.go
/kind bug
This PR sets a timeout on each Expect during interactive integration tests, so tests do not run infinitely if the expected string does not come
=> Set timeout for interactive tests Expects

.github/PULL_REQUEST_TEMPLATE.md, docs/website/README.md, docs/website/docs/command-reference/flags.md, docs/website/docs/contribution.md, docs/website/docs/getting-started/features.md, docs/website/docs/intro.md, docs/website/docs/using-odo/create-component.md, docs/website/docusaurus.config.js, docs/website/src/pages/index.tsx, docs/website/versioned_docs/version-3.0.0/command-reference/flags.md, docs/website/versioned_docs/version-3.0.0/contribution.md, docs/website/versioned_docs/version-3.0.0/getting-started/features.md, docs/website/versioned_docs/version-3.0.0/intro.md, docs/website/versioned_docs/version-3.0.0/using-odo/create-component.md
This fixes a few minor issues I stumbled upon while playing with the `odo` tutorials on the [odo.dev](https://odo.dev/) website.
Those are fixes for both the `2.5.0` and `3.0.0` versions of the documentation.
Also, some URLs were no longer valid and used to point to a 404 page, like when clicking on the `Edit this page` links in the website. This PR also fixes this behavior.
This was quick to fix. So I did not create a new issue.
I did not find any automated tests for the website. So this has to be checked manually.
=> Fix typos and invalid URLs in documentation

pkg/init/init.go, pkg/init/interface.go, pkg/init/mock.go, pkg/odo/cli/deploy/deploy.go, pkg/odo/cli/dev/dev.go, pkg/odo/cli/init/init.go, tests/helper/helper_interactive.go, tests/integration/devfile/cmd_dev_test.go, tests/integration/devfile/cmd_devfile_deploy_test.go, tests/integration/interactive/cmd_deploy_test.go, tests/integration/interactive/cmd_dev_test.go, tests/integration/interactive/cmd_init_test.go
/kind feature
odo Initializes a devfile interactively when `odo dev` and `odo deploy` are executed from a directory without a devfile.
Fixes #5476, #5477, #5491
=> Initialize devfile on odo dev/deploy without devfile

Makefile, tests/helper/helper_generic.go
/kind tests
Updated CommonAfterEach to save test results for each test spec to improve test results reporting.
Will work in conjunction with the test pipeline to update cumulative test results file to IBM cloud bucket
No related issue
Fixes #5430 
=> Save test results for each test spec to improve test results reporting

Makefile
/kind tests
Integration and E2E tests targets rely on the `odo` binary to execute subcommands in separate processes.
While iterating on the code, we could often end up with situations where  the `odo` binary is no longer up-to-date, should we forget to `make install` before.
This fixes such behavior by ensuring the installed binary is always up-to-date prior to running the actual test target.
I am not sure yet of the implications (e.g., in terms of performance in CI), but I guess there should be a minimal impact thanks to the Go build cache.
Let me know if you think this should be done differently. …
=> Make sure Makefile targets for both integration and E2E tests depend on the 'install' target

pkg/odo/cli/init/init.go, tests/integration/devfile/cmd_devfile_init_test.go
/kind bug
This PR fixes panic when a non-existent devfile path is provided to odo init.
Fixes #5540
```sh
➜  odo init --name aname --devfile-path /tmp/devfile.go
✗  Copying devfile from "/tmp/devfile.go" [42631ns]
✗  unable to download devfile: open /tmp/devfile.go: no such file or directory
the command failed, the devfile has been removed from current directory
```
=> Fix panic with odo init when non-existent devfile path is provided

pkg/watch/watch.go
/kind bug
This PR removes message about resource cleanup from the `odo dev` exit message. Cleanup has not been implemented yet, the message should be added once it is done.
Fixes #
```sh
➜  odo dev
Using devfile.yaml from the current directory.
Starting your application on cluster in developer mode
✓  Waiting for Kubernetes resources [11s]
✓  Syncing files into the container [143ms]
✓  Building your application in container on cluster [508ms]
✓  Executing the application [1s]
Your application is running on cluster.
Waiting for something to change in /tmp/101
Press Ctrl+c to exit.
```
=> Remove information about resource cleanup from odo dev exit message

pkg/component/component.go, pkg/component/component_full_description.go, pkg/component/component_test.go, pkg/component/labels/labels.go, pkg/component/labels/labels_test.go, pkg/component/pushed_component.go, pkg/component/types.go, pkg/deploy/deploy.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter_test.go, pkg/devfile/adapters/kubernetes/storage/utils.go, pkg/kclient/deployments.go, pkg/kclient/fake/ingress.go, pkg/service/link.go, pkg/service/service.go, pkg/storage/labels/labels_test.go, pkg/storage/storage.go, pkg/testingutil/deployments.go, pkg/testingutil/routes.go, pkg/url/labels/labels_test.go, pkg/url/url.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/helper/helper_run.go
/kind feature
/kind cleanup
In this PR we:
* Correctly name all the labels in a more concise manner (ex. Project Type
is an annotation)
* Add Dev and Deploy mode labels to both `odo dev` and `odo deploy`
commands so that we can intuitively retrieve what components are in
deploy or dev mode
* Somewhat refactors how we do labeling
1/2 of PR's for https://github.com/redhat-developer/odo/issues/5405
N/A
=> Add Dev and Project labeling / refactoring labeling and annotations

pkg/log/fidget/spinner.go, pkg/log/status.go
/kind feature
When using the spinner, we shouldn't output the spinner if it is less
than 1ms (nanoseconds).
Fixes https://github.com/redhat-developer/odo/issues/5380
N/A, unable to write (function could possibly be more than 1ns)
N/A, unable to write (function could possibly be more than 1ns)
```
odo create nodejs foobar
odo push
```
And you should see that all nanosecond spinners are no longer shown.
=> Remove nanoseconds from spinner

pkg/init/init.go, pkg/init/interface.go, pkg/init/mock.go, pkg/odo/cli/deploy/deploy.go, pkg/odo/cli/dev/dev.go, tests/interactive/cmd_deploy_test.go, tests/interactive/cmd_dev_test.go
/kind feature
/area ux
This relates to #5494, because users might have similar symptoms (few seconds before any output) when running either `odo dev` or `odo deploy` in a source code directory with no Devfile, and those commands try to do an `Alizer` analysis first.
Relates to #5494
Run either `odo dev` or `odo deploy` from a source code directory with no Devfile. A welcoming message should be displayed before the Alizer detection messages are showed.
=> Make `odo dev` and `odo deploy` display welcoming messages too before running Alizer detection, just like `odo init`

Makefile
This PR removes reference of the old delete test file from Makefile and replaces it with the new one.
Fixes #5559 
Run `make test-cmd-delete` and check if it runs the desired set of tests, ie tests/integration/devfile/cmd_delete_test.go
=> Remove v2delete reference from Makefile

pkg/init/backend/alizer.go, pkg/init/backend/flags.go, pkg/init/backend/flags_test.go, pkg/init/backend/interactive.go, pkg/init/backend/interactive_test.go, pkg/init/backend/interface.go, pkg/init/backend/mock.go, pkg/init/init.go, pkg/init/interface.go, pkg/init/mock.go, pkg/odo/cli/deploy/deploy.go, pkg/odo/cli/dev/dev.go, pkg/odo/cli/init/init.go, tests/helper/helper_generic.go, tests/integration/devfile/cmd_devfile_init_test.go, tests/interactive/cmd_init_test.go
/kind feature
/area ux
To improve user experience, the goal of this PR (and linked issue) is to ask users all questions first, prior to performing actions. For the reasons discussed [here](https://github.com/redhat-developer/odo/issues/5495#issuecomment-1062984433) however, the Devfile download action cannot be delayed and still has to happen sooner.
Fixes #5495 
When ran interactively and a starter project selected, `odo init` should download the starter project after all interactive questions have been asked, like so (notice that the `Downloading starter project ...` action line is executed and …
=> Interactive mode — Ask all questions first

docs/website/package.json, docs/website/yarn.lock
update prismjs dependency for docs
the older version had a security issue (https://nvd.nist.gov/vuln/detail/CVE-2022-23647)
=> docs: update prismjs

tests/integration/devfile/cmd_delete_test.go, tests/integration/devfile/cmd_dev_test.go, tests/integration/devfile/cmd_devfile_push_test.go
/kind bug
```
odo delete command tests
/go/src/github.com/redhat-developer/odo/tests/integration/devfile/cmd_delete_test.go:13
when a component is bootstrapped
/go/src/github.com/redhat-developer/odo/tests/integration/devfile/cmd_delete_test.go:32
when the component is deployed in DEV mode and dev mode stopped
/go/src/github.com/redhat-developer/odo/tests/integration/devfile/cmd_delete_test.go:68
when the component is deleted using its name and namespace from another directory
/go/src/github.com/redhat-developer/odo/tests/integration/devfile/cmd_delete_test.go:76
when odo delete command is run again with nothing deployed on the cluster …
```
=> Fix some flaky tests

pkg/odo/cli/build_images/build_images.go, pkg/odo/cli/cli.go, pkg/odo/cli/component/component.go, pkg/odo/cli/delete/delete.go, pkg/odo/cli/deploy/deploy.go, pkg/odo/cli/dev/dev.go, pkg/odo/cli/init/init.go, pkg/odo/cli/login/login.go, pkg/odo/cli/logout/logout.go, pkg/odo/cli/preference/preference.go, pkg/odo/cli/project/project.go, pkg/odo/cli/url/url.go, tests/integration/loginlogout/cmd_login_logout_test.go
/kind cleanup
This updates the help usage so it outputs a working example, as well as
reorganizes commands to the appropriate places.
```sh
▶ odo -h
__
/  \__     odo is a CLI tool for fast iterative application development
\__/  \    deployed immediately to your kubernetes cluster.
/  \__/    Find more information at https://odo.dev
\__/
Usage:
odo [flags]
odo [command]
Examples:
Initialize and take your pick from multiple languages or frameworks:
odo init
After creating your initial application, start development with:
odo dev
Want to deploy to production? See it live with:
odo deploy
Main Commands:
build-images Build images
deploy       Deploy components
dev          Deploy component to development cluster
init …
```
=> Update help usage to a working example / updated commands

pkg/init/init.go, pkg/init/interface.go, pkg/init/mock.go, pkg/odo/cli/deploy/deploy.go, pkg/odo/cli/dev/dev.go, pkg/odo/cli/init/init.go, pkg/odo/cli/init/init_test.go, tests/integration/devfile/cmd_devfile_init_test.go, tests/interactive/cmd_deploy_test.go, tests/interactive/cmd_dev_test.go, tests/interactive/cmd_init_test.go
/kind bug
Fixes #5513 
**odo init**
1. `mkdir /tmp/101; cd /tmp/101`
2. `odo init -v 4`
**odo dev**
1. `mkdir /tmp/102; cd /tmp/102`
2. `cp -r $ODOPATH/tests/examples/source/nodejs/* .  `
3. `odo dev -v 4`
Ensure both the commands run. Test with `odo deploy` as well.
=> Fix odo interactive with verbosity flags

pkg/devfile/image/docker_compatible.go, tests/examples/source/devfiles/nodejs/devfile-outerloop-project_source-in-docker-build-context.yaml, tests/integration/devfile/cmd_devfile_build_images_test.go, tests/integration/devfile/cmd_devfile_deploy_test.go
/kind bug
Fixes #5322
Run the reproduction steps depicted in #5322:
```shell
$ git clone https://github.com/kadel/devfile-nodejs-deploy && cd devfile-nodejs-deploy
$ sed -i "s/tkral/<quay-username>/" devfile.yaml
$ # Force odo to use Docker for building images
$ export PODMAN_CMD=a-command-not-found-should-make-odo-use-docker 
$ # Both odo deploy and odo build-images should now be able to build the container images
$ odo deploy
$ odo build-images
```
To run the integration tests related to this issue:
```shell
ginkgo -v -focus 'using a devfile.yaml containing an Image component with a build context' …
```
=> [#5322] Add `PROJECT_SOURCE` to the container image build command environment

pkg/component/delete/delete.go, pkg/component/delete/delete_test.go, pkg/component/delete/interface.go, pkg/component/delete/mock.go, pkg/odo/cli/delete/component.go, pkg/odo/cli/delete/component_test.go, tests/integration/devfile/cmd_delete_test.go
/kind feature
This PR adds information about not deleted component resources because devfile.yaml was changed.
Fixes #5555 
1. `mkdir /tmp/101; cd /tmp/101`
2. `cp $ODOPATH/tests/examples/source/devfiles/nodejs/devfile-deploy-with-multiple-resources.yaml devfile.yaml`
3. `cp -r $ODOPATH/tests/examples/source/nodejs/* . `
4. `export PODMAN_CMD=echo`
5. `odo deploy`
6. `odo dev`
7. Replace `my-cs` service name to `my-changed-cs` in devfile.yaml
8. `odo delete component`
Output will be similar to:
```sh
➜  odo delete component …
```
=> odo delete component - show warning that something was not deleted

pkg/devfile/image/image.go, pkg/libdevfile/errors.go, tests/integration/devfile/cmd_devfile_build_images_test.go
/kind bug
See #5330 for more context.
Fixes #5330 
When running `odo build-images` with a Devfile that has no `Image` component in it, the command should not succeed and should output an error message on the standard error instead, like so:
```
asoro in work-laptop in /tmp/no-image-in-devfile on ☁️   
❯ odo build-images            
✗  no component with type "Image" found in Devfile
```
=> [#5330] Make `odo build-images` return an error if no Image component found in Devfile

pkg/kclient/interface.go, pkg/kclient/mock_Client.go, pkg/kclient/port_forwarding.go, pkg/odo/cli/dev/dev.go, pkg/odo/cli/dev/writer.go, tests/helper/helper_dev.go, tests/integration/devfile/cmd_delete_test.go, tests/integration/devfile/cmd_dev_test.go, tests/interactive/cmd_dev_test.go
/kind tests
This PR adds a `random-ports` flag to `odo dev`, that calls the port-forward library with a destination port set to zero, this way a port is automatically chosen by the system atomically.
```
func net.Listen(network string, address string) (net.Listener, error)
[net.Listen on pkg.go.dev]()
Listen announces on the local network address.
The network must be "tcp", "tcp4", "tcp6", "unix" or "unixpacket".
[...]
If the port in the address parameter is empty or "0", as in "127.0.0.1:" or "[::1]:0", a port number is automatically chosen.
[...]
```
Fixes #5603
Using Decorators with integration …
=> Fix flaky test "should expose two endpoints on localhost"

pkg/devfile/image/image.go, pkg/devfile/image/image_test.go
/kind tests
For some valid reasons, we could want `odo` to use Docker as backend when building images.
One way of doing so is to set the `PODMAN_CMD` system environment variable to a command we know does not exist.
This is what I did a few days ago on my system.
Now the `image` unit tests will not pass, because they rely on the system environment variables.
```
~/w/p/odo on  main [$] via 🐹 v1.16.15 on ☁️   
❯ PODMAN_CMD=a-command-not-found-should-make-odo-use-docker go test -race github.com/redhat-developer/odo/pkg/devfile/image
↪ Building & Pushing Container: a name
↪ Building & Pushing Container: a name
↪ Building & Pushing Container: a name
↪ Building & Pushing Container: a name
--- FAIL: TestSelectBackend (0.00s)
--- …
```
=> Fix potential issue with `image.TestSelectBackend` unit tests when `PODMAN_CMD` env var is set

pkg/odo/cli/deploy/deploy.go, pkg/odo/cli/dev/dev.go
Updates the error output for running `odo dev` or `odo deploy` in an
empty directory. Telling the user to run the same command in a non-empty
dir, OR use `odo init`.
N/A
=> Updates the error output for an empty directory

pkg/component/delete/delete.go, pkg/component/delete/delete_test.go, pkg/component/delete/interface.go, pkg/component/delete/mock.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/kclient/deployments.go, pkg/kclient/dynamic.go, pkg/kclient/interface.go, pkg/kclient/mock_Client.go, pkg/kclient/operators.go, pkg/kclient/owner_reference.go, pkg/kclient/owner_reference_test.go, pkg/kclient/utils.go, pkg/odo/cli/delete/component.go, pkg/odo/cli/delete/component_test.go, pkg/service/service.go, pkg/watch/watch.go, tests/helper/helper_cli.go, tests/helper/helper_dev.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/integration/devfile/cmd_dev_test.go
/kind feature
- During odo dev, when creating resources (services, pvcs) attached to the main deployment, odo first tries to set `BlockOwnerDeletion` on the ownerReference, so the call to `Delete` with `PropagationPolicy` set to `DeletePropagationForeground` is effective. Because this operation needs specific rights, if the execution fails, it is not fatal and the ownerReference is still set but without `BlockOwnerDeletion`,
- a flag `--wait` is added to the `odo delete component` command, that calls the `Delete` functions with the `wait` parameter,
- When executing `Delete`  calls on resources with `wait` set to true, set  `PropagationPolicy` is set to `DeletePropagationForeground`, so the `Delete` call returns only …
=> Wait deletion

pkg/component/component.go
/kind bug
Feel free to use other [labels](https://github.com/redhat-developer/odo/labels) as needed. However one of the above labels must be present or the PR will not be reviewed. This instruction is for reviewers as well.
-->
Prevents PackageManifets to be shown as a component in `odo list` output.
before
```
▶ odo list
✓  Listing components from namespace 'test' [323ms]
NAME                             PROJECT TYPE  RUNNING IN  MANAGED                         
* devfile-nodejs-deploy          nodejs        None        odo                             
my-nodejs-app                    nodejs        Dev         odo                             
ibm-spectrum-scale-csi-operator  Unknown       Unknown …
```
=> Ignore PackageManifets resources when listing components

pkg/odo/cli/list/list.go
/kind bug
This PR moves the `list` command into the `main` help section, so it is displayed when running `odo help`
=> Set list command in main help section

pkg/devfile/adapters/kubernetes/utils/utils.go, pkg/devfile/adapters/kubernetes/utils/utils_test.go, tests/examples/source/devfiles/nodejs/issue-5620-devfile-with-container-command-args.yaml, tests/integration/devfile/cmd_dev_test.go
/kind bug
/kind hotfix
Before this fix, running `odo dev` would not succeed if the Devfile defines a container component with `command` or `args`. 
Fixes #5620
=> [Hotfix] Always ignore `command` and `args` defined in Devfile container components

pkg/devfile/adapters/kubernetes/utils/utils.go, pkg/devfile/adapters/kubernetes/utils/utils_test.go, tests/examples/source/devfiles/nodejs/issue-5620-devfile-with-container-command-args.yaml, tests/integration/devfile/cmd_devfile_push_test.go
/kind bug
/kind hotfix
This backports the hotfix done in #5639 to `v2`.
I am manually creating a separate PR because the test cases are different for `v2` and `main` branches, so I cannot rely on openshift-bot to cherry-pick commits and create a new PR automatically.
This adapts the tests by using `odo push` instead of `odo dev`.
Before this fix, running `odo push` would not succeed if the Devfile defines a container component with `command` or `args`. 
Fixes #5620
=> [Hotfix][v2] Always ignore `command` and `args` defined in Devfile container components

pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/odo/cli/dev/dev.go, pkg/odo/cli/dev/writer.go, tests/integration/devfile/cmd_dev_test.go
/kind cleanup
This PR does the following:
- Removes the references to `odo log`
- Changes the output to last 100 lines and puts the number in a constant
- Reworks the output of `odo dev` a bit to be bolded / more consise with
out outputs.
See below for the changes:
```sh
▶ copy-odo && devfiles && cd deploy-no-knative && odo dev
go build -mod=vendor -ldflags="-X github.com/redhat-developer/odo/pkg/version.GITCOMMIT=4669bc9dc" cmd/odo/odo.go
__
/  \__     Developing using the deploy-no-knative Devfile
\__/  \    Namespace: default
/  \__/    odo version: v2.5.0
\__/
↪ Deploying to the cluster in developer mode
✓  Waiting for Kubernetes resources [360ms]
✓  Syncing files into the container [1ms]
✓  Building your …
```
=> Updates the odo dev output for logging

pkg/devfile/image/image.go, pkg/log/status.go
/kind feature
Warns the user if we are trying to run Podman on Mac M1. As we are
unable to build x86 images natively unless using the workaround.
Fixes https://github.com/redhat-developer/odo/issues/5597
Run it on a M1 mac :)
=> Adds warning for running podman on Apple Silicon

tests/integration/devfile/cmd_dev_test.go, tests/integration/devfile/cmd_devfile_deploy_test.go
/kind tests
Fixes partially #5621 
=> Tests cleanup after odo dev terminates

docs/website/docs/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.md, docs/website/versioned_docs/version-3.0.0/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.md
**What type of PR is this:
What does this PR do / why we need it:**
For Power, we have verified latest languages and runtimes refer to https://github.com/devfile/registry/tree/main/stacks. So this PR is to update document https://odo.dev/docs/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power for Power.
All the added type of languages have been verified on Power.
Fixes #
/area system-PZ
=> Update devfiles information and used images for ppc64le

pkg/devfile/image/docker_compatible.go, pkg/devfile/image/docker_compatible_test.go, tests/examples/source/devfiles/nodejs/issue-5600-devfile-with-image-component-and-no-buildContext.yaml, tests/integration/devfile/cmd_devfile_build_images_test.go, tests/integration/devfile/cmd_devfile_deploy_test.go
/kind bug
This makes the build context directory for Docker (and Podman) default to the Devfile parent directory, if not set.
Fixes #5600
See reproduction steps detailed in https://github.com/redhat-developer/odo/issues/5600#issue-1184803587
=> Fix issue with `build-images` and `deploy` not working with Docker if optional `buildContext` field is not set in Devfile (#5600)

pkg/odo/cli/dev/dev.go, pkg/watch/interface.go, pkg/watch/mock.go, pkg/watch/watch.go, tests/helper/helper_dev.go, tests/integration/devfile/cmd_dev_test.go
/kind feature
Need this to allow users to avoid syncing the code too fast
Fixes #5631
1. Execute `odo dev --no-watch`; modify a file in the component directory.
2. odo should not trigger a sync for the file change
3. Hitting `Ctrl+c` should correctly delete the resources from the cluster
=> Adds `odo dev --no-watch`

pkg/odo/cli/list/list.go
/kind bug
When there are no components shown, we should exit with an error 0,
rather than a info / warning.
N/A
N/A
=> Error when running odo list and there are no components deployed

.golangci.yaml, Makefile, pkg/component/delete/delete.go, pkg/component/starter_project.go, pkg/deploy/deploy.go, pkg/devfile/adapters/helper.go, pkg/devfile/adapters/kubernetes/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/storage/utils.go, pkg/devfile/image/image.go, pkg/init/backend/interactive.go, pkg/kclient/deployments.go, pkg/kclient/kclient.go, pkg/kclient/namespace.go, pkg/kclient/oc_server.go, pkg/odo/cli/cli.go, pkg/odo/cli/preference/registry/list.go, pkg/odo/cli/project/delete.go, pkg/odo/cli/project/set.go, pkg/odo/cmdline/cobra.go, pkg/odo/genericclioptions/context.go, pkg/odo/genericclioptions/localprovider.go, pkg/odo/genericclioptions/resolve.go, pkg/odo/genericclioptions/runnable.go, pkg/service/service.go, pkg/service/service_binding_builder.go, pkg/sync/adapter.go, pkg/util/util.go, pkg/util/util_test.go
/kind task
This configures [golangci-lint](https://golangci-lint.run/) with the following additional checks:
- [`depguard`](https://golangci-lint.run/usage/linters/#depguard), to check whether packages imported are allowed or denied. For example, this allows to check that the deprecated `github.com/pkg/errors` is not introduced again.
- [`revive`](https://golangci-lint.run/usage/linters/#revive) (successor of the deprecated golint), configured with the following rules:
- [`error-strings`](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#error-strings), to check common conventions around error messages. This PR also fixes errors reported by this rule.
Additional checks might be added later on as …
=> Add additional checks to golangci-lint (#5567)

.ibm/pipelines/windows-test.sh
/kind tests
This PR will fix the broken link to the logs for the windows CI tests. 
Fixes #5680
=> change path to fix windows log

pkg/dev/dev.go, pkg/sync/adapter.go, pkg/sync/sync.go, pkg/sync/sync_test.go, pkg/util/file_indexer.go, pkg/watch/watch.go, pkg/watch/watch_test.go, tests/integration/devfile/cmd_dev_test.go
=> Fix ignores files during sync

pkg/dev/dev.go, pkg/dev/interface.go, pkg/odo/cli/dev/dev.go, pkg/odo/cli/errors/errors.go, pkg/watch/watch.go, tests/examples/source/devfiles/nodejs/devfile-with-debugrun.yaml, tests/examples/source/devfiles/nodejs/devfile-without-debugrun.yaml, tests/helper/helper_dev.go, tests/helper/helper_http.go, tests/integration/devfile/cmd_dev_debug_test.go, tests/integration/devfile/cmd_dev_test.go
=> odo dev --debug

.wwhrd.yml
Stumbled upon this while working on #5567
This changes the terminology used in `.wwhrd.yml`, as this is the recommended way of configuring [wwhrd](https://github.com/frapposelli/wwhrd) [1].
Also, those are more inclusive terms in line with Red Hat recommendations [2].
[1] https://github.com/frapposelli/wwhrd#configuration-file
[2] https://www.redhat.com/en/blog/making-open-source-more-inclusive-eradicating-problematic-language
No related issue, as this was very quick to update.
Both `make validate-vendor-licenses` and `make validate` should pass.
=> Favor use of "allowlist" and "denylist" in `wwhrd` license check config

.ibm/pipelines/kubernetes-tests.sh, .ibm/pipelines/openshift-tests.sh, tests/integration/generic_test.go
=> refactoring generic-test

.ibm/pipelines/windows-test-script.ps1
/kind tests
This PR will make sure to use correct odo binary for tests even if there are other binary in the PATH
Fixes #5683
=> fix PATH for odo binary

.ibm/images/Dockerfile, docs/website/versioned_docs/version-3.0.0/command-reference/dev.md, pkg/api/component.go, pkg/odo/cli/dev/dev.go, pkg/odo/cli/dev/writer.go, pkg/odo/cli/dev/writer_test.go, pkg/odo/genericclioptions/clientset/clientset.go, pkg/state/const.go, pkg/state/doc.go, pkg/state/interface.go, pkg/state/state.go, pkg/state/state_test.go, pkg/state/types.go, pkg/watch/watch.go, tests/helper/helper_generic.go, tests/integration/devfile/cmd_alizer_test.go, tests/integration/devfile/cmd_dev_test.go, tests/integration/devfile/cmd_devfile_init_test.go
/kind feature
See issue.
The PR updates the image used to run tests on IBM Cloud to be able to run tests as non-root user, to make a new test relying on user rights pass.
Fixes #5676 
The values for the forwarded ports are obtained through the `PortWriter`, from the text written by the low level port forwarder. This is because we need to get the information of the local port when we are using random ports (with --random-ports flag).
=> odo dev store information about currently forwarded ports

docs/website/blog/2022-05-02-odo-v3-alpha1.md
TODO:
Preview: https://deploy-preview-5710--odo-docusaurus-preview.netlify.app/blog/odo-v3-alpha1-release/
=> Blog post for v3-alpha1

tests/helper/helper_generic.go
/kind tests
Fixes `+Error when opening file:  open \tmp\testResults.txt: The system cannot find the path specified.` when running tests on Windows
Fixes #5681 
Run any test on windows platform and should not fail with `+Error when opening file:  open \tmp\testResults.txt: The system cannot find the path specified.`
=> Fix error when opening file in windows OS

docs/website/versioned_docs/version-3.0.0/command-reference/describe.md, pkg/api/component.go, pkg/api/devfile-data.go, pkg/api/utils.go, pkg/component/component.go, pkg/component/component_test.go, pkg/log/status.go, pkg/odo/cli/describe/component.go, pkg/registry/registry.go, tests/integration/devfile/cmd_describe_test.go
/kind feature
Fixes #5661 
Doc preview: https://deploy-preview-5725--odo-docusaurus-preview.netlify.app/docs/3.0.0/command-reference/describe
=> odo describe component

docs/website/versioned_docs/version-3.0.0/command-reference/json-output.md, pkg/odo/cli/alizer/alizer.go, tests/integration/devfile/cmd_analyze_test.go
/kind feature
Thos PR renames the `alizer` command to `analyze`
The internal name of the process is still referenced as `alizer`, as it is the name of the library we are using.
Related to #5642
=> Rename alizer command to analyze

docs/website/versioned_docs/version-3.0.0/command-reference/create-namespace.md, docs/website/versioned_docs/version-3.0.0/command-reference/odo-create-namespace.md, pkg/odo/cli/cli.go, pkg/odo/cli/create/create.go, pkg/odo/cli/create/namespace/namespace.go, tests/helper/helper_cli.go, tests/helper/helper_generic.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/integration/cmd_namespace_test.go
/kind feature
Fixes part of #5525 
1. `odo create namespace my-namespace`
2. `odo create project my-project`
3. `odo create`
4. `odo create namespace --help`
Note: The main logic of this PR comes from https://github.com/valaparthvi/odo/blob/main/pkg/odo/cli/project/create.go.
=> odo create namespace

docs/website/versioned_docs/version-3.0.0/command-reference/delete-component.md, docs/website/versioned_docs/version-3.0.0/command-reference/delete-namespace.md, pkg/odo/cli/delete/component/component.go, pkg/odo/cli/delete/component/component_test.go, pkg/odo/cli/delete/delete.go, pkg/odo/cli/delete/namespace/namespace.go, tests/helper/helper_cli.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/integration/cmd_namespace_test.go
/kind feature
This PR continues the work started by @valaparthvi by implementing the missing `odo delete namespace/project` command.
Relates to #5525
```
❯ odo help delete namespace
Delete the specified namespace
Usage:
odo delete namespace [flags]
Aliases:
namespace, project
Examples:
odo delete namespace my-namespace
Flags:
-f, --force   Delete namespace without prompting
-h, --help    Help for namespace
-w, --wait    Wait until the namespace no longer exists
Additional Flags:
--kubeconfig string    Paths to a kubeconfig. Only required if out-of-cluster.
-v, --v Level              Number for the log …
```
=> Implement `odo delete namespace/project`

docs/website/versioned_docs/version-3.0.0/command-reference/set-namespace.md, pkg/odo/cli/cli.go, pkg/odo/cli/set/namespace/namespace.go, pkg/odo/cli/set/set.go, tests/helper/helper_cli.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/integration/cmd_namespace_test.go
/kind feature
This PR continues the work started by @valaparthvi by implementing the missing `odo set namespace/project` command.
Relates to #5525
Note: as depicted in the acceptance criteria, if `odo set namespace` is executed inside a component directory, it should show a warning, that this won't update the namespace of the existing component.
```
❯ odo help set namespace
Set the current active namespace.
If executed inside a component directory, this command will not update the namespace of the existing component.
Usage:
odo set namespace [flags]
Aliases:
namespace, project
Examples:
odo set …
```
=> Implement `odo set namespace/project`

docs/website/versioned_docs/version-3.0.0/user-guides/quickstart.md
What's done:
- Minor update to the quickstart guide to remove references to my username
- Add more details how to test under Deploy
N/A
=> Update quickstart guide

tests/helper/helper_cli.go, tests/helper/helper_generic.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/integration/cmd_namespace_test.go, tests/integration/devfile/cmd_delete_test.go, tests/integration/devfile/cmd_dev_test.go, tests/integration/devfile/cmd_devfile_deploy_test.go
/kind tests
/area testing
When running against my local K8s cluster, I noticed that we were spending several seconds just waiting for the test namespace to be gone, as part of the tear-down logic.
However, when running against an OpenShift cluster, project/namespace deletion appears not to be blocking.
I might be missing something, but I was wondering if it wouldn't make sense to have the same behavior in `helper_kubectl.go`.
This might not have any notable impact in CI, but I noticed substantial gains when iterating locally.
Example with a simple test suite (execution time went from ~116 seconds to ~25 seconds with the test namespace deleted asynchronously):
**Before these changes**
```
❯ time ginkgo -focus 'odo …
```
=> Speed up tests on K8s by not blocking until test namespace is gone

docs/website/versioned_docs/version-3.0.0/command-reference/add-binding.md, docs/website/versioned_docs/version-3.0.0/command-reference/build-images.md, docs/website/versioned_docs/version-3.0.0/command-reference/create-namespace.md, docs/website/versioned_docs/version-3.0.0/command-reference/delete-component.md, docs/website/versioned_docs/version-3.0.0/command-reference/delete-namespace.md, docs/website/versioned_docs/version-3.0.0/command-reference/deploy.md, docs/website/versioned_docs/version-3.0.0/command-reference/describe.md, docs/website/versioned_docs/version-3.0.0/command-reference/dev.md, docs/website/versioned_docs/version-3.0.0/command-reference/init.md, docs/website/versioned_docs/version-3.0.0/command-reference/json-output.md, docs/website/versioned_docs/version-3.0.0/command-reference/list-namespace.md, docs/website/versioned_docs/version-3.0.0/command-reference/list.md, docs/website/versioned_docs/version-3.0.0/command-reference/preference.md, docs/website/versioned_docs/version-3.0.0/command-reference/registry.md, docs/website/versioned_docs/version-3.0.0/command-reference/set-namespace.md
Fixes the ordering of the command reference so it is alphabetical (with
JSON output being the top doc)
Fixes https://github.com/redhat-developer/odo/issues/5766
=> Fix ordering of command reference docs

docs/website/versioned_docs/version-3.0.0/command-reference/describe-binding.md, docs/website/versioned_docs/version-3.0.0/command-reference/describe-component.md, docs/website/versioned_docs/version-3.0.0/command-reference/json-output.md, pkg/api/binding.go, pkg/binding/binding.go, pkg/binding/interface.go, pkg/binding/mock.go, pkg/kclient/binding.go, pkg/kclient/interface.go, pkg/kclient/mock_Client.go, pkg/kclient/operators.go, pkg/odo/cli/describe/binding.go, pkg/odo/cli/describe/describe.go, tests/examples/source/devfiles/nodejs/devfile-with-service-binding-envvars.yaml, tests/examples/source/devfiles/nodejs/devfile-with-service-binding-files.yaml, tests/examples/source/devfiles/nodejs/devfile-with-spec-service-binding-envvars.yaml, tests/examples/source/devfiles/nodejs/devfile-with-spec-service-binding.yaml, tests/integration/devfile/cmd_describe_binding_test.go, tests/integration/devfile/cmd_describe_component_test.go
=> odo describe binding

pkg/odo/cli/alizer/alizer.go, pkg/odo/cli/cli.go
`alizer` command looked a little bit weird in "GUI Commands" section.
It made it look like the command itself has some kind of GUI.
For now, I moved it into the utility section. Later we might consider some other placement.
=> move alizer command from gui to utility group

docs/website/versioned_docs/version-3.0.0/user-guides/quickstart.md
Testing out Golang with `odo` was really straight forward and simple,
and I thought I may as well add it to the quick start guide!
N/A
=> Add Golang to the quickstart guide

docs/website/versioned_docs/version-3.0.0/user-guides/quickstart.md, go.mod, go.sum, pkg/alizer/alizer.go, vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/go_enricher.go, vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/component_recognizer.go, vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/devfile_recognizer.go, vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/language_recognizer.go, vendor/github.com/redhat-developer/alizer/go/pkg/schema/languages.go, vendor/github.com/redhat-developer/alizer/go/pkg/utils/langfiles/languages_file_handler.go, vendor/modules.txt
=> Use latest alizer library version, including .net detection

Makefile, tests/e2escenarios/e2e-test.go
/kind tests
This PR adds e2e tests for odo.
Fixes #5752
Fixes #5750 
=> add e2e tests

docs/website/versioned_docs/version-3.0.0/command-reference/deploy.md, docs/website/versioned_docs/version-3.0.0/command-reference/dev.md, go.mod, go.sum, pkg/dev/dev.go, pkg/dev/interface.go, pkg/dev/mock.go, pkg/devfile/devfile.go, pkg/odo/cli/deploy/deploy.go, pkg/odo/cli/dev/dev.go, pkg/odo/genericclioptions/context.go, pkg/vars/doc.go, pkg/vars/errors.go, pkg/vars/vars.go, pkg/vars/vars_test.go, pkg/watch/watch.go, tests/integration/devfile/cmd_dev_test.go, vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/import_reference.go, vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/zz_generated.parent_overrides.go, vendor/github.com/devfile/library/pkg/devfile/parse.go, vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/2.2.0/devfileJsonSchema220.go, vendor/github.com/devfile/library/pkg/devfile/parser/parse.go, vendor/github.com/devfile/library/pkg/util/util.go, vendor/modules.txt
=> Substituting variables into the devfile from the CLI

pkg/kclient/dynamic.go
/kind bug
If there are cluster scoped resources that are reported in the
`BindableKinds`, they will be included when trying to retrieve Service
Instances. When this happens and we try to search for those resources
in a namespace, Kubernetes will return the error that they are not found.
We can not assume all developers would have access to these
cluster scoped resources, so we can not safely run additional checks to
verify they are cluster scoped resources. However, if nothing is found,
it is safe to assume they can not be bound to as the developer does not
have access to them.
N/A
- Add service …
=> ignore dynamic resource when not found

pkg/init/backend/interactive.go, pkg/init/backend/interactive_test.go
/kind bug
This PR fixes the Devfile Volume component shown when personalizing devfile configuration.
Fixes #5779 
1. `touch pom.xml a.java`
2. `odo init`
3. Select java-springboot project type.
4. Make sure `m2` Volume component does not appear on the list.
```sh
➜  odo init
__
/  \__     Initializing new component
\__/  \    Files: Source code detected, a Devfile will be determined based upon source code autodetection
/  \__/    odo version: v3.0.0-alpha3
\__/
Interactive mode enabled, please answer the following questions:
Based on the files in the current directory odo detected
Language: java …
```
=> Fix: configuration shows volumes as containers

pkg/kclient/dynamic.go, pkg/kclient/interface.go, pkg/kclient/mock_Client.go, pkg/service/link.go, pkg/service/service.go, tests/integration/devfile/cmd_dev_test.go
/kind bug
This PR tests during the patch of the service binding if this one has been created/updated or not, during `odo dev`.
If the binding has not been created or updated, odo dev does not wait for the pod to restart
Fixes #5781 
=> Wait for deployment rollout only when binding created / modified

docs/website/versioned_docs/version-3.0.0/command-reference/add-binding.md, pkg/binding/asker/survey_asker.go, pkg/odo/cli/add/binding/binding.go, tests/integration/cmd_namespace_test.go, tests/interactive/cmd_add_binding_test.go
/kind feature
This PR adds a more understandable question when asking how to service should be bound to the component.
Fixes #5770 
1. `mkdir /tmp/101; cd /tmp/101`
2. Setup a bindable operator and spawn a service. For example - https://operatorhub.io/operator/cloud-native-postgresql
3. `odo init --name restapi --devfile go --starter go-starter`
4. `odo add binding`
=> odo add binding - Bind as files UI update

docs/website/docs/getting-started/installation.md, docs/website/versioned_docs/version-3.0.0/overview/installation.md
Adds documentation on how to install via `brew`.
Fixes https://github.com/redhat-developer/odo/issues/5801
=> Add Homebrew installation details

tests/examples/source/devfiles/nodejs/devfile-deploy-with-multiple-resources.yaml, tests/integration/cmd_namespace_test.go, tests/integration/devfile/cmd_delete_test.go, tests/integration/devfile/cmd_describe_binding_test.go, tests/integration/devfile/cmd_devfile_build_images_test.go, tests/integration/devfile/cmd_devfile_deploy_test.go
/kind tests
This PR makes an attempt at fixing dynamically generated specs. We have been using for loops with our integration tests, but it doesn't work as expected. The fix introduced with this PR attempts at fixing that.
Fixes #5814 
1. Debug tests, make sure correct data is taken into account.
=> Fix parametrized integration tests

pkg/devfile/adapters/kubernetes/component/commandhandler.go, pkg/remotecmd/kubeexec.go, pkg/remotecmd/kubexec_test.go, pkg/remotecmd/types.go
/kind tests
/area testing
Unit tests in `pkg/remotecmd/kubeexec_test.go` expect an exact command-line string to be passed when running commands in containers. The problem is that the environment variables are stored in a map, the iteration order of which is not guaranteed.
Initially reported in https://github.com/redhat-developer/odo/pull/5823#issuecomment-1160383237
```
==================
--- FAIL: TestKubeExecProcessHandler_StartProcessForCommand (10.00s)
--- FAIL: TestKubeExecProcessHandler_StartProcessForCommand/command_with_all_fields_returned_no_error (10.00s)
remotecmd.go:36: Unexpected call to *kclient.MockClientInterface.ExecCMDInContainer([my-container my-pod [/bin/sh -c …
```
=> Fix flaky `kubeexec` unit test case with env vars

pkg/odo/cli/cli.go, tests/integration/generic_test.go
/kind bug
When we type:
```sh
odo foobar --help
```
We should error out that it's an invalid command.
Fixes https://github.com/redhat-developer/odo/issues/5439
=> When typing odo foobar --help should error out with invalid command

docs/website/versioned_docs/version-3.0.0/command-reference/add-binding.md, pkg/binding/add.go, pkg/binding/asker/interface.go, pkg/binding/asker/survey_asker.go, pkg/binding/backend/flags.go, pkg/binding/backend/interactive.go, pkg/binding/backend/interface.go, pkg/binding/backend/mock.go, pkg/binding/binding.go, pkg/binding/binding_test.go, pkg/binding/interface.go, pkg/binding/list_test.go, pkg/binding/mock.go, pkg/kclient/binding.go, pkg/kclient/deployments.go, pkg/kclient/interface.go, pkg/kclient/kclient.go, pkg/kclient/mock_Client.go, pkg/kclient/operators.go, pkg/odo/cli/add/binding/binding.go, pkg/preference/mock.go, pkg/service/link.go, tests/integration/devfile/cmd_add_binding_test.go, tests/interactive/cmd_add_binding_test.go
/kind feature
- ServiceBinding service is now referenced by its Kind, not its Resource, to be consistent with the value added as flag (with Kind)
- Ability to run `odo add binding` withtout devfile.yaml
- in interactive mode, output as:
- file
- stdout
- creat on cluster
- in non-interactive mode, with `--workload` flag, output as:
- stdout
Fixes #5772 
=> odo add binding without devfile.yaml

docs/website/docs/command-reference/dev.md, pkg/dev/dev.go, pkg/dev/interface.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/utils/utils.go, pkg/libdevfile/errors.go, pkg/libdevfile/libdevfile.go, pkg/libdevfile/libdevfile_test.go, pkg/odo/cli/dev/dev.go, tests/examples/source/devfiles/nodejs/devfile-with-two-run-commands.yaml, tests/helper/helper_dev.go, tests/integration/devfile/cmd_dev_test.go, tests/interactive/cmd_deploy_test.go
/kind feature
/area dev
See #5775 for the use case.
Fixes #5775 
`odo dev --run-command <command>` should allow to run the specified `<command>`, provided it is in the `run` group.
=> Add `run-command` flag to `odo dev` to run non-default Run command

tests/integration/cmd_namespace_test.go
=> Eventually list namespaces for test

docs/website/docs/command-reference/dev.md, pkg/dev/dev.go, pkg/dev/interface.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/libdevfile/libdevfile.go, pkg/libdevfile/libdevfile_test.go, pkg/odo/cli/dev/dev.go, tests/examples/source/devfiles/nodejs/devfile-with-alternative-commands.yaml, tests/integration/devfile/cmd_dev_test.go
/kind feature
/area dev
This adds a `build-command` flag to `odo dev`. See #5776 for more context.
Fixes #5776
`odo dev --build-command <command>` should allow to build the application using the specified `<command>`, provided it is in the `build` group.
=> Add `build-command` flag to `odo dev` to run non-default Build command

pkg/binding/binding.go, pkg/binding/binding_test.go, pkg/kclient/binding.go
/kind bug
This PR fixes the misleading error message when running `odo add binding`.
Fixes #5882
Run `odo add binding` when -
1. Service Binding Operator is not installed.
```sh
$ odo add binding
✗  Service Binding Operator is not installed on the cluster, please ensure it is installed before proceeding.
```
2. No Bindable operator is installed
```sh
$ odo add binding
✗  No bindable operators found on the cluster. Please ensure that at least one bindable operator is installed successfully before proceeding. Kno
wn Bindable operators: https://github.com/redhat-developer/service-binding-operator#known-bi …
```
=> Fix misleading add binding  error message

pkg/binding/mock.go, pkg/dev/dev.go, pkg/dev/interface.go, pkg/dev/mock.go, pkg/devfile/adapters/helper.go, pkg/devfile/adapters/helper_test.go, pkg/devfile/adapters/kubernetes/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter_test.go, pkg/kclient/interface.go, pkg/kclient/mock_Client.go, pkg/kclient/port_forwarding.go, pkg/odo/cli/dev/dev.go, pkg/odo/genericclioptions/clientset/clientset.go, pkg/portForward/interface.go, pkg/portForward/portForward.go, pkg/portForward/writer.go, pkg/portForward/writer_test.go, tests/e2escenarios/e2e-test.go, tests/examples/source/devfiles/nodejs/project-with-multiple-endpoints/server.js, tests/helper/helper_dev.go, tests/integration/devfile/cmd_dev_test.go
=> odo dev: handle port forwarding after pod restart

docs/website/docs/command-reference/list.md, pkg/kclient/all.go, pkg/kclient/kclient.go
~This PR changes odo to use a cached discovery client.~
This PR adds a cached discovery client along with the existing discovery 
client. Functions can use the client appropriate for their use.
A cached discovery client refers its cache under `~/.kube/cache` instead
of checking with the cluster every time.
Fixes part of #5872
**How to test changes:**
* Spin up a k8s/ocp cluster other than one on the local box. For example, use ClusterBot.
* Execute `odo list -v2` and look for the line that reads: `all.go:119] queried api discovery in`. Also, worth noting is the line that reads: `all.go:61] all goroutines have returned in`.
* Note the …
=> Use cached discovery client

docs/website/blog/2022-06-30-binding-database-service-without-sbo.md
Fixes #5771 
https://deploy-preview-5915--odo-docusaurus-preview.netlify.app/blog/binding-database-service-without-sbo
=> Blog: Connecting to a service without SBO

tests/e2escenarios/e2e-test.go, tests/e2escenarios/e2e_devfile_test.go, tests/helper/helper_generic.go, tests/integration/cmd_add_binding_test.go, tests/integration/cmd_analyze_test.go, tests/integration/cmd_delete_test.go, tests/integration/cmd_describe_component_test.go, tests/integration/cmd_describe_list_binding_test.go, tests/integration/cmd_dev_debug_test.go, tests/integration/cmd_dev_test.go, tests/integration/cmd_devfile_build_images_test.go, tests/integration/cmd_devfile_deploy_test.go, tests/integration/cmd_devfile_init_test.go, tests/integration/cmd_devfile_list_test.go, tests/integration/cmd_devfile_registry_test.go, tests/integration/cmd_logs_test.go, tests/integration/cmd_namespace_test.go, tests/integration/cmd_pref_config_test.go, tests/integration/cmd_remove_binding_test.go, tests/integration/generic_test.go, tests/integration/interactive_add_binding_test.go, tests/integration/interactive_deploy_test.go, tests/integration/interactive_dev_test.go, tests/integration/interactive_init_test.go
/kind cleanup
/kind tests
This PR will update the commonBeforeEach and CommonAfterEach to skip or to execute cluster related operation.
Now commonBeforeEach require bool argument, we can pass `helper.SetupClusterFalse` or `helper.SetupClusterTrue` as we require.
Fixes #5868 
=> Cleanup test to skip setup cluster steps if needed

.github/ISSUE_TEMPLATE/Documentation.md
documentation should be in /area documentation
`kind` is meant to be more like kind of an issue (bug, epic, user-story, feature request etc...) 
`area` is to what area the issue/pr is related to 
each issue or PR can have only one kind, but multiple areas
=> update documentation issue template

Makefile, scripts/openshiftci-presubmit-unittests.sh
/area testing
Removing golangci-lint from the script, as the installation is added as [pre step](https://github.com/anandrkskd/release/blob/0692f2611817db9766dd338317b5627e4c4b52cf/ci-operator/config/redhat-developer/odo/redhat-developer-odo-main.yaml#L14) in unit test set on prow, it downloads the binary directly for the test.
Fixes [#5879](https://github.com/redhat-developer/odo/issues/5879)
=> download golangci-lint binary with test script

docs/website/blog/2022-07-01-odo-v3-beta1.md
This adds a blog post for the previous v3.0.0-beta1 release.
For simplicity, I've copied the changelog associated with this release. And I also picked the points mentioned during the Sprint Demos as "most notable changes" along with the relevant videos. I've also included the link to the corresponding [playlist](https://www.youtube.com/playlist?list=PLGMB2PY4SNOrBQabcLZ_M5rN8l5u0B_cw).
A separate PR will follow up for v3.0.0-beta2 once it is completely released.
Fixes #5904
Preview: https://deploy-preview-5956--odo-docusaurus-preview.netlify.app/blog/odo-v3-beta1-release
=> Add blog post for v3.0.0-beta1 release

pkg/logs/logs.go, pkg/odo/cli/logs/logs.go, tests/integration/cmd_logs_test.go
/kind bug
As a result of the code pushed in https://github.com/redhat-developer/odo/pull/5942, `odo logs --follow` would hang
if user executed it without pushing the component in either dev or 
deploy modes. This was not a problem before that PR was merged.
This was caused because below code would not get executed in business
layer if user was using follow mode:
```
if !follow {
doneChan <- struct{}{}
}
```
The reason we didn't execute it for follow mode was that it prematurely
exited and often didn't print the logs of all the containers.
This PR uses `sync/atomic` to keep a tab on go routines started for 
`odo logs --follow` instead of using `sync.WaitGroup`, and …
=> Use sync/atomic to keep tab on go routines

docs/website/docs/command-reference/add-binding.md, docs/website/docs/command-reference/describe-binding.md, docs/website/docs/command-reference/json-output.md, docs/website/docs/command-reference/list-binding.md, pkg/binding/add.go, pkg/binding/asker/interface.go, pkg/binding/asker/survey_asker.go, pkg/binding/backend/flags.go, pkg/binding/backend/interactive.go, pkg/binding/backend/interface.go, pkg/binding/backend/mock.go, pkg/binding/binding.go, pkg/binding/binding_test.go, pkg/binding/interface.go, pkg/binding/list_test.go, pkg/binding/mock.go, pkg/kclient/binding.go, pkg/kclient/dynamic.go, pkg/kclient/interface.go, pkg/kclient/mock_Client.go, pkg/odo/cli/add/binding/binding.go, pkg/odo/cli/describe/binding.go, pkg/odo/cli/list/binding/binding.go, pkg/odo/genericclioptions/clientset/clientset.go, pkg/service/service.go, tests/integration/cmd_add_binding_test.go, tests/integration/cmd_describe_list_binding_test.go, tests/integration/interactive_add_binding_test.go
/kind feature
This PR makes it possible to select or specify any other namespace when listing the service instances to use for adding a new binding.
For consistency, this supports both interactive and non-interactive modes. And output / docs for `odo describe binding` and `odo list binding` (and their JSON counterparts) have been updated to include information about the service namespace, if available.
Fixes #5820
- Non-Interactive mode: new `--service-namespace` flag added to `odo add binding`
- Interactive mode: new questions added when running `odo add binding`. They allow picking the namespace …
=> Allow binding to services from other namespaces

pkg/odo/cli/add/add.go, pkg/odo/cli/cli.go, pkg/odo/cli/create/create.go, pkg/odo/cli/delete/delete.go, pkg/odo/cli/describe/describe.go, pkg/odo/cli/list/list.go, pkg/odo/cli/remove/remove.go, pkg/odo/cli/set/set.go
/kind cleanup
One thing I noticed is that all of our commands are clustered into one
section.
We mix both nouns and verbs together.
I've gone ahead and separated it into a different section so it's easier
to decipher what can be done, I've named the section "management
commands".
```sh
go/src/odo  improve-help-page-usage ✔                                                                                                                                                                                                                                                                                                                             2h18m
/  \__     odo is a CLI tool for fast iterative application development
\__/  \ …
```
=> Improve --help page by separating commands to management commands

docs/website/blog/2022-07-21-odo-v3-beta2.md, docs/website/docs/overview/installation.md, docs/website/docusaurus.config.js
Now that the artifacts for our `v3.0.0-beta2` are [publicly available in the Content Gateway](https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/v3.0.0~beta2/), this PR adds the blog post for this release.
It also updates the installation doc to use such version.
Fixes #5905
- Updated
- [Installation doc](https://deploy-preview-5966--odo-docusaurus-preview.netlify.app/docs/overview/installation)
- New
- [Blog post](https://deploy-preview-5966--odo-docusaurus-preview.netlify.app/blog/odo-v3-beta2-release)
=> Add blog post for `v3.0.0-beta2` release and update installation doc

pkg/init/backend/interactive.go, pkg/log/status.go, pkg/portForward/writer.go
/kind cleanup
This PR fixes the following:
- Updates the interactive mode so it's better looking when outputting
configuration so it's similar to the rest of the output:
```sh
? Is this correct? Yes
✓  Downloading devfile "nodejs" from registry "DefaultDevfileRegistry" [1s]
↪ Container Configuration "runtime":
OPEN PORTS:
- 3000
ENVIRONMENT VARIABLES:
? Select container for which you want to change configuration? runtime
? What configuration do you want change? Delete port "3000"
? What configuration do you want change? NOTHING - configuration is correct
↪ Container Configuration "runtime":
OPEN PORTS:
ENVIRONMENT VARIABLES:
? Select container for which you want to change configuration?  [Use arrows to move, type to …
```
=> Refactor color througout interactive mode and dev

.github/dependabot.yml
/kind task
To help alleviate the review burden on PRs, this PR reduces the number of PRs created by Dependabot to a maximum of 2 (1 for `go.mod` related PRs, and 1 for NPM packages).
This was discussed in the Retrospective meeting.
None
=> Limit the total number of Dependabot PRs to 2

Makefile, tests/e2escenarios/e2e_test.go
=> Increase timeout by 60sec devEnv check

pkg/component/pushed_component.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/odo/cli/deploy/deploy.go, pkg/odo/cli/dev/dev.go, pkg/storage/storage.go, tests/helper/helper_filesystem.go, tests/integration/cmd_dev_test.go
/kind bug
By default we should be saving the namespace / project name, not the app name /
component name.
Fixes https://github.com/redhat-developer/odo/issues/5780
Fixes https://github.com/redhat-developer/odo/issues/5886
=> Do not save component name in env.yaml

docs/website/docs/command-reference/build-images.md, docs/website/docs/command-reference/deploy.md, pkg/deploy/deploy.go, pkg/deploy/interface.go, pkg/deploy/mock.go, pkg/devfile/image/docker_compatible.go, pkg/devfile/image/docker_compatible_test.go, pkg/devfile/image/image.go, pkg/devfile/image/image_test.go, pkg/devfile/image/mock_Backend.go, pkg/odo/cli/build_images/build_images.go, pkg/odo/cli/deploy/deploy.go, tests/integration/cmd_devfile_build_images_test.go, tests/integration/cmd_devfile_deploy_test.go
/kind feature
This PR adds support for remote Dockerfiles (specified via an HTTP or HTTPS URL) when running `odo build-images` or `odo deploy`.
Fixes #5450
See the reproduction steps provided in #5450 for functional testing.
From the code perspective, commits in this branch are atomic and self-contained. This PR can be reviewed on a commit-by-commit basis.
=> Allow using remote Dockerfiles (HTTP(S) only) for building images

docs/website/docs/overview/configure.md
=> add documenation for env variables used by odo

docs/website/docs/command-reference/create-namespace.md, docs/website/docs/command-reference/delete-namespace.md, docs/website/docs/command-reference/describe-binding.md, docs/website/docs/command-reference/dev.md, docs/website/docs/command-reference/init.md, docs/website/docs/command-reference/json-output.md, docs/website/docs/command-reference/list-binding.md, docs/website/docs/command-reference/list-namespace.md, docs/website/docs/command-reference/registry.md, docs/website/docs/command-reference/remove-binding.md, docs/website/docs/command-reference/set-namespace.md, docs/website/docs/user-guides/quickstart.md
This PR does the following:
* Removes all `$` from commands that should be "copied-and-pasted"
* Separates all console output to a separation section.
Notes:
* "Details" markdown feature would of been used, but Docusaurus does not
support <details> within a <tab>.
Fixes https://github.com/redhat-developer/odo/issues/5844
=> Remove $ symbol from some commands

scripts/check-fit.sh
/kind tests
This PR adds more checks to check-fit.sh script.
Fixes #
1. Add focus to your tests by adding `F` to your specs.(https://onsi.github.io/ginkgo/#focused-specs)
2. Run the script and see if it detects them.
=> Add more checks to check-fit.sh

docs/website/docs/overview/configure.md, tests/integration/cmd_devfile_registry_test.go
/kind tests
This PR makes all tests use the devfile proxy, including the tests using `odo init --devfile-registry`
=> Use devfile proxy for odo init --devfile-registry

pkg/kclient/all.go, pkg/kclient/deployments.go, pkg/kclient/interface.go, pkg/kclient/mock_Client.go, pkg/kclient/pods.go, pkg/logs/logs.go, pkg/storage/mock_Client.go
/kind bug
We first fetch the pods matching the selector so that we can quickly start showing the logs to the user. For a component created using [this devfile in test suite](https://github.com/redhat-developer/odo/blob/main/tests/examples/source/devfiles/nodejs/devfile-deploy-functional-pods.yaml) and running in both Dev and Deploy modes, performance improvement is as below:
```sh
$ odo-main logs | grep "===="
============================= 2.322569471s =============================
============================= 2.614284155s =============================
============================= 6.419786304s =============================
============================= 6.727155955s =============================
$ odo-pods-first logs | grep "====" …
```
=> Fetch pods first; use channel instead of slice

pkg/odo/genericclioptions/context_test.go, pkg/odo/genericclioptions/localprovider.go, tests/integration/cmd_delete_test.go
/kind bug
Enhance error message when user runs from a non-component directory
Fixes #5987
1. Run `odo delete component` or any other command from an empty directory.
The error message is long and could use an improvement, so I am looking for suggestions.
=> Enhance error message when user runs from a non-component directory

docs/website/docs/command-reference/create-namespace.md, docs/website/docs/command-reference/delete-namespace.md, docs/website/docs/command-reference/deploy.md, docs/website/docs/command-reference/dev.md, docs/website/docs/command-reference/set-namespace.md, pkg/odo/cli/create/namespace/namespace.go
=> Document how odo works with projects/namespaces

pkg/portForward/portForward.go, tests/examples/source/devfiles/nodejs/devfile-composite-apply-commands.yaml, tests/helper/helper_cli.go, tests/helper/helper_dev.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/integration/cmd_dev_test.go
=> Restart port forwarding on failure

pkg/devfile/adapters/kubernetes/component/commandhandler.go, pkg/log/status.go
/kind bug
It fixes the UX that would lead a user to think that there was some error in executing the `run` command
Fixes #5881
* Run `odo dev`
* Change a code file in the directory; odo should not exhibit the erroneous UX
* Stop `odo dev` with `Ctrl+C`; odo should not exhibit the erroneous UX
=> Allow specifying message to end the spinner with

pkg/component/component.go, pkg/component/component_test.go, tests/examples/manifests/deployment-app-label.yaml, tests/examples/manifests/deployment-without-managed-by-label.yaml, tests/integration/cmd_devfile_list_test.go
/kind bug
This PR fixes the bug where components not managed by odo were not detected by odo.
Fixes #6007 
1. Create a component from OpenShift Web Console.
2. Run `odo list`
3. See if the component is detected.
=> Fix: Non odo components not reported

pkg/odo/cli/dev/dev.go, pkg/odo/genericclioptions/runnable.go, pkg/odo/util/cmdutils.go, pkg/watch/watch.go, pkg/watch/watch_test.go, tests/integration/cmd_dev_test.go
=> odo dev: Cleanup after displaying the error

pkg/libdevfile/generator/component.go, pkg/libdevfile/testdata/child-devfile-commands-only.yaml, pkg/libdevfile/testdata/child-devfile-complete.yaml, pkg/libdevfile/testdata/child-devfile-components-only.yaml, pkg/libdevfile/testdata/child-devfile.yaml, pkg/libdevfile/testdata/parent/parent-devfile-commands-only.yaml, pkg/libdevfile/testdata/parent/parent-devfile-components-only.yaml, pkg/libdevfile/testdata/parent/parent-devfile-empty.yaml, pkg/libdevfile/testdata/parent/parent-devfile.yaml, pkg/libdevfile/uris.go, pkg/libdevfile/uris_test.go, pkg/watch/watch.go, tests/examples/source/devfiles/nodejs/devfile-child.yaml, tests/examples/source/devfiles/nodejs/devfile-parent.yaml, tests/helper/helper_filesystem.go, tests/integration/cmd_dev_test.go
=> Watch for devfile dependencies

docs/website/blog/2022-08-18-odo-v3-beta3.md, docs/website/docs/overview/installation.md, docs/website/docusaurus.config.js
This adds blog post for odo v3.0.0-beta3
Fixes #5906 
=> Add blog post for v3.0.0-beta3 and update installation docs

tests/helper/helper_cmd_wrapper.go
On Windows, when sending the Ctrl-C signal to the `odo dev` process to stop it, we firt need to set a specific attribute on the process (`CREATE_NEW_PROCESS_GROUP`), or the parent process will also receive the signal.
By changing from `CmdRunner()` to `Cmd().Runner()` in commit (https://github.com/redhat-developer/odo/commit/224069cd68f4a03f4b5b17009fb4ca42ef8c5d89), `setSysProcAttr` in `CmdRunner()` is not called anymore.
=> Troubleshoot IBM Cloud Windows tests failing

pkg/envinfo/envinfo_test.go, pkg/odo/genericclioptions/context_test.go, pkg/preference/implem_test.go, pkg/registry/registry_test.go, pkg/registry/utils_test.go, pkg/segment/integrations_test.go, pkg/segment/segment_test.go
/kind cleanup
This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
This saves us at least 2 lines (error check, and unsetting the env var) on every instance.
Reference: https://pkg.go.dev/testing#T.Setenv
=> test: use `T.Setenv` to set env vars in tests

docs/website/docs/command-reference/create-namespace.md, docs/website/docs/command-reference/delete-namespace.md, docs/website/docs/command-reference/deploy.md, docs/website/docs/command-reference/dev.md, docs/website/docs/command-reference/set-namespace.md, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/envinfo/envinfo.go, pkg/localConfigProvider/localConfigProvider.go, pkg/odo/cli/delete/component/component.go, pkg/odo/cli/delete/component/component_test.go, pkg/odo/cli/deploy/deploy.go, pkg/odo/cli/dev/dev.go, pkg/odo/cli/set/namespace/namespace.go, pkg/odo/cmdline/cmdline.go, pkg/odo/cmdline/cobra.go, pkg/odo/genericclioptions/context.go, pkg/odo/genericclioptions/context_test.go, pkg/odo/genericclioptions/errors.go, pkg/odo/genericclioptions/localprovider.go, pkg/odo/genericclioptions/resolve.go, tests/integration/cmd_delete_test.go, tests/integration/cmd_describe_component_test.go, tests/integration/cmd_dev_test.go, tests/integration/cmd_devfile_build_images_test.go, tests/integration/cmd_devfile_deploy_test.go, tests/integration/cmd_namespace_test.go
/kind feature
- set current namespace in env.yaml file when starting `odo dev`, remove it when cleanup
- do not read project from env.yaml file when running `odo dev` (or any other command)
- env.yaml file is not created when running `odo deploy`
- the existence of env.yaml file is not checked when running `odo delete component`, `odo build-images` (or any other command)
Fixes #6018
Fixes #6027
=> Do not get project from env.yaml file

pkg/segment/integrations.go, pkg/segment/integrations_test.go
=> Do not send userId to registry when ODO_DEBUG_TELEMETRY_FILE is set

pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/component/commandhandler.go, pkg/devfile/adapters/kubernetes/component/push.go, pkg/service/link.go, pkg/service/service.go, tests/examples/source/devfiles/nodejs/devfile-deploy-with-SB.yaml, tests/integration/cmd_devfile_deploy_test.go
/kind bug
ServiceBinding resources are now allowed to be deployed on the cluster with odo deploy.
Fixes #5883
1.
```sh
odo init --devfile go --name my-go-app --starter go-starter
``` 
2. Copy the contents of the devfile.yaml as mentioned in #5883 
3. Deploy the bindable kind instance as mentioned in #5883 
4. Run `odo deploy`.
```sh
PODMAN_CMD=echo odo deploy
```
Note: Test case for `odo dev` without SBO is pending.
=> Fix: ServiceBinding resources are not deployed with odo deploy

docs/website/docs/command-reference/list-binding.md, docs/website/docs/command-reference/list-component.md, docs/website/docs/command-reference/list.md, pkg/component/component.go, pkg/odo/cli/list/binding/binding.go, pkg/odo/cli/list/component/list.go, pkg/odo/cli/list/list.go, tests/e2escenarios/e2e_test.go, tests/integration/cmd_describe_list_binding_test.go, tests/integration/cmd_devfile_list_test.go
=> Implement "odo list"

scripts/bump-version.sh
This PR updates the scripts/bump-version.sh to support any version name, not only x.y.z
=> Update script to support alpha/beta/rc versions

docs/website/blog/2022-09-01-odo-v3-rc1.md, docs/website/docs/overview/installation.md, docs/website/docusaurus.config.js
=> Blog post for v3.0.0-rc1 release

pkg/alizer/alizer.go, pkg/alizer/alizer_test.go, pkg/alizer/interface.go, pkg/alizer/mock.go, pkg/component/component.go, pkg/init/backend/alizer.go, pkg/init/backend/interactive.go, pkg/init/backend/interactive_test.go, pkg/init/init.go
/kind bug
Move the DetectName function to a method in the `pkg/alizer` method, to be able to mock it from `pkg/init/backend` package
Fixes #6092 
=> [flaky test] Move DetectName to method in alizer package

docs/website/docs/command-reference/init.md, pkg/init/asker/asker.go, pkg/init/backend/flags.go, pkg/init/backend/flags_test.go, pkg/init/backend/interactive.go, pkg/init/backend/interactive_test.go, pkg/init/init.go, pkg/init/init_test.go, pkg/odo/cli/init/init.go, tests/integration/cmd_devfile_init_test.go, tests/integration/interactive_init_test.go
/kind bug
This PR adds validation to component name input to make sure it aligns with K8s naming convention.
Fixes #5765 
1. `odo init --devfile go --name 123`
2. `odo init` - use name `myapp-<script>alert('Injected!');</script>` or `my-go-app1;ls -las` when asked for devfile name.
Both should fail.
=> (odo init): Add input validation for component name

docs/website/docs/command-reference/json-output.md, pkg/api/binding.go, pkg/api/component-abstract.go, pkg/api/component.go, pkg/api/component_test.go, pkg/binding/list.go, pkg/binding/list_test.go, pkg/component/component.go, pkg/component/component_test.go, pkg/odo/cli/init/init.go, tests/integration/cmd_describe_component_test.go, tests/integration/cmd_devfile_list_test.go
=> Use map for runningIn instead of array in JSON output

pkg/odo/cli/list/component/list.go
/kind bug
Fixes #6061
1. `mkdir /tmp/101; cd /tmp/101`
2. `odo init --devfile go --name my-go --starter go-starter`
3. `odo list` should not show empty parenthesis for odo version
=> Fix: (odo list) Empty parenthesis for odo version if component is not on the cluster

tests/integration/cmd_dev_test.go
/kind tests
This PR removes skip from `odo dev` integration tests when working with k8s cluster.
Fixes #
=> Remove skip for k8s from `odo dev` integration tests

pkg/log/status.go, pkg/odo/cli/init/init.go, pkg/odo/cli/messages/messages.go, tests/integration/cmd_devfile_init_test.go, tests/integration/interactive_init_test.go
/kind bug
Fixes #5957
Running `odo init` non-interactively should no longer display the "Interactive mode enabled, please answer the following questions" message.
=> Display "Interactive mode enabled" only when running `odo init` interactively

docs/website/docs/overview/installation.md
Reorganizes installation document
- Separates Homebrew and Binary sections for MAC
- Separates installing from source / maven plugins / etc.
Fixes https://github.com/redhat-developer/odo/issues/6082
=> Reorganizes installation document

pkg/watch/watch.go, tests/helper/helper_dev.go
=> Do not display message when using no-watch flag

docs/website/docs/user-guides/deploy/_prerequisites.mdx
[Adds tabs for mac / windows / linux environments in docs](https://github.com/redhat-developer/odo/pull/6087/commits/7188302856097da0688b3e53eba81c0f2e1eaaa7) 
* Updates the documentation with regards to different operating systems
when deploying an image
Fixes https://github.com/redhat-developer/odo/issues/6085
=> Adds tabs for podman/docker docs and OS differences

pkg/libdevfile/libdevfile.go, pkg/libdevfile/libdevfile_test.go, pkg/odo/cli/dev/dev.go, tests/integration/cmd_dev_test.go
/kind bug
This removes the condition that caused endpoints with `exposure: none` to be ignored. Now `odo dev` should port-forward all endpoints, regardless of their exposures.
This is needed as part of #5988: a separate PR in the Devfile registry will add endpoints for debug ports to all relevant Devfiles.
ref #5988
Endpoints with `exposure: none` should be port-forwarded, just like any other endpoint.
=> Port-forward all endpoints regardless of exposure

pkg/component/component.go, pkg/component/delete/delete_test.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/component/commandhandler.go, pkg/labels/constants.go, pkg/labels/labels.go, pkg/storage/kubernetes.go, pkg/storage/kubernetes_test.go, pkg/storage/storage.go, pkg/storage/storage_test.go, pkg/testingutil/pods.go, pkg/testingutil/services.go, tests/examples/source/devfiles/nodejs/devfile-with-metadata-language.yaml, tests/examples/source/devfiles/nodejs/devfile-with-metadata-no-language-project-type.yaml, tests/examples/source/devfiles/nodejs/devfile-with-metadata-project-type.yaml, tests/helper/helper_cli.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/integration/cmd_dev_test.go
=> Add runtime label based on metadata:language/projectType

scripts/openshiftci-presubmit-all-tests.sh
/kind tests
This PR fixes failing interop tests on 4.11/4.12
Fixes #
=> fix login failure error: x509

pkg/kclient/oc_server.go, pkg/odo/cli/version/version.go, tests/integration/generic_test.go, tests/integration/loginlogout/cmd_login_logout_test.go
/kind bug
Fixes #5650
1. Start a kubernetes cluster.
2. Run `odo version`. It should display kubernetes version and Server URL.
```sh
$ odo version
odo v3.0.0-rc1 (6c6f8ef5ad)
Server: https://192.168.49.2:8443
Kubernetes: v1.23.3
```
=> Show Kubernetes cluster version in odo version

docs/website/docs/user-guides/v3-migration-guide.md
=> Guide for migrating from v2 to v3

tests/helper/helper_cli.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/integration/interactive_add_binding_test.go
=> check if namespace is created instead of project

pkg/kclient/interface.go, pkg/kclient/mock_Client.go, pkg/kclient/refresh.go, pkg/watch/watch.go
/kind bug
1. When disconnected from the cluster and `odo dev` is interrupted with Ctrl-c, this message is displayed:
```
Error connecting to the cluster, the resources were not cleaned up.
Please log in again and cleanup the resource with `odo delete component
```
2. When disconnected from the cluster, `odo dev` tries to reload the configuration from kubeconfig file.
- If a change of namespace or cluster in the current context is detected, the configuration is not updated. The user can still update the current namespace / cluster 
- if the namespace and cluster are the same, the new configuration is loaded, and `odo dev` continues with it
```
Keyboard Commands:
[Ctrl+c] - Exit and delete resources from the cluster
[p] …
```
=> Try to reload config when disconnected from the cluster

docs/website/docs/user-guides/advanced/_create-mongodb-service.mdx, docs/website/docs/user-guides/advanced/_delete-mongodb-service.mdx, docs/website/docs/user-guides/advanced/connecting-a-service.md
=> Add documentation on connecting to a service

docs/website/docs/command-reference/add-binding.md, docs/website/docs/command-reference/build-images.md, docs/website/docs/command-reference/create-namespace.md, docs/website/docs/command-reference/delete-component.md, docs/website/docs/command-reference/delete-namespace.md, docs/website/docs/command-reference/deploy.md, docs/website/docs/command-reference/describe-binding.md, docs/website/docs/command-reference/describe-component.md, docs/website/docs/command-reference/dev.md, docs/website/docs/command-reference/init.md, docs/website/docs/command-reference/list-binding.md, docs/website/docs/command-reference/list-component.md, docs/website/docs/command-reference/list-namespace.md, docs/website/docs/command-reference/list.md, docs/website/docs/command-reference/logs.md, docs/website/docs/command-reference/registry.md, docs/website/docs/command-reference/remove-binding.md, docs/website/docs/command-reference/set-namespace.md
Fixes #6000 
Ensure all the reference docs have a `running the command` section, and collapsible examples.
=> Make command reference docs consistent

docs/website/docs/overview/concepts.md, docs/website/docs/overview/dev_and_deploy.md
Create document highlighting dev and deploy
* Changes title of "Basics" to "Concepts" in concepts doc
* Adds document on how to do dev vs deploy and which command you should
use
* Highlights when to use either command
Closes https://github.com/redhat-developer/odo/issues/6083
=> Create document highlighting dev and deploy

docs/website/docs/development/architecture/_category_.json, docs/website/docs/development/architecture/how-odo-works.md, docs/website/src/css/custom.css
This adds a new 'Architecture' section under 'Developer Reference' that documents in detail how `odo` works, for users to understand what `odo` does in their clusters.
Let me know if I've missed anything, or if you think the structure or style should be different.
Fixes #5174 
Visit https://deploy-preview-6145--odo-docusaurus-preview.netlify.app/docs/development/architecture/how-odo-works
=> Document how `odo` translates `container` component into Kubernetes resources

pkg/odo/cli/delete/namespace/namespace.go
/kind bug
/area UX
This PR fixes `odo delete project` command to use `project` instead of `namespace` in it's interactive messages.
Fixes #
There should be no reference to namespace while deleting project.
```sh
$ odo delete project myproject
? Are you sure you want to delete project "myproject2"? Yes
✓  Project "myproject2" deleted
```
```sh
$ odo delete project myproject
? Are you sure you want to delete project "myproject2"? No
✗  Aborting project deletion
```
Note: Deleting a non-existent project still shows namespace in the unwrapped errors, but the …
=> Fix message for interactive odo delete project

docs/website/docs/command-reference/add-binding.md, docs/website/docs/command-reference/build-images.md, docs/website/docs/command-reference/delete-namespace.md, docs/website/docs/command-reference/describe-binding.md, docs/website/docs/command-reference/init.md, docs/website/docs/command-reference/list-component.md, docs/website/docs/command-reference/list-namespace.md, docs/website/docs/command-reference/logs.md, docs/website/docs/command-reference/remove-binding.md, docs/website/docs/command-reference/set-namespace.md, docs/website/docs/overview/configure.md
This PR adds missing data.
Fixes #6000 
=> Make command reference docs consistent (2)

pkg/odo/cli/deploy/deploy.go, pkg/odo/cli/dev/dev.go, pkg/odo/cli/messages/messages.go, tests/integration/interactive_deploy_test.go, tests/integration/interactive_dev_test.go
Add extra output when init project using odo dev
/kind cleanup
Updates the messaging when you run `odo dev` and there is no
`devfile.yaml` available. Outputs more information that makes it similar
to running `odo dev` or `odo init`
Fixes https://github.com/redhat-developer/odo/issues/5679
=>  Add extra output when init project using odo dev or deploy

pkg/odo/genericclioptions/runnable.go, pkg/segment/context/context.go, pkg/segment/context/context_test.go, tests/integration/cmd_devfile_deploy_test.go, tests/integration/cmd_devfile_init_test.go
/kind feature
Record what flags are used when the odo command is executed.
This will be helpful to get more insights what features are being used.
For example, currently, we can't see how many users user debug mode `odo dev --debug` or `--no-watch` feature. With this, we will be able to get more insights if those features are being used. 
It would be nice to include this in the v3 GA build, so we can start tracking this from the beginning. 
=> telemetry: start tracking flags usage

docs/website/docs/command-reference/completion.md, pkg/odo/cli/completion/completion.go
/kind bug
/area completion
Replaces `odo zsh` (which does not exist) with `odo completion zsh` in doc and `odo help completion` output.
&mdash;
=> Fix help and doc for `odo completion zsh`

scripts/ansible/kubernetes-cluster/create.yml
=> Fix postgreSQL containers failing due to file permissions errors

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
Bumps odo version from `3.0.0-rc2` to `3.0.0` (on the `release/v3.0.0` branch).
ref #6011
```sh
$ odo version --client
odo v3.0.0 (dafce5dc8)
```
=> Bump odo version from 3.0.0-rc2 to 3.0.0

docs/website/docs/_imageregistrynote.mdx, docs/website/docs/command-reference/deploy.md, docs/website/docs/user-guides/advanced/deploy/_running_deploy.mdx
=> Note regarding image visibility for odo deploy

docs/website/docs/overview/installation.md
=> Fix broken links in the installation guide

.github/workflows/issue-management.yaml
/kind feature
To ease project and issue management, this PR adds a GitHub Workflow that automates some manual tasks:
- automatically labels new or reopened issues with the "needs-triage" label
- automatically adds new or reopened issues to the odo Project.
&mdash;
Once merged, new or reopened issues should be added to the Project and labeled accordingly.
=> Add GitHub Workflow for issue management

pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/exec/exec.go, pkg/exec/exec_test.go, pkg/kclient/interface.go, pkg/kclient/kclient.go, pkg/kclient/pods.go, pkg/odo/genericclioptions/clientset/clientset.go, pkg/odo/genericclioptions/runnable.go, pkg/platform/interface.go, pkg/sync/copy.go, pkg/sync/interface.go, pkg/sync/sync.go, pkg/sync/sync_test.go
This package makes the exec package, and thus the sync package using it, agnostic of the platform. 
The platform is injected by the dependency injection system, depending on the `--run-on` flag.
Fixes #6160 
=> Make exec package agnostic of platform

docs/website/docs/overview/configure.md
This is useful in understanding when an environment variable can be used.
I thought about this while working on https://github.com/redhat-developer/odo/pull/6258, but chose to create a separate PR.
&mdash;
This is useful for https://github.com/redhat-developer/odo/pull/6258
=> Document in which version an environment variable controlling odo behavior appeared

scripts/check-gofmt.sh
/kind bug
`make validate` does not pass if run right after generating a local RPM Package using the `rpm-prepare.sh` and `rpm-local-build.sh` scripts.
The problem is that `check-gofmt.sh` picks Go files from the `dist/rpmbuild/BUILD/**/vendor` folder, e.g.:
```
$ ./scripts/rpm-prepare.sh
$ ./scripts/rpm-local-build.sh
$ make validate 
./scripts/check-gofmt.sh
gofmt ERROR - These files are not formated by gofmt:
./dist/rpmbuild/BUILD/openshift-odo-3.1.0-1/vendor/github.com/AlecAivazis/survey/v2/terminal/display_posix.go
./dist/rpmbuild/BUILD/openshift-odo-3.1.0-1/vendor/github.com/AlecAivazis/survey/v2/terminal/output.go
./dist/rpmbuild/BUILD/openshift-odo-3.1.0-1/vendor/github.com/AlecAivazis/survey/v2/terminal/runerea …
```
=> Exclude the 'dist' folder in 'check-gofmt.sh' script

Makefile
Adds new `release-bin` make target.
This is for the homebrew package, and it could be also used by another packaging system.
The problem is that currently, [odo-dev formulae ](https://github.com/Homebrew/homebrew-core/blob/master/Formula/odo-dev.rb) uses `make bin`, this is a problem because this build odo with dev Segment key. This means that MacOS users installing odo via homebrew don't show up in our production telemetry. 
new `make release-bin` uses prod Segment key and it should be used only in packaging systems.
=> add make release-bin target

.ibm/pipelines/kubernetes-tests.sh, .ibm/pipelines/nocluster-tests.sh, .ibm/pipelines/openshift-tests.sh, .ibm/pipelines/windows-test-script.ps1, Makefile, tests/helper/helper_generic.go, tests/helper/labels.go, tests/integration/cmd_analyze_test.go, tests/integration/cmd_devfile_init_test.go, tests/integration/cmd_devfile_registry_test.go, tests/integration/cmd_pref_config_test.go, tests/integration/interactive_init_test.go
/kind tests
This PR moves integration tests for commands not needing a cluster to a specific directory
so they can be executed separately, in an environment without any cluster.
Fixes partly #6237 
=> Isolate no cluster tests

pkg/init/init.go, pkg/init/interface.go, pkg/init/mock.go, pkg/odo/cli/init/init.go, tests/integration/interactive_init_test.go
/kind feature
Fixes #5465 
```
run `odo init` in interactive mode
odo init
```
=> display equivalent odo init command for odo init interactive

pkg/odo/cli/preference/view.go, pkg/preference/implem.go, pkg/registry/registry_test.go, tests/integration/cmd_devfile_registry_test.go
/kind bug
This PR resolves the inconsistency in output of registry list in command `odo preference view` and `odo preference view -o json`
Fixes #6205 
```
odo preference add registry CheRegistry https://che-devfile-registry.openshift.io
odo preference view 
odo preference view -o json
```
Order of registry list should be same in `odo preference view` `odo preference view -o json` with latest added registry on the top.
=> resolve inconsistent order of registries in preference view

pkg/registry/starter_project.go, tests/examples/source/devfiles/java/devfile-with-git-main-branch.yaml, tests/integration/cmd_devfile_init_test.go
=> Disable loading a single branch when getting git starter project

scripts/openshiftci-Nightly-SBO-tests.sh, scripts/openshiftci-periodic-tests.sh, scripts/openshiftci-presubmit-all-tests.sh
/kind bug
/kind tests
This PR fixes failing interop tests on 4.11/4.12.
Tests are failing as it doesn't contain changes from [PR](https://github.com/redhat-developer/odo/pull/6121) which was implemented on v2 branch.
Fixes #NA
=> fix login failure on interop tests with error: x509

Makefile
Modify installation of golangci-lint
- No use of binaries because of errors(1)
- Using -mod=mod for go install because of: https://github.com/golang/go/issues/54908
(1)
```
golangci-lint run ./... --timeout 15m
level=warning msg="[runner] Can't run linter goanalysis_metalinter: S1019: failed prerequisites: [(inspect@github.com/redhat-developer/odo/pkg/log/fidget, isgenerated@github.com/redhat-developer/odo/pkg/log/fidget): analysis skipped: errors in package: [/go/odo_1/pkg/log/fidget/spinner.go:26:2: could not import fmt (/usr/local/go/src/fmt/errors.go:7:8: could not import errors (/usr/local/go/src/errors/wrap.go:8:2: could not import internal/reflectlite (/usr/local/go/src/internal/reflectlite/swapper.go:8:2: could not import internal/goarch (-: could not load export data: cannot …
```
=> Debug validate errors on IBM Cloud

pkg/init/backend/flags.go, pkg/init/backend/flags_test.go, pkg/init/init.go, pkg/init/init_test.go, pkg/odo/cli/preference/view.go, pkg/odo/cli/preference/view_test.go, pkg/preference/implem.go, pkg/preference/mock.go, pkg/preference/preference.go, pkg/registry/registry.go, pkg/registry/registry_test.go, pkg/registry/utils.go
/kind bug
Fixes #6283 
```
$ odo preference add registry StageDevfileRegistry https://registry.stage.devfile.io
$ odo preference view                                                               
Preference parameters:
PARAMETER           VALUE           
ConsentTelemetry    false (default) 
Ephemeral                           
PushTimeout                         
RegistryCacheTime                   
Timeout                             
UpdateNotification                  
Devfile registries:
NAME                    URL …
```
=> fix to prioritize newly added registry

.gitignore, Makefile, scripts/openshiftci-presubmit-all-tests.sh
/kind tests
As we are want to start InterOP testing for v3, we need to start test reports generation.
Fixes #
=> InterOP: enable test report generation for tests

pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter_test.go, pkg/devfile/adapters/kubernetes/component/push.go, pkg/devfile/components.go, pkg/devfile/components_test.go, pkg/kclient/secrets.go, pkg/labels/labels.go, pkg/service/link.go, pkg/service/service.go, tests/examples/source/devfiles/nodejs/devfile-with-k8s-resource.yaml, tests/integration/cmd_add_binding_test.go, tests/integration/cmd_dev_debug_test.go, tests/integration/cmd_dev_test.go, tests/integration/cmd_remove_binding_test.go
/kind bug
/area dev
With this PR, `odo dev` now handles K8s component related changes to the Devfile. It will remove resources from the cluster that are not present in the local Devfile.
Fixes #5943
Fixes #6101
1.
```sh
odo init --devfile nodejs --name my-node-app --starter nodejs-starter
```
2. Replace the devfile.yaml with content below.
<details>
<summary>devfile.yaml</summary>
```yaml
commands:
- exec:
commandLine: npm install
component: runtime
group:
isDefault: true
kind: build
hotReloadCapable: false
workingDir: ${PROJECT_SOURCE}
id: install
- exec:
commandLine: npm start
component: runtime …
```
=> `odo dev` deletes remote resources not present in the Devfile

docs/website/docs/user-guides/advanced/deploy/_accessing_application.mdx, docs/website/docs/user-guides/advanced/deploy/_editing_devfile.mdx, docs/website/docs/user-guides/advanced/deploy/_running_deploy.mdx, docs/website/docs/user-guides/advanced/deploy/dotnet.md, docs/website/docs/user-guides/advanced/deploy/go.md, docs/website/docs/user-guides/advanced/deploy/java.md, docs/website/docs/user-guides/advanced/deploy/nodejs.md
This PR updates the doc with latest `odo describe` output.
Fixes #6319 
=> Update odo describe output in docs

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bump odo version to v3.3.0

pkg/dev/podmandev/pod.go, pkg/dev/podmandev/pod_test.go
=> Set labels for component on podman

docs/website/docs/user-guides/quickstart/dotnet.md, docs/website/docs/user-guides/quickstart/go.md, docs/website/docs/user-guides/quickstart/nodejs.md
=> Make remaining Quickstart docs consistent

pkg/dev/podmandev/pod.go, pkg/dev/podmandev/pod_test.go, pkg/libdevfile/generator/component.go
=> odo dev on podman: Add support for devfile volume

tests/integration/interactive_init_test.go
/kind tests
This test fails on Windows because of the terminal emulator behaviour.
Fixes #6327
=> Disable flaky test on Windows

pkg/config/config.go, pkg/config/config_test.go, pkg/segment/segment_test.go
/kind bug
/area testing
I just ran into the issue below, where our unit tests might fail depending on the system environment variables:
```
$ GLOBALODOCONFIG=/dev/null PODMAN_CMD=docker go test -race github.com/redhat-developer/odo/pkg/config/
--- FAIL: TestDefaultValues (0.00s)
config_test.go:30: default value for "PodmanCmd" should be "podman" but is "docker"
config_test.go:44: value for non specified env var "Globalodoconfig" should be nil but is "/dev/null"
config_test.go:44: value for non specified env var "Globalodoconfig" should be nil but is "/dev/null"
FAIL
FAIL    github.com/redhat-developer/odo/pkg/config      0.008s
FAIL
```
I think unit tests should not depend on the system environment, as this can cause …
=> Fix potential unit tests failures caused by envconfig relying on the system environment

Makefile, tests/e2escenarios/e2e_devfile_test.go, tests/e2escenarios/e2e_test.go, tests/helper/helper_dev.go, tests/helper/labels.go, tests/integration/cmd_add_binding_test.go, tests/integration/cmd_delete_test.go, tests/integration/cmd_describe_component_test.go, tests/integration/cmd_describe_list_binding_test.go, tests/integration/cmd_dev_debug_test.go, tests/integration/cmd_dev_test.go, tests/integration/cmd_devfile_deploy_test.go, tests/integration/cmd_devfile_list_test.go, tests/integration/cmd_logs_test.go, tests/integration/cmd_remove_binding_test.go
/kind tests
This PR defines a new Makefile entry 
```
make test-integration-podman
```
that will run 5 integration tests featuring podman integration.
A system with a podman command line is necessary to run these tests.
Fixes partially #6236 
=> Integration tests for odo dev running on podman 

.ibm/pipelines/windows-test-script.ps1
/kind bug
/kind tests
This PR adds the check for exit code in windows tests for no-cluster tests
Fixes #6342
=> fix: add exit code check for no-cluster tests

pkg/init/asker/asker.go, pkg/init/backend/interactive.go, tests/integration/interactive_init_test.go
/kind bug
This PR fixes downloading of the wrong devfile-starter when using `odo init` in interactive mode
Fixes #6195 
=> Downloading wrong starter project when using `odo init`

.ibm/pipelines/kubernetes-tests.sh, tests/examples/source/devfiles/nodejs/devfile-with-volumes.yaml, tests/examples/source/devfiles/springboot/devfile-registry.yaml, tests/examples/source/devfiles/springboot/devfile-with-missing-projectType-and-language-metadata.yaml, tests/examples/source/devfiles/springboot/devfile-with-missing-projectType-metadata.yaml, tests/examples/source/devfiles/springboot/devfile.yaml, tests/examples/source/java-quarkus/devfile.yaml, tests/integration/cmd_dev_test.go
/kind tests
Using persistent volumes during integration tests fail because of missing permissions.
This PR:
- modifies the PR to make the devfile volumes ephemeral.
- tests the non-ephemeral volumes on OpenShift only
- disables the e2e tests on Kubernetes (the e2e tests are using the Devfiles from the registry, defining persistent volumes)
=> Integration tests: Declare devfile volumes as ephemeral

tests/integration/cmd_namespace_test.go
/kind bug
/area testing
I noticed repeating issues with this test on a few PRs.
For some reason, `odo list namespaces/projects` would contain the current test namespace, but the subsequent `odo list namespaces/projects -o json` would no longer contain this namespace.
After taking a look at [Gomega doc](https://onsi.github.io/gomega/#category-3-making-assertions-eminem-the-function-passed-into-codeeventuallycode), this PR changes the test so that it only relies on what is actually needed for the test and uses expectations on the JSON output only.
&mdash;
=> Fix flaky behavior with "list namespaces/projects -o json" integration tests

pkg/odo/cli/list/namespace/namespace.go
=> Fix completion error when command is empty

pkg/odo/cli/add/binding/binding.go, pkg/odo/cli/alizer/alizer.go, pkg/odo/cli/build_images/build_images.go, pkg/odo/cli/create/namespace/namespace.go, pkg/odo/cli/delete/component/component.go, pkg/odo/cli/delete/namespace/namespace.go, pkg/odo/cli/deploy/deploy.go, pkg/odo/cli/describe/binding.go, pkg/odo/cli/describe/component.go, pkg/odo/cli/dev/dev.go, pkg/odo/cli/init/init.go, pkg/odo/cli/list/binding/binding.go, pkg/odo/cli/list/component/list.go, pkg/odo/cli/list/list.go, pkg/odo/cli/list/namespace/namespace.go, pkg/odo/cli/list/services/services.go, pkg/odo/cli/login/login.go, pkg/odo/cli/logout/logout.go, pkg/odo/cli/logs/logs.go, pkg/odo/cli/preference/add/registry.go, pkg/odo/cli/preference/remove/registry.go, pkg/odo/cli/preference/set.go, pkg/odo/cli/preference/unset.go, pkg/odo/cli/preference/view.go, pkg/odo/cli/registry/registry.go, pkg/odo/cli/remove/binding/binding.go, pkg/odo/cli/set/namespace/namespace.go, pkg/odo/cli/telemetry/telemetry.go, pkg/odo/cli/version/version.go, pkg/odo/genericclioptions/runnable.go
=> Do not call LogErrorAndExit but return err in GenericRun

pkg/kclient/all.go
/kind bug
This PR lower log levels for the kclient.GetAllResourcesFromSelector fucntion.
These levels have been imported from the original source code (https://github.com/ahmetb/kubectl-tree) but are not correct for odo level policy, and they spam the tests output.
=> Lower log level for kclient.GetAllResourcesFromSelector

pkg/dev/kubedev/kubedev.go, pkg/dev/podmandev/cleanup.go, pkg/dev/podmandev/podmandev.go, pkg/dev/podmandev/reconcile.go, pkg/odo/genericclioptions/clientset/clientset.go, pkg/watch/noop_watcher.go, pkg/watch/watch.go, tests/integration/cmd_dev_test.go
=> Sync files on Podman

docs/website/docs/command-reference/json-output.md, docs/website/docs/command-reference/list-services.md, pkg/api/bindable_service.go, pkg/odo/cli/list/services/services.go, tests/integration/cmd_list_services_test.go
/kind bug
Thos PR removes the `group` field containing the group of the resource, and replaces it with an `apiVersion` field, containing the `group/version` information.
```
$ odo list services -o json -A
{
"bindableServices": [
{
"name": "cluster-sample",
"namespace": "cmd-describe-list-binding-test549cmw",
"kind": "Cluster",
"apiVersion": "postgresql.k8s.enterprisedb.io/v1",
"service": "cluster-sample/Cluster.postgresql.k8s.enterprisedb.io/v1"
}
]
}
```
Fixes #6347 
=> Replace group by apiVersion in odo list services output

pkg/odo/cli/remove/binding/binding.go, pkg/odo/genericclioptions/clientset/clientset.go, tests/integration/cmd_namespace_test.go
/kind bug
Fixes #6316 
`odo list namespace` no longer panics, instead throws an appropriate error.
```sh
KUBECONFIG=/dev/null odo list namespace
```
```sh
$ KUBECONFIG=/dev/null odo list namespace
✗  
Please ensure you have an active kubernetes context to your cluster. 
Consult your Kubernetes distribution's documentation for more details.
Error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```
`odo remove binding` still works when the cluster is inaccessible. The [test](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-open …
=> Fix: Panic when running odo list namespaces without an active Kubernetes context

docs/website/docs/command-reference/init.md, docs/website/docs/command-reference/json-output.md, docs/website/docs/user-guides/quickstart/_creating_app.mdx, pkg/alizer/alizer.go, pkg/alizer/interface.go, pkg/alizer/mock.go, pkg/api/analyze.go, pkg/init/backend/alizer.go, pkg/init/backend/alizer_test.go, pkg/init/backend/applicationports.go, pkg/init/backend/applicationports_test.go, pkg/init/backend/flags.go, pkg/init/backend/flags_test.go, pkg/init/backend/interactive.go, pkg/init/backend/interactive_test.go, pkg/init/backend/interface.go, pkg/init/backend/mock.go, pkg/init/init.go, pkg/init/init_test.go, pkg/init/interface.go, pkg/init/mock.go, pkg/libdevfile/libdevfile.go, pkg/libdevfile/libdevfile_test.go, pkg/odo/cli/alizer/alizer.go, pkg/odo/cli/init/init.go, pkg/testingutil/devfile.go, tests/integration/interactive_init_test.go
/kind feature
/area init
This bumps the Alizer library to a more recent commit, in order to benefit from automatic port detection when running `odo init` interactively from a directory with source code.
More details and context in #5863
Fixes #5863 
- [All Quickstart Guides](https://deploy-preview-6365--odo-docusaurus-preview.netlify.app/docs/user-guides/quickstart/)
- [odo init interactive mode](https://deploy-preview-6365--odo-docusaurus-preview.netlify.app/docs/command-reference/init#interactive-mode)
- [odo analyze -o json](https://deploy-preview-6365--odo-docusaurus-preview.netlify.app/docs/command-reference/json-output#odo-analyze--o-json) 
**How to …
=> Support Alizer-based automatic port detection with odo init interactive mode

scripts/ansible/kubernetes-cluster/operators-kubernetes.yml, scripts/ansible/kubernetes-cluster/operators-openshift.yml, scripts/configure-cluster/common/setup-operators.sh, tests/examples/manifests/bindablekind-instance.yaml, tests/examples/source/devfiles/go/cluster.yaml
/kind tests
This PR updates the bindable kind instance to work with OCP 4.12, it also updates the version channel to use stable-v1.18 for postgres.
Fixes #6334 
=> updating bindable kind instance

pkg/odo/cli/feature/doc.go, pkg/odo/cli/feature/features.go, pkg/odo/genericclioptions/runnable.go
=> Delay the display of warnings related to experimental features

docs/website/docs/user-guides/advanced/deploy/dotnet.md, docs/website/docs/user-guides/advanced/deploy/go.md, docs/website/docs/user-guides/advanced/deploy/java.md, docs/website/docs/user-guides/advanced/deploy/nodejs.md
/kind feature
This PR adds complete Devfile to all the advanced guides.
Fixes #6337 
[Nodejs](https://deploy-preview-6388--odo-docusaurus-preview.netlify.app/docs/user-guides/advanced/deploy/nodejs#step-4-run-the-odo-deploy-command), [Go](https://deploy-preview-6388--odo-docusaurus-preview.netlify.app/docs/user-guides/advanced/deploy/go#step-4-run-the-odo-deploy-command), [Java](https://deploy-preview-6388--odo-docusaurus-preview.netlify.app/docs/user-guides/advanced/deploy/java#step-4-run-the-odo-deploy-command), [Dotnet](https://deploy-preview-6388--odo-docusaurus-preview.netlify. …
=> Add complete devfiles to advanced guides

.ibm/pipelines/openshift-unauth-tests.sh, Makefile, tests/helper/helper_cli.go, tests/helper/helper_generic.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/helper/labels.go, tests/integration/cmd_analyze_test.go, tests/integration/cmd_describe_component_test.go, tests/integration/cmd_devfile_build_images_test.go, tests/integration/cmd_devfile_init_test.go, tests/integration/cmd_devfile_list_test.go, tests/integration/cmd_devfile_registry_test.go, tests/integration/cmd_namespace_test.go, tests/integration/cmd_pref_config_test.go, tests/integration/cmd_remove_binding_test.go, tests/integration/generic_test.go, tests/integration/interactive_init_test.go
/kind tests
Helps test #6379
Run the same tests with NoCluster and with Unauth label.
=> Test with OpenShift cluster non authenticated

pkg/odo/cli/describe/component.go, pkg/odo/cli/errors/errors.go, tests/integration/cmd_describe_component_test.go
/kind bug
This PR makes `odo describe component` display a warning (in non-json output mode) when an error occurs when trying to get ingresses/routes, and not fail.
For the moment, is warning is not returned to json output, the error is just ignored.
Fixes #6379 
```
$ odo logout
$ odo describe component 
⚠  failed to get ingresses/routes: ingresses.networking.k8s.io is forbidden: User "system:anonymous" cannot list resource "ingresses" in API group "networking.k8s.io" in the namespace "prj3"
Name: empty
Display Name: Go Runtime
Project Type: Go
Language: Go
Version: 1.0.2
Description: Go is an open …
```
=> Display a warning when connection to cluster fails

tests/integration/interactive_add_binding_test.go
/kind tests
This PR fixes test Flake of odo interactive mode
- [It] should error out if service is not found in the namespace selected
Fixes #6390
=> Flake odo add binding in interactive doest show namespace recently created

docs/website/docs/command-reference/json-output.md, docs/website/docs/command-reference/registry.md, docs/website/docs/user-guides/quickstart/quickstart.md, pkg/api/registry.go, pkg/odo/cli/registry/registry.go, pkg/registry/registry.go, pkg/registry/registry_test.go, tests/integration/cmd_devfile_registry_test.go
/kind feature
/area registry
This PR fetches and displays the Devfile Stack versions in the "odo registry" output (both human-readable and JSON).
As discussed in the linked issue, it does so by first querying (using the Devfile library) the `/v2index` registry endpoint (which should expose a list of stack versions), and falls back to the `/index` endpoint if the `/v2index` is not available.
See https://github.com/redhat-developer/odo/issues/6314 for more context.
For backward compatibility, the `Version` and `Starter Projects` fields have not been removed. Just like before, they are representing the version and starter projects of the default Stack version.
Fixes #6314
**PR acceptance …
=> Show Devfile Stack versions in "odo registry" output

.github/workflows/issue-management.yaml
/kind feature
This adds a job to the GH issue management Workflow, enabling a one-way sync from the issue priority label to the priority field in the Project.
This way, we can keep prioritizing our issues with the `priority/*` labels; and this workflow, once triggered, will take care of updating the Project field for that issue accordingly.
I initially wanted also to sync the other way, but I could not find a way yet to trigger a workflow based on a field update in the Project item.
NOTES:
- once a `priority/*` label is added to the issue, the corresponding Priority field is updated accordingly
- if the issue already had a `priority/*` label and a new `priority/*` label is added, that newly-added label is used to set …
=> Set Priority field in GitHub Project item based on the 'priority/*' label on the issue

scripts/openshiftci-presubmit-all-tests.sh
/kind test
InterOP tests uses  `scripts/openshiftci-presubmit-all-tests.sh` script to run tests, which is failing due to copy of artifact as it's handled differently on their side.
This PR adds a check if ARTIFACT_DIR var is not provided, it will not copy tests result files
Fixes #NA
=> copy aritifacts only if ARTIFACT_DIR var is exposed

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bump version to 3.4.0

.github/workflow-data/release-management/blog-post-footer.tpl.md, .github/workflow-data/release-management/blog-post-header.tpl.md, .github/workflow-data/release-management/pr.tpl.md, .github/workflows/issue-management.yaml, .github/workflows/release-management.yaml
/kind feature
In preparation for the upcoming release, I'm adding a new Workflow to automate as much as possible what we can automate.
When a new Release is created on GitHub (it can be a pre-release), this Workflow will take care of creating a draft PR with the following changes:
- Generates the release notes and adds them to a new blog post file
- Updates the `build/VERSION` file
- Updates the installation page with the new version
We still need to review this new PR (and potentially update at least the blog post), but that should be a good starting point.
Fixes #6386 
Example of …
=> Automate release process (GitHub part)

pkg/init/init.go, tests/integration/interactive_deploy_test.go, tests/integration/interactive_dev_test.go, tests/integration/interactive_init_test.go
/kind bug
/area init
If there is no match from Alizer, odo should ask users to select a Devfile manually, similarly to how it is done when `odo init` is executed in the empty directory.
So instead of exiting right away in such cases, this PR makes `odo` use the interactive backend of `odo init` as a fallback. This is applicable to all places where Devfile selection happens:
- `odo init` from a directory with source code and no Devfile
- `odo dev` from a directory with source code and no Devfile
- `odo deploy` from a directory with source code and no Devfile
Fixes #6364
See …
=> Fallback to interactive mode if there is no match from Alizer when initializing a component

docs/website/docs/development/architecture/how-odo-works.md, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/labels/labels.go, tests/integration/cmd_dev_test.go
=> Enable use of ImageStreams on OpenShift

cmd/odo/help_test.go, pkg/odo/cli/add/add.go, pkg/odo/cli/alizer/alizer.go, pkg/odo/cli/build_images/build_images.go, pkg/odo/cli/completion/completion.go, pkg/odo/cli/create/create.go, pkg/odo/cli/create/namespace/namespace.go, pkg/odo/cli/delete/delete.go, pkg/odo/cli/delete/namespace/namespace.go, pkg/odo/cli/deploy/deploy.go, pkg/odo/cli/describe/describe.go, pkg/odo/cli/dev/dev.go, pkg/odo/cli/init/init.go, pkg/odo/cli/list/component/list.go, pkg/odo/cli/list/list.go, pkg/odo/cli/login/login.go, pkg/odo/cli/logout/logout.go, pkg/odo/cli/logs/logs.go, pkg/odo/cli/preference/add/add.go, pkg/odo/cli/preference/preference.go, pkg/odo/cli/preference/remove/remove.go, pkg/odo/cli/registry/registry.go, pkg/odo/cli/remove/remove.go, pkg/odo/cli/set/namespace/namespace.go, pkg/odo/cli/set/set.go, pkg/odo/cli/version/version.go, pkg/odo/util/cmdutils.go
/kind bug
This PR adds the PREFERNECE dependency to `odo version`, and creates a CommandGroup abstraction to avoid this error occurs again.
`odo version` can use the Timeout value defined in the odo preferences, but this value were never taken into account, because the PREFERENCE dependency were overwritten when setting the command group.
Fixes #6417
=> Fix preference not taken into account for `odo version`

tests/helper/component_cluster.go, tests/helper/component_interface.go, tests/helper/component_podman.go, tests/helper/helper_dev.go, tests/integration/cmd_dev_test.go
/kind tests
Fixes partially #6416 
=> Add more tests for Podman + write Component abstraction for integration tests

docs/website/docs/user-guides/advanced/experimental-mode.md, pkg/log/status.go, pkg/odo/cli/feature/doc.go, pkg/odo/cli/feature/experimental.go, pkg/odo/cli/feature/features.go, pkg/odo/cli/feature/features_test.go, pkg/odo/genericclioptions/runnable.go, tests/helper/helper_experimental.go, tests/integration/generic_test.go
This fixes the issue of having this warning message displayed for a specific feature that might not be actually used by the user.
Instead, we are now displaying a more generic and feature-agnostic warning message once we detect that the experimental mode is enabled.
Fixes #6381 
The experimental mode warning message should now be more visible, and not dependent on the experimental feature:
Before:
```
$ ODO_EXPERIMENTAL_MODE=t odo version --client
Experimental mode enabled for flag: --run-on. Use at your own risk. More details on …
```
=> Display a generic Experimental mode warning message when this mode is enabled

docs/website/docs/command-reference/init.md, pkg/alizer/alizer.go, pkg/alizer/alizer_test.go, pkg/alizer/interface.go, pkg/alizer/mock.go, pkg/api/analyze.go, pkg/init/asker/asker.go, pkg/init/asker/interface.go, pkg/init/asker/mock.go, pkg/init/backend/alizer.go, pkg/init/backend/alizer_test.go, pkg/init/backend/flags.go, pkg/init/backend/interactive.go, pkg/init/init.go, pkg/odo/cli/alizer/alizer.go, pkg/odo/cli/init/init.go, pkg/registry/registry.go, tests/integration/cmd_devfile_init_test.go, tests/integration/interactive_deploy_test.go, tests/integration/interactive_dev_test.go, tests/integration/interactive_init_test.go
/kind feature
This PR allows fetching a specific devfile stack version.
Fixes #6315
Try to fetch a Go/Springboot/Python devfile and select the version. Test with ACs described in https://github.com/redhat-developer/odo/issues/6315#issue-1452906773.
=> Allow fetching specific devfile stack version

docs/website/docs/command-reference/init.md
/kind bug
This PR adds a missing example to the init command reference doc.
https://odo.dev/docs/command-reference/init#fetch-devfile-from-any-registry-of-the-list is missing the example.
Fixes #
=> Add missing example to init command reference doc

pkg/component/delete/delete.go, pkg/component/delete/delete_test.go, pkg/component/delete/interface.go, pkg/component/delete/mock.go, pkg/dev/kubedev/cleanup.go, pkg/dev/podmandev/cleanup.go, pkg/kclient/mock_Client.go, pkg/odo/cli/cli.go, pkg/odo/cli/delete/component/component.go, pkg/odo/cli/delete/component/component_test.go, pkg/odo/cli/delete/delete.go, pkg/odo/genericclioptions/clientset/clientset.go, pkg/podman/interface.go, pkg/podman/mock.go, pkg/podman/podman.go, tests/helper/component_cluster.go, tests/helper/component_interface.go, tests/helper/component_podman.go, tests/integration/cmd_delete_test.go, tests/integration/cmd_dev_test.go
/kind feature
`odo delete component` support for podman when devfile is present
(support for `--name` will be done in a separate PR)
Fixes partially #6296
=> odo delete component deletes components running on podman

docs/website/docs/command-reference/list-services.md, docs/website/docs/command-reference/set-namespace.md, docs/website/docs/user-guides/advanced/experimental-mode.md
=> Make remaining docs consistent

pkg/component/delete/delete.go, pkg/component/delete/delete_test.go, pkg/component/delete/interface.go, pkg/component/delete/mock.go, pkg/odo/cli/delete/component/component.go, pkg/odo/cli/delete/component/component_test.go, tests/integration/cmd_delete_test.go
/kind feature
`odo delete component` on podman with `--name`
Fixes #6296 
=> odo delete component on podman with --name

pkg/odo/cli/add/binding/binding.go, pkg/odo/cli/remove/binding/binding.go
=> Fix typo in odo remove binding

Dockerfile.rhel, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bump to v3.5.0

docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx
/kind bug
This PR fixes a bug with `odo dev` output for Java springboot quickstart.
Fixes #
=> Fix odo init output in java quickstart guide

docs/website/docs/user-guides/quickstart/java.md
It looks like the default "Project" on [1] is now "Gradle - Groovy" (it used to be Maven),
but there is no Devfile usable with a SpringBoot Gradle project.
Without this, "odo init" prompts to select the "java-openliberty-gradle" Devfile,
which won't work because it executes tasks specific to OpenLiberty.
And even if we manually select the "java-springboot" Devfile,
it won't work out of the box because it requires Maven and there is
no "pom.xml" in the project generated by the Spring Initializr.
[1] https://start.spring.io/
&mdash;
=> Tell readers of the QuickStart Guide to select "Maven" on Spring Initializr

pkg/exec/exec.go
/kind bug
When running `odo dev -v2`, output of commands are displayed on stdout, and makes some tests fail because of these unexpected data in output. 
Fixes #
=> Do not output log to stdout

pkg/libdevfile/libdevfile.go, pkg/libdevfile/libdevfile_test.go, pkg/portForward/portForward.go, tests/examples/source/devfiles/nodejs/devfile-no-endpoint.yaml, tests/integration/cmd_dev_test.go
=> Make odo dev work if no endpoint is defined

cmd/odo/help_test.go, docs/website/docs/command-reference/dev.md, docs/website/docs/user-guides/advanced/connecting-a-service.md, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx, pkg/odo/cli/deploy/deploy.go, pkg/odo/cli/dev/dev.go
=> Change wording for dev/deploy

pkg/component/delete/delete.go, pkg/component/delete/delete_test.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/kclient/errors.go, pkg/kclient/pods.go, pkg/platform/errors.go, pkg/podman/component.go, pkg/podman/inspect.go, pkg/podman/logs.go, pkg/podman/pods.go, tests/examples/source/devfiles/nodejs/devfileCompositeBuildRunDebugInMultiContainersAndSharedVolume.yaml, tests/helper/component_cluster.go, tests/integration/cmd_dev_debug_test.go, tests/integration/cmd_dev_test.go, tests/integration/interactive_dev_test.go
=> [podman] show logs when command fails

pkg/dev/podmandev/pod.go, pkg/dev/podmandev/pod_test.go, pkg/dev/podmandev/reconcile.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/libdevfile/libdevfile.go, pkg/libdevfile/libdevfile_test.go, pkg/portForward/interface.go, pkg/portForward/portForward.go, tests/examples/source/devfiles/nodejs/devfile-with-debugrun.yaml, tests/examples/source/devfiles/nodejs/devfile-with-multiple-endpoints.yaml, tests/examples/source/devfiles/nodejs/project-with-multiple-endpoints/package.json, tests/examples/source/devfiles/nodejs/project/package.json, tests/integration/cmd_dev_debug_test.go, tests/integration/cmd_dev_test.go
=> Port-forward Debug endpoints only when running `odo dev` with `--debug`

tests/examples/source/devfiles/nodejs/devfile-with-MR-CL-CR-modified.yaml, tests/examples/source/devfiles/nodejs/devfile-with-MR-CL-CR.yaml, tests/examples/source/devfiles/springboot/devfile-registry.yaml, tests/helper/component_cluster.go, tests/helper/component_interface.go, tests/helper/component_podman.go, tests/integration/cmd_dev_test.go
- prepare test dev.odo.push.path - not implemented yet on Podman
- Skip 'should create vcs-uri annotation for the deployment when running odo dev' on Podman
- [Test cpu/memory limit/resources on podman/cluster](https://github.com/redhat-developer/odo/pull/6482/commits/1ffb48ed3e941bd7f540dccb43b4ac4252009c84)
- [WIP add GetPodDef implementation for cluster](https://github.com/redhat-developer/odo/pull/6482/commits/dcb788fd14305bf5d274d27d666b98890dcc1602)
- [Convert springboot compare lo](https://github.com/redhat-developer/odo/pull/6482/commits/40a4f04a8f2404f0ed286b1af7b5280efdf7e386)[cal and remote files test for podman](https://github.com/redhat-developer/odo/pull/6482/commits/40a4f04a8f2404f0ed286b1af7b5280efdf7e386)
- [Fix namespace instead of component …
=> Add more tests for odo dev on Podman (2)

tests/examples/source/devfiles/springboot/devfile.yaml, tests/helper/helper_dev.go, tests/integration/cmd_dev_test.go
=> Add more tests for odo dev on Podman (3)

docs/website/docs/command-reference/docs-mdx/init/devfile_from_any_registry_output.mdx, docs/website/docs/command-reference/docs-mdx/init/devfile_from_specific_registry_output.mdx, docs/website/docs/command-reference/docs-mdx/init/devfile_from_url_output.mdx, docs/website/docs/command-reference/docs-mdx/init/latest_versioned_devfile_output.mdx, docs/website/docs/command-reference/docs-mdx/init/registry_list_output.mdx, docs/website/docs/command-reference/docs-mdx/init/registry_output.mdx, docs/website/docs/command-reference/docs-mdx/init/versioned_devfile_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/create_namespace_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/create_project_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx, pkg/init/backend/interactive.go, tests/documentation/command-reference/doc_command_reference_init_test.go, tests/documentation/user-guides/doc_user_guides_quickstart_test.go
=> Make doc tests pass

pkg/util/file_indexer.go, pkg/util/file_indexer_test.go
/kind bug
This PR allows to sync files with special characters.
Fixes #6503
1. Clone https://github.com/devfile/devfile-web
2. `odo init --devfile nodejs-react --name devfile-web`
3. `odo dev`
=> Fix: odo dev unable to sync files with name containing special characters

pkg/odo/genericclioptions/runnable.go, pkg/segment/context/context.go, tests/integration/cmd_dev_test.go, tests/integration/cmd_devfile_deploy_test.go
/kind feature
Fixes partially #6508
=> Set experimental mode in telemetry

.github/workflows/podman-test.yaml, Makefile, pkg/dev/podmandev/pod.go, pkg/dev/podmandev/pod_test.go, pkg/dev/podmandev/reconcile.go, pkg/podman/podman.go, tests/helper/helper_generic.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/helper/helper_podman.go, tests/helper/labels.go, tests/helper/odo_utils.go, tests/integration/cmd_dev_test.go
/kind tests
/area testing
Unblocks #6485 by isolating each Podman test under a dedicated namespace. See https://github.com/redhat-developer/odo/pull/6485#issuecomment-1384068344
Note that even with isolated namespaces, two Podman containers cannot have the same name (I guess they share the same underlying `storage.conf`). So #6504 made sure to use random component names in our tests.
With proper isolation, we can run those Podman tests in parallel. This is the tentative done in [`66ed98f` (#6499)](https://github.com/redhat-developer/odo/pull/6499/commits/66ed98fe0ee0e1ec5b42d35650c54615bc40ae96), …
=> Isolate Podman tests in namespaces

pkg/dev/podmandev/cleanup.go, pkg/dev/podmandev/reconcile.go, pkg/podman/podman.go, tests/integration/cmd_dev_test.go
/kind bug
This PR ensures `odo dev` on podman exits with actual failure from podman and also cleans up pod if it was created.
Fixes #6487 
1. `odo init --devfile nodejs --starter nodejs-starter --name my-nodejs-app`
2. `sed -i "s/registry.access.redhat.com\/ubi8\/nodejs-16:latest/adsffdfe/" devfile.yaml`
3. `ODO_EXPERIMENTAL_MODE=true odo dev --platform=podman`
For 6501
1. `export PODMAN_CMD=echo`
2. `ODO_EXPERIMENTAL_MODE=true odo dev --platform=podman`
=> Display error message when odo dev fails on podman and clean resources

pkg/sync/sync_test.go, pkg/util/file_indexer_test.go, pkg/util/util_test.go
/kind tests
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := ioutil.TempDir("", "")
if e != nil {
t.Fatal(e)
}
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```
=> test: use `t.TempDir` to create temporary test directory

.github/workflows/podman-test.yaml, Makefile
/kind tests
Stop containers, to make the ginkgo process terminate
Fixes #6532
=> Stop containers after Podman tests

.github/workflows/podman-test.yaml, tests/integration/cmd_delete_test.go
/kind tests
/area testing
Otherwise, "odo delete component --running-in $mode" might leave some resources running
(on Podman especially).
For example, the Podman test that runs "delete component --running-in deploy"
(after starting and killing a Dev Session abruptly) might leave those Dev resources running.
This has been alleviated in CI via 9ebf766 by ensuring Ginkgo does not hang indefinitely and
by deleting those leftover resources.
But the issue was still persisting locally.
=> Make sure to delete the component resources after each "delete component" test spec

tests/e2escenarios/e2e_test.go, tests/examples/source/devfiles/go/router/router.go, tests/helper/component_cluster.go, tests/helper/component_interface.go, tests/helper/component_podman.go, tests/helper/helper_cli.go, tests/helper/helper_component.go, tests/helper/helper_dev.go, tests/helper/helper_generic.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/integration/cmd_dev_debug_test.go, tests/integration/cmd_dev_test.go
/kind tests
/area testing
This is an attempt to fix the recurring issues we have been seeing with E2E tests.
In a nutshell, it waits for the application to be actually running in the container before sending a request to the local port created by odo.
Otherwise, sending a request to the local port too early sometimes causes the port forwarding to be automatically restarted (with new random ports because we are running `odo dev` with `--random-ports`) (#6013)
Fixes #6463 
=> Fix potential issues with E2E tests

pkg/odo/cli/logs/logs.go, pkg/podman/logs.go, pkg/podman/pods.go, tests/helper/helper_logs.go, tests/integration/cmd_logs_test.go
=> Implement odo logs on podman

tests/helper/helper_cli.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/integration/cmd_dev_test.go, tests/integration/cmd_devfile_deploy_test.go
/kind tests
On OpenShift platforms used by prow tests, oc version does not return the OCP version. 
The tests get the value from oc/kubectl version to compare this value with the one found by odo
Fixes #
=> Test version upon oc/kubectl version

.ibm/images/Dockerfile
/kind tests
`oc` versions v4.7 and v4.11 use different information from the cluster to retrieve the OpenShift cluster version.
In odo, we send platform information to telemetry, and get information from the cluster the same way oc v4.11 is getting it.
In the tests, we currently compare the output of `oc version` v4.7 with what odo get, to check that we are sending the good version.
Unfortunalety, in some circumstances, oc v4.7 and v4.11 return different version.
This makes our tests fail in these circumstances.
Updating oc to version v4.11 for the tests should fix the problem.
Failing test: https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-6545-openshift …
=> Use oc v4.11 instead v4.7 to fix version comparison

docs/website/blog/3.0.0-GA-blog.md
This sets an explicit date for the v3 GA blog post, which does not follow the `YYYY-MM-DD-$myBlogTitle.md` file naming pattern. See https://docusaurus.io/docs/blog#blog-post-date.
Otherwise, in some circumstances, Docusaurus would list this post as the first one on the list.
It happened to me while working on #6564 and #6562.
&mdash;
=> Set the date for the v3 GA blog post

docs/website/.gitignore, docs/website/devfile.yaml, docs/website/package.json
While working on #6562, I thought it would be interesting to eat our own food when working on the website.
I wanted to iterate locally with odo and Podman, hence this PR.
We can improve the `devfile.yaml` later on to cover more things like outer-loop.
&mdash;
```
cd docs/website
ODO_EXPERIMENTAL_MODE=t odo dev --platform=podman
```
=> Dogfood odo for working on the website

pkg/binding/binding.go, pkg/kclient/errors.go, pkg/odo/cli/describe/component.go, pkg/odo/cli/dev/dev.go, pkg/odo/cli/list/component/list.go, pkg/odo/genericclioptions/clientset/clientset.go, pkg/podman/errors.go, pkg/podman/podman.go, tests/integration/cmd_describe_component_test.go, tests/integration/cmd_dev_test.go
/kind bug
Fixes #6501 
1. `export PODMAN_CMD=echo`
2. `odo dev --platform podman -v 2`
=> Log error when podman client cannot be initialized

docs/website/docs/user-guides/quickstart/docs-mdx/odo_dev_description.mdx
The sample output displayed at the end of the Quickstart Guides no longer matches the port number we are instructing users to reach in order to access the application.
This PR changes the value displayed and adds an additional clarification line.
&mdash;
=> Fix the port value (20001) in the quickstart guides

pkg/component/delete/delete.go, pkg/component/exec_handler.go, pkg/dev/podmandev/reconcile.go, pkg/devfile/adapters/kubernetes/component/adapter.go, tests/integration/cmd_delete_test.go
/kind bug
/area UX
/area dev
See https://github.com/redhat-developer/odo/issues/6573.
For the example provided in the issue description, this PR changes the `odo dev` output from:
```
✓  Executing copy-galleon command "cp -Rf /opt/jboss/container/wildfly/s2i/galleon/galleon-m2-repository /tmp/. && cp -Rf /opt/wildfly /tmp/." on container "wildfly" [960ms]
✓  Executing provision-server command "/usr/local/s2i/assemble && cp -Rf $JBOSS_HOME ." on container "wildfly" [8s]
✓  Executing store-config command "mkdir $STANDALONE_RESTORE && cp -f $JBOSS_HOME/standalone/configuration/standalone.xml $STANDALONE_RESTORE/standalone.xml" on container "wildfly" [47ms]
```
to
```
✓  Executing post-start command in container (command: …
```
=> Fix UX inconsistency when handling commands bound to events

docs/website/docs/user-guides/advanced/pushing-specific-files.md, docs/website/versioned_docs/version-2.5.0/tutorials/using-devfile-odo.dev.push.path-attribute.md, pkg/dev/podmandev/podmandev.go, pkg/devfile/adapters/attributes.go, pkg/devfile/adapters/attributes_test.go, pkg/devfile/adapters/kubernetes/component/adapter.go, tests/examples/source/devfiles/nodejs/devfile-with-remote-attributes.yaml, tests/integration/cmd_dev_debug_test.go, tests/integration/cmd_dev_test.go
Co-authored-by: @valaparthvi 
/kind feature
This adds support for command-level attributes prefixed with `dev.odo.push.path:` on Podman. See #6492 and [the doc](https://deploy-preview-6576--odo-docusaurus-preview.netlify.app/docs/user-guides/advanced/pushing-specific-files) for more context.
While working on this issue, we also found out that `odo` was always picking the attributes of the `run` command, regardless of whether users were running in Debug or not. This PR also fixes that behavior, by making sure we pick the right command attributes.
Fixes #6492 
See …
=> Support `dev.odo.push.path:*` attributes on Podman

.github/workflows/build-push-ibm-image.yaml
/area testing
For some context, while working on #6586, I wanted to make sure that updating the Go version in the Dockerfile will not break the image (this happened already in the past - see https://github.com/redhat-developer/odo/pull/6166#discussion_r1016623089).
I checked manually but thought it would be nice to have our Workflow check that instead.
So this PR allows us to test that the image can be built successfully on PRs as well.
Pushing the image to the registry is run only upon a push on the `main` branch.
&mdash;
An example of workflow run on this PR: …
=> Trigger the IBM Cloud Image Workflow on PRs as well

Dockerfile.rhel, docs/website/docs/command-reference/docs-mdx/init/devfile_from_any_registry_output.mdx, docs/website/docs/command-reference/docs-mdx/init/devfile_from_specific_registry_output.mdx, docs/website/docs/command-reference/docs-mdx/init/devfile_from_url_output.mdx, docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx, docs/website/docs/command-reference/docs-mdx/init/interactive_mode_empty_directory_output.mdx, docs/website/docs/command-reference/docs-mdx/init/latest_versioned_devfile_output.mdx, docs/website/docs/command-reference/docs-mdx/init/versioned_devfile_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_deploy_output.mdx, docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_deploy_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx, pkg/version/version.go, scripts/rpm-prepare.sh
=> Bump version to v3.7.0

.github/workflows/build-push-ibm-image.yaml, .ibm/images/Dockerfile, Dockerfile.rhel, go.mod, openshift-ci/build-root/Dockerfile, pkg/preference/implem_test.go, pkg/registry/registry.go, pkg/registry/registry_test.go, pkg/registry/starter_project.go, pkg/registry/utils_test.go, pkg/segment/integrations_test.go, pkg/segment/segment.go, pkg/segment/segment_test.go, pkg/sync/sync_test.go, pkg/testingutil/filesystem/default_fs.go, pkg/util/config_util.go, pkg/util/file_indexer.go, pkg/util/file_indexer_test.go, pkg/util/util.go, pkg/util/util_test.go, scripts/rpm-prepare.sh, tests/examples/source/devfiles/go/middleware/handlers.go, tests/helper/helper_configValidate.go, tests/helper/helper_filesystem.go, tests/helper/helper_http.go, tests/helper/helper_oc.go, tests/helper/helper_telemetry.go, tests/integration/cmd_dev_test.go, tests/integration/cmd_devfile_init_test.go, tests/integration/plugin_handler_test.go
=> Bump Go to 1.19

docs/website/src/pages/index.module.css, docs/website/src/pages/index.tsx
This displays a short demo of the main commands on the home page, showcasing a typical inner-loop development workflow.
I've tried to make it short and to the point, so let me know what you think.
To make room for the video, I've also reworded the title to make it shorter and highlight more appealing words like "container". So let me know what you think.
Fixes #6524 
https://deploy-preview-6605--odo-docusaurus-preview.netlify.app/
Preview:
=> Add preview video of odo on the website home page

.github/workflows/release-management.yaml
This renames the branch backing the generated release PR, from `blog_post_$tagName` to `release_pr_$tagName`, because it contains more than a blog post. This way, it is easier to identify and check out if needed.
&mdash;
=> Rename the generated branch for release PRs

scripts/bump-version.sh
`bump-version.sh` is used whenever we are ready to tag a new version. But now that documentation tests are integrated into the CI jobs (https://github.com/redhat-developer/odo/pull/6521), checks for the new version would not pass straight away, and we would need to manually figure out which files would need to be updated.
This happened in the PR for `v3.7.0`: https://github.com/redhat-developer/odo/pull/6596#issuecomment-1431213837
So this PR is about ensuring the odo version is also updated accordingly in the documentation sample outputs potentially referenced by the Docs tests.
Related to  #6192
Run …
=> Make `bump-version.sh` also update the version in documentation sample outputs

pkg/component/component.go, pkg/component/component_test.go, pkg/labels/labels.go, tests/examples/manifests/ingress-app-label.yaml, tests/examples/manifests/route-app-label.yaml, tests/integration/cmd_describe_component_test.go
/kind bug
odo describe component --name &lt;non-odo-component> displays information
Fixes #6584
=> Describe non-odo component

pkg/util/util.go, pkg/util/util_test.go
=> Allow `:` character in devfile registry URI

tests/examples/source/nodejs/Dockerfile
What type of PR is this:
kind code-refactoring
What does this PR do / why we need it:
It fixes podman failures on Z and P environment which are due to image compatibility issue
Which issue(s) this PR fixes:
podman test cases image issue for Z and P
Fixes
=> Use Node image compatible with Z and P environments

docs/website/docs/user-guides/advanced/air-gap-environment.md
Fixes #6542 
Preview: https://deploy-preview-6627--odo-docusaurus-preview.netlify.app/docs/user-guides/advanced/container-based-application-development-air-gapped-environment
=> Document air-gapped env

tests/integration/cmd_devfile_init_test.go, tests/integration/cmd_devfile_registry_test.go, tests/integration/cmd_pref_config_test.go, tests/integration/interactive_init_test.go
/kind bug
/area testing
On Prow, users do not seem to have permission to install the `DevfileRegistriesList` Custom Resource Definition.
Fixes #6637 
On an OpenShift cluster (with the `oc` client available in the `PATH`), this should pass:
```
unset KUBERNETES && make test-integration-cluster
```
=> Skip DevfileRegistriesList-related tests on non Kubernetes clusters

tests/integration/cmd_describe_component_test.go
/kind bug
/area testing
```
content of path "message" should contain "no component found with name \"unknown-name\" in the namespace \"cmd-describe-component-test70ezo\"" but is "no component found with name \"unknown-name\""
Expected
<string>: no component found with name "unknown-name"
to contain substring
<string>: no component found with name "unknown-name" in the namespace "cmd-describe-component-test70ezo"
```
I noticed this error message when running the following integration tests locally:
- `odo describe component command tests when creating a component [It] should not describe the component from another directory`
-  `odo describe component command tests [It] should fail, with cluster`
`odo describe …
=> Fix potential issue with `odo describe component` integration tests when Podman is installed

pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter_test.go
/kind bug
Stumbled upon this issue recently, and found a mistake in the `if` condition used to skip non-deletable resources (like `PodMetrics`). 
We had this previously, which would actually never match:
```go
if !kerrors.IsNotFound(err) || !kerrors.IsMethodNotSupported(err) {
```
After adding some unit tests, I also noticed that the way any error is detected might lead to a race condition: multiple Goroutines are trying to assign a shared error variable, and we are using that to determine the return value.
This is solved by using [`errgroup`](https://pkg.go.dev/golang.org/x/sync/errgroup) instead, which looks more appropriate to simplify goroutine error handling.
Fixes #6475 
**PR …
=> Fix error handling when trying to delete remote resources not present in Devfile

pkg/util/util.go, pkg/util/util_test.go
/kind bug
Due to regression on 6.1+ kernels [1], binding on 127.0.0.1:$port after some process listens on 0.0.0.0:$port does pass, which is not expected. Until this issue is fixed [2], a possible workaround is to try to bind on 0.0.0.0:$port. This works correctly on Podman, and also on Kubernetes (because we do port-forwarding on Kubernetes on 127.0.0.1:$port).
The unit test added should allow us to detect similar issues faster in the future, should it happen again.
[1] https://lore.kernel.org/stable/e21bf153-80b0-9ec0-15ba-e04a4ad42c34@redhat.com/T/
[2] https://lore.kernel.org/netdev/20230312031904.4674-3-kuniyu@amazon.com/T/
Fixes #6612 
**PR acceptance …
=> Fix issue with conflicting ports when starting multiple Dev sessions on Podman

pkg/deploy/deploy.go
/kind bug
/area UX
/area deploy
I stumbled upon this issue while reviewing https://github.com/redhat-developer/odo/pull/6672.
Before the changes, the `Execution output:` message was displayed on the same line as the spinner, like so:
```
↪ Executing command:
◓  Executing command in container (command: exec-deploy)Execution output:
/bin/sh: line 1: helm: command not found
✗  Executing command in container (command: exec-deploy) [8s]
✗  failed to execute (command: exec-deploy)
```
This is now fixed by ending the spinner as soon as the command is done, and then displaying the command output. Example output:
```
↪ Executing command:
✗  Executing command in container (command: exec-deploy) [8s]
Execution output:
/bin/sh: …
```
=> Fix UX issue when exec command fails to run as part of a deploy command

docs/website/docs/command-reference/deploy.md, docs/website/docs/development/devfile.md
/kind feature
This doc is a reference to how odo runs exec commands in Deploy mode. 
Fixes #
https://deploy-preview-6672--odo-docusaurus-preview.netlify.app/docs/development/devfile#how-odo-runs-exec-commands-in-deploy-mode
https://deploy-preview-6672--odo-docusaurus-preview.netlify.app/docs/command-reference/deploy
=> Documentation: How odo supports exec on Deploy

pkg/init/init.go, pkg/init/interface.go, pkg/init/mock.go, pkg/odo/cli/init/init.go, tests/integration/interactive_init_test.go
/kind bug
Fixes #6638 
1. `odo init` in interactive mode from an empty dir and select latest Go/Java Springboot/Python devfile that has extra stack files. Ensure that you are asked to select a starter project.
=> Fix: `odo init` does not ask for starter project if the Devfile stack contains extra files

pkg/odo/cli/deploy/deploy.go, pkg/odo/cli/dev/dev.go, pkg/odo/genericclioptions/util.go, tests/helper/helper_dev.go, tests/helper/helper_generic.go, tests/integration/cmd_dev_test.go, tests/integration/cmd_devfile_deploy_test.go
/kind bug
This PR adds a warning if the user is using a default namespace.
This PR also modifies `helper.IsKubernetesCluster` to work if `KUBERNETES=true,t,1,T,true,True,TRUE`.
Fixes #5591 
1. `odo set namespace default`
2. `odo init --devfile go --starter go-starter --devfile-version latest`
3. `odo dev` should display the warning right away
4. `PODMAN_CMD=echo odo deploy` should display the warning right away.
If you are on an OpenShift cluster, it will use `project` instead of `namespace`.
=> odo dev/deploy should display a warning about default namespace on cluster

.ibm/pipelines/windows-test-script.ps1, .ibm/pipelines/windows-test.sh, scripts/devfile-registry/ci-values.yaml, tests/helper/helper_generic.go, tests/integration/cmd_devfile_registry_test.go
=> Get DEVFILE_REGISTRY value for tests, to use local Registry

docs/website/docs/command-reference/json-output.md, docs/website/docs/command-reference/registry.md, go.mod, go.sum, pkg/alizer/alizer.go, pkg/alizer/alizer_test.go, pkg/api/registry.go, pkg/init/backend/interactive.go, pkg/init/backend/interactive_test.go, pkg/odo/cli/registry/registry.go, pkg/registry/interface.go, pkg/registry/mock.go, pkg/registry/registry.go, pkg/registry/registry_test.go, tests/integration/cmd_devfile_registry_test.go, vendor/github.com/devfile/registry-support/index/generator/schema/schema.go, vendor/modules.txt
/kind feature
- `odo registry --details -o json` continues to make new calls to get Devfile content for all stacks of registries (to not break plugin compatibility). **This command will be deprecated**, as `--details` flag was not intended to be used without `--devfile` flag.
- `odo registry --details --devfile "name" -o json` continues to make a new call to get the "name" Devfile content (to not break plugin compatibility).
- `odo registry --details` do not make anymore new calls to get Devfile content for all stacks of registries. **This command will be deprecated**, as `--details` flag was not intended to be used without `--devfile` flag.
- `odo registry --details --devfile "name"` do not make anymore a new call to …
=> Speedup odo registry --details

tests/helper/helper_dev.go, tests/helper/helper_run.go
/kind tests
This PR extends the helper functions `WaitForOutputToContain` and the likes to exit early if a session has exited due to an error.
The motivation behind adding this change is while developing a new feature, in my case #6704, I had run into a case where `--port-forward` was given an invalid value, and `odo dev` exited, but the test session running `StartDevMode` and in turn running `WaitForOutputToContain` still kept running and waiting for the output to contain a given substring. It would save a lot of time while developing a new test if the test exited early.
Fixes #
Add the following …
=> Exit a test early if a session has exited while waiting for an output to contain a substring

tests/helper/helper_cmd_wrapper.go
/kind bug
/area testing
Fixes #6715 
=> Fix problem when odo deploy processes do not terminate

pkg/dev/interface.go, pkg/dev/kubedev/kubedev.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/types.go, pkg/odo/cli/dev/dev.go, pkg/odo/cli/dev/dev_test.go, pkg/portForward/kubeportforward/portForward.go, pkg/portForward/kubeportforward/portForward_test.go, pkg/watch/watch.go, tests/helper/helper_dev.go, tests/helper/helper_http.go, tests/integration/cmd_dev_debug_test.go, tests/integration/cmd_dev_test.go
/kind feature
Fixes part of #6479 
1. `odo dev --port-forward <localPort>:<containerPort> --port-forward <localPort>:<containerName>:<containerPort>`
=> Allow users to define custom port-mappings for port forwarding [Kubernetes]

docs/website/docs/development/devfile.md, pkg/deploy/deploy.go, pkg/dev/podmandev/reconcile.go, pkg/devfile/adapters/kubernetes/component/push.go, pkg/libdevfile/component_image.go, pkg/libdevfile/component_image_test.go, pkg/libdevfile/component_kubernetes.go, tests/examples/source/devfiles/nodejs/devfile-autobuild-deploybydefault.yaml, tests/examples/source/nodejs/package.json, tests/helper/helper_podman.go, tests/integration/cmd_dev_debug_test.go, tests/integration/cmd_dev_test.go, tests/integration/cmd_devfile_build_images_test.go, tests/integration/cmd_devfile_deploy_test.go
This is a follow-up PR to https://github.com/redhat-developer/odo/pull/6654 (support for `autoBuild` and `deployByDefault` fields), addressing some of the comments left there.
Related to #5694 
=> Follow-up to comments on #6654 (support for `autoBuild` and `deployByDefault`)

docs/website/docs/command-reference/create-namespace.md, docs/website/docs/command-reference/docs-mdx/create-namespace/create_namespace.mdx, docs/website/docs/command-reference/docs-mdx/create-namespace/create_project.mdx, tests/documentation/command-reference/doc_command_reference_createnamespace_test.go
=> Doc automation:Command Reference: odo create namespace

pkg/odo/cli/dev/dev_test.go, pkg/portForward/kubeportforward/portForward.go, pkg/portForward/kubeportforward/portForward_test.go
/kind bug
Fixes part of #6479 
1. `odo init --devfile nodejs --starter nodejs-starter`
2. `odo dev --port-forward 20001:5858 --debug`
Resulting port mapping: 3000 -> 20002, 5858 -> 20001
=> For custom port mapping, handle case where ranged random port matches a custom local port

scripts/openshiftci-Nightly-SBO-tests.sh, scripts/openshiftci-config.sh, scripts/openshiftci-periodic-tests.sh, scripts/openshiftci-presubmit-all-tests.sh
This reverts commit f0bf9ee1dd86eba0c6917f0b857ea5840d9bb314.
/area testing
PR #6709 modified the periodic tests to use the Devfile registry setup on IBM cloud because of the broken Staging Registry. But it would be helpful to have our tests use the Staging Registry in order to catch any problem with it early on before it propagates to the Production Registry.
This PR reverts back to using the Staging Registry.
Fixes #
=> Revert "Add DEVFILE_REGISTRY env var for periodic tests (#6709)"

docs/website/docs/command-reference/docs-mdx/init/registry_list_output.mdx, tests/e2escenarios/e2e_test.go
/kind bug
/area testing
This PR fixes e2e and doc test failures related to an update in the Devfile registry.
Prod/Staging Devfile registries updated all the JavaScript related Devfiles with a newer version, which is causing a failure in our tests.
Fixes #
=> Fix e2e test failures and doc test failures due to updated devfile registry

docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx, pkg/dev/podmandev/reconcile.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/port/port.go, pkg/port/port_test.go, tests/helper/helper_documentation.go, tests/integration/cmd_dev_test.go
/kind feature
/area dev
To fix some flaky behavior due to the app sometimes not being ready when sending out requests to the local forwarded ports, this PR leverages the port detector (introduced in #6620 to detect if container ports are bound on the container loopback interface) to wait until the container ports are actually opened before trying to start the port forwarding logic. See https://github.com/redhat-developer/odo/issues/6667#issuecomment-1478256277
For consistency, this is done on both Kubernetes and Podman platforms.
At the moment, this additional check will not prevent `odo dev` from starting, but a warning will just be displayed if the timeout (arbitrarily set to `1m`) is reached and the port is not …
=> Wait until expected ports are opened in the container before starting port-forwarding

pkg/kclient/kclient.go
/kind bug
Fixes #6699 
1. Run `odo dev` and ensure that the warning is printed only once.
2. Run `odo dev` or `odo deploy` with Devfile containing multiple containers and ensure that a warning is printed only once per container.
=> Fix: PodSecurity Admission: Display duplicate warnings only once

pkg/dev/podmandev/pod.go, pkg/dev/podmandev/pod_test.go, pkg/dev/podmandev/podmandev.go, pkg/dev/podmandev/reconcile.go, pkg/odo/cli/dev/dev.go, tests/integration/cmd_dev_debug_test.go, tests/integration/cmd_dev_test.go
=> Podman custom port mapping

pkg/portForward/kubeportforward/portForward.go, pkg/portForward/kubeportforward/portForward_test.go
/area testing
/kind flake
This fixes flaky test.
Fixes part of #6479
Fixes #6741
=> Fix flaky unit Test_getCompleteCustomPortPairs

cmd/odo/odo.go, pkg/dev/podmandev/reconcile.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/odo/cli/describe/component.go, pkg/odo/cli/dev/dev.go, pkg/odo/context/odo.go, pkg/portForward/interface.go, pkg/portForward/kubeportforward/portForward.go, pkg/portForward/podmanportforward/portForward.go, pkg/registry/mock.go, pkg/state/const.go, pkg/state/doc.go, pkg/state/errors.go, pkg/state/interface.go, pkg/state/process_unix.go, pkg/state/process_windows.go, pkg/state/state.go, pkg/state/state_test.go, pkg/state/types.go, tests/helper/helper_dev.go, tests/integration/cmd_dev_test.go
/kind feature
State of `odo dev` if now saved in a file `.odo/devstate.${PID}.json`, to be able to run multiple instances and state for each of them.
For compatibility, the file `.odo/devstate.json` is also used for the first instance of `odo dev`.
One drawback is that if an instance of `odo dev` is killed, the `devstate.json` file won't be overwritten. One possibility would be to delete it when running `odo delete component` and the process with registered PID into devstate.json is not existing.
Fixes #6494 
=> Use devstats.PID.json as devstate

pkg/dev/podmandev/pod.go, pkg/dev/podmandev/pod_test.go, pkg/dev/podmandev/reconcile.go, tests/helper/component_cluster.go, tests/helper/component_interface.go, tests/helper/component_podman.go, tests/helper/helper_podman.go, tests/integration/cmd_dev_test.go
=> Set vcs-uri annotation on podman

tests/examples/source/devfiles/springboot/devfile-with-missing-projectType-and-language-metadata.yaml, tests/examples/source/devfiles/springboot/devfile-with-missing-projectType-metadata.yaml, tests/examples/source/devfiles/springboot/devfile-with-subDir.yaml
Updates the springboot devfiles stored in the odo repository with a more up-to-date image.
(https://github.com/devfile/registry/commit/bf3a2ce6d9ccf1d9d9d49a53d489ced2d052bd43)
/area testing
Fixes #6754
=> Update image for springboot devfiles

docs/website/docs/user-guides/advanced/automounting-volumes.md, pkg/configAutomount/interface.go, pkg/configAutomount/kubernetes.go, pkg/configAutomount/kubernetes_test.go, pkg/devfile/adapters/kubernetes/storage/utils.go, pkg/devfile/adapters/kubernetes/storage/utils_test.go, tests/examples/manifests/config-automount/access-mode-configmap-decimal.yaml, tests/examples/manifests/config-automount/access-mode-configmap.yaml, tests/examples/manifests/config-automount/access-mode-secret.yaml, tests/examples/manifests/config-automount/access-mode-subpath-configmap.yaml, tests/examples/manifests/config-automount/access-mode-subpath-secret.yaml, tests/integration/cmd_dev_test.go
/kind feature
Fixes #6549 
Fixes #6728 
=> Add annotation for setting access mode on automounted configmap/secret files

pkg/sync/sync.go, tests/integration/cmd_dev_test.go
=> Check files to sync with gitignore library

tests/integration/cmd_dev_test.go
/area testing
/kind bug
Fixes #6601 
=> Test flaky devfile modification test

docs/website/docs/command-reference/delete-namespace.md, docs/website/docs/command-reference/docs-mdx/delete-namespace/delete_namespace.mdx, docs/website/docs/command-reference/docs-mdx/delete-namespace/delete_project.mdx, docs/website/docs/command-reference/docs-mdx/list-namespace/list_namespace.mdx, docs/website/docs/command-reference/docs-mdx/list-namespace/list_project.mdx, docs/website/docs/command-reference/docs-mdx/set-namespace/set_namespace.mdx, docs/website/docs/command-reference/docs-mdx/set-namespace/set_project.mdx, docs/website/docs/command-reference/list-namespace.md, docs/website/docs/command-reference/set-namespace.md, tests/documentation/command-reference/doc_command_reference_deletenamespace_test.go, tests/documentation/command-reference/doc_command_reference_listnamespace_test.go, tests/documentation/command-reference/doc_command_reference_setnamespace_test.go
area/documentation
Fixes #6724 
=> Doc automation:Command reference: odo delete,list and set namespace

docs/website/docs/command-reference/build-images.md, pkg/odo/cli/build_images/build_images.go, tests/examples/source/devfiles/nodejs/devfile-variables.yaml, tests/integration/cmd_devfile_build_images_test.go
/kind feature
Fixes #6274 
You can run `odo build-images [--var ... | --var-file ...]` using the Devfile used in the tests (`tests/examples/source/devfiles/nodejs/devfile-variables.yaml`) or any Devfile where image names are variables (like in our [Advanced Guides for deploying apps](https://odo.dev/docs/user-guides/advanced/deploy/nodejs#step-3-modify-the-devfile))
=> Support variable substitution with `--var` and `--var-file` in `odo build-images`

docs/website/docs/command-reference/dev.md, pkg/dev/interface.go, pkg/dev/kubedev/innerloop.go, pkg/dev/podmandev/pod.go, pkg/dev/podmandev/pod_test.go, pkg/dev/podmandev/reconcile.go, pkg/kclient/interface.go, pkg/kclient/mock_Client.go, pkg/kclient/port_forwarding.go, pkg/odo/cli/dev/dev.go, pkg/odo/cli/dev/dev_test.go, pkg/portForward/interface.go, pkg/portForward/kubeportforward/portForward.go, pkg/portForward/kubeportforward/portForward_test.go, pkg/portForward/kubeportforward/writer.go, pkg/portForward/kubeportforward/writer_test.go, pkg/portForward/podmanportforward/portForward.go, pkg/util/util.go, pkg/util/util_test.go, tests/examples/source/devfiles/go-devfiles/devfile.yaml, tests/helper/helper_dev.go, tests/integration/cmd_dev_debug_test.go, tests/integration/cmd_dev_test.go
/kind feature
With this PR, users can now provide custom address for port forwarding.
Fixes #6479 
Fixes part of #6744 (works as a workaround, need to document this behavior)
0. `odo init --devfile go --starter go-starter --name custom-address-go-app`
1. `odo dev --address 192.168.0.2`
=>  Use custom address for port forwarding

docs/website/blog/deploy-and-connect-to-microservice-using-helm-and-exec.md
Fixes #6645 
https://deploy-preview-6775--odo-docusaurus-preview.netlify.app/blog/using-helm-with-odo
=> Blog: Helm integration with odo

tests/helper/helper_registry.go, tests/integration/cmd_devfile_init_test.go
/kind bug
/area testing
An integration test is failing after registry is updated and the Go stack got a new version.
```
[FAILED] Expected
<string>: 2.1.0
to be equivalent to
<string>: 2.0.0
In [It] at: /go/src/github.com/redhat-developer/odo/tests/integration/cmd_devfile_init_test.go:187 @ 05/04/23 00:38:54.514
```
Instead of hardcoding the value of the latest version of the Go stack, the latest value is obtained by reading the index of the Devfile Registry.
Fixes #
=> Check latest version from index instead of using hardcoded value

docs/website/blog/2023-05-04-odo-v3.10.0.md
=> Update the release doc with Sprint 235 updates

pkg/dev/podmandev/pod.go, pkg/dev/podmandev/pod_test.go, pkg/dev/podmandev/podmandev.go, pkg/dev/podmandev/reconcile.go, tests/integration/cmd_dev_test.go
=> Delete previous pod and creates new ond when modifying devfile on podman

docs/website/docs/development/architecture/podman-support-limitations.md, pkg/dev/podmandev/cleanup.go, pkg/dev/podmandev/reconcile.go, pkg/odo/cli/delete/component/component.go, pkg/odo/cli/delete/component/component_test.go, pkg/podman/interface.go, pkg/podman/mock.go, pkg/podman/podman.go
=> Reuse same volumes when devfile is modified, on podman

pkg/init/init.go, pkg/init/init_test.go, pkg/init/interface.go, pkg/init/mock.go, pkg/odo/cli/init/init.go, pkg/registry/interface.go, pkg/registry/mock.go, pkg/registry/registry.go, pkg/registry/registry_test.go, tests/integration/interactive_init_test.go
/kind bug
Fixes #6799 
Fixes #6752
=> Fix: `odo init` overwrites personalized configuration when downloading starter project

tests/integration/cmd_dev_test.go
/kind bug
/area testing
Fixes #6815
=> Wait after killing odo during integration test

.github/workflows/infra-test.yaml
/kind bug
/area infra
/area testing
Currently, the `odo-infra-stage-test` job runs on *all* PRs (and ends up failing), even if the PR has not changed anything in `scripts/ansible`:
The job ends up failing and we manually have to override it.
This PR makes sure not to run it if not needed.
There is one additional point related to this job (see https://github.com/redhat-developer/odo/issues/6813#issuecomment-1549859387), but that can be addressed later.
Related to #6813 
This way, we won't need to manually override this job on all PRs.
=> Do not run 'odo-infra-stage-test' Workflow on PRs if not needed

scripts/openshiftci-Nightly-SBO-tests.sh, scripts/openshiftci-periodic-tests.sh
/kind bug
/area testing
Fixes #6812
=> Only run cluster tests on nightly tests, not nocluster tests

Makefile
/area testing
Per [1], this instructs Ginkgo to automatically emit a progress report whenever a node takes too long to complete.
The Progress Report includes information about which node is currently running and the exact line of code that it is currently executing, along with any relevant goroutines that were launched by the spec.
[1] https://onsi.github.io/ginkgo/#getting-visibility-into-long-running-specs
Deprecation warnings as seen at the end of all our tests, like [here](https://github.com/redhat-developer/odo/actions/runs/5045832057/jobs/9053658068#step:5:24):
```
Ran 162 of 888 Specs in 1072.811 seconds
SUCCESS! -- [16](https://github.com/redhat-developer/odo/actions/runs/50458 …
```
=> Replace deprecated `--slow-spec-threshold` Ginkgo flag with `--poll-progress-after`

.github/workflow-data/release-management/blog-post-header.tpl.md, docs/website/blog/2020-09-24-odo-v2.0.0-ga-release.md, docs/website/blog/2020-10-28-odo-v2.0.1-release.md, docs/website/blog/2021-05-04-odo-v2.2.0-breaking-changes.md, docs/website/blog/2021-12-14-odo-v2.4.3.md, docs/website/blog/2022-01-14-odo-v2.5.0.md, docs/website/blog/2022-05-02-odo-v3-alpha1.md, docs/website/blog/2022-06-14-binding-external-service.md, docs/website/blog/2022-06-30-binding-database-service-without-sbo.md, docs/website/blog/2022-07-01-odo-v3-beta1.md, docs/website/blog/2022-07-21-odo-v3-beta2.md, docs/website/blog/2022-08-18-odo-v3-beta3.md, docs/website/blog/2022-09-01-odo-v3-rc1.md, docs/website/blog/2022-09-22-odo-v3-rc2.md, docs/website/blog/2022-11-29-odo-v3.3.0.md, docs/website/blog/2022-12-13-odo-v3.4.0.md, docs/website/blog/2023-01-04-odo-v3.5.0.md, docs/website/blog/2023-01-24-odo-v3.6.0.md, docs/website/blog/2023-01-30-local-container-dev-on-podman.md, docs/website/blog/2023-02-15-odo-v3.7.0.md, docs/website/blog/2023-02-17-odo-dotnet-postgresql-openshift.mdx, docs/website/blog/2023-03-08-odo-v3.8.0.md, docs/website/blog/2023-03-22-deploying-and-using-in-cluster-devfile-registry.md, docs/website/blog/2023-04-05-odo-v3.9.0.md, docs/website/blog/2023-05-04-odo-v3.10.0.md, docs/website/blog/3.0.0-GA-blog.md, docs/website/blog/deploy-and-connect-to-microservice-using-helm-and-exec.md
While sharing blogs on social media platform, the author image is highlighted in big picture which is not always desirable. Using odo logo instead seems like a better option.
Fixes #6807 
=> Use odo logo instead of author image in blog posts

go.mod, go.sum, vendor/github.com/devfile/library/v2/pkg/devfile/parser/parse.go, vendor/github.com/devfile/library/v2/pkg/git/git.go, vendor/github.com/devfile/library/v2/pkg/git/mock.go, vendor/modules.txt
/area dependency
This bumps the Devfile library to the latest commit [1], which fixes the issue with parsing child Devfiles
referencing parents via URIs (GitHub blob, raw or any hosted URL).
See [2] for more context.
[1] https://github.com/devfile/library/commit/04a8b3fc66c0ca7a33d03190f3a026a3d9e6a940
[2] https://github.com/devfile/api/issues/1119
Related to https://github.com/devfile/api/issues/1119
Given the following Devfile:
```yaml
metadata:
description: Java application using Spring Boot® and OpenJDK 17
name: my-java-sb
version: 1.3.0
parent:
components:
- container:
image: …
```
=> Bump Devfile library to latest commit (04a8b3f)

tests/e2escenarios/e2e_test.go, tests/helper/helper_filesystem.go, tests/integration/cmd_delete_test.go, tests/integration/cmd_describe_component_test.go, tests/integration/cmd_dev_debug_test.go, tests/integration/cmd_dev_test.go, tests/integration/cmd_devfile_build_images_test.go, tests/integration/cmd_devfile_deploy_test.go, tests/integration/cmd_devfile_init_test.go, tests/integration/cmd_devfile_list_test.go, tests/integration/cmd_namespace_test.go
/kind flake
/kind bug
/area testing
This fixes the flakiness of the test reported in #6832, by randomizing the component names used in this test.
It also changes the signature of `helper.CopyExampleDevfile` so as to make sure we don't forget to set a component name when copying an example Devfile.
Fixes #6832 
=> Fix flaky `odo dev` test on Podman by randomizing component names

pkg/odo/cli/list/list.go, tests/integration/cmd_describe_list_binding_test.go
/kind bug
/area testing
This PR fixes some issues we discovered with the describe/list binding tests while working on #6829.
Fixes #6846
=> Fix issues with describe/list binding tests

tests/integration/cmd_dev_test.go
/kind bug
/area testing
The goal of this test is to ensure that the warning message is displayed when using the default namespace/project;
so it does not matter if the Dev Session does not start correctly (as can be the case in certain environments like OCP 4.14).
Fixes #6847
=> Fix `should print warning about default namespace when running odo dev` test when Dev Session does not start correctly

pkg/odo/cli/preference/set.go, pkg/odo/cli/preference/unset.go, pkg/segment/context/context.go, tests/helper/helper_telemetry.go, tests/integration/cmd_pref_config_test.go
/kind feature
/area telemetry
Fixes #6791 
=> Track preference options usage

pkg/dev/podmandev/podmandev.go, tests/integration/cmd_dev_test.go
/kind bug
/area dev
/area UX
See #6856 for more context. This issue was discovered while working on #6855 , but I preferred to address that in a separate issue and PR.
Fixes #6856 
See #6856
=> Make sure the "Syncing files into the container" spinner is displayed on Podman

cmd/odo/help_test.go, pkg/component/component.go, pkg/component/delete/delete.go, pkg/component/delete/delete_test.go, pkg/dev/common/run.go, pkg/dev/interface.go, pkg/dev/kubedev/run.go, pkg/dev/mock.go, pkg/dev/podmandev/run.go, pkg/exec/exec_test.go, pkg/libdevfile/errors.go, pkg/libdevfile/libdevfile.go, pkg/odo/cli/cli.go, pkg/odo/cli/errors/errors.go, pkg/odo/cli/run/run.go, pkg/platform/interface.go, pkg/platform/mock.go, pkg/podman/component.go, pkg/podman/interface.go, pkg/podman/mock.go, pkg/podman/pods.go, tests/examples/source/devfiles/nodejs/devfile-for-run.yaml, tests/integration/cmd_run_test.go
/kind feature
Fixes partially #6568 
The points covered by this PR are:
- there should be a command (odo run for example) that takes one argument that is the command name and executes the command defined in devfile
- odo run assumes that odo dev is running in a separate terminal, if odo dev is not running (resources not present on the cluster) odo run errors out and tells the user to run odo dev first.
- if the command is exec command and the container where the program needs to be started is not running, the command should be executed as a Job; for podman this can be running inside a pod/container (this case is not possible currently: odo dev includes **all** the containers defined …
=> Add an `odo run` command to manually execute command during `odo dev`

.github/workflows/podman-test.yaml, .ibm/pipelines/functions.sh, .ibm/pipelines/kubernetes-tests.sh, .ibm/pipelines/nocluster-tests.sh, .ibm/pipelines/openshift-tests.sh, .ibm/pipelines/openshift-unauth-tests.sh, .ibm/pipelines/unit-tests.sh, .ibm/pipelines/validate.sh, .ibm/pipelines/windows-test.sh
/kind feature
/area testing
Fixes #6854 
=> Skip tests if all changes in docs

.github/workflows/stale.yaml
=> Mark issues and pull requests as stale

docs/website/docs/command-reference/run.md, pkg/component/delete/delete.go, pkg/component/execute_terminating.go, pkg/component/handler.go, pkg/deploy/deploy.go, pkg/dev/common/run.go, pkg/dev/kubedev/innerloop.go, pkg/dev/podmandev/reconcile.go, pkg/exec/exec.go, pkg/podman/exec.go, tests/examples/source/devfiles/nodejs/devfile-for-run.yaml, tests/integration/cmd_run_test.go
/kind feature
This PR completes the implementation for #6568.
- odo run streams logs into the terminal and waits for the command to finish.
- user can interrupt the command by pressing  control-c; cleanup the resources.
- the exit code of odo run command reflect the exit code of the last devfile command executed. If the last command was apply and it was successful it returns 0, if failed returns 1
- Because odo dev is running, if Kubernetes/OpenShift resources are created with Apply commands, they should be deployed in "Dev" mode (to be cleanup when odo dev terminates) - make it clear it will be cleaned up.
Fixes #6568
Doc: https://deploy-preview-6865--odo-docusaurus-preview.netlify.ap …
=> Display outputs when executing `odo run`

.github/workflows/nightly-build.yaml, docs/website/docs/overview/installation.md
/kind feature
This adds a scheduled GitHub Workflow that builds `odo` for multiple platforms, and uploads those binaries to IBM Cloud Storage, so users can consume them.
Fixes #6693 
Example of job in action: https://github.com/rm3l/odo/actions/runs/5220887665/jobs/9424500936
=> Build nightly binaries of odo and make them available (via IBM Cloud Object Storage)

tests/integration/interactive_deploy_test.go, tests/integration/interactive_init_test.go
/kind bug
/area testing
Fixes #6890 
=> Stop test as soon as expectation is verified

.github/workflows/pr-website.yaml, docs/website/.dockerignore, docs/website/.kubernetes/resources.yaml, docs/website/Dockerfile, docs/website/devfile.yaml
/area testing
This is a follow-up to the Dogfooding idea started with https://github.com/redhat-developer/odo/pull/6564
I wanted to take this opportunity to try odo as an outer-loop tool from a user perspective.
This PR adds a 'deploy' command to the website Devfile, and adds a GitHub Workflow that is triggered on PR events, and uses this Devfile to run `odo deploy` against our internal Kubernetes cluster, in order to create Deploy Previews for PRs (similar to what Netlify currently does).
Once a PR is open, a dedicated namespace is created, and `odo deploy` is run against it. If deployment is successful (and the preview URL is reachable), a comment with the preview URL is automatically added to the PR.
Once a PR is …
=> [Dogfooding] Create website deploy previews for PRs using `odo deploy`

.github/workflows/pr-website.yaml
/area testing 
This improves the website PR preview workflow introduced in https://github.com/redhat-developer/odo/pull/6871 by:
- triggering it only when there are actual changes in the `docs/website/` folder. Initially, I wanted to take this as a way to test `odo deploy` against any PR changing the source code  and/or the website, but this might create useless deployments. We should already have other E2E tests running `odo deploy`.
- auto-approving preview deployments for PRs coming from authorized users (us as odo maintainers or certain robot accounts that can manipulate PRs). This way, we won't need to manually approve them. Previously, only PRs created from branches in the same `redhat-developer/odo` repo would …
=> Improve website PR preview workflow

.github/PULL_REQUEST_TEMPLATE.md, scripts/changelog-script.sh
/area refactoring
This fixes the remaining places, after cleaning up all the labels we use in the repo: https://github.com/redhat-developer/odo/labels?sort=name-asc
I wanted to delete the `kind/code-refactoring` label (superseded by `area/refactoring`), but it was still being used here.
Also, the `kind/tests` label had been removed already in the past, but the changelog script was not updated accordingly.
&mdash;
=> Fix GitHub labels in release changelog generator script and PR template

cmd/odo/alizer_test.go, cmd/odo/common_test.go, cmd/odo/delete_test.go, pkg/dev/kubedev/kubedev.go, pkg/dev/podmandev/podmandev.go, pkg/devfile/location/location.go, pkg/odo/cli/add/binding/binding.go, pkg/odo/cli/alizer/alizer.go, pkg/odo/genericclioptions/devfile.go, pkg/odo/genericclioptions/runnable.go, pkg/registry/registry.go, pkg/registry/starter_project.go, pkg/testingutil/filesystem/fake_fs.go, pkg/util/util.go, pkg/util/util_test.go, pkg/watch/file_watcher.go
/kind bug
Fixes #6683 
See repro steps in #6683
=> Do not return an error in `odo analyze` if current directory contains an invalid Devfile

.github/workflows/podman-test.yaml
/kind bug
/area testing
/area infra
As reported in https://github.com/redhat-developer/odo/issues/6927, the tests on Podman have been consistently failing since a few days, due to an error: `Error: k8s.gcr.io/pause:3.5: image not known`
A regression in `libpod` has been identified in Ubuntu 22.04.1 LTS and reported [1][2]. Though not strictly the same error as the one we observed, I think this regression might affect networking.
As suggested in [3], I'm trying to downgrade Podman to see if it helps. 🤞🏿 
[1] https://github.com/actions/runner-images/issues/7753
[2] https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/2024394
[2] https://github.com/actions/runner-images/issues/7753#issuecomment-160076 …
=> Temporarily downgrade Podman on GitHub to fix CI failures for Podman tests

.ibm/pipelines/windows-test-script.ps1, .ibm/pipelines/windows-test.sh, scripts/ansible/Cluster/kubernetes-cluster/README.md, scripts/devfile-registry/ci-values.yaml, tests/examples/source/devfiles/nodejs/devfile-fsgroup.yaml, tests/integration/cmd_add_binding_test.go, tests/integration/cmd_describe_list_binding_test.go, tests/integration/cmd_dev_test.go, tests/integration/cmd_devfile_deploy_test.go, tests/integration/cmd_list_services_test.go, tests/integration/cmd_remove_binding_test.go, tests/integration/interactive_add_binding_test.go
/area testing
The purpose of this PR is to test the impact of removing the integration tests related to service binding.
It introduces an `SKIP_SERVICE_BINDING_TESTS` environment variable which indidate to skip tests related to service binding.
This variable has been set to `true` for *Kubernetes*, *OpenShift* and *Windows* tests on IBM Cloud, to disable these tests for PRs.
The tests will still run during the nightly tests.
=> Disable service binding related integration tests

.ibm/pipelines/windows-test-script.ps1
=> Fix service binding skip on Windows

docs/website/docs/command-reference/json-output.md, docs/website/docs/command-reference/version.md, pkg/api/version.go, pkg/kclient/oc_server.go, pkg/odo/cli/version/version.go, tests/helper/helper_generic.go, tests/helper/helper_podman.go, tests/integration/cmd_dev_test.go, tests/integration/generic_test.go
/kind feature
This PR adds podman version (if available) to the `odo version` output.
Fixes #6806
=> Add podman version to odo version output

tests/documentation/user-guides/doc_user_guides_quickstart_test.go, tests/helper/helper_devfile.go
/area testing
This PR fixes the following `Kubernetes-Docs-Integration-Tests` test, by setting an fsGroup to the container's pod.
```
[FAILED] user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx
Expected
<string>:   (
"""
... // 12 identical lines
✓  Pod is Running
✓  Syncing files into the container [1s]
- 	✓  Building your application in container (command: build) [1s]
- 	•  Executing the application (command: run)  ...
- 	✓  Waiting for the application to be ready [1s]
- 	-  Forwarding from 127.0.0.1:20001 -> 8080
+ 	✗  Building your application in container (command: build) [1s]
+ 	Error occurred on Push - watch command was unable to push component: unable to exec command [/bin/sh -c cd ${PROJECT_SOURCE} …
```
=> Set FsGroup for spring boot test

ododevapispec.yaml, pkg/apiserver-gen/README.md, pkg/apiserver-impl/api_default_service.go, pkg/apiserver-impl/starterserver.go, pkg/component/describe/describe.go, pkg/dev/interface.go, pkg/odo/cli/describe/component.go, pkg/odo/cli/dev/dev.go, pkg/watch/watch.go, tests/integration/cmd_dev_api_server_test.go
=> Implement API endpoints

tests/helper/helper_generic.go, tests/integration/generic_test.go
/kind bug
/area testing
This fixes a potential issue with the `odo version` integration tests, which failed in the nightly jobs (running on Prow) because the `developer` user does not have the permissions to get the OpenShift version.
Based on what had been done in https://github.com/redhat-developer/odo/pull/6551 to fix a similar issue, it gets the version from `oc version` and if something is reported about the server, will check that `odo version` displays the right information about OpenShift. If not, then such information should be missing from the `odo version` output.
- Fixes #6932 
- Related to https://github.com/redhat-developer/odo/pull/6913
- Related issue: [`Normal users …
=> Fix potential issue in `odo version` nightly tests if user does not have permission to get the OpenShift version

docs/website/docs/command-reference/docs-mdx/create-namespace/create_namespace.mdx, docs/website/docs/command-reference/docs-mdx/create-namespace/create_project.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/create_namespace_output.mdx, docs/website/docs/user-guides/quickstart/docs-mdx/create_project_output.mdx, pkg/odo/cli/create/namespace/namespace.go, tests/helper/helper_documentation.go, tests/integration/cmd_namespace_test.go
/kind bug
/flake
This PR fixes the bug where `odo create namespace -w` does not work as expected.
Fixes #6827
=> List namespace right after namespace has been created

ododevapispec.yaml, pkg/apiserver-gen/README.md, pkg/apiserver-impl/api_default_service.go
/kind bug
Fixes the API response data for the error cases, and documents these error responses in the openapi spec
=> Document and return JSON data for API errors

pkg/exec/exec_test.go, pkg/logs/logs.go, pkg/odo/cli/logs/logs.go, pkg/platform/interface.go, pkg/platform/mock.go, pkg/podman/mock.go, pkg/podman/pods.go, tests/examples/source/devfiles/nodejs/devfile-deploy-functional-pods.yaml, tests/integration/cmd_logs_test.go
=> Watch for new pods when logs --follow

.gitattributes
/kind task
GitHub UI is terribly slow when reviewing/commenting on PRs that contain a lot of changes in the vendored directories, like in https://github.com/redhat-developer/odo/pull/6937
As suggested, we can keep certain files from displaying in diffs by default, by using a standard `.gitattributes` file.
This should make it easier to review large PRs with a lot of changes from certain files (like in `**/vendor/**`), by hiding them by default.
See https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github for more details.
This is how matching files would appear if `linguist-generated` attribute is `true`; so it will still be possible to show the diff on …
=> Add `.gitattributes` file with Git-style path matchers customizing how PR changed files appear on GitHub

tests/helper/helper_interactive.go, tests/integration/interactive_init_test.go
=> Flake: Attempt at fixing Personalize configuration

scripts/openshiftci-config.sh
/area testing
/kind bug
We had a lot of failures because the OCP Interop tests were still using the old Devfile registry URL, which is no longer reachable since we created a new cluster.
See https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-redhat-developer-odo-main-odo-ocp4.14-lp-interop-odo-scenario-aws/1675746432100864000
&mdash;
=> Fix CI Devfile Registry URL used in OCP interop tests

pkg/odo/cli/apiserver/apiserver.go, pkg/odo/cli/cli.go, pkg/util/util.go
=> Implement odo api-server command

docs/website/docs/command-reference/docs-mdx/init/devfile_with_run-port_output.mdx, docs/website/docs/command-reference/init.md, pkg/init/backend/applicationports.go, pkg/init/backend/flags.go, pkg/init/backend/flags_test.go, pkg/init/init.go, pkg/libdevfile/libdevfile.go, pkg/odo/cli/init/init.go, tests/documentation/command-reference/doc_command_reference_init_test.go, tests/helper/helper_devfile.go, tests/integration/cmd_devfile_init_test.go
/kind feature
/area init
This introduces a new `--run-port` repeatable flag to `odo init`, allowing to set application ports non-interactively. It looks into the fetched Devfile for any default (or single non-default) run command; and, if it is an exec command, tries to find the referenced container component to overwrite its endpoints.
More context in https://github.com/redhat-developer/odo/issues/6925
Fixes #6925 
- https://odo-dev-pr-6953.odo-test-kubernete-449701-49529fc6e6a4a9fe7ebba9a3db5b55c4-0000.eu-de.containers.appdomain.cloud/docs/command-reference/init#non-interactive-mode
- [Specify the application …
=> Add new `--run-port` flag to `odo init` to set ports non-interactively

docs/website/docs/command-reference/docs-mdx/init/registry_list_output.mdx, docs/website/docs/command-reference/json-output.md, docs/website/docs/command-reference/registry.md, docs/website/docs/user-guides/quickstart/quickstart.md, pkg/api/registry.go, pkg/odo/cli/registry/registry.go, pkg/registry/registry.go, pkg/registry/registry_test.go, tests/integration/cmd_devfile_registry_test.go
/kind feature
/area registry
This displays the Devfile stacks architectures in the `odo registry` output (both human-readable and JSON).
It also makes the `--filter` flag search in the architectures.
Fixes #6804 
- [JSON output](https://odo-dev-pr-6959.odo-test-kubernete-449701-49529fc6e6a4a9fe7ebba9a3db5b55c4-0000.eu-de.containers.appdomain.cloud/docs/command-reference/json-output#odo-registry--o-json)
- [Command reference](https://odo-dev-pr-6959.odo-test-kubernete-449701-49529fc6e6a4a9fe7ebba9a3db5b55c4-0000.eu-de.containers.appdomain.cloud/docs/command-reference/registry)
Some examples:
<details> …
=> Support Architectures in `odo registry`

.github/workflows/ui-e2e.yaml, ui/angular.json, ui/cypress.config.ts, ui/cypress/support/commands.ts, ui/cypress/support/e2e.ts, ui/package-lock.json, ui/package.json
/area testing
In preparation for the work on #6902, this PR is an attempt to fix Cypress E2E tests for the Dev UI.
It uses the `api-server` command introduced in #6943 and runs it against the UI folder itself #inception #dogfooding
- Related to #6943 
- Will be needed for #6902 
=> Fix Dev UI Cypress E2E tests

docs/website/docs/command-reference/_category_.json, docs/website/docs/overview/_category_.json, docs/website/docs/troubleshooting.md, docs/website/docs/user-guides/_category_.json, docs/website/docs/user-guides/advanced/_category_.json
I was looking at past issues and wanted to "close" https://github.com/redhat-developer/odo/issues/6778, but then remembered we discussed a while back about having a "Troubleshooting" FAQ guide in our documentation.
So this PR adds this page with some common issues we have seen so far.
We'll need to enrich this later on as we get other common issues.
- Related to https://github.com/redhat-developer/odo/issues/6526
- Related to https://github.com/redhat-developer/odo/issues/6778
https://odo-dev-pr-6965.odo-test-kubernete-449701-49529fc6e6a4a9fe7ebba9a3db5b55c4-0000.eu-de.containers.ap …
=> Add a Troubleshooting page with most common issues and solutions

pkg/auth/login.go, pkg/auth/login_test.go
/kind bug
Fixes #6898
This fix is specific to OpenShift. Even though I have not been able to test this fix due to the lack of an OpenShift cluster, I believe it should still work.
=> Fix oc to odo project translation

docs/website/blog/2023-05-30-odo-v3.11.0.md
Fixes #6975.
Ideally, we should test that all links in our docs are valid, but this is the scope of https://github.com/redhat-developer/odo/issues/6617.
https://deploy-preview-6980--odo-docusaurus-preview.netlify.app/blog/odo-v3.11.0/
=> Fix invalid links in `v3.11.0` blog post

pkg/apiserver-impl/starterserver.go, pkg/odo/cli/apiserver/apiserver.go, pkg/odo/cli/dev/dev.go, tests/integration/cmd_dev_api_server_test.go
/area testing
/kind bug
This lets the OS assign a random ephemeral port to the API Server if `--random-ports` is specified when running `odo dev` or `odo api-server`.
This should hopefully fix the potential port conflict flaky issue we are seeing, especially on Windows.
Fixes #6939 
=> Fix potential port conflict issue with the API server tests by using a random server port if `--random-ports` is set

pkg/api/component.go, pkg/apiserver-impl/starterserver.go, pkg/component/describe/describe.go, pkg/odo/cli/describe/component.go, pkg/odo/cli/dev/dev.go, pkg/odo/cli/feature/features.go, pkg/state/state.go, tests/helper/helper_dev.go, tests/integration/cmd_dev_api_server_test.go
=> Remove API Server from experimental mode, set UI Server as experimental

OWNERS, docs/OWNERS, docs/website/OWNERS, openshift-ci/build-root/OWNERS, scripts/OWNERS, tests/OWNERS
This makes sure the list is accurate, to avoid requesting PR reviews
from people no longer maintaining the project.
Ideally, I would put a GitHub team,
but this does not seem to be supported [1].
It can be done via an additional OWNERS_ALIASES file [2],
but this is yet to be tested.
[1] https://www.kubernetes.dev/docs/guide/owners/
[2] https://www.kubernetes.dev/docs/guide/owners/#owners_aliases
&mdash;
=> Cleanup OWNERS files

pkg/podman/version.go
/kind bug
There was a problem with the previous implementation; cmd.Wait() and reading the stdout pipe were executed in parallel, but because cmd.Wait() closes the std pipes before to return, this can make the reading of the pipe fail.
Fixes #6956 
=> Fix podman version check

pkg/remotecmd/kubeexec.go, pkg/remotecmd/kubeexec_test.go
/kind bug
This PR makes a command stopped appear as terminating normally. 
This is do by removing the remote pid file **before** to kill the process.
Fixes #6486
=> Makes stopped command terminate normally

cmd/odo/odo.go, pkg/odo/cli/list/list.go, tests/integration/generic_test.go
/kind bug
- --kubeconfig flag was introduced by mistake by using the library controller-runtime.
- This PR removes the check of the KUBECONFIG value for `odo list`, as this value can be a list of files. The check of the KUBECONFIG value is done by the `clientcmd` library used to get the Kubernetes config
Fixes #5732
Fixes #6700 
=> Remove kubeconfig flag

pkg/dev/podmandev/pod.go, pkg/dev/podmandev/pod_test.go, pkg/dev/podmandev/reconcile.go, pkg/podman/capabilities.go, pkg/podman/info.go, pkg/podman/interface.go, pkg/podman/mock.go
=> Do not set Memory limit on podman when cgroup is v1

pkg/apiserver-impl/starterserver.go
/kind bug
/area dev
This ensures the same local address is used for listening and checking if a given port is free.
Otherwise, `net.listen("tcp", ":$port")` would listen on `0.0.0.0:$port` (see output below),
and, on some operating systems like Windows 11, `127.0.0.1:$port` is surprisingly considered free.
```
PS C:\Users\asoro> netstat -aon | grep 2000
TCP    0.0.0.0:20000          0.0.0.0:0              LISTENING       11044
TCP    127.0.0.1:20001        0.0.0.0:0              LISTENING       11044
TCP    [::]:20000             [::]:0                 LISTENING       11044
```
This, as a consequence, made it impossible to run multiple Dev Sessions on Windows.
Using the same local address for listening and checking if …
=> Fix API Server port detection issue by making sure the same local address is used for listening and checking if the port is available

tests/helper/helper_generic.go, tests/helper/helper_kubectl.go, tests/helper/helper_oc.go, tests/helper/helper_podman.go, tests/helper/odo_utils.go, tests/integration/cmd_namespace_test.go
/area testing
A random namespace/project was created in the `namespace is created with -w` tests, but never deleted, thus increasing the likelihood of name collisions upon several subsequent runs.
This PR makes sure to delete such namespace/project and also makes other changes to be better resilient to similar issues in the future.
Fixes #7044
=> Fix potential namespace name collision issue with `odo create/delete/list/set namespace/project` tests

tests/examples/manifests/bindablekind-instance.yaml, tests/examples/source/devfiles/go/cluster.yaml
Sets a multiarch image for PostgreSQL Cluster instances, used during tests
/area testing
Fixes #7034
=> Use multiarch image for postgresql instance

pkg/odo/cli/alizer/alizer.go, pkg/odo/cli/delete/component/component.go, pkg/odo/cli/describe/binding.go, pkg/odo/cli/describe/component.go, pkg/odo/cli/init/init.go, pkg/odo/cli/list/services/services.go, pkg/odo/cli/preference/add/registry.go, pkg/odo/cli/preference/remove/registry.go, pkg/odo/cli/preference/set.go, pkg/odo/cli/preference/unset.go, pkg/odo/cli/preference/view.go, pkg/odo/cli/registry/registry.go, pkg/odo/cli/set/namespace/namespace.go, pkg/odo/genericclioptions/devfile.go, pkg/odo/genericclioptions/runnable.go, tests/helper/helper_filesystem.go, tests/integration/cmd_delete_test.go, tests/integration/cmd_describe_component_test.go, tests/integration/cmd_describe_list_binding_test.go, tests/integration/cmd_devfile_registry_test.go, tests/integration/cmd_list_services_test.go, tests/integration/cmd_pref_config_test.go
/kind bug
This PR makes the following commands not dependent of a devfile.yaml present in the directory:
- odo registry
- odo init
- odo analyze
- odo list services
- odo set namespace
- odo preference *
And these commande not dependent of a devfile.yaml if a name is specified with `--name`:
- odo delete component
- odo describe binding
- odo describe component
Fixes #6971
=> Add a Devfile dependency for commands

pkg/component/delete/delete.go, pkg/libdevfile/command.go, pkg/libdevfile/command_composite_parallel.go
/kind bug
/area devfile-spec
Fixes #6681 
See the repro steps in #6681. With the changes in this PR, the output of `odo dev` should reflect that the commands are running in parallel:
```
$ odo init \
--name my-component-with-parallel-commands \
--devfile-path https://gist.githubusercontent.com/rm3l/5691e926a4cfe37e369d93695187bdd6/raw/95abc768e83bd83e7acda035a6053f57b20f4939/devfile-with-parallel-commands.yaml
$ odo dev
[...]
•  Waiting for Kubernetes resources  ...
⚠  Pod is Pending
✓  Pod is Running
✓  Syncing files into the container [57ms]
✓  Building your application in container (command: …
```
=> Make sure to run parallel commands part of a composite command in parallel

pkg/apiserver-impl/devstate/content.go, pkg/apiserver-impl/devstate/content_test.go
/kind bug
Fixes #7079 
See the retro steps in #7079
=> Fix API Server panic when volume component has no `ephemeral` field set

pkg/deploy/deploy.go, tests/examples/source/devfiles/nodejs/devfile-autobuild-deploybydefault-no-deploy-cmd.yaml, tests/integration/cmd_devfile_deploy_test.go, tests/integration/interactive_deploy_test.go
/kind bug
/area deploy
When the Devfile does not have any `deploy` command but contains some components that are auto-applied (e.g., with `autoBuild` or `deployByDefault` set to `true`), `odo deploy` will try to apply them before ending up complaining that it could not find any `deploy` command.
This PR makes sure to check this before applying anything.
See #6743 for more context.
Fixes #6743 
See #6743 for the repro steps.
=> Make sure a Deploy command is present in the Devfile before auto-applying components

.github/dependabot.yml
/area dependency
This prevents warning messages displayed by Docusaurus when all the `@docusaurus/*` versions are not the same. This avoids having to manually do so (needed in https://github.com/redhat-developer/odo/pull/7112#issuecomment-1761753913), like in https://github.com/redhat-developer/odo/pull/6877#issuecomment-1586793246
Per https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/, Dependabot can create a single PR grouping multiple updates.
&mdash;
=> Group Dependabot updates to `@docusaurus/*` together

.github/dependabot.yml
/kind task
/area dependency
This instructs Dependabot to maintain dependencies for GitHub Actions as well. I noticed that some of the versions there are a bit outdated.
&mdash;
=> Instruct Dependabot to maintain dependencies for GitHub Actions

docs/website/docusaurus.config.js
This shows information about the last update on all documentation pages.
This can be useful to quickly determine if some page is still up-to-date or not.
&mdash;
**Preview**:
=> Show last update date on documentation pages

openshift-ci/build-root/Dockerfile, openshift-ci/build-root/README.md
Use build root tag compatible with oc 4.16 (and below).
Fixes #7242
=> Fix issue with OpenShift CI Interop tests failing due to error with glibc when executing any `oc` command

pkg/podman/inspect.go
/kind bug
This PR addresses an issue when using the `odo` commands with Podman, specifically related to the `podman pod inspect` command. Due to a recent change in Podman (see [podman PR #21514](https://github.com/containers/podman/pull/21514)), the output now returns a JSON array instead of a JSON object. This PR modifies `odo` to correctly handle this change, preventing errors in commands like `odo debug` and `odo logs` when running on Podman.
Fixes #7252
=> fix: manage podman inspect result as a list also
