README.md, plugin.yaml
This commit adds the plugin.yaml file to the root of the project
which can be copied to ~/.kube/plugins/ocdev/, thence enabling
ocdev as an oc plugin.
=> add plugin.yaml to be used as oc plugin

pkg/config/config.go
this is causing tests to fail
```
$ make test-coverage
./scripts/generate-coverage.sh
?   	github.com/redhat-developer/ocdev	[no test files]
?   	github.com/redhat-developer/ocdev/cmd	[no test files]
?   	github.com/redhat-developer/ocdev/pkg/application	[no test files]
/tmp/go-build735719731/github.com/redhat-developer/ocdev/pkg/config/_test/_obj_test/config.go:10:2: imported and not used: "reflect"
FAIL	github.com/redhat-developer/ocdev/pkg/config [build failed]
make: *** [test-coverage] Error 2
```
=> remove unused reflect from config pkg

cmd/app.go
This commit implements a `-q` flag for `application get` which
returns only the application name.
=> add short flag for `application get`

cmd/app.go
This commit makes application delete throw better error.
Also, removed logging and switched to printing.
=> Make `application delete` throw pretty errors

cmd/application.go
When doing `oc delete project`, the project is not immediately
deleted, while the command returns a 0 exit code immediately.
For this reason, this commit changes the word "deleted" to
"deleting" so the end user does not get confused when running
`ocdev application list` after `ocdev application delete`
=> Change deleted to deleting

cmd/component.go, pkg/component/component.go
This commit refactors the `ocdev component` parts to better print,
and also fixes the error when `ocdev component get` will not return
an error when no component is set
=> Refactor component to fix errors

pkg/occlient/occlient_test.go
This is a very poor fix for the flaky test, but I think this should
work for now. The test was "occasionally" failing because the order
in a map is not maintained, so the conversion to string was failing
at times. This commit fixes that.
=> Fix flaky test due to map to string operation

pkg/occlient/occlient.go
This commit removes the first line being printed at the top of the
output of `oc get project` in GetProjects() function.
=> Fix printing of `oc project` output in GetProjects

cmd/component.go, pkg/component/component.go, pkg/occlient/occlient.go
This commit implements `ocd component push` which lets the user
push the local or remote changes to the running application in
the OpenShift cluster.
=> Implement `ocd component push`

scripts/prepare-release.sh
when `make prepare-release` is run on travis check that `ocdev version` matches git tag version
I've forgot to change version when doing first release ;-)
=> check if binary has correct version when doing release

.travis.yml, Makefile, scripts/create-packages.sh, scripts/prepare-release.sh, scripts/upload-packages.sh
It creates binary packages, so they can't be used in any of the official distribution's repositories.
But they can be used in our repository to make it easier for users to install ocdev.
there are two types of packages
- build from master: version number is timestamp
(YearMonthDateHourMinuteSecond) those are uploaded to
ocdev-rpm-dev and ocdev-deb-dev repositories
- build from tag: those are released version and they have normal
semver version. They are uploaded to ocdev-rpm-releses and
ocdev-deb-releases repositories 
Packages are build and uploaded automatically by Travis.
PR with documentation on how to install it from repos will follow.
=> build  rpm and deb packages and upload them to repositories

cmd/application.go, pkg/application/application.go, pkg/component/component.go, pkg/config/config.go, pkg/config/config_test.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go
Applications are now grouped using labeles.
`app.kubernetes.io/name` is used for application grouping.
`app.kubernetes.io/component-name` is used for component grouping
It is also possible to add additional labels to applications.
Currently, there is  `app` label for OpenShift console.
fixes #85 #83
=> Allow multiple applications in one OpenShift project

.travis.yml
you can't run one deploy job for tags and master
=> travis - separate master and releases upload

README.md
From 2016, Apple is branding its OS as macOS. 
See https://en.wikipedia.org/wiki/MacOS.
=> Fixed macOS text

.travis.yml, README.md, docs/contributing.md, scripts/install.sh, scripts/test-install.sh
This commit adds an installation shell script to install ocdev
on Linux machines. The script currently downloads only the latest
ocdev release from GitHub.
related to https://github.com/redhat-developer/ocdev/issues/74
=> Add installation script to ocdev

cmd/root.go, pkg/notify/notify.go
Prior to this commit, the latest release information was fetched
from GitHub in a blocking manner, which means that even for a very
quick command like `ocdev version`, the tool would wait for a few
seconds before outputting the version, because the execution would
be blocked on waiting for the response from GitHub APIs.
This commit changes that and makes the request to GitHub
concurrent and non-blocking. This means that if the request has
not completed but the program execution has ended, then the tool
will exit gracefully without waiting for the request to complete.
However, if the program execution took longer than the request and
the response has been received by the goroutine before the program
execution is over, then, if applicable, the information is
printed.
Fixes #122
=> Get latest release info in a non-blocking manner

cmd/application.go, cmd/completion.go, cmd/component.go
Use the same naming pattern for all cobra commands variables.
The patter is camel-cased `<root command name><subcommand name>Cmd`. Example `applicationListCmd`.
=> Cleanup cobra names.

LICENSE, cmd/completion.go, cmd/component.go, cmd/root.go, cmd/version.go, main.go
We have (incomplete) copyright header in 5 files.
Removing it will at least make it consistent. If in future there is a
need to have it in files, we will add it to every file we have created.
There is also root LICENCE file, that is indicating what licence this
project is under.
=> remove copyright header from files

cmd/component.go
It was removed by mistake when refactoring cobra variables :-(
#132
=> Add back 'ocde component create' command

cmd/application.go, cmd/component.go, pkg/application/application.go
fixes #68 
Currently implemented as
```
ocdev component set <name>
ocdev application set <name>
```
In use case document this is used without subcommand like this:
```
ocdev application <name>
ocdev component <name>
```
But the problem with not using subcommand is that it puts restrictions on application names. For example, `list` can't be used as application name, because there is `ocdev application list` subcommand.
```
▶ ./ocdev application create list
Creating application: list
Switched to application: list
▶ ./ocdev application list
ACTIVE   NAME
f
app
myapp
*      list
```
I've chosen `set` as it is short and descriptive. I was also considering `activate` and `use`.
=> Allow setting active application and component

README.md, docs/advanced-installation-guide.md
- Move instructions on how to manually install ocdev repositories and packages to docs/advanced-installation-guide.md
=> README cleanup - splitting installation guide

cmd/application.go, cmd/component.go, cmd/create.go, cmd/push.go, cmd/storage.go
- change `component push` to `push`
Push is now a root level command as specified in use cases.
fixes #86
- change all `os.Exit(-1)` to `os.Exit(1)` 
(exit code should be between 0-255)
-  `ocdev app` and `ocdev component` shows current app/component
`ocdev application` is the same as `ocdev application get`
`ocdev component` is the same as `ocdev component get`
- add `ocdev create` as an alias for `ocdev component create`
=> update commands structure to match it to what is in use cases

.travis.yml, scripts/create-packages.sh
because of change in `ocdev version` output generated packages had an invalid version.
=> fix release automation

pkg/occlient/occlient.go
We should assume that if `oc whoami` returns an error code, then the user is not logged in regardless what output of `oc whoami` was.
fixes #125  and one part of #189
=> if 'oc whoami' retruns error assume that user is not logged in

cmd/component.go
default behaviour for `ocdev create <type>` is the same as running
`ocdev create <type> --dir ./`
related to https://github.com/redhat-developer/ocdev/issues/165
=> change `ocdev create` (`ocdev component create`) behaviour

cmd/application.go, cmd/component.go, pkg/application/application.go, pkg/component/component.go, pkg/config/config.go, pkg/config/config_test.go
This fixes bug where default application was created when listing apps or
just getting the current app.
- If `ocdev app` is run and there are no applications, a message is shown
informing user about this fact. Previously it showed that default application is active.
- When `ocdev create ...` is run and there are no application, default
the application is automatically created and used.
fixes #190 and #142 
TODO:
=> fix application list and get

README.md
This commit updates the outdated CLI structure in README.md with
the current structure generated using `make generate-cli-docs`.
=> Update CLI structure in README.md

docs/contributing.md, scripts/bump-version.sh
bump-version.sh is there to make it easier to changes version number when doing release.
It upates version number in README.md, cmd/version.go and install.sh.
=> add bump-version.sh script and update contributing.md

cmd/component.go, cmd/list.go, pkg/application/application.go, pkg/component/component.go, pkg/occlient/occlient.go
fixes #53 
fixes #191 
implements:
`ocdev component list`/`ocdev list` -  list component names in current application and their types 
```
▶ ./ocdev list
You have deployed:
nodejs using the nodejs component
ffff using the nodejs component
wildfly using the wildfly component
```
TODO:
=> implement 'ocdev component list'

cmd/component.go, cmd/push.go, pkg/component/component.go, pkg/occlient/occlient.go
When a component is created type and path to the source is saved to objects
annotations.
Later when `ocdev push` is called it detects what source was used and
uses the same source for a new build. (If it was a local source, the same dir is pushed to
BuildConfig, if it was built from remote git it starts new BuildConfig
with to rebuild from updated git.)
fixes https://github.com/redhat-developer/ocdev/issues/220
related to #222 and #221
=> Make push smart

cmd/url.go, pkg/component/component.go, pkg/occlient/occlient.go, pkg/url/url.go
This commit adds the `ocdev url create/delete/list` commands which
can be used to add URLs to components.
Underneath, these commands manage OpenShift route objects to
achieve this functionality.
Fix #231 #65
=> Add `ocdev url` command

scripts/generate-coverage.sh
run go test -i before running unit tests with coverage
this saves about 20%  `generate-coverage.sh` run time
=> speed up running unit tests on travis-ci

cmd/project.go, pkg/project/project.go
This commit renames the commands in project package to be more
consistent with the other packages.
- ListProjects() is now List()
- CreateProjects() is now Create()
=> Rename project commands

cmd/application.go, cmd/component.go, cmd/create.go, cmd/delete.go, cmd/list.go, cmd/project.go, cmd/root.go, cmd/storage.go, tests/e2e/e2e_test.go
This PR removes the `ocdev component X` commands for the following
commands:
```sh
Available Commands:
application Perform application operations
catalog     Catalog related operations
completion  Output shell completion code
create      Create new component
delete      Delete existing component
get         Get currently active component
help        Help about any command
list        List all components in the current application
project     Perform project operations
push        Push source code to component
set         Set active component.
storage     Perform storage operations
url         Expose component to the outside world
version     Print the version of ocdev
```
=> Remove all aliases to get/list/create/set/delete commands

pkg/application/application.go, pkg/component/component.go, pkg/url/url.go
This commit removes the extra return value of type error from the
GetLabels() function in package application and package component.
There was no case under which these functions could have failed,
and having the error as a return was not required.
=> Remove unnecessary return from both GetLabels()

Makefile, tests/e2e/e2e_test.go
Adds verbosity to the tests as well as command-line-outout:
```sh
▶ make test-e2e
go test github.com/redhat-developer/ocdev/tests/e2e -ginkgo.v
$ git clone https://github.com/openshift/nodejs-ex /tmp/ocdev807324634/nodejs-ex
Running Suite: ocdev test suite
===============================
Random Seed: 1522871416
Will run 9 of 9 specs
Usecase #5 ocdev project
should create a new project
/home/wikus/seafile/files/dev/go/src/github.com/redhat-developer/ocdev/tests/e2e/e2e_test.go:120
$ ocdev project create ocdev-1522871416
New project created and now using project : ocdev-1522871416
$ ocdev project get --short
ocdev-1522871416
•
------------------------------
Usecase #5 creating an application when application by the same name doesn't exist
should create an application …
```
=> Add a bit of verbosity to e2e tests

tests/e2e/e2e_test.go
This is a quick temporary fix to have a little bit more visibility into failing e2e tests.
related to #316 
This should help with figuring out what is happening with test in https://github.com/redhat-developer/ocdev/pull/303
=> use ginkgo's Fail instead of os.Exit in e2e tests

cmd/application.go, cmd/catalog.go, cmd/completion.go, cmd/component.go, cmd/create.go, cmd/delete.go, cmd/list.go, cmd/project.go, cmd/push.go, cmd/root.go, cmd/storage.go, cmd/update.go, cmd/url.go
The way errors are currently being handled in `package cmd` is
first the error is printed and then `os.Exit(1)` is called.
This is repeated pattern and makes a code unreadable to some
extent.
This commit extracts the error handling logic to a separate
function and calls that function whenever an error has to be
handled. This improved the readability by quite a bit.
=> Improve error handling in cmd/

pkg/application/application.go, pkg/component/component.go, pkg/url/url.go
This commit refactors the GetCurrentOrDefault() function to
GetCurrentOrGetAndSetDefault(), because every caller expects the
default application to be set to default.
=> Set application as default if current absent

cmd/storage.go, pkg/component/component.go, pkg/occlient/occlient.go, pkg/storage/storage.go, pkg/util/util.go, tests/e2e/e2e_test.go
This commit refactors the current implementation of `ocdev
storage` command to client-go.
=> Move storage to client-go

cmd/storage.go, pkg/storage/storage.go, tests/e2e/e2e_test.go
This commit renames the `ocdev storage add` command to `ocdev
storage create` command as per the original use case requirements
=> Rename storage add to storage create

.codecov.yml
Currently, we are not writing unit tests. 
Codecov check is failing for most PR, and it makes it hard to quickly see for what PR is Travis failing.
This will make sure that codecov check will be always green. We will enable this check again once we start requiring unit tests for every PR.
=> temporary set target codecov coverage to 0%

cmd/create.go
Updates the description for ocdev create with a bit more information.
=> Update desription for ocdev create

pkg/application/application.go, pkg/application/labels/labels.go, pkg/application/labels/labels_test.go, pkg/component/component.go, pkg/component/labels/labels.go, pkg/component/labels/labels_test.go, pkg/occlient/occlient.go, pkg/storage/labels/labels.go, pkg/storage/labels/labels_test.go, pkg/storage/storage.go, pkg/url/url.go
- move label handling to separate packages to avoid cyclic imports
- refactor `component.GetComponentDeploymentConfig` to `occlient.GetOneDeploymentConfigFromSelector`
This avoids importing component in storage pkg, so there is no risk of cyclic imports.
ping @containscafeine and @surajnarwade
=> Separate pkg for labels

cmd/create.go, pkg/catalog/catalog.go
This component first queries the catalog if the given component
type is supported or not. If the component type does not match
any name in catalog list, an error is thrown.
=> Check if component type exists before deploying

cmd/create.go, pkg/component/component.go, pkg/occlient/occlient.go, tests/e2e/e2e_test.go
fixes #327 
BuildConfig is created without any Triggers.
Build is started explicitly after component from git repo is created.
Build is NOT started if the component is created from a local directory.
Messages informing user what is happening was added.
How output looks like
local component:
```
▶ odo create wildfly
Component 'wildfly' was created.
To push source code to the component run 'odo push'
Component 'wildfly' is now set as active component.
```
git component:
```
▶ odo create nodejs --git https://github.com/openshift/nodejs-ex.git
Component 'nodejs' was created.
Triggering build from https://github.com/openshift/nodejs-ex.git.
Cloning "https://github.com/openshift/nodejs-ex.git" ...
Commit:	93fc25fd35068aa311f4722e4d7e5187b06edd7b (Merge pull request #170 from …
```
=> Don't automatically start build when component is created

cmd/describe.go, pkg/component/component.go
Resolves #196
As of now, it looks like,
```
$ ocdev component describe nodejs
Component nodejs with source in file:///tmp/nodejs-ex
This Component is externally exposed via nodejs-myproject.192.168.42.231.nip.io
```
=> Description of component using `describe` subcommand

docs/contributing.md
This commit adds the generate-cli-docs target to prepare-release
target. We can add the output of this to the release notes as
well as in the README.md at the time of the release.
=> Add generate-cli-docs to Makefile

cmd/create.go, cmd/link.go, cmd/watch.go
this will rename `ocdev`  to `odo` on comments and messages
=> rename ocdev to odo on comments and warning messages

cmd/update.go
=> Fixes the problem of a better description when no component is listed during update

cmd/version.go, pkg/occlient/occlient.go
Now odo version command will also show
the output of oc version command at the end
This will help users to get info about client and server
Fix a typo in runOcCommand
#72
=> Show client and cluster version also in odo version

pkg/component/watch.go
This decreases the delay between detecting file change and sync to 1 second.
There has to be at least some small delay between file change and triggering a sync.
One file edit actually triggers multiple fs events (WRITE, and multiple CHMODs), with no delay this triggers rsync multiple times. So there has to be at least some small delay 1 second is bearly noticeable by the user.
=> Decrease sync delay in watch to 1s.

cmd/version.go, pkg/occlient/occlient.go
This commit refactors the code to fetch version from the server to
- handle some previously handled errors
- move version info to a struct than an array of strings
=> Refactor server version code

tests/e2e/e2e_test.go
=> Fix infinite loop in e2e tests

cmd/storage.go, tests/e2e/e2e_test.go
rename `odo storage remove` to `odo storage delete`
for better consistency
ref: https://github.com/redhat-developer/odo/issues/391
=> rename storage remove to storage delete

cmd/list.go
changes the format of odo list command by using tabwriter for printing the output
fix https://github.com/redhat-developer/odo/issues/256
=> reformat output of odo list cmd using tabwriter

cmd/application.go, cmd/utils.go
=> Application Deletion will show what will be deleted

Makefile
Let's disable it, we are not looking at it anyway, and it has been just troubles in last two days.
https://github.com/golang/lint/issues/397
=> disable golint

docs/installation.md
Updates the installation document a little bit.
=> Update installation document

cmd/application.go, cmd/create.go, cmd/utils.go, cmd/utils_test.go
Fixes #431
* Reference taken from Kubernetes: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L3296
* Kubernetes resource name criteria: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/
=> Added validation for component and application name

pkg/occlient/occlient.go
Partially fixes #444, This PR will port `GetLabelValues` & `DeleteProject`
to client-go. so that it will remove dependency of `oc` binary.
=> Porting `GetLabelValues` & `DeleteProject` function to client-go

cmd/log.go, pkg/component/component.go, pkg/occlient/occlient.go, tests/e2e/e2e_test.go
This adds a new command `odo log` which will display the
DeploymentConfig logs for that particular component.
For example:
```sh
github.com/redhat-developer/odo  add-logs ✔                                                                                                                                                                                                                                                                                                                         15h55m
▶ ./odo list
ACTIVE     NAME        TYPE
*          nodejs3     nodejs
github.com/redhat-developer/odo  add-logs ✔ …
```
=> Adds DeploymentConfig log functionality to Odo

cmd/storage.go, pkg/occlient/occlient.go, pkg/storage/labels/labels.go, pkg/storage/storage.go
This commit adds `ocdev storage unmount` command, which will
unmount the given storage from a component. For implementing this,
an Unmount() function has been introduced in the storage package.
Other parts of code have also been refactored to use the Unmount()
function for much clearer logic.
storage.Remove() has been refactored to first use Unmount(), and
then delete the PVC. The logic looks much cleaner now. Also, to
remove all the components, List() is being used.
Also, introducing the unmount command led to a refactor in
storage.List(), because before this commit all the PVCs with the
relevant labels for storage were being printed, but this commit
decouples this logic from PVCs to the Deployment Config associated
with the component. So, the unmounted storage is no longer being …
=> Add `ocdev storage umount` command

cmd/application.go, cmd/component.go, cmd/project.go, pkg/occlient/occlient.go
Fixes #274
Now,
```
odo project xyz
odo component abc
odo application pqr
```
they will work same as `set` operation.
=> Added consistency in commands for project, application & components

cmd/storage.go, pkg/storage/storage.go, tests/e2e/e2e_test.go
=> Added confirmation for storage deletion

cmd/delete.go, pkg/application/application.go, pkg/component/component.go, pkg/occlient/occlient.go
Partially fixes #444, This PR will port Delete function to client-go, so that it will remove dependency of `oc` binary
to client-go. so that it will remove dependency of oc binary.
=> Porting `Delete` function to client-go

cmd/url.go, tests/e2e/e2e_test.go
Solves #474
```
odo url delete nodejs
Are you sure you want to delete the url nodejs? [y/N] y
Deleted URL: nodejs
```
=> Added confirmation before deleting URL

.travis.yml, scripts/test-install.sh
`test-install.sh` was not returning error exit code when something failed
=> enable macos install test and fix test-install.sh

cmd/application.go, cmd/catalog.go, cmd/completion.go, cmd/component.go, cmd/create.go, cmd/delete.go, cmd/describe.go, cmd/link.go, cmd/list.go, cmd/log.go, cmd/project.go, cmd/push.go, cmd/root.go, cmd/storage.go, cmd/update.go, cmd/url.go, cmd/version.go, cmd/watch.go
Separates the commands into appropriate categories.
Example:
```sh
Usage:
odo [command]
Examples:
git clone https://github.com/openshift/nodejs-ex && cd nodejs-ex
odo push
odo url create
Component Commands:
component   Components of application.
create      Create a new component
delete      Delete an existing component
describe    Describe the given component
link        Link target component to source component
list        List all components in the current application
log         Retrieve the log for the given component.
push        Push source code to a component
update      Update the source code path of a component
watch       Watch for changes, update component on change
Other Commands:
app         Perform application operations
catalog     Catalog related …
```
=> Improve CLI --help documentation

cmd/log.go, pkg/component/component.go, pkg/occlient/occlient.go
This adds the --follow or -f command to `odo log` in order to stream logs
as they are being built for DeploymentConfig.
=> Adds --follow command to odo log

pkg/occlient/fakeclient.go, pkg/occlient/occlient_test.go
=> add unit test for CreatePVC

cmd/storage.go, pkg/storage/storage.go
Issue : https://github.com/redhat-developer/odo/issues/493
=> Adds the functionality of unmounting storage using the mounted path.

tests/e2e/e2e_test.go
Changes the ambiguous "usecase5" name to "testing". Also adds a constant
to the e2e_test.go file.
=> Change usecase5 to testing app name for e2e tests

pkg/url/url_test.go
=> add unit test for url.Delete

cmd/root.go, pkg/occlient/occlient.go
Adds --skip-connection-check parameter to ignore `oc` checking for
logged in status / cluster is online.
=> Add --skip-connection-check parameter

pkg/occlient/fakeclient.go, pkg/occlient/occlient_test.go
=> add unit test for DeletePVC

cmd/application.go
As of now,
```
$ odo app
There's no active application.
You can create one by running 'odo application create <name>'.✔ ~/go/src/github.com/redhat-developer/odo [without-storage-name L|⚑ 20]
```
This PR will add newline here so that output will be like,
```
$ odo app
There's no active application.
You can create one by running 'odo application create <name>'.
✔ ~/go/src/github.com/redhat-developer/odo [without-storage-name L|⚑ 20]
```
=> fixed newline in `odo app`

.codecov.yml
Enable code coverage checks.
Let's start with auto settings, we can adjust as we go.
=> enable codecov.io coverage checks

cmd/cmdutils.go
according to this[0] comment, there is no error handling if there is no current component or there is no any component created.
This PR will resolve this issue.
[0] https://github.com/redhat-developer/odo/pull/541#issuecomment-400564871
=> Handle error when no component is there

docs/examples.md
There was no documentation on how to deploy a binary, I've added a small
tutorial on how to deploy a test application.
=> Adds an example on how to deploy a binary

cmd/create.go, cmd/push.go, pkg/component/component.go, pkg/occlient/occlient.go
Adds io.Writer to the FollowBuildLog function. This follows the
convention of only passing in `stdout` from either `color.Output` or
`os.Stdout`.
=> Adds io.Writer to FollowBuildLog function

pkg/occlient/occlient.go
add validation to dc before dereferencing pointers
=> add validation to dc before dereferencing pointers

pkg/occlient/occlient.go
remove double `buildSource` definition
in `BootstrapSupervisoredS2I`
closes #537
=> remove double `buildSource` definition

.travis.yml, Makefile, cmd/update.go, pkg/component/component.go, pkg/occlient/fakeclient.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, tests/e2e/e2e_test.go
To achieve this, two functions have been added SetupForSupervisor and CleanupAfterSupervisor in occlient.go. Also some other functions are added in occlient to add and remove initContainers, volumeMounts and volumes to the deploymentConfig. Also updateDcAnnotations in occlient is added to update the annotations in the deploymentConfig.
Issue: https://github.com/redhat-developer/odo/issues/439
=> Fixes odo update from git to binary/local and vice versa

pkg/config/config.go
rename configEnvName in config.go to `ODOCONFIG`
rename func getOcdevConfigFile in config.go to getOdoConfigFile
=> rename configEnvName & func getOcdevConfigFile in config.go

cmd/push.go
Issue: #571 
Adds a warning/error message when pushing local component to a component with a git repo or binary file as source in buildConfig
=> Adds a warning/error message when pushing local component 

pkg/occlient/fakeclient.go, pkg/occlient/occlient_test.go
Adds test for `NewAppS2I`, `GetImageStreams` func in `pkg/occlient/occlient.go`
=> Imagestream and Buildconfigs unit tests

cmd/catalog.go, pkg/catalog/catalog.go, pkg/catalog/catalog_test.go, pkg/testingutil/imagestreams.go
When using `odo catalog list` the tags will now be listed:
```
github.com/redhat-developer/odo  add-versioning ✗                                                                                                                                                                                                                                                                                                                    7d ⚑  ⍉
▶ ./odo catalog list
NAME        TAGS
dotnet      2.0,latest
httpd       2.4,latest
nginx       1.10,1.12,1.8,latest
nodejs      0.10,4,6,8,latest
perl        5.16,5.20,5.24,latest
php         5.5,5.6,7.0,7.1,latest
python      2.7,3.3,3.4,3.5,3.6,latest
ruby        2.0,2.2,2.3,2.4,latest
wildfly     10.0,10.1,8.1,9.0,latest
```
=> Show tags / versions when doing odo catalog list

cmd/url.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/url/labels/labels.go, pkg/url/labels/labels_test.go, pkg/url/url.go, pkg/url/url_test.go, tests/e2e/e2e_test.go
Issue: #520 
This revamps the URL command and adds support for custom names for url. It also adds a component flag to the create command for URL to specify the component. It also changes the behaviour of the odo delete command and now a component flag can be passed to delete the url from or else the current component is used.
=> Revamps the URL command and adds support for custom names for url.

pkg/occlient/occlient.go, pkg/occlient/occlient_test.go
Most validations for the image name were being made by the parseImageName
func of occlient.go. However, the case for its emptyness and incompleteness
with just a separator were accidentally left out.
This PR adds the validations for the same and also adds UT cases to validate
the validations are as intended.
fixes #581
=> Add empty image name validation

cmd/create.go, pkg/component/component.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, tests/e2e/e2e_test.go
Issue : #552 
Adds option to allow users to specify port when component is created and the flag is used as 
```
odo create nodejs --ports 8080/tcp,8081,9100/udp
```
If the ports flag is not used than the ports, that are exposed by the given image, is used.
It adds a new function getContainerPortsFromString which takes a string array containing the port string e.g 8080/tcp,8081,9090/udp and returns the ContainerPorts or error. If no protocol is passed, tcp is considered as default.
=> Adds option to allow users to specify port when component is created

cmd/create.go, pkg/catalog/catalog.go, pkg/catalog/catalog_test.go, pkg/component/component.go, pkg/component/labels/labels.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, tests/e2e/e2e_test.go
This adds the ability to pick both the image as well as the image
version when deploying, for example, using `odo create nodejs:8 foobar`
=> Adds ability to pick version when deploying

Makefile, tests/e2e/e2e_test.go
In this PR, we do away with http calls on IP:Port (which failed on minishift), but instead create a route using `odo url` and then run curl on that url.
=> Fixing e2e tests on minishift:

pkg/component/component.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go
This:
- Changes label retrieval for GetComponentSource from usin BuildConfig
to DeploymentConfig (not all deployments use BuildConfig)
- Renames GetBuildConfig to GetBuildConfigFromName
- Adds project param to GetDeploymentConfigFromName function in order
to be similar / the same as GetBuildConfigFromName
=> Retrieve labels via DeploymentConfig not BuildConfig

cmd/create.go, tests/e2e/e2e_test.go
To make it align with `odo url create` it is better to have flag as singular, even tho multiple ports can be specified.
When `odo create --port 8080 --port 9090` form is used it also makes more sense to have it singular.
=> rename '--ports' flag for 'odo create' to singular '--port'

cmd/create.go
The odo create command documentation suggests usage of
odo component list instead of odo catalog list. This PR
fixes the same.
fixes #645
=> Fix the odo component creation documentation

pkg/application/application.go
Made the verbal part grammatically correct and corrected some misspelled words.
=> Corrected spelling mistakes and some grammatical errors.

cmd/cmdutils.go, cmd/storage.go, pkg/storage/storage.go, tests/e2e/e2e_test.go
This will list all the storages in all the components in a
current application and project
Syntax will be odo storage list --all
on execution of odo storage list --all componentName it will fail
Fixes #507
=> Add odo storage list --all command feature

cmd/catalog.go, cmd/service.go, pkg/occlient/fakeclient.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/service/service.go, tests/e2e/demo_test.go
Fixes #266
Signed-off-by: Suraj Narwade <surajnarwade353@gmail.com>
This PR adds the support for creating services from service catalog. for this support, we have used
client from [kubernetes-incubator/service-catalog](https://github.com/kubernetes-incubator/service-catalog).
Currently, we are supporting template service broker only. In future, we will add support for
other brokers as well.
We have added entire new command set for this purpose.
* to check available services in service catalog
```
$ odo service catalog
```
* to create service,
```
$ odo service create mysql-persistent
```
* to delete service,
```
$ odo service delete mysql-persistent
```
* to list the current provisioned services with their status
```
$ odo service list
```
=> Add support for creating component from service catalog

README.md, docs/cli-reference.md
Added respective command reference related to service catalog in `cli-reference.md`
under docs section
=> Add CLI-reference related to service catalog

Makefile
This PR adds vendor-update command to Make, so that
we can simply update vendor using `make vendor-update` command
=> Added vendor-update command to makefile

cmd/catalog.go, cmd/create.go, docs/getting-started.md, pkg/catalog/catalog.go, pkg/catalog/catalog_test.go, pkg/component/component.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/util/util.go, pkg/util/util_test.go, tests/e2e/e2e_test.go
This PR considers imagestream in current namespace along with
imagestreams in openshift namespace for:
1. catalog listing i.e, `odo catalog list` is now expected to show items in local
namespace along with those in openshift namespace
2. component create i.e `odo create <comp_name> --git <git_url>` is expected
to work even if comp_name is present in current namespace but not in openshift
namespace
fixes #566
=> Include imagestreams in current namespace for catalog listing

cmd/root.go, docs/development.md, docs/logging.md
This PR adds the following information:
1. Enhancements in odo create command added to docs/cli-reference.md
2. docs/logging.md describes about the use of glog for logging
fixes #667
=> Add documentation for logging in odo and odo create enhancements

cmd/push.go, cmd/watch.go, pkg/component/component.go, pkg/occlient/occlient.go, pkg/util/util.go, pkg/util/util_test.go
=> Fix create, push and watch commands on windows

pkg/notify/notify.go, pkg/notify/notify_test.go
Modify getLatestReleaseTag function to
fetch version using raw.github* URL
=> Change version checker to use rawURL instead of calling API

Makefile
Adds a `make clean` command that removes the odo binary in the folder as
well as the `dist` folder where compiled binaries go.
Closes https://github.com/redhat-developer/odo/issues/102
=> Adds 'make clean' command

cmd/application.go
Modifies the help description to keep in-line with `odo list`
Closes: https://github.com/redhat-developer/odo/issues/644
=> Update description for odo app list

cmd/catalog.go, cmd/service.go, pkg/occlient/occlient.go, pkg/service/service.go
Since PR 413 is merged, there were few minor comments charlie mentioned later.
Those comments are addressed in this PR.
=> Improve service catalog related stuff from PR 413

docs/development.md
Add Unit test documentation to deployment.md
=> Add unit test doc

pkg/notify/notify_test.go
=> Fix latestReleaseTag() unit test

docs/development.md
We had some troubles following the current instructions and thus these
new instructions go into more detail (as well as what order to go in for
the Homebrew package).
=> Update the release documentation for Odo.

cmd/watch.go
Fix watch support check
This PR fixes a regression which wrongly validated sourcepath against the sourcetype(local)
The PR now checks if sourceType is local or binary and allows watch to be created
fixes #746
=> Fix watch support check

.travis.yml, pkg/application/application.go, pkg/component/watch.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/testingutil/deploymentconfigs.go
fixes #767
Updates the go version to 1.11 in travis.yml as go fmt is not detecting many errors. This PR also fixes the current go fmt errors.
=> Update go version to 1.11 in .travis.yaml and fix current go fmt errors

pkg/component/component.go
Fixes #402 
Switching to color.output in PushLocal as color.output passed to the function and cast to io.writer is not working on windows. Will solve this in future by moving this more upstream in code at cmd/create.go.
Note : Windows Power Shell doesn't seem to support **FgYellow** color and so the text in not colored in case of power shell but the weird unknown characters are gone. For CMD, the color works fine.
https://superuser.com/questions/1202003/some-git-colors-dont-work-in-powershell-why
=> Fixes the color issue on Windows for odo push.

cmd/project.go, tests/e2e/e2e_test.go
fixes : #758
It removes the new line from the short flags for `project get`
=> Removes a new line from the project get short flag

cmd/watch.go, pkg/component/watch.go, pkg/component/watch_test.go, pkg/occlient/occlient.go
Make odo watch command configurable
This PR makes the list of filepath patterns to be ignored
and also the watch-push delay configurable which can now be
passed as arguements to the command. It also performs the
following fixes to the watch command:
1. Ignore watch on directories and files matching the ignore paths
2. Avoid pushing changes in files and folders that match ignore paths
2 above is required in-spite of 1, because, 1 can only ignore paths
that match the ignores along with their children but not their parents.
So, the watch on parent dir still can potentially catch a change in its
immediate child which can only be ignored at the time of push.
fixes #639 #640
=> Configurable watch

appveyor.yml
Adds  appveyor.yml file.  This defines tests running on Windows using appveyor.com
Right now it just setups environment and runs unit tests.
This is the first step. After this, we can start figuring out how to run e2e tests there.
related to #401
--
Right now [link](https://ci.appveyor.com/project/kadel/odo
) to the ci jobs contains my nick, I'm not sure why I'll look into it later. But it shouldn't be a blocker preventing this to be merged.
https://ci.appveyor.com/project/kadel/odo
=> Run unit tests on Windows using Appveyor

cmd/root.go
example of how the latest notification looks like
```sh
$./odo catalog list components
NAME        PROJECT       TAGS
dotnet      openshift     2.0,latest        
httpd       openshift     2.4,latest  
nginx       openshift     1.10,1.12,1.8,latest
nodejs      openshift     0.10,4,6,8,latest       
perl        openshift     5.16,5.20,5.24,latest
php         openshift     5.5,5.6,7.0,7.1,latest
python      openshift     2.7,3.3,3.4,3.5,3.6,latest
ruby        openshift     2.0,2.2,2.3,2.4,2.5,latest
wildfly     openshift     10.0,10.1,11.0,12.0,8.1,9.0,latest
---                                   
A newer version of odo (version: 0.0.12) is available.
Update using your package manager, or run
curl https://raw.githubusercontent.com/redhat-developer/odo/master/scripts/install.sh | sh
to …
```
=> Add info to turn off update notification

cmd/catalog.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/service/service.go
This PR modifies `service catalog list services` command to show corresponding plans
to services,
For example,
```
$ odo catalog list services
NAME                         PLANS
dh-gluster-s3-apb            default
dh-nginx-apb                 default
dh-proxy-config-apb          passthrough,custom
dh-eclipse-che-apb           prod
dh-galera-apb                persistent,ephemeral
```
=> Modify service catalog list to show plans

pkg/component/watch.go
A break from select case with signal handling causes complete
exit from receiving that particular signal. So avoid break from
select case with signal handling.
fixes #796
=> Fix watch command

scripts/prepare-release.sh
This PR adds CHECKSUM file to the release page.
Currently, everything in dist/release/ on the build machine(travis) is
pushed to release page as in the `deploy` job config in travis configuration
So, this PR just loops around contents of dist/release and generates sha256
for each file in the folder and puts them in a file by name CHECKSUM in the
same path(dist/release/) expecting it to be uploaded to the release page.
fixes #736
=> Add CHECKSUM file to the release page

cmd/service.go
fixes #810 
This PR makes `odo service delete` accept exactly one argument to stop it from crashing when no argument is passed.
=> Added support for exact one  argument in service delete

cmd/service.go, pkg/service/service.go
fixes #811 
Removed the unused parameter from service/service.go and cmd/service.go
=> Removed unused parameter from DeleteService()

cmd/completion.go, cmd/root.go
This PR implements the requirement in #77 but also goes on step further.
It provides bash completion support to:
* `odo create`
- By providing the available components (essentially using `odo catalog list components`)
* `odo service create`
- By providing the available services (essentially using `odo catalog list service`)
* `odo project delete|set`
- By providing the available projects (essentially using `odo project list`)
* `odo storage delete|mount|unmount`
- By providing the available storage objects (essentially using `odo storage list`)
* `odo url delete`
- By providing the available url (essentially using `odo url list`)
=> Add implementation of bash completion for a few commands

cmd/project.go, pkg/occlient/fakeclient.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/project/project.go, pkg/project/project_test.go, pkg/testingutil/configs.go, pkg/testingutil/projects.go, tests/e2e/cmp_test.go, tests/e2e/e2e_test.go
Delete project enhancements + Unit tests and e2e tests
This PR adds the following:
1. When a project is deleted, the delete project now displays also the
active project post deletion if there are more projects left post deletion
2. Adds UTs and e2e tests for project delete
3. Handles the case of project list with no projects with a proper message
indicating that there are no currently available projects and suggests the
command to create a project instead of displaying an empty table.
fixes #726 #750
=> Enhance project delete + Add UTs

cmd/root.go, cmd/version.go, pkg/occlient/occlient.go, tests/e2e/e2e_test.go
odo version shows the server version without logging in.
fixes #690
First login and logout from a cluster, then 
run `odo version` - verify it shows the server version.
disconnect from the network and make the server not reachable from the machine where you are running odo
run `odo version` - verify it shows `Unable to connect to OpenShift cluster, is it down`
=> fix #690 : odo version shows server version without logging in

pkg/occlient/occlient.go, pkg/occlient/occlient_test.go
In order to allow base64 encoded environment variables, only the first encountered `=` is used for the string split. This has the side-effect of reading in `key1=value1=value2` as `{"key1": "value1=value2"}`, but does allow, for example, ssh keys to be passed in as env vars.
No
make test
=> Split env vars only by the first `=` to allow for base64-encoded values

cmd/catalog.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/service/service.go, pkg/service/service_test.go, pkg/util/util.go, pkg/util/util_test.go
fixes #689 
Added the odo catalog describe service command e.g `odo catalog describe service <service-name>`
Functions GetClusterServiceClass() and GetClusterPlansFromServiceName() are added to occlient to get the service class and the plans associated with the class.
How to test : 
1. odo catalog list services      //select a plan name
2. odo catalog describe service <service-name>
=> Added the odo catalog describe service command

README.md
For some reason, `####` was added for the index page.
It's been removed so there are no newlines for Odo.
=> Update README index

cmd/application.go, cmd/cmdutils.go, cmd/component.go, cmd/create.go, cmd/delete.go, cmd/describe.go, cmd/link.go, cmd/list.go, cmd/log.go, cmd/project.go, cmd/push.go, cmd/root.go, cmd/service.go, cmd/storage.go, cmd/update.go, cmd/url.go, cmd/watch.go, pkg/application/application.go, pkg/component/component.go, pkg/config/config.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/project/project.go, pkg/service/service.go
This PR does:
* Adds flags `project`, `application` and `component` flag to respective commands
* added `getProjectName` and `getAppName` reusable functions which looks for `project` or `application` flag first, if not provided then it gives current value by default.
* Provide comments to some of the exported functions
* Refactors the way we provide `namespace` value for methods in `occlient.go`.
(No method will accept namespace as a argument, whenever needed we will use `client.Namespace` value)
* Updated unit tests as per new refactoring
-- edit by @kadel 
https://github.com/redhat-developer/odo/issues/656
=> Refactoring code and added flags `project`, `application` &  `component` 

cmd/config.go, pkg/config/config.go, pkg/config/config_test.go, pkg/occlient/occlient.go, tests/e2e/e2e_test.go
add a parameter for modifying default connect check timeout 
```sh
$ odo utils config set timeout 9
$ odo utils config set timeout 0
Cannot set timeout to 0 setting it to the minimum value(1sec)
$ odo utils config view 
PARAMETER             CURRENT_VALUE
UpdateNotification    false
Timeout               1
```
=> add config parameter to modify server connection check timeout

cmd/catalog.go, pkg/service/service.go, pkg/service/service_test.go
We now include all the information about parameters of a service plan in the internal data structures.
The information is displayed to the user via `odo catalog describe service ...` but could definitely use an improvement in that area :)
#880 
Have the service catalog installed in the cluster you are using. Use any service in
`odo catalog describe service ...` to view the output.
=> Enhance the odo service describe

pkg/occlient/occlient.go
this pr will update supervisord image to use v0.2.0
which will fix issue #840 
#840 
build this pr or download binary from the  AppVeyor build artifacts [here](https://ci.appveyor.com/project/kadel/odo/builds/19935811/artifacts) and try deploying the example code mentioned in issue #840 
and validate if the stderr logs are being shown on `./odo logs`
=> update supervisord image to use v0.2.0

cmd/root.go, cmd/service.go, docs/completion-architecture.md, pkg/odo/util/client.go, pkg/odo/util/completion/completion.go
The previous implementation only used the command's name as key which
wasn't enough. This implementation requires the command hierarchy to be
resolved before the registration process as the key is generated by
walking back to the root command. The implementation will exit with an
error message if registration happens before the hierarchy is set.
#903 
Before the change: `odo create <tab>` would result in showing service class names as completions. 
After the change: `odo create <tab>` properly doesn't show any completions while `odo service create <tab>` still shows the service class names as completions.
=> Fix #903: rewrite completion handler key generation to avoid collisions.

cmd/service.go, docs/completion-architecture.md, pkg/odo/util/completion/completion.go
It should now work even the command hierarchy is not complete and the
code is also simpler. Win! :)
Fix #913 
#913 
Completion should still work as before with the added bonus that completion handlers can now be registered as soon as the target command is created.
=> Fix #913: fix completion handler key generation.

cmd/url.go, pkg/util/util.go
This function adds the --open parameter to `odo url create`.
This will open the created link on the user's default browser.
To test:
```sh
odo url create --open
```
Closes https://github.com/redhat-developer/odo/issues/905
=> Open created url with --open

cmd/watch.go, pkg/component/component.go, pkg/component/watch.go, pkg/component/watch_test.go, pkg/occlient/occlient_test.go, pkg/testingutil/fileutils.go, scripts/generate-coverage.sh, tests/e2e/cmp_test.go, tests/e2e/e2e.go
Add unit tests for the following functions:
1. makeTar: The test for this function:
i. creates requested dir structure with files and folders with some data put in.
ii. tars the dir structure created.
iii. untars the tar using another utility created in testingutil/fileutils.go#UntarAll
iv. Verifies contents obtained from iii to those in i.
This test has been pulled from https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/cp/cp_test.go
2. WatchAndPush: The test for this function:
i. Creates a temporary component source directory structure
ii. Mocks implementation of PushLocal to only use compare the diff set against the expected ones
iii. Creates, deletes and modifies some files and folders
iv. Ignores some files and folders specified using regexp
v. Also, stops the watch …
=> Add e2e and unit tests for `odo watch` command

pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, tests/e2e/cmp_test.go
This fixes an intermittent bug of `odo update` failing due to Odo being
"too fast" on CI / local machines and not waiting for OpenShift to
update the correct annotation labels.
Closes: https://github.com/redhat-developer/odo/issues/835
=> Fix intermittent bug of `odo update` failing

cmd/version.go, pkg/occlient/occlient.go
Change version command to tolerate missing possible /version/openshift
This is done because a cluster created with "oc cluster up" can in some
cases (as is the case for OKD 3.11) the endpoint is missing completely
and we don't want the tool to fail in such cases (following the example
set by oc)
#872
Launch Minishift using OKD 3.11.
Doing `odo version` should now yield all the expected output, except the `Openshift:....` line (which is the same behavior you'll see with `oc version` as well).
When applying `odo version` against a proper Openshift cluster, or even one launched by Minishift that uses OKD 3.10, the `Openshift: ....` should be present
=> Change version command to tolerate missing possible /version/openshift

README.md
Removes the "Why Did we Create Odo" section and cleans up the README so
it's more concise / smaller.
I believe that there's *too much* text and multiple paragraphs that iterate
over the same concept (Odo is fast, it reduces development time, etc.).
Having a few sentences / list of features is more than enough.
=> Removes Why Did We Create Odo and cleans up README

cmd/link.go, pkg/component/component.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/secret/secret.go, pkg/secret/secret_test.go
This is done by making `link` always "inject" a secret into the
DeploymentConfig of the source component.
In the case of services, the secret is created indirectly via the
ServiceBinding (this was implemented in #723).
In the case of components, the secret is created when when we create
the component. In such cases on secret is created per exposed port.
Fixes: #652 (see [this](https://github.com/redhat-developer/odo/issues/652#issuecomment-431317769) and [this](https://github.com/redhat-developer/odo/issues/652#issuecomment-431452720))
To test the changes:
For component to component linking:
1. Create a backend application
2. Create a frontend application
3. `odo link --to-component backend`
4. Exec into the frontend pod and make sure `COMPONENT_BACKEND_HOST=backend-app`
For component to …
=> Make link handling common across both components and services

tests/e2e/cmp_test.go
This is just quick ugly fix to make test passing again.
It should be removed once we make `waitForPodTimeOut` timeout configurable.
Check https://github.com/redhat-developer/odo/pull/943 for more details.
=> e2e test: Ugly and temporary fix for timeout issue during odo push.

cmd/link.go
Corrects the link documentation with the correct examples (library /
component source FIRST and then the name..)
=> Correct link documentation

cmd/create.go, pkg/odo/util/completion/completionhandlers.go
fixes #960 
This completion handler is added to the create command for the local and binary flags.
=> Added completion support for files and directories.

tests/e2e/e2e.go, tests/e2e/service_test.go
This is done because odo's part in deleting a service from the service
catalog ends with it's deletion of the serviceinstance, the actual
delete process is not something odo has any control of, so waiting
for the service to actually be deleted doesn't test odo, but Openshift.
No. This work was performed because we have noticed that the integration test in Travis sometimes timeout waiting for the service to be deleted
Nothing to test in odo proper. The service-catalog e2e tests should now never fail in delete operation
=> Decouple service catalog e2e tests from the the actual Openshift delete

cmd/application.go, pkg/odo/util/completion/completionhandlers.go
command completion for `odo app` commands
command completion for `odo app`
`odo app describe <tab>`
=> Added command completion for `odo app` commands

tests/e2e/cmp_test.go
replacing  wget with curl in e2e tests, because wget is not present in macOS
Resolves #933
=> Using curl instead of wget

Makefile, tests/e2e/cmp_test.go, tests/e2e/e2e_test.go
This PR attempts to reduce the flakiness of the component end-to-end tests.
The source of flakiness that was identified and fixed with this PR was a race condition that was being incurred when updating a component a quick succession.
No, but the team has been experiencing lots of flakiness the past few weeks
**How to test changes?**
This PR does not touch odo proper. All tests should now pass without flakiness
=> Attempt to fix cmp e2e test flakiness

cmd/link.go, cmd/service.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/service/service.go, pkg/service/service_test.go, tests/e2e/e2e.go, tests/e2e/service_test.go
This PR makes the handling of `odo link` better for the user.
This is done by doing the following:
* Provide a `wait` flag that when enabled wait for the service to be provisioned and the secret to be created, before updating the DeploymentConfig. If the flag is not enabled, the command fails with the appropriate message
* Slightly improve the error messages to give even more information about what is going on
* Provide some "smart" statuses (as part of `odo service list`) for the Services that have been linked and / or bound. This makes it easier for the user to determine the status of the service provisioning
Fixes: #846
=> Improve odo link support

cmd/application.go, cmd/catalog.go, cmd/cmdutils.go, cmd/component.go, cmd/create.go, cmd/delete.go, cmd/describe.go, cmd/link.go, cmd/list.go, cmd/log.go, cmd/project.go, cmd/push.go, cmd/root.go, cmd/service.go, cmd/service_test.go, cmd/storage.go, cmd/update.go, cmd/url.go, cmd/version.go, cmd/watch.go, pkg/odo/genericclioptions/context.go, pkg/odo/genericclioptions/fakecontext.go, pkg/odo/util/client.go, pkg/odo/util/completion/completion.go, pkg/odo/util/completion/completionhandlers.go
== What is the purpose of this change? What does it change?
Introduces a new `Context` struct to hold project, application and component information based on specified flags. This should simplify the commands a bit and ultimately, this structure should be passed as an argument to lots of functions which currently take a client, project, application or component name as arguments. This work also targets #871 
== Was the change discussed in an issue?
No
== How to test changes?
External behavior shouldn't change.
=> Factor out creation of contextual information (project, application, component) to make it easier to manage and facilitate refactoring of commands

cmd/logout.go
Because #699 wasn't properly rebased and up to date with master branch, we ended up with failing build. This fixes that.
=> Use context in logout command (fix failing build)

scripts/install.sh
See subject ;)
No.
Nothing to do, should just improve diagnosing test errors when building from brew.
=> Display odo version when installing via brew.

tests/e2e/e2e.go, tests/e2e/service_test.go
Robustness is improved by introducing an extra wait step for the
ServiceInstance.
Completeness is improved by updating the list test to take into account
the detailed status. This is needed because of #847 was merged
No
**How to test changes?**
Not part of odo proper, this only affects the e2e tests
=> Update the service catalog test to take into account the detailed status and improve robustness

docs/getting-started.md
Corrected the incorrectly mentioned `oc import` to `oc import-image` in the custom builder readme section
No
No need to test the changes
=> Corrected the import command in readme

tests/e2e/cmp_test.go, tests/e2e/e2e_test.go
Now we wait until there are no pods of the old replication controller
running before updating a DC
No. But we are all feeling the pain of flaky tests
**How to test changes?**
Nothing to test in `odo` proper
=> Add an even more strict policy of waiting for dc updates

cmd/service_test.go, docs/completion-architecture.md, pkg/odo/util/completion/completion.go, pkg/odo/util/completion/completionhandlers.go
Update documentation.
Fix #984 
#984 
Completion handlers should now have a properly initialized context.
=> Properly init context and improve information provided to handlers.

.travis.yml
This test at its current form it is just wasting resources without
adding any benefit. It tests latest released version over and over
again.
=> Temporary disable installation script test

cmd/url.go, pkg/odo/util/completion/completionhandlers.go
Add go completion for odo url delete
#938 
```
make install
odo create ....
odo url create ...
odo url delete <tab>
````
the last command should auto-complete the url that was created from the previous step
Fixes: #938
=> Add go completion for odo url delete

.travis.yml
-  skip deploy stage for PRs
- reduced number of jobs (by 1) ;-) 
We used to run unit tests twice (one for computing coverage, and run regular run). Now there is only one job (the one that computes coverage)
=> better travis.yaml: run deploy stage only for tags and master

pkg/occlient/occlient.go
`odo version` error message shows `oc login` if kubeconfig is not present.
Fixes #1003
remove `kubeconfig` and do `odo version`
=> Fixed `odo login` message

cmd/update.go
changing the way component was determined during `odo update` cmd
also fixing #995
#995
create a component and use `odo update` to change the source eg:`odo update --git https://github.com/openshift/nodejs-ex.git`
=> Fix #995 update without cmp specified as argument

.travis.yml
Increase timout to 20 minutes
Travis-ci kills jobs that don't output something for more than 10 mins.
=> e2e: add travis_wait for test-cmp-e2e

tests/e2e/e2e.go
The `runFailCmd` wasn't waiting for the command to complete due to which the exit code of the Cmd always returned as `-1`. This occurs due to premature stopping.
No Issue
try using `runFailCmd` for a failing odo cli combination  eg. `odo create test --local test --git test`
=> made runFailCmd wait till cmd gets completed

Makefile, pkg/component/watch.go, pkg/component/watch_test.go, pkg/odo/cli/component/watch.go, tests/e2e/cmp_test.go, tests/e2e/e2e.go
Fix watch UTs on Appveyor
The problem in watch test was that the same channel was fed and listened
to by 2 functions: the UT and the main WatchAndPush function which does
not guarantee which listener gets the message.
So, the fix now is to make 2 separate channels one each for each of the
directions of the communications:
a. watch UT to WatchAndPush: To signal graceful exit without SIGINT to
terminate WatchAndPush -- ExtChan
b. WatchAndPush to watch UT: To signal the readiness of watch function
to listen to any file change as of now simulated by the watch
UT. -- StartChan
fixes: #919
=> Fix watch UTs on Appveyor

appveyor.yml
add step to compress before publishing artifacts to appveyor
to reduce the storage consumption on appveyor
https://github.com/redhat-developer/odo/issues/1025
check if artifacts are publishing on appveyor in a compressed form and validate the binaries
=> add step to compress before publishing artifacts to appveyor

pkg/component/component.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, tests/e2e/cmp_test.go
Fix a race condition occurs sometimes in e2e tests.
The race condition occurs because we try to update update the same DC in succession.
The fix that is introduced in this PR (based on the suggestions in the linked issue) is to apply all DC changes in one update call
fixes #1008 
This component e2e tests should now all work without flakes. 
For regression sake, we should test that `odo update...` still works as expected
=> Fix race-condition that occurs during component update to git

pkg/odo/cli/project/project.go, pkg/project/project.go, pkg/project/project_test.go
fixes #887 
The project delete function in pkg folder now returns the current set project along with the error if any. If no project is left to be set active, "" is returned.
To test :
1. Create a new project
2. Delete the project and check the name of the project which is set as active.
=> Fixed the problem of displaying wrong project as active after project delete

Makefile, pkg/odo/cli/component/create.go, pkg/util/util.go, tests/e2e/cmp_test.go
In the spirit of what was done for #907, we introduce flags to control the cpu requests and limits.
This work was made super easy by the great implementation that was done by @anmolbabu for #907 - you'll notice that the code changes are very minimal  
Fixes: #908
Fixes: #1037
Test the creation of the DC using of `--cpu` or `--min-cpu` / `--max-cpu`.
Also try testing with `--memory` to make sure that both resources are applied properly
=> Add cpu flags to component create

pkg/odo/cli/component/create.go, pkg/odo/cli/component/update.go, pkg/util/util.go, pkg/util/util_test.go
This PR adds a wrapper around filepath#Abs to apart from resolving
relative paths to absolute paths also resolves ~ to user home.
This PR also resolves all references to filepath#Abs to the new wrapper
util.
This is in attempt to resolve bugs like #916
fixes #916
=> Wrap filepath#Abs to also resolve shell symbol ~ to user home

pkg/occlient/occlient.go
Update supervisord container image version to `0.4.0`
fixes https://github.com/redhat-developer/odo/issues/445
=> Bump Supervisord image version

pkg/odo/util/cmdutils.go
This happened because PR #1046 fell behind master and was not rebased
No
`make bin` should now work
=> Fix broken master

pkg/odo/cli/service/create.go
Updates the `odo service create` logging messages to reflect the
change in UI.
For example:
```sh
github.com/redhat-developer/odo  add-checkmark ✗                                                                                                                                                                                                                                                                                                                      2d ⚑
▶ ./odo service create dh-hello-world-apb
OK  Service 'dh-hello-world-apb' was created
Progress of the provisioning will not be reported and might take a long time.
You can see the current status by executing 'odo service list'
```
=> Update `odo service create` logging messages

pkg/odo/cli/version/version.go
fix version number in version.go that wasn't updated due to broken bump-version.sh script (fix in #1074)
=> fix v0.0.17 version

scripts/bump-version.sh
fixes script that updates version number before release
this got broken due to moving verision.go file.
=> fix bump-version.sh (version.go file was moved)

Makefile
`odo version` was always reporting just HEAD because this was not properly updated after the file moved
=> fix path to GITCOMMIT variable to display correct value in 'odo version'

pkg/odo/cli/component/create.go
There's a ) missing with the --port output
=> Add ) to end of help description

Makefile
the previous path in #1081  was not correct :-(
don't know how it is possible i would sweare that i tested it
=> fix path to GITCOMMIT variable to dislay correct value in 'odo version'

pkg/log/status.go
This changes the output to use all checkmarks / X's instead of OK and
ERR.
Closes https://github.com/redhat-developer/odo/issues/1078
=> Switch the output to all checkmarks / x's

pkg/component/component.go, pkg/component/component_test.go, pkg/odo/cli/component/link.go, pkg/odo/util/completion/completionhandlers.go, pkg/odo/util/completion/completionhandlers_test.go
This PR adds support for providing completion suggestions for `odo link`.
It also refactors `components.List` to make a single API server call and adds a unit test for it (I also spotted plenty more improvement of such nature that can be made to `component` but didn't attempt them in this PR since I didn't want to change irrelevant code)
Fixes: #1064
Assuming that the completion scripts have already been setup and that the binary from this PR is on $PATH, a good test would be the following:
```
odo create nodejs frontend
odo create python backend
odo service create mysql-ephemeral
```
Now `odo link` + [TAB] should yield `fronend` and `mysql-ephemeral` while
`odo link --component frontend` + [TAB] should yield `backend` and `mysql-ephemeral` while
=> Add completion for odo link

pkg/component/component.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/occlient/templates.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/update.go, tests/e2e/cmp_test.go
Adds `--ref` flag for creation of a component using git as a source
Fixes https://github.com/redhat-developer/odo/issues/899
`odo create <type> --git <url> --ref <commit> or <tag> or <branch>`
=> Adds ref flag for git source in create and update operation

pkg/odo/cli/url/url.go, pkg/url/url.go, pkg/url/url_test.go, tests/e2e/e2e_test.go
fixes #1040 
It introduces a new function GetValidPortNumber() to check and return the valid port of the component.
=> Fixes the issue of url creation for same component when no name is provided

pkg/occlient/occlient.go, pkg/odo/cli/version/version.go
`odo version` should not end with an error code if the server is not reachable.
fixes #1028 
`odo version` when not logged in will result in an error before the change.
`odo  version` will complete successfully after the change.
=> Fix #1028: odo version does not exit with error code when server is not reachable

README.md
Fixing the missing link. ```Deploying an Application using Odo``` should redirect to the proper place
Actually it is a minor change, not really need any discussion i guess. The problem is with the link ```Deploying an Application using Odo``` in [README.md](https://github.com/redhat-developer/odo/blob/master/README.md) and is not redirected to the place where should actually go.
=> Missing Deploying an Application using Odo link

.travis.yml, pkg/component/watch_test.go, pkg/occlient/occlient_test.go, pkg/odo/cli/application/application.go, pkg/odo/cli/cli.go, pkg/odo/cli/component/component.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/link.go, pkg/odo/cli/component/push.go, pkg/odo/cli/service/delete.go, pkg/odo/cli/service/list.go, pkg/odo/genericclioptions/context.go, pkg/odo/util/completion/completionhandlers_test.go, pkg/odo/util/validation.go, pkg/secret/secret.go, pkg/secret/secret_test.go, pkg/service/service_test.go, pkg/storage/storage_test.go
This reduces conflicts / errors for people who are running the latest
version of go (1.11.2).
The following commands have been ran:
```sh
gofmt -s -w pkg
goimports -w pkg
```
=> Updated gofmt and goimports

cmd/odo/odo.go
Make CommandLine not exit on error and intercept flag.ErrHelp to return
0 instead of default behavior of flag.Parse which is to exit with code 2
on error (flag.ErrHelp is raised when help is asked).
fixes #1086 
`odo -h` returns `2` prior to this change
`odo -h` returns `0` after
Nothing else should change.
=> Fix #1086: exit with 0 code on help

pkg/occlient/occlient.go, pkg/occlient/templates.go
adds dumb-init to fix the issue with orphaned processes, because there was no init process in a container to clean it
more at https://github.com/redhat-developer/odo/issues/1076#issuecomment-444642582
fixes #1076
it requires a new version of initContainer image with this PR https://github.com/redhat-developer/odo-supervisord-image/pull/8
build new odo-supervisord-image inside minishift instance
```
eval $(minishift docker-env)
docker build -t quay.io/openshiftdo/supervisord:0.5.0 .
```
now you can build odo with this patch and run it as usual
**Tests will be failing until `quay.io/openshiftdo/supervisord:0.5.0`(with https://github.com/redhat-developer/odo-supervisord-image/pull/8)  is released**
=> use dumb-init as PID1 process for containers

pkg/util/util.go, pkg/util/util_test.go
This PR fixes 2 cases where the component creation fails due to an invalid name
Fixes #1031
Two scenarios need to be checked:
[First](https://github.com/redhat-developer/odo/issues/1031#issuecomment-444871742)
[Second](https://github.com/redhat-developer/odo/issues/1031#issuecomment-444792501)
=> Fix component creation invalid name cases

pkg/odo/cli/utils/config.go
Removes the newline that was accidently added to the help menu.
Changes timeout to Timeout in the example
=> Remove newline from odo utils config help

pkg/odo/cli/service/create.go, pkg/odo/cli/service/service.go
`ktemplates` removes all extra newlines. Example output has been
modified to use `\n\n`.
Before:
```sh
Examples:
odo service create dh-postgresql-apb my-postgresql-db --plan dev -p postgresql_user=luke -p postgresql_password=secret
odo service delete mysql-persistent
odo service list
```
After:
```sh
Examples:
odo service create dh-postgresql-apb my-postgresql-db --plan dev -p postgresql_user=luke -p postgresql_password=secret
odo service delete mysql-persistent
odo service list
```
`odo service create --help` has been modified and truncated into a
simpler long description.
=> Add newlines for help menu, modify odo service create help

docs/development.md, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go
Fixes a subtle race condition that can occur during `odo link` or `odo unlink`.
The race condition could (and sometimes does in our e2e tests) occur if we were adding a link while the
deployment was still being rolled out.
With this change, we now use Patch instead of Update ensuring that
no write conflicts occur.
No, but I have seen the problem occur a few times in the integration tests
`odo link` and `odo unlink` should continue to work as before.
Furthermore, the `link` integration tests should now not exhibit flaky behavior (unless Travis fails to launch Openshift)
=> Fix potential race condition on odo link/unlink

pkg/odo/cli/component/push.go
added a check for componentName being set before pushing
fixes #1016 
remove the `~/.kube/odo` from your local computer then go to any local component source, try `odo push --local .`
=> added check for componentName before pushing

Makefile
Adds a `debug` target to Makefile.
fixes #1132 
`make debug` then try to attach a debugger to the running `odo` instance. Without this fix, you'd get an error similar to: `could not attach to pid 90236: decoding dwarf section info at offset 0x0: too short`
=> Fix #1132: Add debug target.

pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/util/util.go, pkg/util/util_test.go
Connect to correct port when testing openShift connection
It uses `net.LookupPort` to correctly resolve url schema part to port if not explicitly specified.
fixes #1028
modify part of the kubeconfig that points to the server and remove port from it
```
clusters:
- cluster:
server: https://youurhost:443
```
```
clusters:
- cluster:
server: https://youurhost
```
NOTE: your cluster has to be using standart https port (443) or http (80)
=> Detect correct port when testing OpenShift connection

pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/odo/cli/service/delete.go, pkg/service/service.go, pkg/service/service_test.go, tests/e2e/link_test.go
When a service is deleted (`odo service delete ...`) then we need to "links" that have been created in the DeploymentConfig of components that were linked to the service (via `odo link ...`)
Fixes: #1094
The following scenario should cover everything: 
Create the components
```
odo create nodejs frontend
odo create python backend
```
Create the service
```
odo service create postgresql-persistent
```
Create a link from the frontend to the backend
```
odo link backend --component frontend
```
Create a link from backend to the database
```
odo link postgresql-persistent -w
```
Both components should now have a single `envFrom` value in their DC.
We now delete the service
```
odo service delete postgresql-persistent -f
```
Now the frontend service should not have been touched while the …
=> Unlink service that was deleted

docs/examples.md
fixes #???
#839, but does not completely resolve. #839 suggests that the getting started page include java. This makes sense, but is a more involved rewrite. I would suggest the team 1) split 839 and 2) use the example from the katacoda to rewrite the getting started docs for java and node
It's a doc change.
A couple notes:
- due to #1152, I cannot use any of the red hat repos for java examples as they need --context-dir support. Thus, I'm using Spring Pet Clinic here. 
- I think it would be good to refactor this whole page to include all commands needed for a working example (e.g. `odo push` & `odo url create`). Creating the component is only one part of the job and makes the docs a bit confusing.
=> adding example java docs

docs/ci-reference.md, scripts/oc-cluster.sh, tests/e2e/e2e_test.go
Test should be run on latest available OpenShift release version
Mattermost channel - https://chat.openshift.io/developers/pl/cn5ihkt8htdy5emjdeg89ribze
This is CI specific. On master test suite runs on oc version v3.10.0, however with this changes test suite will run on oc v3.11.0
=> Update openshift origin client used in e2e tests to v3.11.0

pkg/occlient/occlient.go, pkg/odo/cli/service/create.go, pkg/odo/cli/service/service.go, pkg/odo/util/completion/completion.go, pkg/odo/util/completion/completionhandlers.go, pkg/odo/util/completion/completionhandlers_test.go, pkg/testingutil/services.go, scripts/generate-coverage.sh
See $SUBJECT
Fixes: #1171
Assuming that the completion scripts have already been setup and that the binary from this PR is on $PATH, a good test would be the following:
Now by execuring
`odo service create $some_service --plan + [TAB]` 
you should yield the various plans
Once you decide on a plan, you can see the required parameters by using
`odo service create $some_service --plan $some_plan -p + [TAB]`
=> Add service plan and parameter completion

pkg/occlient/templates.go
odo will generate DeplymentConfig with Recreate strategy instead of Rollout. 
More info an be found at #1141
fixes #1141
=> use Recreate deployment strategy

pkg/odo/util/completion/completionhandlers.go, pkg/odo/util/completion/completionhandlers_test.go, pkg/testingutil/services.go
fixes #1212 
This issue fixes the duplication error in the completion handlers of service names, service class names and app names
How to test : 
Press <tab> multiple times in case of name completion of the above entities. The name should be suggested only once
=> This issue fixes the duplication error in the completion handlers

pkg/log/fidget/spinner.go, pkg/log/status.go
This PR updates the spinner so it now uses "◐◓◑◒" icons in order to not
only switch to ASCII only (since ◐◓◑◒ keys are ASCII), but to also
reduce the amount of spacing needed for everything to format correctly.
Previously, the spinner was using 2 character spaces, this will now only
use 1 character space. This will make the logging more "concise" and
appear more compact.
For example:
```sh
▶ ./odo create nodejs --git https://github.com/openshift/nodejs-ex
✓  Checking component
✓  Checking component version
✓  Creating component nodejs-ex-nodejs-jkzn
◑  Triggering build from git
```
=> Updates the spinner output and refactors prefix/suffix spacing

pkg/component/component.go, pkg/component/component_test.go, pkg/odo/cli/component/common_link.go, pkg/odo/cli/component/link.go, pkg/testingutil/deploymentconfigs.go, tests/e2e/link_test.go
See $SUBJECT
Fixes: #1201
Create a backend component and then a fronted.
The first attempt to link to the backend should work.
The second one will fail.
Note that when ports are needed, links to a different ports are allowed - but not multiple links to the same port.
Also linking from a component to a service is also only allowed once
=> Prevent a link from being created twice

tests/e2e/watch_test.go
Removes 'time' from the watch tests as these tests fail locally with zsh
terminals.
Closes issue https://github.com/redhat-developer/odo/issues/1226
=> Remove 'time' from watch tests

pkg/odo/cli/version/version.go
=> Fix #1248: ignore client errors when asking for version.

pkg/component/component.go, pkg/odo/cli/application/application.go, pkg/odo/cli/component/describe.go, pkg/odo/util/cmdutils.go, tests/e2e/link_test.go
See $SUBJECT
Fixes #1202
```
odo create nodejs frontend
odo describe # you shouldn't see any linked components or services
odo create python backend
odo describe # you shouldn't see any linked components or services
odo link backend --component frontend
odo describe frontend # you should the backend linked to the frontend
odo service create mongodb-ephemeral
odo link -w mongodb-ephemeral
odo describe # the mongodb service should now be visible in the output  
```
=> Add the linked components and services to odo describe

pkg/occlient/occlient.go, pkg/odo/cli/service/create.go
fixes #1254 
`odo service create` while connected to a non service catalog enabled cluster.
=> Fix #1254: don't ignore errors when retrieving service classes and plans

.travis.yml, Makefile, pkg/auth/login.go, tests/e2e/login_test.go
See title 
- Adding buffer to replace os.Stdout and intercept output of login
- Customizing a message from odo based on what was intercepted, so if new-project
is present in original message, appropriate addition is done to odo message
- Printing custom message for login success case.
fixes #1017 
Run `odo login -u user` with or without any active projects
=> Fixing #1017: Intercepting login message and customising the message message

pkg/component/watch_test.go
Renames TestIsRegExpMatch in watch_test.go to TestIsGlobExpMatch
Also modified ignores from regular expressions to glob expressions in TestWatchAndPush
=> Renamed TestIsRegExpMatch to TestIsGlobExpMatch

pkg/catalog/catalog.go, pkg/catalog/catalog_test.go, pkg/occlient/occlient.go, pkg/odo/cli/catalog/list/components.go, pkg/odo/cli/catalog/util/util.go, pkg/odo/cli/catalog/util/util_test.go, pkg/odo/util/completion/completionhandlers.go, pkg/testingutil/imagestreams.go, tests/e2e/cmp_test.go
See $SUBJECT
Fixes: #1180 (the components part)
`odo catalog list components` should only display non hidden builder images.
The most prominent example is the nodejs builder. 
For that builder the `0.10` and `4` versions are marked as hidden (because they are deprecated) and thus should not show up in the output of the aforementioned command
=> Ensure that listing catalog components ignores hidden ones

pkg/odo/cli/service/service.go
Fix in-line/cmd docs to reflect that we can add any service that is visible in `svcat get classes -o=json` ( ie, any ClusterServiceClass ), and not just those from the Template Service Broker.
=> Doc: create instances from any service class

pkg/odo/cli/cli.go, pkg/odo/cli/logout/logout.go
See $SUBJECT
fixes #1269 
Check that `odo logout` still works as expected.
=> Fix #1269: Refactor logout command to use Complete/Validate/Run pattern.

tests/e2e/e2e.go, tests/e2e/login_test.go
See title
- Project deletion does not happen now when it is not needed
- Project deletion, when run only targets specific projects
fixes #1278 
=> Fixing #1278: Changing cleanup to run as needed

pkg/odo/cli/catalog/catalog.go, pkg/odo/cli/cli.go, pkg/odo/cli/component/component.go, pkg/odo/cli/project/delete.go, pkg/odo/cli/project/get.go, pkg/odo/cli/project/project.go, pkg/odo/cli/project/set.go, pkg/odo/cli/storage/create.go, pkg/odo/cli/storage/delete.go, pkg/odo/cli/storage/list.go, pkg/odo/cli/storage/mount.go, pkg/odo/cli/storage/storage.go, pkg/odo/cli/storage/unmount.go
Fixes:
- documentation issues
- missed global variable usage
- use command name constants where possible
No.
Everything should still work as expected. Only change that could have an impact is on `storage mount` where global variable use was replaced by options field.
=> Clean-up after command refactoring

pkg/odo/cli/component/component.go
Make `component` commands sub-commands of `component` command! ^_^
Top-level commands are kept for compatibility reason since I don't think there's an obvious way to create aliases to sub-commands.
fixes #779 
Check that `odo component <command>` works as expected, i.e. exactly as `odo <command>`.
=> Fix #779: move component commands under component.

pkg/odo/cli/cli.go, pkg/odo/cli/login/login.go
See $SUBJECT
fixes #1268 
Check that `odo login` still works as expected.
=> Fix #1268: Refactor login command to use Complete/Validate/Run pattern.

tests/e2e/java_test.go
This is needed because it seems like the latest 1.6 version has broken
the binary builds (see https://issues.jboss.org/browse/SB-1172 for a
similar issue).
Note that version 1.6 of the builder image was released yesterday which coincides with the timing when our builds started to break
No, but it should fix the e2e test issues we have been having with java
CI should pass
=> Pin the openjdk18 image version we are using in our e2e tests

pkg/odo/cli/service/create.go, pkg/odo/cli/service/create_test.go, pkg/odo/cli/service/ui/ui.go
Users might explore creating a service using the interactive mode and would like to see the equivalent command in non-interactive mode so that it can be used in a script.
No.
Create a service interactively: `odo service create` and asks for the equivalent command at the end of the process. Check that the resulting command line results in the equivalent service being created.
=> Add possibility to output non-interactive equivalent command for service create.

Makefile
resolved the incorrect PHONY in make file for `test-odo-login-e2e`
No issue
doesn't change the behavior
=> resolved the incorrect PHONY in make file

pkg/occlient/occlient.go, pkg/occlient/templates.go
ODO_BOOTSTRAPPER_IMAGE overwrites default initContainer image for
SupervisorD bootstrapping. This is especially helpful for debugging and
testing new initContainer images.
fixes #???
```
ODO_BOOTSTRAPPER_IMAGE=quay.io/myrepo/myimage:test odo create nodejs test
```
This will create a new component and use `quay.io/myrepo/myimage:test` as initContainer for bootstrapping SupervisorD (https://github.com/redhat-developer/odo-supervisord-image/blob/master/assemble-and-restart)
=> Allow to ovewrite SupervisorD bootrapping image using env variable

pkg/occlient/occlient.go
Get rid of `io: read/write on closed pipe` error.
fixes #1286.
See issue #1286. description.
=> Do not use closed writer when pushing files to pod.

pkg/odo/cli/service/create.go, tests/e2e/service_test.go
Add wait flag to service create and also use spinners to display progress
Fixes: #1144, #1063
Both
`odo service create mongodb-ephemeral --plan default -p MONGODB_VERSION=3.2`
and 
`odo service create mongodb-ephemeral --plan default -p MONGODB_VERSION=3.2 -w` should work with the latter waiting for the service to come up fully
=> Add wait flag to service create

pkg/odo/cli/application/delete.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/delete.go, pkg/odo/cli/component/ui/ui.go, pkg/odo/cli/project/delete.go, pkg/odo/cli/service/create.go, pkg/odo/cli/service/delete.go, pkg/odo/cli/service/ui/ui.go, pkg/odo/cli/storage/delete.go, pkg/odo/cli/ui/common.go, pkg/odo/cli/url/delete.go, pkg/odo/cli/utils/config/set.go, pkg/odo/cli/utils/config/unset.go
Adding interactive mode to commands has brought along a library that provides UI elements to ask questions to users. It makes sense to use these elements where we ask the user for confirmation. This simplifies client code and makes sure the experience is consistent across commands.
No.
Any of the `delete` (`app`, `component`, etc.) commands that ask for confirmation should still work as before, though the UI might be a little different.
=> Use ui.Proceed instead of log.AskF

pkg/component/component.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/odo/cli/component/common_link.go, pkg/odo/cli/component/link.go, pkg/odo/cli/component/unlink.go, tests/e2e/link_test.go, tests/e2e/service_test.go
We now:
* Re-purpose `wait` to enforce waiting for the pod being updated to be
in running state (meaning that is can be immediately used by
other tools)
* Introduce `wait-for-target` that would do what wait does currently
Fixes #1337 
When using link/unlink with the `-w` flag should no wait until the component has been redeployed.
If the flag is not specified, the command returns immediately.
The old `-w` flag is now `--wait-for-target`. Use it when linking to a service to have odo wait until the service has been fully provisioned.
=> Rationalize the use of --wait for link/unlink

pkg/odo/cli/service/create.go
See $SUBJECT.
No.
Create a service in interactive mode and answer `y` when asked if you want to wait for it to be ready and then check that the command actually waits for the service to be ready.
=> Make it possible to wait for service when creating one in interactive mode.

pkg/odo/cli/component/create.go, pkg/odo/cli/component/ui/ui.go
`odo create` might issue improper paths when creating components.
fixes #1356 
`odo create` in both interactive and non-interactive mode should work properly.
=> Fix #1356: make sure that paths are absolute

pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/odo/cli/service/create.go
Remove non-working DoesPlanExist and use GetMatchingPlans instead.
See $SUBJECT
fixes #1359 
See #1359 for failing scenario
=> Fix #1359: properly detect improper plan.

pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/odo/cli/project/create.go, pkg/project/project.go
See $SUBJECT.
fixes #1329
See #1329 for failing scenario that should now be fixed by adding the `-w` flag to the `project create` command to wait for the project to be created before returning.
=> Fix #1329: Add wait flag to wait for project to be ready.

pkg/odo/cli/component/create.go, pkg/odo/cli/component/push.go
Updates the help outputs for `odo push` as well as `odo create` (newline
by mistake) in order to make it clearer.
Closes https://github.com/redhat-developer/odo/issues/1398
=> Update help outputs

pkg/service/service.go
Mark it as `Unknown` instead.
No.
=> Do not error out if a service instance status cannot be determined

pkg/log/status.go, pkg/odo/cli/component/create.go, pkg/odo/util/cmdutils.go, tests/e2e/java_test.go
Removes all unnecessary newlines that were added, this was caused by not
accounting `Sprintln` (which includes a newline...)
Changes:
```sh
github.com/redhat-developer/odo  remove-newline-error ✗                                                                                                                                                                                                                   1d ⚑  ⍉
▶ ./odo create nodejs
✗  unable to get current application
github.com/redhat-developer/odo  remove-newline-error ✗                                                                                                                                                                                                                   1d ⚑  ⍉
▶ make bin
go build -ldflags="-w -X …
```
=> Removes unnecessary newlines / outputs

docs/development.md, pkg/component/component_test.go, pkg/config/config.go, pkg/project/project_test.go, pkg/testingutil/configs.go, pkg/testingutil/configs_test.go, pkg/util/util.go, pkg/util/util_test.go
This is needed for getting UTs to run on OpenShift CI where
we login to build root as randomUID
#1411
=> Adding way to get around resolution of user.Current().in randomuid environments

tests/e2e/component.go, tests/e2e/utils.go
Update the test file to run it on all oc supported platform including windows
fixes Part of #1129
make test-cmp-e2e
make test-cmp-sub-e2e
=> Remove terminal specific command from e2e component test file

pkg/config/config.go, pkg/config/config_test.go, pkg/preference/preference.go, pkg/preference/preference_test.go
added a `metav1.TypeMeta` in the `LocalConfig` and `Preference` struct
fixes https://github.com/redhat-developer/odo/issues/1365
```
odo preference set timeout 20
odo config set memory 500MiB
```
=> added type meta in config and preference structs

tests/e2e/e2e_test.go
Importing of Odo core package (Those can directly influence the user facing variable) should not be the part of test suite.
No, But discussed in odo team cabal
make test-main-e2e
=> Avoid use of odo core package in testsuite

pkg/odo/cli/cli.go, pkg/odo/cli/component/component.go, pkg/odo/cli/component/log.go, pkg/odo/cli/utils/utils.go
This PR changes the following help page to list all the sub-commands of
each "root" command. For example:
```sh
Other Commands:
app         Perform application operations (create, delete, describe, get, list, set)
catalog     Catalog related operations (describe, list, search)
project     Perform project operations (create, delete, get, list, set)
service     Perform service catalog operations (create, delete, list)
storage     Perform storage operations (create, delete, list, mount, unmount)
url         Expose component to the outside world (create, delete, list)
```
Closes https://github.com/redhat-developer/odo/issues/1257
=> List all sub-commands within odo help

pkg/odo/cli/component/create.go
Re-organizes the examples for odo create in order to emphasis the
creation, CPU and memory limits have been moved to the bottom in order
to conserve / focus on other parameters.
Closes https://github.com/redhat-developer/odo/issues/1391
=> Re-organize examples for odo create

scripts/configure-installer-tests-cluster.sh
To run e2e_test on OpenShift 4.0. Just update the user name which is being used in e2e_test.go as a login user.
No
As of now make sure the user name "odonoprojectattemptscreate" should be present in e2e_test.go test file.
=> Fixing username as per e2e_test file

tests/e2e/e2e_test.go, tests/e2e/utils.go
To run the e2e_test file on OpenShift 4.0 cluster. re updated for few scenarios
Partly #1431
Run ```test-main-e2e``` on OpenShift 4.0 cluster
=> Updating re to run e2e_test on 4.0 cluster

pkg/config/config.go, pkg/config/config_test.go, pkg/odo/cli/config/set.go, pkg/odo/cli/config/unset.go, pkg/odo/cli/preference/set.go, pkg/odo/cli/preference/unset.go, pkg/preference/preference.go, pkg/util/config_util.go
Removes the `GetConfiguration` method and adds `IsSet` method. Uses `IsSet` for checking if the config or preference is set or not.
No issue
check if `odo config` and `odo preference` work correctly
=> remove GetConfiguration from config and preference

tests/e2e/component.go, tests/e2e/e2e.go
To run component test on OpenShift 4.0 cluster. Removes some terminal specific operation includes some unnecessary operation and most importantly **trim space** of output check which was failing on 4.0 cluster. 
No
Run ```make test-cmp-e2e``` and ```make test-cmp-sub-e2e``` both on 3.11 and 4.0 cluster
=> Run component test on OpenShift 4.0 cluster

pkg/odo/cli/application/delete.go, tests/e2e/json_test.go
adding -o json flag to `odo app delete`
https://github.com/redhat-developer/odo/issues/1383
`odo app create myapp`
`odo app delete myapp -o json`
and check its exist code is 0 and not asking for user inputs
=> Add -o json  flag to `odo app delete`  

pkg/odo/cli/cli.go, pkg/odo/cli/utils/utils.go
This code was used from `knctl`:
https://github.com/cppforlife/knctl/blob/612840d3c9729b1c57b20ca0450acab0d6eceeeb/pkg/knctl/cmd/knctl.go#L183
and
https://github.com/cppforlife/knctl/blob/612840d3c9729b1c57b20ca0450acab0d6eceeeb/pkg/knctl/cmd/knctl.go#L170
I had forgotten to add comments on the previous PR (had just `...` under
the comments).
This adds some source information to the code.
=> Add notes with regards to listing subcommands.

pkg/config/config.go, pkg/config/config_test.go, pkg/occlient/occlient_test.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/list.go, pkg/odo/cli/component/push.go, pkg/odo/cli/component/update.go, pkg/odo/genericclioptions/context.go, tests/e2e/component.go
See title
- Adding fuction that allows to check if a config file exists
- Updating component list to check existence of odo config and fail
if it does not exist
- Adding regression tests
fixes #1485 
```
$ cd nodejs-ex
$ pwd
/redacted//nodejs-ex
$ odo component list
ACTIVE     NAME            TYPE
*          nodejs-vypi     nodejs
$ cd someotherdir
$ odo component list
✗  the current directory does not represent an odo component
```
=> Fixing error when user lists component in directory without one

pkg/component/component.go, pkg/component/watch.go, pkg/component/watch_test.go, pkg/log/status.go, pkg/odo/cli/component/push.go, tests/e2e/e2e_test.go
Adds a --show-log parameter to `odo push` in order to see the log while
building.
Closes https://github.com/redhat-developer/odo/issues/1058
=> Adds --show-log to odo push

pkg/config/config.go, pkg/config/env_var.go, pkg/config/env_var_test.go, pkg/odo/cli/component/list.go, pkg/odo/cli/config/set.go, pkg/odo/cli/config/unset.go, pkg/odo/cli/config/view.go, pkg/util/util.go, tests/e2e/component.go, tests/e2e/e2e_test.go, tests/e2e/watch_test.go
Added env variables in the component settings of local odo config.
Note - using the env variables in workflow is not in the scope of this PR, its in the next one once this gets merged
partly  https://github.com/redhat-developer/odo/issues/1390
```
odo config set --env PORT=4000
odo config set  --env DB_USERNAME=postgres,DB_HOSTNAME=postgres
odo config set  --env KAFKA_HOST=kafka --env KAFKA_PORT=6639
odo config unset --env PORT
odo config unset --env DB_USERNAME,DB_HOSTNAME
odo config unset --env KAFKA_HOST --env KAFKA_PORT
odo config view 
```
=> added env variables in component config

pkg/odo/cli/service/create.go
Fixes a panic when no service class is available on the cluster in interactive mode (will happen for example if service catalog is deployed on minishift but not brokers).
No.
=> fix: prevent panic when no classes are available

pkg/occlient/templates.go
Fixes the issues of two DeploymentConfig revisions happening on one `odo
push`.
OpenShift will automatically propagate the actual image using the
TriggerChange and thus having it blank is viable / okay.
Closes https://github.com/openshift/odo/issues/1493
note from @kadel:
This is why it works: https://github.com/openshift/origin/blob/f5f540d6503b3978a242117fb94b229135201df3/pkg/apps/controller/deploymentconfig/deploymentconfig_controller.go#L146
=> Fix issue of 2 deployments on one odo push

Makefile
Running test suite on master from windows platform. Added windows executable extension for odo file.
Part of #1131
Run ```make bin``` on Windows platform and run  ```.\odo.exe -h``` to verify it
=> Adding .exe extension for make bin on Windows

README.md
minishift supports OpenShift version 3.10 and above.
It modifies the OpenShift version based on what minishift supports.
=> Update OpenShift version based on what minishift supports

README.md
To remove a couple of extra backticks that could interfere with users who copy/paste the commands
fixes #???
No
Look at the rendered markdown
=> Removing extra backticks

pkg/component/types.go, pkg/config/config.go, pkg/config/config_test.go, pkg/odo/cli/component/push.go, pkg/odo/cli/component/watch.go, pkg/odo/cli/utils/utils.go, pkg/odo/genericclioptions/context.go
Implements `odo watch` by using the local configuration file.
To use these changes, simply use: `odo watch` in the same directory that
you've deployed, or `odo watch --context ~/nodejs-ex`.
This builds upon: https://github.com/redhat-developer/odo/pull/1360
Closes https://github.com/redhat-developer/odo/issues/1419
=> Implement new odo workflow for: odo watch

pkg/component/component.go, pkg/config/env_var.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/odo/cli/component/create.go
Consuming the Env Variables from the config for component lifecycle 
fixes https://github.com/openshift/odo/issues/1390
```
odo create --env 
odo push # should reflect the env
```
=> added env variables from config to create and update component

pkg/config/config.go, pkg/config/config_test.go, pkg/occlient/occlient_test.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/list.go, pkg/odo/cli/component/push.go, pkg/odo/cli/component/update.go, pkg/odo/cli/component/watch.go, pkg/odo/cli/config/set.go, pkg/odo/cli/config/unset.go, pkg/odo/cli/config/view.go, pkg/odo/genericclioptions/context.go, tests/e2e/component.go, tests/e2e/e2e_test.go
- Does above
- Removes old fix for component list as this covers that
more easily
- Does some breakup of functions of context.go along the way.
#1486 
Go into a directory where there is no .odo file and try `odo app list` or `odo component list`
=> Short circuiting invalid context file in context.go

pkg/odo/cli/component/create.go, pkg/odo/cli/component/delete.go, pkg/odo/cli/component/describe.go, pkg/odo/cli/component/get.go, pkg/odo/cli/component/link.go, pkg/odo/cli/component/list.go, pkg/odo/cli/component/log.go, pkg/odo/cli/component/push.go, pkg/odo/cli/component/unlink.go, pkg/odo/cli/component/update.go, pkg/odo/cli/component/watch.go, pkg/odo/genericclioptions/add_flags.go
This PR aims to add context flag to all commands that should have them
```
$ odo create nodejs --context ~/nodejs-ex/helm
✓  Checking component
✓  Checking component version
Please use `odo push` command to create the component with source deployed
```
This should work for most commands with exceptions as listed
=> Adding context flag function and updating all components to use it

Makefile, scripts/openshiftci-presubmit-e2e.sh, scripts/openshiftci-presubmit-unittests.sh
This abstracts all commands that are run on OpenShift CI into separate scripts in this repository. 
This will allow us to modify those scripts without touching openshift/release repo.
Idea is that jobs will just run `make openshiftci-presubmit` and `make openshiftci-master`.
https://github.com/openshift/release/blob/0f4bf0f581103c14f54dd6eee548c63c3455ab36/ci-operator/config/openshift/odo/openshift-odo-master.yaml
https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/odo/openshift-odo-master-presubmits.yaml
=> Scripts to run on OpenShift CI

Makefile, pkg/odo/cli/component/push.go, tests/e2e/component.go, tests/e2e/helper/helper_oc.go, tests/e2e/helper/helper_run.go, tests/e2e/source_test.go
This commit adds:
1. `--config` flag to update the component with component settings
2. `--source` flag to push only the source to an already existing
component.
3. If neither `--config` nor `--source` flags are passed, update
both source and configuration onto the component
fixes #1489
* `odo push`
* `odo push --source`
* `odo push --config`
The above 3 with `--context` also should behave with changes above
=> Add `--config` and `--source` flags to push

pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/occlient/templates.go, pkg/occlient/utils.go, tests/e2e/e2e_test.go
This PR:
- Adds more checks for IsDCRolledOut, including waiting for the new
revision, making sure that DeploymentConfig is actually deployed / has a
new image as well as the desired revision is available.
- More debug information when waiting for deploymentconfig
- Moves the functions from template.go to utils.go (I have no idea why a
utility function was in a templates file...)
- These changes also makes sure that our revision doesn't skip a number
/ goes to the next revision.
Closes https://github.com/openshift/odo/issues/1567
=> Increases checks when deploying DeploymentConfig

Makefile, scripts/openshiftci-presubmit-unittests.sh
- get gox before running `make cross`
- remove arm from build targets (no one is using it right now, and it is just slowing down builds), it can be added back if needed
=> openshiftci-presubmit-unittests: get gox before attemting make cross

pkg/odo/cli/config/set.go, pkg/odo/cli/config/unset.go, pkg/odo/cli/config/view.go, pkg/odo/genericclioptions/add_flags.go, tests/e2e/e2e_test.go, tests/e2e/utils.go
Added `--context` flag to `odo config`
fixes https://github.com/openshift/odo/issues/1371
```
odo config view --context <dir>
odo config set --context <dir> Ports 8080/TCP
odo config set --context <dir> Name Test
odo config unset --context <dir> Name 
```
should work
=> added context in config

pkg/occlient/utils.go
This changes the logic to see if the latest image is greather than the
desired image due to rare cases of OpenShift updating the
deploymentconfig quickly in succession when using an ImageTrigger.
=> Logic fix for OpenShift depoymentconfig triggers

README.adoc, docs/cli-reference.adoc, pkg/odo/cli/component/create.go, pkg/odo/cli/version/version.go
It simply fixes the typo from `wil` to `will` in a few files in the repo. This PR has been rebased on #1590.
=> Fixes typo from 'wil' to 'will' in various files

pkg/occlient/occlient.go
It used to be 2 minutes.
2 minutes is not enough for really slow `minishift`/`oc cluster up` cluster
=> increase ocUpdateTimeout to 5 minutes

pkg/odo/cli/component/push.go, tests/e2e/component.go
odo should create component even in new project, for example given below, `asdf` don't exist on cluster.
`odo push` will create project and then create component in it
fixes #1597
```
odo create nodejs --project asdf
odo push
```
=> Create component even in new project

pkg/application/application.go, pkg/application/application_test.go, pkg/odo/genericclioptions/context.go, tests/e2e/component.go
To not autogenerate an app name everytime we are using `app` as the default app name from now on.
fixes https://github.com/openshift/odo/issues/1615
```
odo config view # verify the Application name to be 'app'
```
=> used default appName as 'app'

README.adoc, docs/cli-reference.md, pkg/odo/cli/version/version.go, scripts/bump-version.sh, scripts/install.sh, tests/e2e/e2e_test.go
Odo has reached BETA!
With the release of BETA, we also move to the [OpenShift GitHub repo](http://github.com/openshift).
So what's new in BETA?
- `odo component create` creates a local component configuration in `./.odo/config.yaml`, nothing is created on the cluster at this point.
- `odo config` Similarly to `odo component create`, will update the local component configuration, without affecting the running component.
- All component configurations are saved to `./.odo/config.yaml`. You can commit this file to your repository to easily recreate component with the same configuration later, or to share it with someone else.
- To deploy the component to a cluster or to apply config changes, run `odo push`.
When first using `odo create`, odo will setup the necessary information required to …
=> v1.0.0-beta1

pkg/component/component.go
Adds a spinner to the ApplyConfig function due to how long it takes to
apply a new deployment config to an existing component.
Example:
```sh
▶ make bin && ./odo push --context ~/nodejs-ex
go build -ldflags="-w -X github.com/openshift/odo/pkg/odo/cli/version.GITCOMMIT=3e7ee8a1" cmd/odo/odo.go
✓  Checking component
✓  Checking component version
◐  Applying component settings to component: nodejs-ex-nodejs-ujjl
```
Closes issue https://github.com/openshift/odo/issues/1570
=> Adds spinner to "Applying component settings" / ApplyConfig function

pkg/odo/cli/component/create.go
Removes leftover logging in create.go that was intended for debugging
purposes.
Closes https://github.com/openshift/odo/issues/1653
=> Remove leftover logging

pkg/component/watch.go, pkg/odo/cli/component/watch.go
This PR adds the show parameter to `odo watch` in order to watch your
build:
```sh
github.com/openshift/odo  add-show-log-watch ✗                                                                                                                                                                                                                                                                                                                   14h10m ⚑  ⍉
▶ make bin && ./odo watch --context ~/nodejs-ex --show-log true
go build -ldflags="-w -X github.com/openshift/odo/pkg/odo/cli/version.GITCOMMIT=3e7ee8a1" cmd/odo/odo.go
Waiting for something to change in /home/wikus/nodejs-ex
File /home/wikus/nodejs-ex/hi changed
Pushing files...
✓  Waiting for component to start
✓  Copying files to component
• …
```
=> Add show parameter to `odo watch`

docs/cli-reference.adoc, pkg/odo/cli/component/create.go
Fixes a typo assuming we are not asking user to create a component named `wildly`
fixes #???
=> Fix typo with wildfly in create command and docs

pkg/odo/cli/cli.go, pkg/odo/cli/login/login.go, pkg/odo/cli/utils/utils.go, pkg/odo/util/cmdutils.go
This PR:
- Adds capitalization to all flags / global flags
- Moves some of the functions around from utils to cmdutils into
the appropriate area
Example of the change:
```sh
Flags:
--alsologtostderr                  Log to standard error as well as files
--complete                         Install completion for odo command
--log_backtrace_at traceLocation   When logging hits line file:N, emit a stack trace (default :0)
--log_dir string                   If non-empty, write log files in this directory
--logtostderr                      Log to standard error instead of files (default false)
--skip-connection-check            Skip cluster check
--stderrthreshold severity         Logs at or above this threshold go to stderr (default 2)
--uncomplete                       Uninstall completion …
```
=> Adds capitalization to all flags

README.adoc
This pull request addresses issue #1692. Currently, the main `README.adoc` for the project still has `.md` references under the `Additional documentation` section.
Closes #1692 
Verify the links in this pull request go to the appropriate documentation.
=> Change README .md References to .adoc

pkg/config/config.go, pkg/odo/cli/config/config.go
It changes the case of the words at a few places in help message for `odo config -h`.
fixes #1661
=> Change the cases at a few places in help message

docs/logging.adoc, pkg/odo/cli/cli.go
This PR removes unnecessary logging flags that were added as part of
integrating "glog" into odo.
Instead of the following:
```sh
Global Flags:
--alsologtostderr                  log to standard error as well as files
--log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
--log_dir string                   If non-empty, write log files in this directory
--logtostderr                      log to standard error instead of files (default false)
--skip-connection-check            Skip cluster check
--stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
-v, --v Level                          log level for V logs. Level varies from 0 to 9 (default 0).
--vmodule moduleSpec               comma-separated list of …
```
=> Removes unnecessary logging flags

pkg/odo/cli/preference/set.go
Prints the name of the parameter whose value the user is trying to set again
fixes #1675
=> Print appropriate parameter name when trying to set its value again

pkg/odo/cli/component/ui/ui.go
Closes #1688 
This change updates the the prompt for the `odo component create` command. The current language for the command is `Which component type would wish to create`, which is incorrect English being displayed to the user.
In light of this change, I also updated the other `component` prompts to use similar language. 
#1688 
Assert that the prompts match the changes in this pull request.
One case would be the following: Verify the language is changed from `Which component type would wish to create` to `Which component type do you wish to create` when running `odo component create`.
=> Change UI Language for Component Prompt

README.adoc
This pull request updates `odo`'s `REAMDME` to fix steps in the [Deploying an application using odo](https://github.com/openshift/odo#deploying-an-application-using-odo) section of the documentation. These updates include the following:
1. Including `Minishift` documentation for Step 1 in case users don't have `Minishift` installed.
2. Removing step 3 `odo app create`, which is no longer used in `v1.0.0-beta1`.
3. Adding a step to delete the component created as part of the tutorial.
This change also addresses broken links in the README as referenced in #1704.
fixes #1699
fixes #1704  
Go through the new steps listed and verify you are able to create a component, expose its url, access the `nodejs` application, and delete the component.
=> Update Deploying an application using odo Section and Fixing Broken Links

pkg/occlient/occlient.go, pkg/odo/cli/project/delete.go, tests/integration/generic_test.go
The issue was that the after a project is created it is set as current. But someone deletes the project, the `printDeleteProjectInfo` function takes the consumes the project from the KUBECONFIG rather then 
the one provided as command line arg.
The resolution was as follows -
1 - set the latest project which we are deleting as current in the file ( so we point to the most recent project ) even though the user has to change the project any way in the future
2 - the SetCurrentProject doesn't actually set the runtime project of the client so I made sure it does, I made this change in the low level function of `occlient` i.e. SetCurrentProject instead of cli's Run() because I felt that SetCurrentProject should do both set the runtime and file project and hence mitigate some future …
=> resolved the consecutive project deletion issue

scripts/configure-installer-tests-cluster.sh
The script now checks if api server is stable after success login
and if not does reasonable retry of login
Attempt at mitigation #1638  
Tests should fail less often due to api server flapping
=> Making pre-test setup script check api server stability

pkg/odo/genericclioptions/context.go
This PR excludes the commands `odo catalog list components` and `odo catalog list services` from config file check so that they can be executed from a directory that doesn't have `.odo/config.yaml` file.
fixes #1599 
Build the binary, login to the OpenShift cluster, and execute aforementioned commands from a directory that doesn't have `.odo/config.yaml` file.
=> Don't check for config file to list components and services

.travis.yml, pkg/occlient/occlient.go, pkg/project/project.go, tests/integration/component.go
Currently to check if a project exists or not we used an inefficient List All projects -> match the name approach. This approach becomes quite slow when large number of projects are present. 
Also the `project.Exists` is used at many places and many times which multiplies the slowness. 
This PR addresses this issue by providing a more robust approach of just getting the project.
In my primary cluster which has very less projects I got a 5-7% increase in speed in `project` related commands.
This PR possibly resolves the below issue
fixes https://github.com/openshift/odo/issues/1717
`odo project create <name> #twice should fail`
=> use more robust project.exists function

pkg/component/component.go, pkg/occlient/occlient.go
This PR fixes the invalid paths that are being passed into OpenShift due
to using `FromSlash` that defaults to whatever backslash / forwardslash
the OS uses.
This changes it so that `ToSlash` is used for transfering as *all*
containers in OpenShift are Linux-based and thus forward-slashes are
required.
Also added:
- Checks to see if a directory is empty and error out.
To test this PR out:
- Have a Windows-based OS
- `git clone https://github.com/openshift/nodejs-ex`
- `odo create nodejs --context ~/nodejs-ex`
- `odo push -v 4 --context ~/nodejs-ex`
- `odo watch -v 4 --context ~/nodejs-ex`
Closes issue https://github.com/openshift/odo/issues/1429
=> Fixes invalid paths when using rsync with Windows

pkg/config/config.go, pkg/odo/cli/component/delete.go, tests/integration/component.go
Added a `--all` flag for `odo component delete` which deletes the component from the cluster as well as removes the local config file and directory.
fixes https://github.com/openshift/odo/issues/1654
```
odo create nodejs 
odo push
odo delete --all
```
=> added --all flag for component deletion and test for it

pkg/odo/cli/cli.go, pkg/odo/cli/component/get.go
This PR:
- Hides the component get command. We do not remove it as `odo
component get -q` is required for bash/zsh autocompletion support.
- Updates the "show sub commands" to exclude hidden flags
Closes https://github.com/openshift/odo/issues/1647
=> Hide "component get" command

pkg/component/watch.go, pkg/util/util.go
This fixes the error occuring with ignore on Windows due to
back slash being used and not forward slash.
With the way that "Glob" programming works as well as the
library that we use, we cannot use back slashes.
Closes https://github.com/openshift/odo/issues/1630
=> Fixes ignore behaviour with Windows

pkg/application/application.go, pkg/odo/cli/application/delete.go, tests/integration/component.go
Adds `Exists` function for app which will remove false positives of `odo app delete` command
Fixes #1641
```
odo app delete myapp -f
```
=> correct output for `odo app delete`

Makefile, docs/development.adoc, scripts/bump-version.sh
Currently the Readme.adoc doesn't actually show any version for odo but we still try to update that using the bump-version script and also it has been mentioned in the dev docs, so changed that.
Also resolved the extension of the `cli-reference` from `.md` to `.adoc`
=> resolved development docs and bump-version.sh script

docs/development.adoc
we no longer use GitHub release tarball, but instead, the brew is cloning from git
=> developement.adoc: update brew packaging guide

pkg/odo/cli/application/application.go, pkg/odo/cli/catalog/catalog.go, pkg/odo/cli/cli.go, pkg/odo/cli/component/component.go, pkg/odo/cli/config/config.go, pkg/odo/cli/preference/preference.go, pkg/odo/cli/project/project.go, pkg/odo/cli/service/service.go, pkg/odo/cli/storage/storage.go, pkg/odo/cli/url/url.go
Adds a "shortcut" section to `odo --help`.
See below:
```sh
Shortcuts:
create      Create a new component (shortcut for "component create")
delete      Delete an existing component (shortcut for "component delete")
describe    Describe the given component (shortcut for "component describe")
link        Link component to a service or component (shortcut for "component link")
list        List all components in the current application (shortcut for "component list")
log         Retrieve the log for the given component (shortcut for "component log")
push        Push source code to a component (shortcut for "component push")
unlink      Unlink component to a service or component (shortcut for "component unlink")
update      Update the source code path of a component (shortcut for "component …
```
=> Add "shortcut" section to odo help

pkg/preference/preference.go, pkg/preference/preference_test.go
recently there was confusion around the global preference file `~/.odo/config.yaml`. some of it was related to why it was present if it was empty. So to reduce this confusion the preference file is created lazily now instead of when NewPreferenceInfo is called.
No issue
```
odo preference view # will not create a file
odo preference set Timeout 5000 # will create the file
```
=> create the preference file lazily

pkg/component/component.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/occlient/templates.go, pkg/odo/cli/component/push.go, tests/helper/helper_oc.go, tests/integration/component.go
It also fixes the issue of update failing during update from local to git.
This PR disables the image trigger for git components. For git components, we start the deployment manually via the client.
fixes https://github.com/openshift/odo/issues/1686
fixes https://github.com/openshift/odo/issues/1682
**Create scenario**
```
odo create <component-type> --git <source-url>
odo push
```
The number of deployments and builds should be 1.
**Update scenario**
```
odo create <component-type> --local <source-location>
odo push
odo config set sourcelocation <git-source-location>
odo config set sourcetype git
odo push
```
=> Fixes the issue of 4 deployments for git components

pkg/application/application.go, pkg/util/util.go, pkg/util/util_test.go
This PR puts the app list through a "RemoveDuplicates" function to
remove any duplicate application names.
This is required since we don't have any unique identifies for
applications and thus if we have 2+ components in an application,
multiple deployment config's are returned from OpenShift with the same
application name.
See below for an example of this change:
```sh
▶ odo app list
The project 'foo' has the following applications:
NAME
foobar
app
▶ oc get dc
NAME                 REVISION   DESIRED   CURRENT   TRIGGERED BY
foobar-app           1          1         1         config,image(nodejs:latest)
java-fwwm-app        1          1         1         config,image(java:latest)
nodejs-trym-foobar   1          1         1         config,image(nodejs:latest)
▶ odo app list -o json | jq
{ …
```
=> Remove multiple "odo app list" entries

pkg/occlient/occlient.go, pkg/occlient/occlient_test.go
fixes situation when odo waited forever for a project that was already created
fixes https://github.com/openshift/odo/issues/1707
No easy way to test the fix. 
The only way to that I know how to reproduce the previous bug was by using the debugger. 
I had to comment out the `ProjectRequests().Create` call and then create the project manually right before stepping to water creation.
Creating watcher before the project we make sure that we watcher gets the create even in the go channel.
Due to the nature of the bug, it is almost impossible to write a test to cover this situation :-/
=> fix infinite wait in CreateNewProject

pkg/component/component.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/ui/ui.go
Fixes the path bug when using `odo create` and specifying either:
- A path outside of the location of the command being ran
- ./
- Blank input
This also changes the order of `odo create`. We ask for the type of
deployment (binary, local or git) FIRST and then the directory.
Closes https://github.com/openshift/odo/issues/1676
=> Fixes bug of path directories not working correctly with interactive UI

pkg/odo/cli/config/view.go, tests/integration/config_test.go
Using `genericclioptions.Context` required creation of an oc client
connection to the OpenShift server which was not necessary for viewing
the config stored in local config file at `.odo/config.yaml`
fixes #1745 
1. Stop the minishift instance used by `odo`: `minishift stop`
2. Navigate to a directory containing the `.odo/config.yaml` file or don't if you'd like to view the global config stored under `~/.odo/config.yaml`
3. Execute `odo config view`
=> Use local config info for viewing odo config

pkg/preference/preference.go
The global preference's default name changes to preference.yaml instead of config.yaml. As this file is present in the ~/.odo folder it will not colide with the config.yaml if someone chooses to create a component in home dir.
fixes https://github.com/openshift/odo/issues/1766
```
odo preference set Timeout 5 # this should create a ~/.odo/preference.yaml instead of ~/.odo/config.yaml
```
=> Renamed global preference file to preference.yaml from config.yaml

pkg/odo/cli/component/delete.go, pkg/odo/cli/component/describe.go, pkg/odo/cli/component/list.go, pkg/odo/genericclioptions/context.go, pkg/odo/util/cmdutils.go, tests/integration/component.go
fixes #1646 (only the component part)
This PR makes the app commands work outside a odo component directory if a project flag is given or the current project is used.
How to test:
Create a odo component and push. Then switch to a different directory containing no odo component. Then run the below commands
```
odo list --app <app-name>
odo delete <cmp-name> --app <app-name>
odo describe <cmp-name> --app <app-name>
```
```
odo component list --app <app-name>
odo component delete <cmp-name> --app <app-name>
odo component describe <cmp-name> --app <app-name>
```
These commands should work outside a odo component directory
=> Adds the functionality of running some component commands outside a odo directory

pkg/component/component.go, pkg/component/component_test.go, pkg/component/types.go, pkg/odo/cli/component/list.go, pkg/odo/genericclioptions/context.go, tests/integration/json_test.go
fixes #1587
```
[snarwade@redsuraj github.com]$ odo list --context openshift/nodejs-ex --path openshift
NAME            TYPE       SOURCE     STATE            CONTEXT
php-esgq        php        ./         not deployed     /home/snarwade/go/src/github.com/openshift/cakephp-ex
httpd-nesr      httpd      ./         not deployed     /home/snarwade/go/src/github.com/openshift/httpd-ex
nodejs-rtsc     nodejs     ./         deployed         /home/snarwade/go/src/github.com/openshift/nodejs-ex
ruby-kept       ruby       ./         deployed         /home/snarwade/go/src/github.com/openshift/ruby-ex
```
=> Added path flag and respective logic

.travis.yml, Makefile, docs/development.adoc, scripts/openshiftci-presubmit-e2e.sh, tests/template/template_cleantest_test.go
To reduce test time both locally and on CI too.
make clean-test
=> Running spec parallelly for clean test template

docs/cli-reference.adoc, pkg/odo/cli/version/version.go, scripts/installer.sh
Release notes draft
So what's new in v1.0.0-beta3?
Enhancements
- Adds a timer to UI / UX output to the odo component creation output. #1795 
- We can now run `odo component describe/delete/list` and `odo app describe/delete/list` outside a directory containing a odo component. #1792 and #1779  
- The problem of wrong path during odo create in interactive mode is fixed. #1764 
- We can now view odo config info from the local config without talking to the server. #1758 
- Adds a "shortcut" section to odo --help. #1763 
- Adds a `path` flag to `odo list` for viewing all components in a directory. #1771 
- Improves URL creation and deletion UI/UX. #1774 
- Rename install.sh to installer.sh and Add Uninstall #1802 
- Fix infinite wait in CreateNewProject #1785 
- Remove multiple "odo app …
=> Bumps version to v1.0.0-beta3

pkg/odo/cli/url/create.go, tests/integration/generic_test.go
This PR prevents the user from creating URL longer than 63 characters. Long URLs are not allowed by OpenShift. Refer https://github.com/openshift/odo/issues/1213#issuecomment-501201185
fixes #1213 
1. Build the binary.
2. Create a URL with a really long name like:
```bash
$ odo url create frontend-long-long-long-long-long-long-long-long-long-long-long-long-long-long --port 8080
```
=> Don't allow user to create a URL name longer than 63 characters

pkg/application/application.go, pkg/component/component.go, pkg/log/status.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go
This PR:
- Updates `odo app list` to also include services
- Adds tests to both GetDeploymentConfigLabelValues as well as
GetServiceInstanceLabelValues
- Sorts both functions alphabetically when outputting
To replicate:
```sh
git clone https://github.com/openshift/nodejs-ex
cd nodejs-ex
odo create nodejs --app app
odo service create mysql-persistent --app app2
odo app list
The project 'myproject' has the following applications:
NAME
app
app2
```
Closes https://github.com/openshift/odo/issues/1730
=> List apps deployed via servers within odo app list

docs/cli-reference.adoc, pkg/odo/cli/cli.go, pkg/odo/cli/component/common_link.go, pkg/odo/cli/config/set.go, pkg/odo/cli/config/unset.go, pkg/odo/cli/preference/preference.go, pkg/odo/cli/preference/set.go, pkg/odo/cli/preference/unset.go, pkg/odo/cli/utils/terminal.go, pkg/odo/cli/utils/utils.go, pkg/odo/cli/version/version.go, site/README.adoc
This started as just addressing the situation below, but now changes all `Odo` references to `odo` with the exception of code and comments.
Corrects typo for `utils` description with `odo --help`. 
```
utils       Utilities for terminal commands and modifying Odo configurations (terminal)
```
No
Verify that no `Odo` references are present for command messaging/descriptions.
=> Change Odo References to odo

pkg/log/fidget/spinner.go, pkg/log/status.go
This PR:
- Uses string based formatting for the time
- No longer uses "%v" with time.Duration, so there are no
false-positives when displaying the time
Closes https://github.com/openshift/odo/issues/1811
=> Switch to using string-based formatting for time elapsed

Makefile, pkg/catalog/catalog.go, scripts/openshiftci-presubmit-benchmark.sh, tests/benchmark/basic_benchmark.go, tests/benchmark/benchmark_test.go, tests/helper/helper_filesystem.go, tests/helper/reporter/httpMeasurementReporter.go
Tests are measuring the speed of various odo commands for Java and NodeJS
components.
Results are displayed on the output and also send to the Google Sheet table
https://docs.google.com/spreadsheets/d/1o-GIoYlZoEyW1F25kAwvvEXzbW4tLck0x3EGCC4_L_A/
Results are sent to Google Sheet table only when running on OpenShift CI (`CI=openshift`) 
related to #1726 
Can't be tested on OpenShift CI before it is merged :-(
Once merge I'll update openshift/release to trigger these tests and verify that it is soaking on CI
This can also be executed locally against your cluster `make test-benchmark` or `ginkgo  tests/benchmark`
=> Add benchmark tests

pkg/odo/cli/cli.go
Removes the odd missing subcommand output. Now it outputs like so:
```sh
✗  Subcommand not found, use one of the available commands: app, catalog, component, config, create, delete, describe, help, link, list, log, login, logout, preference, project, push, service, storage, unlink, update, url, utils, version, watch
```
Closes https://github.com/openshift/odo/issues/1800
=> Fix weird subcommand missing output

Makefile, docs/development.adoc, tests/integration/service_test.go
=> Run service test specs in parallel

pkg/odo/genericclioptions/context.go, pkg/odo/util/cmdutils.go
Adds capitalization to error messages since *some* error messages were
lowercase and others capitalized (see context.go file).
Examples:
```sh
github.com/openshift/odo  add-capitalization ✗                                                                                                                                                                              10h10m ⚑
▶ ./odo push
✗  Blank source location provided
github.com/openshift/odo  add-capitalization ✗                                                                                                                                                                             10h10m ⚑  ⍉
▶ ./odo list
✗  Please specify the application name and project name
Or use the command from inside a directory containing an odo component. …
```
=> Add capitalization to error messages

pkg/application/application.go
Removes the warning that Service Catalog is not enabled since some
OpenShift clusters may not have them enabled.
Closes https://github.com/openshift/odo/issues/1848
=> Drop warning message for Service Catalog

pkg/odo/cli/config/set.go, pkg/odo/cli/config/unset.go, tests/integration/cmd_pref_config_test.go
Removes the unecessary connection checks when using `odo config`.
See below for an example of the changes:
```sh
github.com/openshift/odo  remove-connection-check-config ✗                                                                                                                                                                             8h36m ⚑ ◒
▶ export KUBECONFIG=/tmp/non-exsisting
github.com/openshift/odo  remove-connection-check-config ✗                                                                                                                                                                             8h36m ⚑ ◒
▶ ./odo config set Name foobar
Local config was successfully updated.
Run `odo push --config` command to apply changes to the cluster.
github.com/openshift/odo …
```
=> Remove connection checks for `odo config`

pkg/component/component.go, pkg/component/component_test.go, pkg/component/types.go, pkg/odo/cli/component/list.go, tests/integration/cmd_app_test.go, tests/integration/component.go, tests/integration/json_test.go
this PR adds `--all` flag which will list down all components available in the cluster
fixes #1584
```
odo list --all
```
=> Added --all flag to odo list

Makefile, docs/development.adoc, tests/integration/generic_test.go
=> Run generic test file in parallel

pkg/component/component.go, tests/integration/component.go
This PR aims to keep the env vars set using `odo config set --env FOO=BAR` persistent between multiple `odo push` runs.
fixes #1834
=> Multiple odo push should retain the environment variable in OpenShift deployment

pkg/config/config.go, pkg/odo/cli/component/describe.go, pkg/odo/genericclioptions/context.go
Adds a disclaimer to use `odo push` to push the component if there is no
component deployed.
Closes https://github.com/openshift/odo/issues/1847
=> Add notes with regards to no component deployed when using odo describe

.travis.yml, pkg/odo/genericclioptions/context.go, scripts/openshiftci-presubmit-benchmark.sh, scripts/openshiftci-presubmit-e2e-scenarios.sh, scripts/openshiftci-presubmit-e2e.sh
The logout command can be triggered outside the context directory.
fixes #1836
=> Fixes the odo logout issue.

Makefile, docs/development.adoc, tests/integration/java_test.go
=> Run java test specs in parallel

pkg/odo/cli/component/common_push.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/push.go, pkg/odo/genericclioptions/add_flags.go, pkg/odo/genericclioptions/context.go, tests/integration/component.go
Adding `--now` flag with `odo create` and `odo component create`
Refactored ush logic into CommonPushOptions to allow reuse as needed and reused
in `create`
#1595 
Now flag now works on component create
```
$ ls
helm  openshift  package.json  README.md  server.js  tests  views
$ odo create nodejs
✓  Checking component
✓  Checking component version
Please use `odo push` command to create the component with source deployed
$  odo push
✓  Checking component
✓  Checking component version
✓  Creating nodejs component with name nodejs-dyns
✓  Initializing 'nodejs-dyns' component
✓  Creating component nodejs-dyns
✓  Successfully created component nodejs-dyns
✓  Applying component settings to component: nodejs-dyns
✓  Successfully updated component with name: nodejs-dyns
✓  Pushing changes to …
```
=> Adding now flag to component create command and refactoring for common push

Makefile, docs/development.adoc, scripts/openshiftci-presubmit-e2e-scenarios.sh, tests/e2escenarios/core_beta_flow.go
=> Run e2e scenarios test in parallel

docs/completion-architecture.adoc
Fixes the backticks so that asciidoc doesn't render the statement as code-blocks but renders only the specific word. Also a minor grammar fix.
NA
Refer the changed paragraph on below URLs:
- https://github.com/openshift/odo/blob/881a0a0fe3f79a52f9e14ae4396e780904d30b5f/docs/completion-architecture.adoc (current `master` at the time of opening this PR)
- https://github.com/dharmit/odo/blob/fix-backticks/docs/completion-architecture.adoc
=> Fix backticks and minor grammar fix

pkg/odo/cli/config/set.go, pkg/odo/cli/config/unset.go, pkg/odo/cli/config/view.go, tests/e2escenarios/core_beta_flow.go, tests/integration/cmd_pref_config_test.go
Added checks for checking if config file exists before doing `odo config set, view or unset`. also uncommented the failing test
fixes https://github.com/openshift/odo/issues/1895
the below commands will fail in a non-component dir
```
odo config set memory 2Gi
odo config unset memory
odo config view
```
=> check if the config file exists for odo config

pkg/application/application_test.go, pkg/application/types.go, pkg/odo/cli/application/application.go, tests/integration/cmd_app_test.go
Remove `Status.Active` field
Fixes #1866
`odo app list -o json` will not show active field
=> Removed active field for application

pkg/component/component.go
fasten the `component.Exists` function
fixes https://github.com/openshift/odo/issues/1805
`Validating Component` step will be bit faster :smile:
=> optimize component.exists function

pkg/occlient/occlient_test.go
There are times when unit test fail due to different ordering of list returned for ports
```
-- FAIL: TestGetPortsFromBuilderImage (0.00s)
--- FAIL: TestGetPortsFromBuilderImage/component_type:_php (0.00s)
occlient_test.go:5406: Client.GetPortsFromBuilderImage() = [8443/TCP 8080/TCP], want [8080/TCP 8443/TCP]
FAIL
FAIL    github.com/openshift/odo/pkg/occlient    3.282s
```
So used an order independent comparison for slices
No issue
unit tests shouldn't flake out
=> use order less slice comparison in unit tests

pkg/odo/cli/application/describe.go, tests/integration/cmd_app_test.go
having no components in an app shouldn't be an error
fixes https://github.com/openshift/odo/issues/1803
```
odo app describe test --project myproject > out 2>error
```
check `out` file, now it should have the `Application test has no components or services deployed.` message
=> having no components in an app shouldn't be an error

pkg/component/component.go, pkg/component/component_test.go, pkg/odo/cli/component/create.go, tests/integration/component.go
- Changed the ordering of prefix and component type when creating a default component name.
- Use of absolute path for source path when generating the default component name when source type is local
fixes https://github.com/openshift/odo/issues/1825
```
mkdir nodejs-test
odo create nodejs --context ./nodejs-test
cd nodejs-test
odo create nodejs --context .
```
should give the same component name
also
```
mkdir 1234
odo create nodejs --context ./1234
cd 1234
npm init --yes  #just so it doesn't fail on package.json not found error
odo push 
```
shouldn't fail due to `a DNS-1035 label must consist of lower case alphanumeric characters or '-'`
=> consistent component name and resolved failing numeric dir push

pkg/odo/cli/component/create.go, tests/integration/java_test.go
When using context dir with binary location the `SourceLocation` should be saved as a path relative to componentContext because in the end we are joining them both. Which wasn't happening before and is added as part of this PR
fixes https://github.com/openshift/odo/issues/1846
fixes https://github.com/openshift/odo/issues/1922
```
odo create wildfly javaee-war-test --project myproject --binary tests/examples/binary/java/wildfly/ROOT.war --context tests/examples/binary/java/wildfly/
odo push --context tests/examples/binary/java/wildfly/
```
should pass now
and
```
odo create wildfly javaee-war-test --project myproject --binary tests/examples/binary/java/wildfly/ROOT.war --context tests/examples/binary/java/wildfly/
cd ..
odo push --context odo/tests/examples/binary/java/wildfly/
```
should …
=> used relative path to SourceLocation for binary

pkg/occlient/occlient.go
Some older images are using this label for deployment dir.
For example java:8 and java:11 builder images  on OCP 4.2 are using this
label.
=> Add 'org.jboss.container.deployments-dir'  to S2IDeploymentsDir

pkg/odo/cli/component/common_push.go
Currently `Checking component` is shown two times as a exists call still remains. This PR removes it.
=> Removes an extra exist call and removes the spinner around it

Makefile
Due to the typo the component sub test was completely missing form the Makefile
make test-cmp-sub-e2e
=> Enabled component sub test in Makefile

pkg/log/status.go, pkg/odo/cli/application/delete.go, pkg/odo/cli/application/describe.go, pkg/odo/cli/application/list.go, pkg/odo/cli/cli.go, pkg/odo/cli/component/describe.go, pkg/odo/cli/component/list.go, pkg/odo/cli/project/list.go, pkg/odo/cli/storage/create.go, pkg/odo/cli/storage/list.go, pkg/odo/cli/url/create.go, pkg/odo/cli/url/list.go, pkg/odo/genericclioptions/add_flags.go, pkg/odo/genericclioptions/runnable.go
This PR:
- Makes `-o` or `--output` a global parameter
- Disables logging completely when performing `-o json`, including
using verbosity `-v`
- Fixes a minor bug within some commands where `-o json` wasn't
detected corretly due to a local flag being used `outputFlag` rather
than `OutputFlag`
=> Make --output a global parameter, disable logging, fix bug

Makefile, pkg/util/config_util.go, tests/helper/helper_filesystem.go, tests/helper/helper_http.go, tests/integration/component.go
gosec does static code analysis and checks for common security issues in
golang codebases.
This PR introduces the tool, and sets it up as a test target in the Makefile.
=> Introduce gosec for security checks

pkg/odo/cli/application/application.go
Adds newline spacing to `odo app --help` due to not having `\n\n` within
the help example (spacing was only 1 line)
```sh
Examples:
odo app delete myapp
odo app describe webapp
odo app list
odo app list --project myproject
```
=> Add newline spacing to odo app --help

pkg/odo/cli/component/list.go
fixes #1972 
This PR changes the message to `path of the directory to scan for odo component directories`
=> Fixes help message for path flag in odo list

pkg/occlient/occlient_test.go, pkg/odo/cli/component/create.go, pkg/util/util.go, tests/integration/component.go
This change prevents a stack trace from being printed when panic() is called. It will generate a more graceful error message for the end user.
A before/after example:
**Before:**
```
[adewey@localhost lab]$ odo create java backend --memory=1GB
panic: cannot parse '1GB': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
goroutine 1 [running]:
github.com/openshift/odo/vendor/k8s.io/apimachinery/pkg/api/resource.MustParse(0x7fff7e04b75b, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/adewey/go/src/github.com/openshift/odo/vendor/k8s.io/apimachinery/pkg/api/resource/quantity.go:133 +0x216
github.com/openshift/odo/pkg/util.FetchResourceQuantity(0x196aaa6, 0x6, 0x0, 0x0, 0x0, 0x0, 0x7fff7e04b75b, 0x3, 0x196aa6a) …
```
=> recover from panic to give more graceful error message

pkg/application/labels/labels.go, pkg/component/component.go, pkg/component/labels/labels.go, pkg/occlient/occlient_test.go, pkg/odo/cli/service/service_test.go, pkg/odo/cli/storage/storage_test.go, pkg/service/service_test.go, pkg/testingutil/deploymentconfigs.go, pkg/url/labels/labels.go, pkg/url/url_test.go, tests/e2escenarios/core_beta_flow.go, tests/helper/helper_oc.go
This updates labels to match  https://github.com/gorkem/app-labels/blob/master/labels-annotation-for-openshift.adoc and also to match how those labels are used in OpenShift devconsole.
This is to ensure that components created by odo are correctly displayed in devconsole topology view.
**This breaks compatibility with older odo versions!** 
Release notes will need to include a warning about this.
Components that are already pushed to the cluster using older odo versions will not work. User needs to delete a component from the cluster and push it again.
fixes #599
=> Update labels to match gorkem/app-labels recommendations

tests/integration/generic_test.go
```
[odo] Please use `odo push` command to create the component with source deployed
[odo] 
Running odo with args [odo config set Ports 8080/TCP]
? Ports is already set. Do you want to override it in the config (y/N)                               Aborted by the user.
^[[15;102RDeleting project: oipaimbpmd
Running odo with args [odo project delete oipaimbpmd -f]
```
=> Fixing random input applied by ginkgo in test script

docs/cli-reference.adoc, pkg/odo/cli/version/version.go, scripts/installer.sh
This PR bumps the odo version to v1.0.0-beta4
- The openshift labels used internally by odo to identify its components, have been updated to match https://github.com/gorkem/app-labels/blob/master/labels-annotation-for-openshift.adoc. This breaks backward compatibility with older versions of odo as components created by older versions will no longer be identified https://github.com/openshift/odo/pull/1959
- Removes an extra `exist` call and removes the spinner around it https://github.com/openshift/odo/pull/1965
- Graceful recovery from panic with mesage https://github.com/openshift/odo/pull/1954
- Fixed failing push when numeric directory is given https://github.com/openshift/odo/pull/1933
- Remove error if app does not have component https://github.com/openshift/odo/pull/1919
- `odo …
=> Bumps version to v1.0.0-beta4

pkg/odo/cli/service/list.go, pkg/odo/genericclioptions/context.go, tests/integration/service_test.go
User needs to provide the `app` and `project` for which they would like to list the
services.
Listing services (`odo service list`) was not possible unless one's working from a component directory. This PR fixes that issue as long as `--app` field is provided. 
fixes #1838 
1. Build the binary
2. Create a service from a component directory (#1810).
3. `cd` into a non-component directory
4. Execute `odo service list --app <app-name> --project <project-name>` where `<app-name>` and `<project-name>` should be same as the used in the component directory mentioned in Step 2.
=> Makes it possible to list services outside a component directory

pkg/odo/cli/component/delete.go, tests/helper/helper_filesystem.go, tests/integration/component.go
fixes #1925 
How to test
1. Create a component and push it to the cluster
2. Delete it from the cluster without the `all` flag
3. Delete again with the `all` flag and check it deletes the local config file or not
=> Fixes delete --all flag for not pushed components

.github/ISSUE_TEMPLATE/Bug.md, .github/ISSUE_TEMPLATE/Documentation.md, .github/ISSUE_TEMPLATE/Enhancement.md, .github/ISSUE_TEMPLATE/Feature.md
see $SUBJECT
fixes https://github.com/openshift/odo/issues/1931
check the github templates
=> removed the mattermost link and added google groups link in templates

pkg/odo/cli/service/create.go
Due to an ignored error, the creation of service was not checked until the function returned which made the output confusion hence handled the unhandled error.
fixes #1989 
```
odo service create dh-prometheus-apb --plan ephemeral 
odo service delete
odo service create dh-prometheus-apb --plan ephemeral 
```
this should fail quickly instead of giving odd log like
```odo service create dh-prometheus-apb --plan ephemeral --app myapp
✓  Creating service [6ms]
✓  Service 'dh-prometheus-apb' was created
Progress of the provisioning will not be reported and might take a long time.
You can see the current status by executing 'odo service list'
✗  object is being deleted: serviceinstances.servicecatalog.k8s.io "dh-prometheus-apb" already exists```
=> fail quickly if there is an error while creating service

pkg/odo/genericclioptions/context.go, tests/integration/service_test.go
So far, `odo service create` has either worked only from within a component directory or by using a `--context` flag (#1997) that points to a valid component directory. This PR makes it possible to create and delete (as listing a service was already taken care of by #1920) a service from outside a component directory using `--app` and `--project` flags in the stead.
fixes #1810 
1. Build the binary
2. Executing below commands should work:
```sh
$ ls .odo
ls: cannot access '.odo': No such file or directory 
$ odo service create dh-postgresql-apb --plan dev -p postgresql_user=luke -p postgresql_password=secret -p postgresql_database=my_data -p postgresql_version=9.6 --app myapp --project myproject
$ odo service list  --app myapp --project myproject
$ odo service delete  --app myapp …
```
=> Create, list and edit services using "--app" and "--project" flags (without a context)

pkg/odo/cli/url/create.go
Changes the order of the examples and slightly modifies the output.
```sh
Examples:
odo url create example
odo url create --port 8080
odo url create example --port 8080
odo url create example --port 8080 --component frontend
```
=> Small update to help.

pkg/odo/cli/component/common_push.go, pkg/util/file_indexer.go
storing relative filepaths in the file index and also storing the file index in a versioned struct called `FileIndex`
Note - This is a breaking change, this will break all the existing file maps. and I think users should remove the older file maps to transition ( or there could be some unexpected behavior )
fixes https://github.com/openshift/odo/issues/1975
```
odo create
odo push # check the file map to have relative paths
```
=> using relative filepaths in file indexer and added versioned file index

docs/getting-started.adoc
Added a section in Getting Started on how to set/unset/list env vars.
fixes #1677
=> Documentation on how to manage environment variables

pkg/occlient/occlient.go, pkg/odo/cli/component/common_push.go, pkg/util/util.go, pkg/util/util_test.go, tests/integration/cmd_push_test.go
This PR propagates and makes sure that all files which were deleted
locally in the source code is *also* deleted within the container on
OpenShift.
To test:
```sh
touch foobar.txt foobar2.txt && odo push && echo "\nPUSHING WITH REMOVING FILE\n" && rm foobar.txt foobar2.txt && odo push -v 4
```
Closes:
https://github.com/openshift/odo/issues/1354
=> Propagate deleted files to the container

pkg/log/status.go, pkg/machineoutput/types.go, pkg/odo/cli/project/create.go, pkg/odo/util/cmdutils.go, pkg/project/project.go, tests/integration/json_test.go
Adds machine readable output for odo create project.
To test:
```sh
odo create project -o json
```
=> Adds `odo create project -o json` output

pkg/preference/preference.go
add defaults to the global preferences and clearer debug log
fixes #1936 
```
odo preference --help
Modifies odo specific configuration settings within the global preference file. 
Available Parameters:
NamePrefix - Use this value to set a default name prefix (Default: current directory name)
Timeout - Timeout (in seconds) for OpenShift server connection check (Default: 1)
UpdateNotification - Flag to control if an update notification is shown or not (Default: true)
```
=> add defaults to the available global params

scripts/installer.sh, scripts/prepare-release.sh
see $SUBJECT.
fixes #1994 
`make prepare-release` should create
=> change the release extension from .gz to .tar.gz

Makefile, scripts/openshiftci-presubmit-unittests.sh
https://github.com/openshift/odo/pull/1998#discussion_r315745452
make cross
=> Making cross compile independent of gox vender package

docs/installation.adoc
Added instructions on how to uninstall odo 
fixes #1733
=> Documentation on uninstallation procedure

pkg/odo/cli/project/delete.go, tests/integration/json_test.go
Adds capability for `odo project create -o json` output.
To test:
```sh
github.com/openshift/odo  json-delete-project ✗                                                                                                                                                                                                                        1h50m ⚑  ⍉
▶ ./odo project create foobar -o json | jq
{
"kind": "Project",
"metadata": {
"name": "foobar",
"namespace": "foobar",
},
"message": "Project 'foobar' is ready for use"
}
github.com/openshift/odo  json-delete-project ✗ …
```
=> Adds `odo project delete -o json`

README.adoc
Because everybody loves badges :)
=> chore: pretty badges in README

pkg/odo/cli/service/create.go, pkg/odo/cli/service/delete.go, pkg/odo/cli/service/list.go, tests/integration/servicecatalog/service_test.go
This PR enables the users to create a service with `odo service create --context /path/to/component/dir` command. This allows service creation from anywhere in the system.
fixes #1872 
- Build the binary
- Using [nodejs-ex](https://github.com/sclorg/nodejs-ex) as an example, perform following:
```sh
$ git clone https://github.com/sclorg/nodejs-ex /tmp/nodejs-ex
$ cd /tmp/nodejs-ex
$ odo create nodejs
$ cd # this takes you to home dir
$ odo service create dh-postgresql-apb --plan dev -p postgresql_user=luke -p postgresql_password=secret -p postgresql_database=my_data -p postgresql_version=9.6 --context /tmp/nodejs-ex
$ odo service list --context /tmp/nodejs-ex
$ odo service delete --context /tmp/nodejs-ex
$ odo service create dh-prometheus-apb --plan ephemeral --context /tmp/nodejs-ex …
```
=> Adds "odo service create --context" feature

pkg/component/component.go, pkg/occlient/occlient.go, pkg/odo/cli/application/application.go, pkg/odo/cli/component/component.go, pkg/odo/cli/project/project.go, pkg/odo/cli/url/list.go, pkg/odo/util/cmdutils.go, pkg/odo/util/completion/completionhandlers.go, pkg/url/types.go, pkg/url/url.go, pkg/url/url_test.go, tests/integration/json_test.go, tests/integration/url_test.go
This PR is adding `State` field into `URL` structs. Url can be in 3 different states:
- Pushed: Url is present in local config and also on the cluster
- Locally Deleted: Url is present on the cluster but not in the local config
- Not Pushed: Url is present in the local config but not on the cluster
This is also reflected in the output
fixes #1893
This PR replaces https://github.com/openshift/odo/pull/1978
Create some urls, and delete them without pushing.
You should see each url reporting correct state
```
odo create java:8
odo url create url0 --port 8080
odo url create url1 --port 8443
odo push
odo url delete url1
odo url create url2 --port 8778
odo url list
```
```
▶ odo url list
Found the following URLs for component java-spring-boot-yelj in application app:
NAME …
```
=> List all urls even if they are only in local config or only in cluster

docs/development.adoc, pkg/component/component.go, pkg/occlient/occlient.go, pkg/occlient/templates.go
The initContainer image contains more than just  supervisord, this updates naming and paths to be more generic to reflect current use.
The test will fail until  https://github.com/openshift/odo-supervisord-image/pull/29 is merged and new image version is released.
=> rename odo-supervisord-image to odo-init-image

pkg/odo/genericclioptions/context.go
Not major but is realling irking me - this is expected in normal use and there are at least a half-dozen in every debug log.  It doesn't seem like it should be there.
Remove a useless debug log message
no
Run `odo -v4 ...` and note lack of "usually means flag wasn't set" messages.
=> Remove "Ignoring error as it usually means flag wasn't set"

docs/cli-reference.adoc, pkg/odo/cli/version/version.go, scripts/installer.sh
- Lists all URLs even if they are undeployed or not (https://github.com/openshift/odo/pull/2034)
- Added json output for `odo project delete -o json` (https://github.com/openshift/odo/pull/2037)
- You can now create list and edit services using --app and --project (https://github.com/openshift/odo/pull/2001)
- Added `odo service create --context` functionality (https://github.com/openshift/odo/pull/1997)
- Fixed service integration test that was previously failing (https://github.com/openshift/odo/pull/2022)
- `odo push` will now only push changed files (https://github.com/openshift/odo/pull/2030)
- We now use relative paths within the file indexer (https://github.com/openshift/odo/pull/2003)
- Deleted files will now propagate to the OpenShift container …
=> Release 1.0.0-beta5

pkg/odo/cli/service/create.go, tests/integration/servicecatalog/service_test.go
add parameter map population in non-interactive service creation. 
fixes https://github.com/openshift/odo/issues/2033
confirm that env variables get populated and show correctly
```
$ odo service create dh-postgresql-apb dh-postgresql-apb --plan dev -p postgresql_database=mydata -p postgresql_password=secret -p postgresql_user=luke -p postgresql_version=10
$ oc describe pod/<postgres-pod> | grep -A3 Env
Environment:
POSTGRESQL_PASSWORD:  secret
POSTGRESQL_USER:      luke
POSTGRESQL_DATABASE:  mydata
```
=> add parameter map population in non-interactive service creation

Makefile, scripts/cross-compile.sh
Adds a cross-compiling script rather than having it in the Makefile.
To test:
```sh
github.com/openshift/odo  fix-cross ✔                                                                                                                                                                                                                                                                                                                                   0m
▶ make cross
./scripts/cross-compile.sh '-X github.com/openshift/odo/pkg/odo/cli/version.GITCOMMIT=91599ec5'
Cross compiling linux-amd64 and placing binary at dist/bin/linux-amd64/
Cross compiling darwin-amd64 and placing binary at dist/bin/darwin-amd64/
Cross compiling windows-amd64 and placing binary at dist/bin/windows-amd64/
```
=> Add cross compiling script

Dockerfile, Dockerfile.rhel
This Dockerfile is a used by CI to publish openshift/odo binary artifacts. It builds an image containing the Mac, Win and Linux version of odo binary on the OpenShift golang image.
This is a requirement to publish odo artifacts through ART processes
This file is for CI use, however you can build it locally by ```docker build .``` command
Steps:
1. git clone https://github.com/openshift/odo
2. Rename the file Dockerfile.rhel to Dockerfile
2. Use the image registry ```registry.access.redhat.com/ubi7/ubi``` instead of ```registry.svc.ci.openshift.org/ocp/4.2:cli```
3. Run ```docker build .```
=> Dockerfile is used by CI to publish odo artifacts

pkg/occlient/occlient.go, tests/integration/cmd_push_test.go
Update init image to `quay.io/openshiftdo/init:0.10.0` 
The new version of the image includes custom inner loop scripts, see https://github.com/openshift/odo-init-image/pull/27
To test this just make sure that everything works as before :-)
=> update quay.io/openshiftdo/init image to 0.10.0

pkg/machineoutput/types.go, pkg/occlient/occlient.go, pkg/odo/cli/catalog/list/services.go, pkg/odo/util/cmdutils.go, pkg/project/project.go, tests/integration/servicecatalog/cmd_service_test.go
Adds the ability to list catalog services and output to json.
The format is as follows:
```json
{
"kind": "ServiceList",
"metadata": {
},
"items": [
{
"name": "cakephp-mysql-persistent",
"hidden": false,
"planList": [
"default"
]
},
]
}
```
Closes https://github.com/openshift/odo/issues/1357
=> Adds `odo catalog list services -o json`

pkg/odo/cli/component/common_link.go, tests/integration/servicecatalog/cmd_link_unlink_test.go
This PR prints the environment variables that are added or removed from a component as a result of `odo link` or `odo unlink` operation.
fixes #1964 
- Build the binary
- Start a service:
```sh
$ odo service create dh-postgresql-apb dh-postgresql-apb --plan dev -p postgresql_database=mydata -p postgresql_password=secret -p postgresql_user=luke -p postgresql_version=10
```
- Create a component, push it and link the service created above to the component:
```sh
$ odo link dh-postgresql-apb
✓  Service dh-postgresql-apb has been successfully linked from the component nodejs-nodejs-ex-kyvs
Following environment variables were added to nodejs-nodejs-ex-kyvs component:
- DB_PORT
- DB_TYPE
- DB_USER
- DB_HOST
- DB_NAME
- DB_PASSWORD
```
- Similarly, create another component and link the two …
=> Prints environment variables added/removed to a component by doing odo link/unlink

README.adoc, docs/getting-started.adoc
Removes the required `--port` from the README and Getting Started guides
since we now default to the port available on the container/image and if
it's not available, odo will automatically error / prompt you for a
port.
=> Remove required --port within README and Getting Started guides

pkg/odo/cli/component/create.go
Removes an extra newline that was added to the output.
`log.Infof` already adds a newline..
=> Remove newline from odo create output

pkg/occlient/occlient.go, tests/benchmark/basic_benchmark.go, tests/e2escenarios/e2e_beta_test.go, tests/e2escenarios/e2e_java_test.go, tests/e2escenarios/e2e_source_test.go, tests/helper/helper_oc.go, tests/integration/cmd_storage_test.go, tests/integration/component.go, tests/integration/servicecatalog/cmd_service_test.go
a few changes to tests to make them run on 4.2
fixes #2049
issues were:
- image stream java:8 is not latest https://github.com/openshift/odo/issues/2049#issuecomment-525768485
- image stream dotnet:2.0 not available
=> update tests so they run on  openshift 4.2

cmd/odo/odo.go, pkg/log/status.go, pkg/odo/cli/version/version.go
Changes the update information to display at italic in order to not get
mixed in with the other output.
Also remove the quotes for `odo preference set UpdateNotification false`
so it's easier to copy-and-paste from the terminal.
To test:
1. Modify pkg/odo/cli/version/version.go VERSION var to "v1.0.0-beta4"
or any version previous
2. Compile
3. Run a standard create command `odo create nodejs`
=> Makes update information italic text

tests/e2escenarios/e2e_source_test.go
Import dotnet2.0 image stream if not available in cluster
no, but it will fix failure in source test on 4.2 cluster
```
[odo]  ✗  image stream dotnet with tag 2.0 not found in openshift and bubtumritz namespaces
```
Details - https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/4883/rehearse-4883-pull-ci-openshift-odo-master-v4.2-e2e-scenarios/8
See the pr - https://github.com/openshift/release/pull/4883
=> Import dotnet20 image stream on openshift42 cluster

pkg/occlient/occlient.go, pkg/odo/cli/cli.go, pkg/odo/cli/version/version.go, pkg/odo/genericclioptions/context.go, pkg/odo/genericclioptions/context_flags.go
Removes connection check from the workflow
related to #1588 
Do `odo logout` and see if things that should work without an active connection with OpenShift cluster still work.
=> Removes connection check with OpenShift cluster

pkg/component/component.go, pkg/odo/cli/component/common_push.go
fixes #1971 
How to test:
1. Create a git component and push twice
2. Try all update scenarios e.g git to local 
No overlapping should happen in the logs
=> Removes overlapping messages for odo git components

pkg/odo/cli/component/common_push.go
There is enough info in verbose, we shouldn't always be outputting that
a project is being created.
=> Remove creating project info

pkg/odo/cli/version/version.go
Reduces the amount of output the user is given when prompting that odo
needs to update.
See below:
```sh
github.com/openshift/odo  update-message ✗                                                                                                                                   0h1m ⚑
▶ ./odo list --context ~/nodejs-ex
APP     NAME                      TYPE       SOURCE        STATE
app     nodejs-nodejs-ex-wdfr     nodejs     file://./     Pushed
---
A newer version of odo (v1.0.0-beta5) is available.
Visit https://github.com/openshift/odo/releases to update.
If you wish to disable this notification, run:
odo preference set UpdateNotification false
---
```
fixes #2089
To test:
1. Change line 20 in `cli/version/version.go` to any other version
(beta4)
2. `make bin`
3. Run any command
=> Reduces amount of lines in release info / update

README.adoc, docs/installation.adoc
change .gz to .tar.gz in docs.
This is a follow up PR after https://github.com/openshift/odo/pull/2009 as it changes the doc references.
As per https://github.com/openshift/odo/pull/2009#issuecomment-523481624
part of #1994 
check the docs for the change
=> [merge after https://github.com/openshift/odo/pull/2009] change .gz to .tar.gz in docs

tests/integration/cmd_app_test.go, tests/integration/component.go
Match machine readable source path in windows platform
Quick fix of #2115
run ```make test-cmd-app``` and ```make test-cmd-cmp``` on windows platform
=> Fix source path for windows platform

docs/development.adoc
Adds a development doc on how to create correct machine readable output
with a working example on how to implement it.
=> Add development doc on machine readable output

pkg/odo/cli/application/application.go, pkg/odo/cli/application/describe.go, pkg/odo/cli/project/project.go, pkg/odo/cli/service/list.go, pkg/odo/util/completion/completionhandlers.go, pkg/service/service.go, pkg/service/service_test.go, pkg/service/types.go, tests/integration/servicecatalog/cmd_service_test.go
Adds `odo service list -o json` support.
To test:
```sh
github.com/openshift/odo  add-service-listing-json ✔                                                                                                                                                                                                                         0m
▶ ./odo service list -o json --context ~/nodejs-ex | jq
```
```json
github.com/openshift/odo  add-service-listing-json ✔                                                                                                                                                                                                                         5m
▶ ./odo service list -o json --context ~/nodejs-ex | jq
{
"kind": "ServiceList", …
```
=> Adds `odo service list -o json`

.gitignore
Ignore these files when committing. These are test reports which are
generated when running tests locally or on CI.
=> Add tests/reports to .gitignore

pkg/occlient/occlient.go, pkg/occlient/templates.go
This PR makes use of go-init instead of dumb-init to avoid having to maintain our own rpm for dumb-init
All standard workflows should pass
=> Replace dump-init with go-init

pkg/odo/genericclioptions/context.go
Removes the check for search.
To test:
```sh
odo catalog search component ruby
```
Closes https://github.com/openshift/odo/issues/2132
=> Remove context check for search

pkg/odo/cli/catalog/search/component.go, pkg/odo/cli/catalog/util/util.go, pkg/odo/genericclioptions/context.go, tests/integration/servicecatalog/cmd_service_test.go
Updates the output to match the output from `odo catalog search
service`.
See below:
```sh
github.com/openshift/odo  update-search-table ✗                                                                                                                                                                                                                                                                                                                       6m ⚑
▶ ./odo catalog search service rails
NAME                       PLANS
rails-pgsql-persistent     default
github.com/openshift/odo  update-search-table ✗ …
```
=> Update the `odo catalog search component` output

pkg/catalog/catalog.go
add nodejs images present in the minishift in the supported images
party https://github.com/openshift/odo/issues/2129
with 
init image side PR https://github.com/openshift/odo-init-image/pull/36
```
run 
odo catalog list components
```
on minishift
=> add nodejs minishift images in supported

pkg/catalog/catalog.go, pkg/catalog/catalog_test.go, pkg/catalog/types.go, pkg/component/component.go, pkg/machineoutput/types.go, pkg/occlient/occlient.go, pkg/occlient/utils.go, pkg/occlient/utils_test.go, pkg/odo/cli/catalog/list/components.go, pkg/odo/cli/catalog/list/services.go, pkg/odo/cli/catalog/search/component.go, pkg/odo/cli/catalog/search/service.go, pkg/odo/cli/catalog/util/util.go, pkg/odo/cli/catalog/util/util_test.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/ui/ui.go, pkg/odo/util/completion/completionhandlers.go, pkg/service/service.go, tests/integration/component.go, tests/integration/servicecatalog/cmd_service_test.go
This PR:
- Changes how we use `odo catalog list services` (using ServiceTypeList
and ServiceType)
- Changes how we use `odo catalog list components (using
ComponentTypeList and ComponentType)
- Refactors the code from occlient.go and puts it inside of
catalog/catalog.go
- Changes how to we output services by using `ServiceTypeList`
- Changes the API structure of `odo catalog list services`
To test:
```sh
odo catalog list services
odo catalog list components
```
See below for an example of the updated json:
```json
{
"kind": "ServiceTypeList",
"metadata": {
},
"items": [
{
"kind": "ServiceType",
"metadata": {
"name": "cakephp-mysql-persistent",
},
"spec": {
"hidden": false,
"planList": [ …
```
=> Refactor catalog code

Makefile
Removed ```.PHONY openshiftci-presubmit-e2e``` from Makefile as it was a dead command.
No
Nowhere used further, Refer ```https://github.com/openshift/release/tree/master/ci-operator/config/openshift/odo```
=> Delete .PHONY openshiftci-presubmit-e2e From Makefile

Makefile
The Makefile was passing `slowSpecThreshold=$(SLOW_SPEC_THRESHOLD)` without a leading '-' so was ignoring `SLOW_SPEC_THRESHOLD`.
Fixed this and put common flags in a single variable so they can be changed in one place.
Also you can now say `make VERBOSE=` to turn off -v output from ginkgo and
set `make SLOW_SPEC_THRESHOLD=xxx` to change the threshold.
make test-integration was ignoring the `SLOW_SPEC_THRESHOLD`
No
Before change `make test-integration` reports "slow test" after 5 sec.
After change, only reports "slow test" after 120 secs.
=> Fix slowSpecThreshold flag in Makefile

Makefile, tests/integration/loginlogout/cmd_login_logout_test.go
Making each login test spec independent.
https://github.com/openshift/odo/pull/2162#issuecomment-534467268
make test-cmd-login-logout
=> Fixing login flake

pkg/odo/cli/catalog/list/components.go
Updates the spelling errors introduced in:
https://github.com/openshift/odo/pull/2029/files#diff-1898d8a28a2de7aa682a9de52faa269dR96
=> Fix spelling errors in catalog list components

Dockerfile.rhel, docs/cli-reference.adoc, docs/development.adoc, pkg/odo/cli/version/version.go, scripts/installer.sh, scripts/rpm-prepare.sh
* Support for `odo debug`. `odo` now lets users debug the application running in the pod on OpenShift (#2043)
* Add json output for `odo catalog list services`. This helps the consumers of `odo`, i.e., Adapters (#2066)
* Add json output for `odo service list`. This helps the consumers of `odo`, i.e., Adapters (#2098)
* Add RPM spec for odo. Very soon, an RPM for `odo` will be available and `odo` could be installed with `yum/dnf install odo`  (#2107)
* Replace dumb-init with go-init. To avoid having to maintain our own RPM for dumb-init  (#2130)
* Refactor catalog code  (#2133)
* Print environment variables when linking a component with another component/service (#2035)
* Fix populating parameters of service when created in non-interactive mode. `odo service create` didn't pick-up the …
=> Bump odo version to 1.0.0-beta6

tests/integration/component.go
Fixing ```no such file or directory``` issue for scenario https://github.com/openshift/odo/blob/master/tests/integration/component.go#L579
fixes #2184 
make test-cmd-cmp
=> Fixing no such file or directory issue

scripts/prepare-release.sh
SHA256_SUM file was generated in the wrong directory, and it was not uploaded to the github release
=> fix sha256 generation for release

pkg/odo/cli/component/create.go, pkg/odo/cli/component/ui/ui.go
fixes #2163 
How to test:
Trigger `odo create` in a directory, enter response of `Location of path component, relative to ...` and check if the correct response is stored by `odo config view`
=> Fixes path for odo create interactive

pkg/occlient/occlient.go
- logs stdout and stderr of the tar command
- logs the DeploymentConfig definition
This will make it easier to debug issues during the file transfer. And issues with DeploymentConfig.
=> log stdout and stderr of tar command

README.adoc
Updates the README formatting for commands. Adds instructions on CRC.
=> Updates the README formatting and adds crc

tests/integration/loginlogout/loginlogout_suite_test.go, tests/integration/servicecatalog/servicecatalog_suite_test.go
sync with other test ```/reports``` directory
no
login, service and link test reports should be generated in ```reports/``` directory
=> Fixing login, service and link reports path

docs/machine-output.md, pkg/application/application.go, tests/integration/cmd_app_test.go
This PR:
- Capitalizes the Kind to Application
- Uses the full name of Application
- Uses ApplicationList instead of List (which is already taken by `odo
list`)
=> Updates machine readable output for `odo app`

tests/integration/cmd_pref_config_test.go
Fixing of random input provided by gikgo.
No
```make test-cmd-pref-config```
=> Fix random ginkgo input in test script

.travis.yml, Makefile, docs/development.adoc, scripts/openshiftci-presubmit-benchmark.sh, scripts/openshiftci-presubmit-e2etests.sh, scripts/openshiftci-presubmit-integrationtests.sh
fixes #2074
NOTE: Make a practice of adding a verbose flag to every odo command in test file
See the test result in the terminal locally
=> Disable ginkgo verbose mode

pkg/component/component.go, pkg/odo/cli/component/create.go, tests/integration/component.go
fixes #1969
```
cd /component/path
odo component create java:8 --binary /component/path/target/java.jar
```
should succeed
Previously it was failing. This is a valid command, as binary is inside the context.
=> fix --binary  flag when --context is not set

pkg/component/component.go, tests/integration/component.go
fixes #2186 
fixes #2032 
How to test:
- Create two or more odo components belonging to different projects and push all to the cluster
- try `odo list --path <root_of_both_component_folders>`
- check if the states for the components are right or not
=> Fixes odo list with path flag

docs/cli-reference.adoc, pkg/odo/cli/catalog/list/components.go, pkg/odo/cli/utils/terminal.go
#1833 Changed references of `Odo` to `odo` in an effort to keep referencing `odo` consistent throughout the CLI. There were some additions to `odo` since then that have added in more `Odo` references. This pull request changes any `Odo` references to `odo`.
No
Verify the `Odo` references are gone for `odo catalog list components` and `odo utils` `terminal` description.
=> Removing Odo References from CLI

README.adoc
Correcting typos in README on using `crc`/`minishift`
N/A
=> Edits to Deploying an application using odo Section of README

README.adoc
#2226 caught most of the issues around adding `crc` to the README, but `crc stop` needs to be mentioned in addition to `minishift stop`.
N/A
=> Add crc stop to Deploy Application Section of README

pkg/odo/cli/storage/create.go, pkg/odo/cli/storage/delete.go, pkg/odo/cli/storage/list.go, pkg/odo/cli/storage/mount.go, pkg/odo/cli/storage/unmount.go, tests/integration/cmd_storage_test.go
fixes #2203 
How to test:
Try the app,project and component flags with all storage commands. ODO will complain of unknown flags for them.
=> Removes app,project and component flag from storage commands

pkg/occlient/occlient_test.go, pkg/occlient/templates.go, tests/integration/cmd_url_test.go
fixes #1981 
How to test:
1. Trigger `test-cmd-url` on a 4.2 cluster close to 10 times and check if the error described in the issue occurs or not and also if the second push only triggers a single deployment revision.
=> Fixes double deployment for git components on second push and later

docs/cli-reference.adoc, pkg/odo/cli/debug/debug.go
Changes `Debug allows you to remotely debug you application` to `Debug allows you to remotely debug your application`.
N/A
`odo debug --help` should provide description that shows `Debug allows you to remotely debug your application`
=> Correct odo debug Typo

pkg/project/project_test.go
Created unit test for project list.
No
Unit test should pass.
=> Adds unit test for project list

pkg/catalog/catalog.go, pkg/odo/cli/catalog/util/util_test.go, tests/integration/servicecatalog/cmd_service_test.go
For `odo catalog list services` machine-readable output for `Kind`
should simply be `List`
=> ServiceTypeList should be List in machine output

pkg/odo/cli/storage/delete.go, pkg/odo/cli/storage/mount.go, pkg/odo/cli/storage/unmount.go
We removed the `--component`,`--app` and `--project` flag from `odo storage` but the examples are still present, so cleaning them up
part of https://github.com/openshift/odo/issues/2243
`odo storage --help`
shouldn't show `--component` examples
=> removed example for --component from storage

Makefile, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, tests/integration/cmd_project_test.go, tests/integration/project/cmd_project_test.go, tests/integration/project/project_suite_test.go
fixes #2117 
How to test:
Check if the `odo project create <project-name> -w` works and it waits properly for the project to be ready.
=> Fixes project wait flag

pkg/odo/cli/cli.go, pkg/odo/cli/component/component.go, pkg/odo/cli/component/delete.go, pkg/odo/cli/component/describe.go, pkg/odo/cli/config/config.go, tests/integration/generic_test.go
This PR:
- Modifies the output of running JUST `odo` similar to how `oc` does
it.
- There is now a difference between running `odo` and running `odo
--help`
- Removes "Normalize" for the long description since it was messing up
newline formatting
- Adds integration tests for help usage
Closes https://github.com/openshift/odo/issues/1672
Example of running JUST `odo`:
```sh
(OpenShift Do) odo is a CLI tool for running OpenShift applications in a fast and automated manner.
Reducing the complexity of deployment, odo adds iterative development without the worry of deploying your source code.
Find more information at https://github.com/openshift/odo
Get started by creating a new application:
git clone https://github.com/openshift/nodejs-ex && cd nodejs-ex
odo push
Your nodejs …
```
=> Updates the help usage of odo

pkg/log/status.go, pkg/odo/util/cmdutils.go
Updates the `odo describe` output to be a bit more intuitive / better
looking.
=> Updates `odo describe` output

pkg/odo/cli/catalog/list/components.go
add an explicit `Unsupported` in catalog list component
fixes https://github.com/openshift/odo/issues/2148
```
odo catalog list components
```
=> add explicit Unsupported in catalog list component

pkg/catalog/catalog.go, tests/integration/component.go
For `odo catalog list components` machine-readable output for `Kind`
should simply be `List`
=> ComponentTypeList should be List in machine output

pkg/odo/genericclioptions/context.go
Changes the error message grammar for `odo project create` and `odo project set`.
Closes #2254
=> Fix Grammar for odo Error for Project Create and Set

.gitignore
Reports path is updated in .gitignore file
No
git should ignore the test report file
=> Update test reports path in gitignore file

pkg/odo/cli/url/create.go, pkg/odo/cli/url/url.go
see $SUBJECT
part of https://github.com/openshift/odo/issues/2243
```
odo url create --help
```
shouldn't have the flags
=> remove --app, --component and --project from odo url

Makefile
Test target execution method should be in sync with other test target
No
make test-cmd-debug
=> Making debug command test target in sync

pkg/component/component.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/push.go, tests/integration/component.go
odo create command should verify that binary is inside the context folder.
how to test:
- When the binary file is outside of the context folder the command should fail.
- `odo create --binary ../file.jar`
- `odo create --binary target/file.jar --context my-component`
- When the binary is in the context folder everything should be ok.
- `odo create --binary target/file.jar`
- `odo create --binary ../mycomponent/file.jar --context ../mycomponent`
fixes https://github.com/openshift/odo/issues/2266
=> Check that --binary is in --context folder

pkg/machineoutput/types.go, pkg/odo/cli/application/describe.go, pkg/odo/cli/application/list.go, pkg/odo/cli/component/describe.go, pkg/odo/cli/component/list.go, pkg/odo/cli/project/list.go, pkg/odo/cli/storage/create.go, pkg/odo/cli/storage/list.go, pkg/odo/cli/url/list.go, pkg/util/util.go, tests/helper/helper_generic.go, tests/integration/component.go, tests/integration/project/cmd_project_test.go
Use formatted json output for Machine Readable Output, This aligns us with oc and kubectl and also makes it easy for developers to consume the output.
Used the same spacing and prefix used by `oc `
fixes #https://github.com/openshift/odo/issues/2235
```
odo list -o json
```
=> show formatted json for machine readable output

pkg/occlient/occlient.go, pkg/occlient/templates.go, tests/helper/helper_oc.go, tests/integration/servicecatalog/cmd_link_unlink_test.go
This fixes the issue where the source code for nodejs was lost after the container was restarted.
This was due to the fact that we removed steps that were coping source files from the /tmp/src directory to /opt/app-root/src.
This updates just the image used by odo, the actual fix is in odo-init-image - https://github.com/openshift/odo-init-image/pull/40
After this is tested. We will release a new odo-init-image, and update this PR to use the released version.
fixes https://github.com/openshift/odo/issues/2224
You can download odo binaries build from this PR at https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_odo/2265/pull-ci-openshift-odo-master-v4.1-unit/407/artifacts/unit/dist/bin/
```
odo component create nodejs
odo url create
odo push
odo config set …
```
=> Fix issue with failing NodeJS component after the container gets restarted

pkg/odo/cli/application/describe.go, pkg/odo/cli/component/describe.go, pkg/odo/util/cmdutils.go
Adds the "secrets" or environment variables that have been passed into
the component by using the `odo link` feature when connecting to a
database.
Builds upon PR: https://github.com/openshift/odo/pull/2231
Closes: https://github.com/openshift/odo/issues/2232
See the below example of how it now looks like:
```sh
Component Name: nodejs-nodejs-ex-cstb
Type: nodejs
Source: file://./
Environment Variables:
· foo=bar
· bar=foo
· DEBUG_PORT=5858
Storage:
· mystorage of size 1Gi mounted to /opt/app-root/src/storage/
URLs:
· http://foobar-app-myproject.192.168.42.79.nip.io exposed via 8080
Linked Components:
· nodejs2 - Port(s): 8080
Linked Services:
· mongodb-persistent
Environment Variables:
· uri
· username
· admin_password
· database_name
· password
· dh-mysql-apb
Environment Variables:
· …
```
=> Add secrets to `odo describe`

pkg/odo/cli/component/common_link.go, tests/integration/servicecatalog/cmd_link_unlink_test.go
Bolds the info message for outputting the environment variables as well
as changes the grammar.
=> Updates environment variable output

cmd/cli-doc/cli-doc.go
When running `make generate-cli-reference`, changes from #2214 are changed back to original format with `Odo` for cli-reference doc. This pr changes `cli-doc.go` to keep the the cli-reference doc title consistent with other references to `odo` throughout the CLI.
N/A
=> Change Odo Reference to odo for cli-docs

pkg/catalog/catalog.go, pkg/catalog/catalog_test.go, pkg/odo/cli/component/create.go, tests/integration/component.go
Show warning for unsupported image types on executing `odo create`
fixes https://github.com/openshift/odo/issues/2156
```
odo create python # should show the warning
odo create java # shouldn't show the warning
```
=> show warning for unsupported image types

pkg/odo/cli/component/watch.go, tests/integration/cmd_watch_test.go
Currently due to the check of source path existence using `os.Stat` being present before `sourceType` validation - `odo watch` showed `directory doesn't exist` error instead of `watch not supported for git ...` kind.
So resolved that and added a test.
fixes https://github.com/openshift/odo/issues/2138
```
odo create nodejs --git https://github.com/openshift/nodejs-ex.git
odo watch # should show an error for kind "Watch is supported by binary and local components only...."
```
=> show error when using odo watch on git components

rpms/openshift-odo.spec
```bash
$ rpm -ql openshift-odo-redistributable-1.0.0beta6-1.fc30.x86_64 
/usr/share/licenses/openshift-odo-redistributable
/usr/share/licenses/openshift-odo-redistributable/LICENSE
/usr/share/openshift-odo-redistributable
/usr/share/openshift-odo-redistributable/SHA256_SUM
/usr/share/openshift-odo-redistributable/odo-darwin-amd64
/usr/share/openshift-odo-redistributable/odo-darwin-amd64.tar.gz
/usr/share/openshift-odo-redistributable/odo-linux-amd64
/usr/share/openshift-odo-redistributable/odo-linux-amd64.tar.gz
/usr/share/openshift-odo-redistributable/odo-windows-amd64.exe
/usr/share/openshift-odo-redistributable/odo-windows-amd64.exe.tar.gz
```
=> Updating spec to use `make prepare-release` to create binaries

Dockerfile.rhel, docs/cli-reference.adoc, pkg/odo/cli/version/version.go, scripts/installer.sh, scripts/rpm-prepare.sh
**Enhancements:**
Issue #1672 - Help message is overwhelming for first time users
Issue #2232 - `odo describe` should also show secrets / linked variables from other components and services
#2283 - Updating spec to use `make prepare-release` to create binaries 
#2240 - Adds unit test for project list 
#2268 - Making debug command test target in sync 
#2231 - Updates `odo describe` output 
#2213 - Updates environment variable output 
#2187 - Move dev documentation to /dev 
#2188 - Updates the README formatting and adds crc
**Bug Fixes:**
Issue #2138 - odo watch should fail with error message for git based components
Issue #2156 - show warning for supported and unsupported images when doing odo create/push 
Issue #2192 - "odo push" panics for component created in interactive mode
Issue …
=> Bump odo version to 1.0.0-beta7

pkg/occlient/occlient.go
registry.access.redhat.com/openshiftdo/odo-init-image-rhel7:1.0.0
=> Updating default bootstrapper image to GA'ed image

Dockerfile.rhel, pkg/odo/cli/version/version.go, scripts/installer.sh, scripts/rpm-prepare.sh
Needs https://github.com/openshift/odo/pull/2292
- Release notes will be copy of beta7 except will also mention the updated image
- There is no code change, so not sure if cli docs need to be generated again
=> Bumping version to 1.0.0

tests/integration/project/cmd_project_test.go
see $SUBJECT
partly https://github.com/openshift/odo/issues/2298
tests shouldn't have `F` (focus) in them
=> Removed forgotten focus from integration tests

pkg/odo/cli/application/describe.go, pkg/odo/cli/application/list.go, pkg/odo/cli/catalog/list/components.go, pkg/odo/cli/catalog/list/services.go, pkg/odo/cli/cli.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/delete.go, pkg/odo/cli/component/describe.go, pkg/odo/cli/component/link.go, pkg/odo/cli/component/list.go, pkg/odo/cli/component/log.go, pkg/odo/cli/component/push.go, pkg/odo/cli/component/unlink.go, pkg/odo/cli/component/update.go, pkg/odo/cli/component/watch.go, pkg/odo/cli/project/create.go, pkg/odo/cli/project/delete.go, pkg/odo/cli/project/list.go, pkg/odo/cli/service/list.go, pkg/odo/cli/storage/create.go, pkg/odo/cli/storage/list.go, pkg/odo/cli/url/list.go, pkg/odo/genericclioptions/runnable.go, pkg/odo/util/cmdutils.go, tests/integration/component.go
This PR:    
- Moves annotations to `&cobra.Command` struct creation rather than    
using the command to add it    
- Errors out if `-o json` has been passed, but json support has not    
been added    
- Hides the `-o json` command if it's not impemented    
- Solves the issue of https://github.com/openshift/odo/issues/2031    
- Changes "Global Flags" to "Additional Flags"
Closes https://github.com/openshift/odo/issues/2031
=> Errors out if json machine output has not been implemented

pkg/config/env_var.go, pkg/config/env_var_test.go, pkg/odo/cli/config/unset.go, tests/integration/cmd_pref_config_test.go
At the moment, there's no check for the scenario where a user tries to unset an environment variable that doesn't exist in the configuration. This PR aims to fix that and fails the execution.
fixes #2274 
* Create a component
* Try to unset an environment variable that doesn't exist in component's config: `odo config unset --env nosuchvar`.
=> Fails if user tries to unset invalid environment variable

.github/PULL_REQUEST_TEMPLATE.md
/kind docs
We need this for a few reasons:
- Our current template has too much "fluff", needing to remove
multiple lines of comments just to commit..
- If you use the template from the command-line using `git commit` you
are actually unable use markdown headers (`#` is a comment in Git...)
- We should have a way to use `/kind`
- This template follows the way Kubernetes does it:
https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md
but simpler
Fixes #?
View the doc :) The above example is what the new "template" looks like.
=> Modifies the PR commit template

pkg/odo/cli/component/common_link.go
/kind cleanup
Changes successful `odo link` message from 
`Component backend has been successfully linked from the component frontend`
to
`Component backend has been successfully linked to the component frontend`
This reads a lot more clearly since information is being shared from the first component as part of `odo link`. The current implementation makes it sound as if information is coming from the component specified via the `--component` flag or via the context being worked in.
Looking for advice on whatever `operationName` options are available that could potentially not work with this message. Link was the only option considered here.
None
=> change "from" to "to" for odo link

tests/integration/cmd_debug_test.go, tests/integration/cmd_push_test.go, tests/integration/component.go
/kind bug
Due to recent change in the s2i image for nodejs in openshift 4.3. The `/tmp/src` directory doesn't hold the code anymore because it gets moved. 
We know this happens for some images and we have a workaround in the odo-init-image. But our test for nodejs assumes that source is present in `/tmp/src`, due to which they are failing on openshift 4.3.
Fixes https://github.com/openshift/odo/issues/2357
tests should pass on 4.3 cluster
=> change checks of ODO_SRC_PATH/src in tests and a temporary fix for project list flake

Makefile, docs/dev/development.adoc, pkg/application/application_test.go, pkg/application/labels/labels.go, pkg/application/labels/labels_test.go, pkg/component/component.go, pkg/component/labels/labels_test.go, pkg/odo/cli/version/version.go, pkg/storage/labels/labels_test.go, pkg/storage/storage_test.go, pkg/url/labels/labels_test.go, pkg/url/url.go, pkg/url/url_test.go, pkg/version/version.go, scripts/bump-version.sh, tests/helper/helper_oc.go, tests/integration/cmd_push_test.go
This PR:
- Moves versioning information to `pkg/version/version.go` so other
parts of odo is able to use the versioning information (namely
`pkg/component/labels/labels.go`.
- Updates documentation on the versioning move
- Adds `app.kubernetes.io/managed-by-version` label
- Adds `app.kubernetes.io/managed-by` label
See example below of the changes:
```yaml
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
annotations:
app.kubernetes.io/component-source-type: local
app.openshift.io/vcs-uri: file://./
creationTimestamp: 2019-10-10T21:15:55Z
generation: 2
labels:
app: app
app.kubernetes.io/instance: foobar
app.kubernetes.io/managed-by: odo
app.kubernetes.io/managed-by-version: v1.0.0-beta6
app.kubernetes.io/name: nodejs
app.kubernetes.io/part-of: app …
```
=> Add managed-by labels

pkg/odo/cli/component/create.go
`odo create` was removed when the annotations were unfortunately set
incorrectly.
```
Component Shortcuts:
delete      Delete component
describe    Describe component
link        Link component to a service or component
list        List all components in the current application
log         Retrieve the log for the given component
push        Push source code to a component
unlink      Unlink component to a service or component
update      Update the source code path of a component
watch       Watch for changes, update component on change
```
No issue
```sh
odo --help
```
Should now show `create` under …
=> Add "odo component create" back to shortcuts.

pkg/odo/cli/application/describe.go, pkg/odo/cli/application/list.go, pkg/odo/cli/component/describe.go, pkg/odo/cli/component/list.go, pkg/odo/cli/project/list.go, pkg/odo/cli/storage/create.go, pkg/odo/cli/storage/list.go, pkg/odo/cli/url/list.go, pkg/util/util.go
/kind code refactorting
Refactors the machine readable output to use the
`machineoutput.OutputSuccess(structFormattedOutputHere)` function instead.
This removes using `fmt.Println(output)`.
N/A
Use odo component list -o json or any other json-output-formatted
command.
No tests have been added as they are already covered via integration /
unit tests and this is simply a code refactor.
=> Refactoring output of machine output

pkg/odo/cli/project/create.go
/kind cleanup
Removes space from project creation success message. The space is unnecessary and is not how `odo` commonly formats output.
N/a
Create a project and verify extra space is gone:
```
$ odo project create myproject
Project 'myproject' is ready for use
New project created and now using project: myproject
```
=> Remove Space from Project Create Success Message

rpms/openshift-odo.spec, scripts/cross-compile.sh
OpenShift is currently available for X86-64 and IBM Power LE, and IBM Z is coming.  IBM customers will expect to be able to download and run odo on their systems (particularly on Z where admins generally prefer homogeneous environments).  oc is also available on all RHEL architectures:
https://mirror.openshift.com/pub/openshift-v4/clients/oc/4.2/
The same should apply to odo, particularly as download links thereto are provided from the console.
A successful scratch build has been done internally.
=> Build and package for all RHEL architectures

README.adoc
/kind docs
Currently Codewind already supported OpenShift projects and can use odo as build engine to build projects, so we can add Codewind as `projects using odo` on official odo website.
Issue in Codewind repository: https://github.com/eclipse/codewind/issues/754
=> Update doc since Codewind project already used odo

cmd/odo/odo.go, docs/dev/logging.adoc
* Add enviroment variable "ODO_LOG_LEVEL" to control odo verbosity. Command line flag "-v", if set, will take precedence over "ODO_LOG_LEVEL"
This PR enable a user to set odo log level by setting the environment variable "ODO_LOG_LEVEL"
Fixes #2351
=> Add env variable "ODO_LOG_LEVEL" to control odo verbosity (#2351)

docs/dev/development.adoc, scripts/changelog-script.sh
/kind docs
- Adds changelog script to quickly generate a changelog using
github_changelog_generator
Fixes N/A
N/A
=> Update the development guide + add changelog script

pkg/auth/login.go, pkg/log/status.go, pkg/odo/cli/application/list.go, pkg/odo/cli/component/common_link.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/push.go, pkg/odo/cli/config/set.go, pkg/odo/cli/config/unset.go, pkg/odo/cli/preference/set.go, pkg/odo/cli/preference/unset.go, pkg/odo/cli/service/create.go, pkg/odo/cli/storage/create.go, pkg/odo/cli/storage/delete.go, pkg/odo/cli/url/create.go, pkg/odo/cli/url/delete.go, tests/integration/component.go
/kind code refactorting
/kind docs
This PR:
- Adds italic font when outputting what to "do next". Essentially, when
using log.Info it's for a "bold" or "title" log. When using log.Italic
it's mainly used for when we want to say to the user what to do next,
such as using `odo push` to propagate changes
- Removes random periods which aren't suppose to be there (all output
should not be sentences with periods)
N/A
Run: `odo create nodejs` or any other similar commands, such as `odo
url create` which have "next steps" in them.
=> Add italic font when describing what to do next

pkg/odo/cli/component/create.go, tests/integration/component.go, tests/integration/project/cmd_project_test.go
/kind cleanup
We don't actually have json / machine readable output implemented yet
for `odo create`
N/A
N/A
=> Remove machineoutput annotation from odo create

scripts/openshiftci-presubmit-all-tests.sh, scripts/openshiftci-presubmit-integratione2ebenchmark.sh
/kind test
Putting all test target to a single OpenShift CI presubmit file to optimize the no of test cluster run for each pr.
Fixes - part of #2360 
pr https://github.com/openshift/release/pull/5909 should work properly after this goes in.
=> Add all test target to a single OpenShift CI presubmit file

pkg/odo/cli/service/create.go
/kind cleanup
Cleans up the output for service creation and adds an output of what to
do next:
```sh
Deploying service mongodb of type: dh-mongodb-apb
✓  Deploying service [78ms]
✓  Service 'mongodb' was created and is currently provisioning
View the status of the provision by executing 'odo service list'
Optionally, link dh-mongodb-apb to your component by running: 'odo link <component-name>'
```
N/A
```sh
make bin && ./odo service create dh-mongodb-apb mongodb --plan persistent -p DATABASE_SERVICE_NAME=mongodb -p MEMORY_LIMIT=512Mi -p MONGODB_DATABASE=sampledb -p VOLUME_CAPACITY=1Gi
```
Signed-off-by: …
=> Cleanup service creation output

pkg/config/config.go, pkg/odo/genericclioptions/context.go, pkg/odo/util/completion/completion.go
There was a change to context that was introduced in commit:
https://github.com/openshift/odo/commit/b800ebc370ee0ed893b3522d323327d36c188847
that made it so odo would error out when there was no configuration.
Previously, there was a boolean value that was passed in to disable
checking for a valid configuration, but that was removed by:
https://github.com/openshift/odo/commit/b800ebc370ee0ed893b3522d323327d36c188847
This re-introduces a boolean value to disable configuration checking
when using context since not always is there a configuration when using
autocompletion / checking parameters.
Closes https://github.com/openshift/odo/issues/1718
**How to test changes?**
Install …
=> Disable context / checking for config when using autocompletion

scripts/openshiftci-presubmit-all-tests.sh, scripts/openshiftci-presubmit-e2etests.sh, scripts/openshiftci-presubmit-integrationtests.sh, tests/e2escenarios/e2escenarios_suite_test.go, tests/integration/integration_suite_test.go, tests/integration/loginlogout/loginlogout_suite_test.go, tests/integration/project/project_suite_test.go, tests/integration/servicecatalog/servicecatalog_suite_test.go
/kind test
Ginkgo customReporters does not record properly the status of specs in JUNIT report. So disabling the JUNIT reports generator
Fixes - No, However due to the ginkgo upstream issue https://github.com/onsi/ginkgo/issues/628, it good to disable the reporting part till the issue is fixed.
make <any_test_target> should not create JUNIT reports.
=> Disabling ginkgo JUNIT report generator

pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/occlient/volumes.go, pkg/url/url_test.go, tests/integration/generic_test.go
This PR sets the DC created by `odo push` as the owner of following OpenShift objects of the component:
- Service
- Route
- PVC
- Secret
As a result, doing `oc delete dc/<dc-name>` deletes all the objects from the cluster that belong to the component. The only object it can't remove is an ImageStream
fixes #1793 
- Build the binary
- Create a component and push it
- Not the output of following commands:
```sh
$ oc get all
$ oc get pvc
$ oc get secret
```
- Do `oc delete dc/<dc-name>` and observe the output of above commands again. Except the ImageStream, all other objects cease to exist on the cluster.
=> Set DC as ownerReference for objects created on OpenShift cluster

tests/integration/cmd_link_unlink_test.go
/kind test
Adding test for missing flag in link test file
Fixes #?No
make test-cmd-link-unlink
=> Adding wait flag test in link command test

pkg/odo/cli/component/list.go
/kind bug
see $SUBJECT
Fixes https://github.com/openshift/odo/issues/2415
Compare
```
odo list --help 
odo component list --help
```
the flags and additional flags should be same for both
=> resolve odo list --help having different output then odo component list --help

pkg/occlient/occlient.go, pkg/odo/cli/preference/preference.go, pkg/odo/cli/preference/set.go, pkg/odo/cli/preference/unset.go, pkg/odo/cli/preference/view.go, pkg/preference/preference.go, pkg/preference/preference_test.go, tests/integration/cmd_push_test.go
/kind feature
Adds the ability to set your own pushtimeout, being able to configure
how long to wait for the push to time out.
For example:
```sh
odo preference set PushTimeout 30
```
Will set the default pod timeout to 30 seconds.
Fixes #943
```sh
odo preference set PushTimeout 1
odo push
```
=> Add `odo preference set PushTimeout` / pod timeout configuration

tests/integration/component.go
/kind bug
Runs component commands with and without shortcut commands
Fixes #2432 
```make test-cmd-cmp```
```make test-cmd-cmp-sub```
=> Run component commands with and without shortcut commands

pkg/odo/cli/component/delete.go
/kind bug
This PR removes redundant `if` check.
NA
Check for the CI's blessings.
=> Removes redundant check for existence of component

pkg/odo/cli/storage/create.go, pkg/odo/cli/storage/delete.go, pkg/odo/cli/storage/list.go, pkg/odo/cli/storage/storage.go, pkg/odo/cli/url/url.go
/kind cleanup
Fixes the output in `odo storage --help` and `odo url --help` with the
missing newlines.
The new output:
```sh
Examples:
odo url create example
odo url create --port 8080
odo url create example --port 8080
odo url delete myurl
odo url list
```
N/A
```sh
odo storage --help
odo url --help
```
=> Fix help output for url and storage

Makefile, scripts/check-fit.sh
Adds a small script to check for instances of `FIt(` being in the code.
This helps with regards to not merging in tests with FIt in integration.
N/A
N/A
=> Add check for "FIt" script

pkg/occlient/occlient.go, pkg/odo/cli/component/common_push.go, pkg/odo/cli/component/push.go, pkg/util/file_indexer.go, tests/integration/cmd_push_test.go
This PR fixes the following issues:
- Deletion not working within windows and using a non-relative path
command, ex: `odo push --context nodejs-ex/`
- File changes not working when using a non-relative path command:
`odo push --context nodejs-ex/`
- Use forward slashes when storing information into
odo-file-index.json
To test (on Windows):
```sh
git clone https://github.com/openshift/nodejs-ex
cd nodejs-ex\
odo push
cd ..
odo push --context nodejs-ex
type nul > nodejs-ex\foobar.txt
odo push --context nodejs-ex
```
All of these commands should now work as odo will now pass on the
absolute path to the file index functions and commands before deletion /
propagating changed files
Then check the index:
```sh
type nodejs-ex\.odo\odo-file-index.json
```
Which will now have …
=> Use the absolute path when using odo push

pkg/component/watch_test.go
/kind bug
Fixes the watch unit test and adds more 
Fixes #2365 
run `make test` and check if it passes
=> Fixes watch unit

pkg/odo/cli/component/list.go
/kind feature
(Honestly not sure what the kind is here. Should it be enhancement?)
$Title
Fixes #2219 
Before:
```sh
$ odo list --path ~/src
APP     NAME         TYPE       SOURCE                      STATE          CONTEXT
app     backend      java       target/wildwest-1.0.jar     Pushed         /home/dshah/src/Wild-West-Backend
app     frontend     nodejs     ./                          Pushed         /home/dshah/src/Wild-West-Frontend
app     node         nodejs     ./                          Not Pushed     /home/dshah/src/nodejs-ex
```
Now:
```sh
$ odo list --path ~/src
APP     NAME         PROJECT        TYPE …
```
=> Adds PROJECT field to 'odo list' output

pkg/catalog/types.go
/kind api-change
/kind cleanup
Cleaning up the machine readable output for `odo catalog list components`. 
No issue
```
odo catalog list components -o json
```
shouldn't have `ImageStreamRef`' information.
=> remove ImageStreamRef from machine readable output

pkg/odo/cli/config/set.go
/kind feature
Adds a warning message while component name or project name of the component name is changed in the config
Fixes #2172
- Create a component
- Change the component name or project name in the config `odo config set name <value>` or `odo config set project <value>`
- Check if the warning message is displayed properly or not
=> Adds warning component name and project change

docs/proposals/odo-debug.md
After https://github.com/openshift/odo-init-image/pull/45 is merged. we will be using `DEV_MODE` to control debug mode so we need to change the docs to reflect that information
Partly https://github.com/openshift/odo/issues/2409
Doc change
=> changed DEBUG_MODE to DEV_MODE in odo-debug design doc

pkg/component/component.go, pkg/component/component_test.go, pkg/odo/cli/component/delete.go, tests/integration/cmd_link_unlink_test.go
/kind bug
This PR unlinks a component requested for deletion from all the components it might be linked to in the OpenShift cluster
Fixes #2355 
1. `odo create nodejs node`
2. `odo create java java`
3. From component `node`'s context directory do `odo link java --port 8080`
4. From component `java`'s context directory do `odo delete -f`
5. From component `node`'s context directory do `odo delete -f`
=> Deleting a component also unlinks it from components it might be linked to

README.adoc
had to escape the # in url to make it actually work.
=> fix links to google group

pkg/catalog/catalog.go, pkg/catalog/types.go, pkg/odo/cli/catalog/list/components.go, tests/integration/component.go
/kind feature
adds `supportedTags` list in the `odo catalog list components`'s machine readable output.
The `supportedTags` is not removed from the out if it's empty, this is done to make the output consistent for all `ComponentType`.
Fixes https://github.com/openshift/odo/issues/2208
```
odo catalog list components -o json
```
should have the `supportedTags` and it should be consistent with `odo catalog list components`
=> add supportedTags list in the odo catalog list component json output

pkg/occlient/occlient.go, pkg/odo/cli/component/common_push.go, pkg/odo/cli/component/update.go, tests/integration/component.go
Use of --context flag in odo update and internally odo update uses common push.
fixes https://github.com/openshift/odo/issues/2155
fixes https://github.com/openshift/odo/issues/1778
fixes https://github.com/openshift/odo/issues/1782
for the issues https://github.com/openshift/odo/issues/1782 and https://github.com/openshift/odo/issues/1778. I have uncommented the tests and haven't observed the flake since locally and on CI.
```
odo push
odo update --git  https://github.com/openshift/nodejs-ex.git
=> Fix odo update

pkg/component/component.go
/kind cleanup
see $SUBJECT
No issue
error log should now show correct information
=> resolve wrong argument in errorf - use component name instead of all args

.wwhrd.yml
new wwhrd version broke some of the detections
- BSD license is split to BSD-3-Clause and BSD-2-Clause
- MPL-2.0 is now MPL-2.0-no-copyleft-exception
- some of the previously detected packages are no detected by new version
=> fix wwhrd licence detection

tests/helper/helper_configValidate.go, tests/helper/helper_generic.go, tests/integration/component.go
/kind test
Verifies local component config on the host.
Fixes #2439 
$ make test-cmd-cmp && make test-cmd-cmp-sub
=> Verify local config after component create

Dockerfile.rhel, pkg/version/version.go, scripts/installer.sh, scripts/rpm-prepare.sh
Preparing to release v1.0.3
> /kind bug
> /kind design
> /kind flake
=> Bump release version 1.0.2 -> 1.0.3

pkg/service/types.go, tests/integration/servicecatalog/cmd_service_test.go
/kind bug
`odo catalog describe service <service-name>` failed for plans where
value of `default` field was an integer. For example below would cause
the command to fail:
```
"instanceCreateParameterSchema": {
"$schema": "http://json-schema.org/draft-04/schema",
"additionalProperties": false,
"properties": {
"cluster_size": {
"default": 1,
"description": "Number of Elasticsearch instances that the cluster will consist of",
"title": "Cluster size",
"type": "integer"
},
```
This PR fixes that issue.
Fixes #2488 
Check that `odo catalog describe service <service-name>` works well for the services.
=> Describe services with multiple plans correctly 

docs/proposals/operator-hub.md
/kind design
/kind feature
Proposes a plan for Operator Hub integration with odo
NA
Easier way to navigate the markdown: https://github.com/dharmit/odo/blob/operator-hub-proposal/docs/proposals/operator-hub.md
=> Proposal for Operator Hub integration with odo

tests/integration/cmd_push_test.go
/kind test
/kind bug
Resolves platform specific file separator in test
Fixes #2523 
`make test-cmd-push` 
Note : No such type of issues are found in other integration test files.
=> Resolved platfrom specific file separator in test

pkg/occlient/occlient_test.go
/kind feature
validates empty values in pkg/occlient/occlient.go
Fixes #598 
//TODO
=> Validation for empty values in pkg/occlient/occlient.go

pkg/kclient/deployments.go, pkg/kclient/deployments_test.go, pkg/kclient/generators.go, pkg/kclient/generators_test.go
Signed-off-by: Rajiv Senthilnathan <rajivsen@ca.ibm.com>
/kind feature
Adds the base kclient functions required for creating a Deployment that consists of a Pod with containers that map to each of the components in a Devfile. Once the devfile parsing is complete I can add the rest of the required code in a separate PR.
Partially implements https://github.com/openshift/odo/issues/2471
1. `cd pkg/kclient`
1. `go test -v`
Results:
```
=== RUN   TestCreateDeployment
=== RUN   TestCreateDeployment/Case:_Valid_deployment_name
=== RUN   TestCreateDeployment/Case:_Invalid_deployment_name
--- PASS: TestCreateDeployment (0.00s)
--- …
```
=> Add kclient functions for creating deployments

pkg/component/component.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go
=> Testing build fix

Makefile, scripts/generate-coverage.sh
/kind bug
missing testingutil test coverage report 
Fixes #? NA
make test-coverage should include ```testingutil``` pkg and it should be reflected in travis job that generates the test coverage report
=> Including testingutil package in test coverage report

scripts/changelog-script.sh
> /kind bug
Updates the changelog script to *not* include summary / epics / etc as
it was not properly generating
N/A
run ./scripts/changelog-script.sh
=> Update changelog script

pkg/odo/cli/component/common_push.go, pkg/odo/util/cmdutils.go
/kind bug
> /kind design
> /kind flake
This commit updates, odo push output to show exact error to user from openshift, so that user can know the cause of error and updates local config accordingly. e.g. When a user creates a storage 
with some **invalid name** ,  it does not out show user the cause of error.
```
[adisky@localhost odo]$ odo storage create storageFive --context ~/my_components/nodejs-ex/ --path /data5 --size 1Gi
✓  Added storage storageFive …
```
=> Odo Push Show Error to User from Openshift

pkg/odo/cli/application/describe.go, pkg/odo/util/cmdutils.go, tests/integration/cmd_app_test.go
/kind bug
> /kind design
> /kind flake
odo app describe command does not work, When run out of component folder, it lists storage from local config. This PR updates it to list storage from oc client, It also adds bounds check at other places to avoid panic in case of no output.
**Which issue(s) this PR fixes**: 
Fixes #2528
Run `odo application describe <app> --project <myproject>` after adding …
=> Fix Panic: When odo app describe run out of component folder

Makefile, docs/dev/development.adoc
Enabling verbose mode for unit test run. Helps to debugging the unit test failure 
Fixes #? NA
UNIT_TEST_VERBOSE_MODE=-v make test
=> Use env variable for unit test verbose mode

pkg/debug/info.go, pkg/debug/info_test.go, pkg/odo/cli/debug/debug.go, pkg/odo/cli/debug/info.go, pkg/odo/cli/debug/portforward.go, pkg/testingutil/fileutils.go, tests/helper/helper_http.go, tests/helper/helper_run.go, tests/integration/cmd_debug_test.go
Adds the debug info command
/kind feature
This PR adds the debug info command. It detects if a debug session is running on the component or not.
Fixes #2015 
- Start a debug port-forward session on a component
- run debug info on the component from a different terminal window
=> Adds the debug info command

pkg/config/fakeConfig.go, pkg/odo/cli/storage/list.go, pkg/storage/storage.go, pkg/storage/storage_test.go, pkg/storage/types.go, tests/integration/cmd_storage_test.go
> /kind bug
> /kind design
/kind feature
> /kind flake
This PR adds feature to list storage state, Pushed, NotPushed
or Locally Deleted
Fixes  #2559
Run `odo storage list`, It will show state in the output
```
[adisky@localhost nodejs-ex]$ odo storage list
The component 'nodejs-nodejs-ex-cqli' has the following storage attached:
NAME             SIZE     PATH       STATE
newstorage …
```
=> Add State to Odo Storage List

.travis.yml, Makefile, cmd/odo/odo.go
Expose ODO_LOG_LEVEL env to the integration tests for getting verbose logs for failing tests
Check that a failing test has verbose logs.
=> Exports ODO_LOG_LEVEL env variable in integration tests

pkg/odo/cli/cli.go, pkg/odo/cli/component/devfile.go, pkg/odo/cli/component/push.go
This PR removes the `push-devfile` command and replaces it's behavior by adding the `--devfile` flag to the `odo push` command itself. 
Fixes #2538 
The experimental mode needs to be enabled and the `--devfile` flag needs to be explicitly set for the devfile feature to work.
=> Remove devfile push cmd

tests/e2escenarios/e2e_images_test.go, tests/integration/cmd_debug_test.go, tests/integration/cmd_push_test.go, tests/integration/component.go
/kind bug
nodejs:latest tag is supported on openshift 4.* so updating nodejs:8 to the latest tag.
Fixes #2542 
It should run successfully on prow 4.*
=> Updating nodejs:8 to nodejs:latest for source example run on openshift 4.*

pkg/catalog/catalog.go
/kind bug
> /kind design
> /kind flake
Resolved a panic on `odo catalog list component` when the docker image url doesn't have registry url and namespace information
Could possibly fix #2628 but we need to wait for the imageStream information to confirm it doesn't panic
=> possible fix: index out of bound error on `odo catalog list compoments` when registry url and namespace are not present

Makefile, pkg/debug/info_test.go, pkg/odo/cli/debug/portforward.go, pkg/testingutil/httputils.go, pkg/util/util.go, pkg/util/util_test.go, tests/helper/helper_http.go, tests/helper/helper_run.go, tests/integration/cmd_debug_test.go, tests/integration/debug/cmd_debug_test.go, tests/integration/debug/debug_suite_test.go
/kind feature
This PR adds auto selection of port if the default port is occupied. This only works when the local-port is not selected by the user using the flag.
Fixes #2606 
- run some command/program and occupy the port 5858
- run `odo debug port-forward` on the component
- it should throw an error that the port is busy and a different port is auto selected and is used by the program.
- run `debug info` on the component to verify the debug session.
=> Adds auto selection of port if the default port is occupied

pkg/component/component.go, pkg/occlient/occlient.go, pkg/util/config_util.go, pkg/util/file_indexer.go, pkg/util/util.go, tests/helper/helper_filesystem.go
- change file permissions to 0600
- ignoring gosec error G307. This checks for "Deferring a method which returns an error". Sometimes this can be a problem as it hides the error returned from the function. I've added `// #nosec G307` to all places where we close files. Failing to close the file doesn't usually have fatal consequences, so it should be ok to ignore it.
fixes #2659
=> fix failing gosec check

pkg/odo/util/cmdutils.go, pkg/storage/storage.go, tests/integration/component.go
> /kind bug
> /kind design
> /kind flake
Fixes odo describe for not pushed components
Fixes  #2594
**How to test changes / Special notes to the reviewer**: `odo describe` command should not fail
```
$ odo create nodejs
$ odo storage create --size 1Gi --path  /data1
$ odo describe
```
=> Fix odo describe for not pushed components

pkg/component/component.go, pkg/component/component_test.go, pkg/odo/cli/component/common_push.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/delete.go, pkg/odo/cli/component/describe.go, pkg/odo/cli/component/list.go, pkg/odo/cli/component/push.go, pkg/odo/cli/component/watch.go, pkg/odo/cli/config/set.go, pkg/odo/cli/config/unset.go, pkg/odo/cli/debug/info.go, pkg/odo/cli/debug/portforward.go, pkg/odo/cli/storage/create.go, pkg/odo/cli/storage/delete.go, pkg/odo/cli/storage/list.go, pkg/odo/cli/url/delete.go, pkg/odo/cli/url/list.go, pkg/odo/genericclioptions/context.go
/kind cleanup
We have `LocalConfigInfo` as part of `Context` but we still are initialising it multiple times and even at places have duplicate declarations. So removing those.
Fixes https://github.com/openshift/odo/issues/2602
Tests should pass and @cdrage you should probably be unblocked.
=> removed duplicate LocalConfigInfo and redundent file reads

pkg/odo/cli/catalog/describe/service.go, pkg/odo/genericclioptions/context.go
> /kind bug
Currently, the odo configuration file is required for describing catalog services. This is not the desired behavior. odo configuration file should not be necessary for describing catalog services. This PR fixes that issue.
Fixes #2605 
Execution of `odo catalog describe service <serivce-name>` command should work without requiring the `.odo/config.yml` file.
=> Fix odo catalog describe service command to not require odo config file

.travis.yml, pkg/component/watch.go, pkg/component/watch_test.go, pkg/debug/info_test.go, pkg/occlient/occlient.go, pkg/odo/cli/service/ui/ui_test.go, pkg/testingutil/survey_ui.go, pkg/util/util_test.go
/kind feature
Run all the unit test on windows platform
Fixes #2539
Unit test should run on windows through travis CI
=> Unit test on windows

.travis.yml, Makefile, scripts/openshiftci-presubmit-unittests.sh
Currently, the validations are run only on travis-ci. 
The problem is that Travis-CI status is not checked by merge-bot, so the PR can be merged even if the tests are failing.
This PR makes sure that the validations are also run on Prow, so we don't merge code that, for example not correctly formated.
=> run validate with unit tests on OpenShift CI

pkg/odo/cli/component/list.go, tests/integration/component.go
> /kind bug
> /kind design
> /kind flake
the description and name for `--all` flag in `odo list` command was misleading. This PR updates it to `--all-apps`
**Which issue(s) this PR fixes**: 
Fixes #2452 
Run `odo list --help` and check for renamed flag and description
```
[adisky@localhost odo]$ odo list --help
List all components in the current application.
Usage:
odo list [flags]
Examples:
odo list …
```
=> Rename -all flag for odo list and Update description

tests/helper/helper_oc.go
/kind cleanup
I was poking through the integration test code and saw that `CheckForExistence` in `test/helper/helper_oc.go` doesn't actually work as intended:
https://github.com/openshift/odo/blob/9b3c652fdf9b155273c06909165fa5dc48d9e858/tests/helper/helper_oc.go#L434-L439
This PR updates `CheckForExistence` so that it uses the passed in resource type, rather than just routes.
Fixes https://github.com/openshift/odo/issues/2697
=> Update CheckForExistence to get right resource

openshift-ci/build-root/Dockerfile
/kind bug
It will create a secret directory inside container, So that we can use the tokens for private registry login
Fixes NA
It should pass.
=> Create a secret directory in docker file for private registry

README.adoc
I found that I had *no idea* what package manager I could use. I would
use Yarn for Node.js and found that it wasn't enabled... Same goes with
Java as well as Ruby (although that's unsupported) with their
corresponding package managers.
This adds more details to the GitHub README with regards to what package
managers are actually supported
Fixes https://github.com/openshift/odo/issues/2683
=> Update the README with corresponding languages and package managers

docs/dev/machine-output.adoc, scripts/generate-machineooutput-doc.sh
Adds a table and references to machine output documentation
N/A
View the doc
=> Add machine output documentation

pkg/component/watch_test.go
/kind bug
It removes the unit tests requiring the survey package and fixes the watch unit tests for windows.
Fixes #2570 (windows part)
- add `// +build !windows` to `testing\survey_ui.go` and `odo\cli\service\service_test.go`
- run the watch tests on windows
=> Fixes watch unit tests for windows

pkg/devfile/parser/apiVersion.go, pkg/devfile/parser/apiVersion_test.go, pkg/devfile/parser/content.go, pkg/devfile/parser/content_test.go
Accommodating review comments from #2500 
Fixes #2553 
Devfile related actions should work without any errors.
=> Fake filesystem changes to devfile parser

.github/ISSUE_TEMPLATE/Feature.md, .github/ISSUE_TEMPLATE/UserStory.md
Updates the labeling for GitHub issue submission
N/A
N/A
=> Update labeling for GitHub issues

pkg/debug/info_test.go
/kind flake
It uses a free port from the system for the debug info unit test
- the debug info unit test should pass on windows
=> Fixes debug info test for windows

pkg/odo/cli/service/create.go, pkg/odo/cli/service/create_test.go
/kind bug
> /kind design
> /kind flake
Fixes https://github.com/openshift/odo/issues/2696
Create a service and check the equivalent command 
```
$ odo service create --app test 
? Which kind of service do you wish to create database
? Which database service class should we use  [Use arrows to move, type to filter]
dh-mssql-apb
dh-mysql-apb
dh-postgresql-apb
> …
```
=> add app and project in the create service equivalent command template

.github/PULL_REQUEST_TEMPLATE.md
Hopefully this fixes the confusion for uncommenting :)
Updates the description on "how" to uncomment so people don't get
confused
N/A
N/A
=> Add additional information to pull request template

pkg/log/fidget/spinner.go, pkg/log/status.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/odo/util/cmdutils.go
/kind feature
This PR:
- Adds more information when deploying via "WaitAndGetPod". We parse
the current events which are happening and then look for event counts
which have occured more than 5 times. We then output this information
with the spinner in order to help the user determine what's taking so
long to deploy
- Collect event information that's outputted when it fails with a
table.
- Changes how we output errors
Example outputs:
```sh
▶ odo push -f
Validation
✓  Checking component [122ms]
Configuration changes
✓  Initializing component
✓  Creating component [733ms]
Pushing to component nodejs-nodejs-ex-dorv of type local
✗  Waiting for component to start [5s]
ERROR:
waited 5s but was unable to find a running …
```
=> Adds event information when waiting for a pod

pkg/occlient/fakeclient.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/project/project.go, pkg/project/project_test.go, tests/integration/project/cmd_project_test.go
fixes #2117 
fixes #2284 
How to test:
- Run `odo project create <name> -w` and check if the command waits properly.
- `make test-cmd-project` should pass.
=> Fixes wait for project creation

tests/helper/helper_oc.go, tests/integration/component.go
**What does does this PR do / why we need it**: 
OC helper decalration is happening twice for the context, so removing it.
Speeds up integration test for deletion of owned resources
`odo component delete should clean owned resources` integration test should pass.
=> Speeds up integration test for deletion of owned resources

pkg/occlient/occlient.go, pkg/odo/cli/url/describe.go, pkg/odo/cli/url/url.go, pkg/url/url.go, tests/integration/cmd_url_test.go
> /kind bug
> /kind design
/kind feature
> /kind flake
implemented this: I certainly can do further change on the output format, just submit 
this for some comments
```
[root@xyimgr77 frontend]# ../odo url list
Found the following URLs for component ubi-frontend-gmhz in application app:
NAME                       STATE          URL     PORT
ubi-frontend-gmhz-8080     Not Pushed     ://     8080
There are local changes. Please run 'odo push'.
[root@xyimgr77 frontend]# …
```
=> Add support for url describe command

docs/dev/machine-output.adoc, pkg/component/component.go, pkg/devfile/versions/1.0.0/devfileJsonSchema100.go, pkg/devfile/versions/common/types.go, pkg/occlient/occlient_test.go, pkg/odo/cli/component/list.go, tests/integration/cmd_app_test.go, tests/integration/component.go
/kind cleanup
Removes the annotation 'app.openshift.io/vcs-uri' for local and binary components. It also removes the 'SOURCE' column from the 'odo list' command.
Fixes #2175 
- create a local component and check that the above mentioned annotation is not present in the DC.
- create a git component and check that the above mentioned annotation is present in the DC.
- check the source code and check if the annotation is used for only git components.
- run `odo list` with combination of all the flags (not with json flag) and check that the `SOURCE` column is not present.
- run the above steps with the json flag and check if …
=> Removes the annotation 'app.openshift.io/vcs-uri' for local and binary components

pkg/application/application.go, pkg/application/labels/labels.go, pkg/component/labels/labels.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/odo/cli/application/application.go, tests/helper/helper_generic.go, tests/integration/servicecatalog/cmd_service_test.go
/kind bug
This PR deletes the service (ServiceInstance) created from Service Catalog when user tries to delete an application (`odo app delete <app-name>`).
When there are no components in the application but only service(s), it also prints the list of services that would be deleted when doing `odo app delete <app-name>`. This list of services was not getting printed unless there was a component in `<app-name>` marked for deletion.
Fixes #2113 
1. Create a service from Service Catalog `odo service create`
2. Make sure the service shows up in `odo service list --app app`
3. Now delete the app `odo app delete app -f`
4. Make …
=> Delete services belonging to an application during 'odo app delete'

pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/kclient/deployments.go, tests/examples/source/devfiles/nodejs/devfile.yaml, tests/helper/helper_filesystem.go, tests/integration/cmd_devfile_push_test.go
/kind bug
/area devfile
fixes problem when `odo push` wouldn't wait for new Pod after there was a change in Deployment
Fixes #2661
use devfile component
`odo push`
update devfile
`odo push`
second push used to fail
=> Wait for rollout

pkg/occlient/occlient.go
/kind bug
Error checking was erronously removed when implementing event
information. Instead of tests failing, they timed out instead..
See this line of code:
https://github.com/openshift/odo/pull/2627/files#diff-6025e9b620e9321c03c11bf29e5c4dbdL1848
Fixes N/A, no issue was created.
N/A
=> Error checking was removed for WaitAndGetPod

pkg/odo/cli/catalog/list/components.go
/kind bug
If the experimental flag is enabled, user should be able to list devfile components even if user doesn't connect to OpenShift cluster. Instead of failing the `odo catalog list components`, we output the following warning to user:
```
odo catalog list components                                                                                  ✔  17:00:33 
⚠  Please log in to an OpenShift cluster to list OpenShift/s2i components
Odo Supported Devfile Components:
NAME                 DESCRIPTION
java-spring-boot     Spring Boot® using IBM Java
openLiberty          Open Liberty microservice in Java
```
Fixes #2740 
Fixes …
=> List devfile component without connecting cluster if experimental flag is enabled

tests/integration/cmd_pref_config_test.go
/kind test
Adds some simple help integration tests
Fixes https://github.com/openshift/odo/issues/1045
N/A
=> Add tests for --help / -h / help

tests/integration/servicecatalog/cmd_service_test.go
/kind flake
Fixes https://travis-ci.com/github/openshift/odo/jobs/302769701#L809
Fixes NA
Ideally Travis should not get such kind of flake.
=> Fixed get service command flake

tests/integration/servicecatalog/cmd_service_test.go
/kind bug
Due to parallel run race condition arises when spec selects the active project. Such flake is fixed in this pr.
Fixes #2765
make test-cmd-service
=> Fixing app delete flake in service test file

pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter_test.go
/kind bug
This PR updates the sync code to sync to the devfile's clonePath folder if it's set. Certain devfiles, such as the official Go devfile, rely on this field being set properly (see https://github.com/eclipse/che-devfile-registry/blob/5a41b4b0c85893a6ee99059fcceab35b8a71780c/devfiles/go/devfile.yaml#L46 for example)
Fixes https://github.com/openshift/odo/issues/2741
=> If clonePath is set, sync to it

pkg/occlient/volumes.go, pkg/occlient/volumes_test.go, tests/helper/helper_oc.go, tests/integration/component.go
This PR also fixes CheckForExistence() function and the unit test for updateStorageOwnerReference()
/kind bug
Fixes storage owner references. This PR also fixes CheckForExistence() function and the unit test for updateStorageOwnerReference()
Fixes #2710 
- create a component, attach a storage to it and push
- execute `odo delete -f`
- execute `oc get pvc` and check if all PVCs belonging to the component are deleted or not.
=> Fixes storage owner references.

pkg/odo/cli/catalog/util/util.go, tests/integration/operatorhub/cmd_service_test.go
Operators listed by `odo catalog list services` could or could not be
installed from Operator Hub.
Fixes #2794 
Enable the experimental mode and check output of `odo catalog list services`. Make sure at least one operator is installed in the cluster.
=> Change the messaging to avoid confusion

tests/e2escenarios/e2e_images_test.go
/kind flake
Flake fix
Fixes #2641
e2e image validation should pass in OpenShift CI and locally too
=> Fixing e2e image test flake

pkg/catalog/catalog.go, pkg/catalog/catalog_test.go, tests/e2escenarios/e2e_images_test.go
> /kind bug
> /kind design
/kind feature
> /kind flake
init-image PR related to this https://github.com/openshift/odo-init-image/pull/50
update supported image list and use the updated bootstrap image for CI ( this needs to be reversed ) and also removed unsupported nodejs tests
Fixes https://github.com/openshift/odo/issues/2603
Fixes https://github.com/openshift/odo/issues/2640
Fixes https://github.com/openshift/odo/issues/2647
Fixes …
=> update supported image list and use the updated bootstrap image for CI

pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter_test.go, pkg/kclient/pods.go, pkg/kclient/pods_test.go
/kind bug
This PR fixes the issue seen in https://github.com/openshift/odo/issues/2807, where if something in the devfile changed that resulted in a new pod, the source code would get lost (as the emptyDir volume went away). Odo wouldn't detect this and wouldn't do a full sync, only a sync of the files that changed on the user's disk.
To fix this, if the component already exists, this PR compares the pod name before and after the call to `a.createOrUpdateComponent`. If the pod names are different, the pod has been re-created and a full sync is needed.
**Which issue(s) this PR fixes**: 
Fixes https://github.com/openshift/odo/issues/2807
1) Build my branch
2) …
=> Fix sync when the pod gets re-created

openshift-ci/build-root/Dockerfile
```
> /kind bug
> /kind design
> /kind flake
```
Updates the base image of go on  openshift CI
Fixes NA
It should pull go-1.13+ image on Openshift CI
=> Update Go version and base image on Openshift CI

pkg/odo/cli/component/create.go, tests/integration/component.go
- Cleaning machine output
- Changing as needed to affected packages
- Adding machine output to component create
/kind bug
Fixes #2309 
```
❯ odo create -o json nodejs
{
"kind": "Component",
"metadata": {
"name": "nodejs-nodejs-ex-2-quxc",
"namespace": "myproject",
},
"spec": {
"app": "app",
"type": "nodejs",
"source": "file://./",
"ports": [
"8080/TCP"
]
},
"status": {
"state": "Not Pushed"
}
}
❯ odo create python --now -o json
{
"kind": "Component",
"metadata": {
"name": "python-python-bveb",
"namespace": "myproject",
},
"spec": { …
```
=> Adding machine output to component create

pkg/odo/cli/component/create.go, tests/integration/cmd_devfile_create_test.go, tests/integration/devfile/cmd_devfile_create_test.go
/kind bug
`odo create` with `--namespace` doesn't work properly, this PR fix the issue.
Fixes #2796
=> Fix --namespace flag bug for odo create

.travis.yml, Makefile, pkg/devfile/adapters/common/interface.go, pkg/devfile/adapters/interface.go, pkg/devfile/adapters/kubernetes/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter_test.go, pkg/kclient/deployments.go, pkg/kclient/deployments_test.go, pkg/odo/cli/component/delete.go, pkg/odo/cli/component/devfile.go, pkg/testingutil/deployments.go, tests/integration/devfile/cmd_devfile_delete_test.go
/kind feature
This PR also adds support for all flag. The all flag deletes the env folder present in the .odo folder.
Fixes #2591 
- execute `odo push` on a devfile component
- execute `odo delete -f` and check if the devfile component is deleted from the cluster
`Test the --all flag`
- execute `odo push` on a devfile component
- create a url
- execute `odo delete -f --all` and check if the devfile component is deleted from the cluster. Also check if the env folder is deleted from the `.odo` folder
=> Adds delete function for devfiles support.

docs/dev/development.adoc
We're missing documentation on our `make vendor-update` command. So here
it is!
N/A
N/A
=> Update documentation on glide

pkg/log/status.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/push.go, tests/integration/devfile/cmd_devfile_push_test.go
Adds a disclaimer that experimental mode is enabled when using `odo
create` or `odo push`.
See asciinema:
[![asciicast](https://asciinema.org/a/A6ITI1wNQL9hahhLsCz4DT6wQ.svg)](https://asciinema.org/a/A6ITI1wNQL9hahhLsCz4DT6wQ)
N/A
```sh
odo preference set experimental true
git clone https://github.com/openshift/nodejs-ex
odo push
```
=> Adds disclaimer that experimental mode is enabled

pkg/occlient/occlient.go
Updates the warning output to have less information (remove the part
about using `-v` for more information).
This is needed in order to reduce the width of text so we don't run into
any issues with output being resized due to small terminals.
Fixes https://github.com/openshift/odo/issues/2782
Run it :)
```sh
git clone https://github.com/openshift/nodejs-ex
odo create node js
odo preference set PushTimeout
watch -n 1 oc delete pvc --all
odo push -f
```
Signed-off-by: Charlie Drage …
=> Shortens warning output for event information

pkg/odo/cli/component/push.go, pkg/odo/cli/url/create.go, pkg/odo/cli/url/delete.go, pkg/odo/cli/url/describe.go, pkg/odo/cli/url/list.go, pkg/odo/genericclioptions/context.go, tests/integration/devfile/cmd_devfile_create_test.go
/kind bug
This PR fixes the issue seen in https://github.com/openshift/odo/issues/2826 when `odo` would panic if experimental mode was enabled and an invalid component name was passed into `odo create`.
The issue was caused by a partially initialized CLI context being created when experimental mode is true, which caused fields needed for odo-s2i like `LocalConfigInfo` to be nil in the CLI context. When an invalid/non-existent devfile component name is passed in, odo would fall back to trying to create an s2i-style component. But since the CLI context wasn't properly initialized, a null pointer …
=> Don't panic when an invalid component name is passed in

pkg/devfile/adapters/kubernetes/component/adapter.go
Same as $Title
odo push for devfile component should show quotes like below:
```sh
odo push
•  Push devfile component nodejs  ...
✓  Waiting for component to start [9ms]
✓  Checking files for pushing [730859ns]
✓  Syncing files to the component [197ms]
✓  Executing devbuild command "npm install" [7s]   <<--------------------
✓  Executing devrun command "nodemon app.js" [1s]   <<--------------------
✓  Push devfile component nodejs [16s]
✓  Changes successfully pushed to component
```
=> Add quotes around the commands being executed during odo push

pkg/application/application.go, pkg/component/component.go, pkg/component/component_test.go, pkg/component/types.go, pkg/occlient/occlient.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/describe.go, pkg/odo/cli/component/list.go, pkg/odo/util/cmdutils.go, pkg/util/util.go, tests/integration/component.go
/kind bug
When odo is not connected to cluster, is should list out component from local config with state `unknown`.
Fixes #2444
Run `odo list --path <path>` on a not logged in cluster, is should return `state` of all the component to `unknown`.
```
[adisky@localhost odo]$ odo list --path ~/
APP     NAME                    PROJECT         TYPE       STATE       CONTEXT
app     frontend                new-project     nodejs     Unknown     /home/adisky/multicompapp/frontend
app     nodejs-mycmp6-fijc      default         nodejs     Unknown     /home/adisky/mycmp6
app     nodejs-myname1-gewe     ezsnxrczvt      nodejs …
```
=> Add Unknown State to Component.

.github/PULL_REQUEST_TEMPLATE.md
[skip ci]
This improves pushing documentation changes by including `[skip ci]`
somewhere in the commit message in order to skip any Travis CI build
from running.
Fixes https://github.com/openshift/odo/issues/2704
N/A
=> Add documentation to skip CI when pushing docs

Dockerfile.rhel, pkg/version/version.go, scripts/installer.sh, scripts/rpm-prepare.sh
Preparing to release odo v1.1.2
=> Bumping odo version to v1.1.2

pkg/kclient/deployments.go, pkg/kclient/kclient.go, pkg/kclient/operators.go, pkg/odo/cli/service/create.go, pkg/service/service.go, tests/integration/operatorhub/cmd_service_test.go
/kind feature
This PR creates operator backed services. 
Fixes a part of #2613 
* On a CRC or OCP 4.x cluster, create a project using `developer` user: `odo project create myproject`
* Log into the OpenShift Web Console as `kubeadmin` user and install etcd operator in the `myproject` namespace.
* Go to the cli and confirm that the operator is installed in `myproject` namespace
```sh
$ export ODO_EXPERIMENTAL=true
$ odo login https://api.crc.testing:6443 -u developer -p developer
$ odo catalog list services
Operators available through Operator Hub
NAME                       CRDs
etcdoperator.v0.9.4        EtcdCluster, …
```
=> Add ability to create new service backed by an operator

pkg/odo/cli/component/common_push.go, tests/integration/cmd_pref_config_test.go
/kind flake
It also fixes the integration test of now flag for config.
Fixes #2642 
- `make test-cmd-pref-config` should pass locally and on the CI
- any `-now` operation should build and push the component e.g
Current behaviour
```
[mrinaldas@localhost nodejs-ex]$ odo url create example --now
✓  Checking component [2s]
✓  URL example created for component: nodejs-nodejs-ex-alyi
Configuration changes
✓  Initializing component
✓  Creating component [4s]
Applying URL changes
✓  URL example: http://example-app-nwfjoupivp.b6ff.rh-idev.openshiftapps.com created
Pushing to component …
```
=> Fixes now flag push.

pkg/application/application.go, pkg/component/component.go, pkg/occlient/occlient.go, pkg/odo/cli/application/delete.go, pkg/odo/cli/component/delete.go, tests/helper/helper_oc.go, tests/integration/component.go
/kind feature
It adds `--wait` flag in `odo component delete`, which waits for component and its dependents to get deleted. with `foregroundDeletionPolicy` kubernetes deletes the dependent first which are referring `dc` with `ownerReference`. Then it deletes the `dc` itself. we have added `watch` to `dc` so that it waits for deletion of `dc`
Fixes #2682  
Run `odo delete -f -w` on a deployed component, 
Run `oc get pvc`, check th s2i pvc gets deleted
Run `oc get route`, check the route created via url gets deleted
=> Wait for component deletion, Add `--wait` flag to `odo delete`

pkg/odo/cli/url/list.go, pkg/url/types.go, pkg/url/url.go, tests/integration/cmd_url_test.go, tests/integration/devfile/cmd_devfile_url_test.go
/kind feature
Adds information about the url being a secure one or not in `odo url list` normal and json output.
Fixes #2775 
- create a normal odo component with secure url and execute `odo url list` and also json version of it.
- create a devfile odo component with secure url and execute `odo url list` and also json version of it.
The outputs should contain information about the url being a secure one or not.
=> Adds secure field to url list table ouput and json output.

docs/dev/experimental-mode.adoc
[skip ci]
We need it so that bullet points and sections of document would properly render.
NA
Compare the rendered document against current master and proposed PR. This can be done by clicking "Display the rich diff" when reviewing the PR.
=> Fix documentation so that it would proper render

pkg/odo/cli/url/create.go
[skip ci]
We need it because it's not clear as to how to use `odo url create` with devfile based components.
Fixes #2832 
Enable the experimental mode and check the output of `odo url create -h` command.
=> Add documentation for `odo url create ` for host flag

pkg/odo/cli/url/create.go, pkg/odo/cli/url/delete.go
/kind cleanup
This PR changes references to `OpenShift cluster` to `cluster` in places where the code could be referring to either an OpenShift cluster or Kubernetes cluster.
Fixes https://github.com/openshift/odo/issues/2852
1. Build my branch
2. Create / Delete a URL, verify that it says `cluster` instead of `OpenShift cluster`
=> Remove references to OpenShift cluster

pkg/odo/cli/service/create.go, tests/integration/operatorhub/cmd_service_test.go
/kind feature
When user does `odo service create <operator-name> --crd <crd-name> --dry-run`,
it will print only the CR's yaml definition that will be used to bring up the
service.
This is needed because yaml definitions provided in the alm-examples are not
always complete. Sometimes they contain template data which needs to be
modified to be able to start the service. After this PR, we will have another
PR which will let the user specify file containing a yaml definition to bring
up the service. That's where this will yaml output in this PR will be really
helpful.
Addresses first acceptance criteria of #2723.
1. Make sure …
=> Print yaml definition of CR when asked for dry-run

.travis.yml, tests/helper/kubernetes_utils.go, tests/helper/odo_utils.go, tests/integration/devfile/cmd_devfile_catalog_test.go
/kind test
Run integration test for devfiles on kubernetes cluster using travis CI
Fixes - Part of #2752 
Fixes #2846 
=> Setup Kubernetes cluster on travis CI and handle odo project create on Kubernetes and Openshift cluster

pkg/odo/cli/preference/set.go, pkg/odo/cli/preference/unset.go
/kind bug
the PushTarget is able to show in `preference view` but not in set/unset example
Fixes #?
=> Add push target into sample

pkg/watch/watch.go, pkg/watch/watch_test.go
/kind bug
/kind cleanup
/kind flake
This fixes the watch test for mac. Also refactors the devfile watch test.
Fixes #2570 
- `make test` should pass on mac (run at least 50-100 times)
=> Fixes watch test

pkg/odo/cli/project/set.go
/kind feature
add additional info to help use the `project` command
Fixes #?
=> nit： add <myproject> as param to command line

pkg/component/component.go, pkg/component/component_test.go, pkg/component/types.go, pkg/odo/cli/component/list.go, tests/integration/cmd_app_test.go, tests/integration/component.go
/kind feature
>
> [skip ci]
adds `sourceType` in json output and standard output for `odo list`.
Fixes https://github.com/openshift/odo/issues/2730
Create a component and before pushing
`odo list`
`odo list --all-apps`
`odo list --path .`
should give `SOURCETYPE` column and similarly `-o json` variants should give json output.
Now push the component and try the same.
when a component is not pushed the code …
=> add source type field in all odo list variants ( json and standard )

pkg/odo/cli/component/delete.go, tests/integration/devfile/cmd_devfile_delete_test.go
/kind bug
It improves the `odo delete` command based on suggestions from https://github.com/openshift/odo/pull/2763
Fixes: NA
- The CI is green 
- `odo delete --all` should also delete the `odo-file-index.json` file.
- `odo delete` prompts should also display the component name
=> Improves odo delete for devfiles

pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/kclient/deployments.go
/kind bug
/area devfile
This PR adds a spinner to the `WaitForDeploymentRollout` function in kclient. Previously, since there was no spinner, the user would be looking at
```
Johns-MacBook-Pro-3:springboot johncollier$ odo push
•  Push devfile component java-spring-boot  ...
```
While they waited for the component to rollout. Now they will see:
```
Johns-MacBook-Pro-3:springboot johncollier$ odo push
•  Push devfile component java-spring-boot  ...
◓  Waiting for component to start
```
and 
```
Johns-MacBook-Pro-3:springboot johncollier$ odo …
```
=> [Devfile] Add a spinner for deployment rollout

.travis.yml, tests/integration/devfile/cmd_devfile_watch_test.go
What type of PR is this?
/kind test
What does does this PR do / why we need it:
Runs the devfile watch integration test on kubernetes cluster.
Which issue(s) this PR fixes:
Fixes - Part of #2752
How to test changes / Special notes to the reviewer:
The test should pass on travis with make test-cmd-devfile-watch command.
=> devfile watch Interation test on kubernetes cluster using travis CI

docs/dev/development.adoc
[skip ci]
Updates the release documentation:
- Simplifies the process
- Remove the references to deb / RPM
N/A
N/A
=> Update release documentation

pkg/devfile/adapters/common/utils.go, pkg/devfile/adapters/docker/component/adapter.go, pkg/devfile/adapters/docker/component/utils.go, pkg/devfile/adapters/docker/component/utils_test.go, pkg/devfile/adapters/docker/storage/adapter.go, pkg/devfile/adapters/docker/storage/adapter_test.go, pkg/devfile/adapters/docker/storage/utils.go, pkg/devfile/adapters/docker/storage/utils_test.go, pkg/devfile/adapters/docker/utils/utils.go, pkg/devfile/adapters/docker/utils/utils_test.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/utils/utils.go, pkg/lclient/containers.go, pkg/lclient/storage.go, pkg/lclient/storage_test.go, tests/helper/helper_docker.go, tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
/kind feature
/area devfile
/area local
This PR implements a storage adapter (based off of the Kube storage adapter code) for odo when deploying components to Docker. When deploying or updating local Docker containers, odo determines the unique number of volumes in the devfile and creates Docker volumes for them. Then, when odo is deploying each container, it determines which volumes need to be mounted to it and where. When determining if a container needs to be updated, odo will compare the volumes for the container in the devfile against the volumes mounted in the container, if any differ, odo …
=> [Local] Create docker volumes from volumes defined in devfile

README.adoc, docs/dev/experimental-mode.adoc
[skip ci]
This PR 
- updates the readme on the main repo and adds a link to the odo experimental doc
- updates the odo experimental doc on how to use the various odo commands for experimental mode and also adds a link to the stack creator guide document
N/A
N/A
=> Update odo readme and docs for the experimental mode

Makefile, pkg/odo/cli/service/create.go, tests/integration/operatorhub/cmd_service_test.go
/kind feature
This PR lets users create operator backed service from a yaml file. We need it
because till we implement interactive mode for operator backed service, users
need to have a way to configure a service before spinning it up.
Fixes #2723 
1. Enable the experimental mode: 
```
$ export ODO_EXPERIMENTAL=true 
OR 
$ odo preference set Experimental true
```
2. Make sure an operator is installed on your cluster. I used etcdoperator during development since it has a working alm-example available for `EtcdCluster` CR:
```
$ odo catalog list services
Operators available in the cluster
NAME                          CRDs …
```
=> Create operator backed service from a yaml file

pkg/odo/util/completion/completionhandlers.go, pkg/storage/storage.go
=> Address failing Gosec G601

pkg/sync/sync.go, pkg/util/file_indexer.go
These are some recursive logs related to sync and file indexer.  They are printed continuously  at V(4)  while `odo push`, making it difficult to check other debug logs. They are trace kind of logs, should be at V(5)
Fixes #?
=> Update some recursive logs to V(5)

pkg/url/url_test.go, pkg/util/util_test.go
/kind flake
Why? Because we need 1.2.0 release out.
Two things:
-  We have to disable the URL tests since they are failing internally
on our CI systems:
```sh
--- FAIL: TestUnzip (0.02s)
--- FAIL: TestUnzip/Case_1:_Valid_zip_ (0.02s)
util_test.go:1459: /tmp/unzip228137821
util_test.go:1464: Error downloading zip: Get https://github.com/che-samples/web-nodejs-sample/archive/master.zip: dial tcp: lookup github.com on [::1]:53: read udp [::1]:57816->[::1]:53: read: connection refused
util_test.go:1468: Error unzipping: zip: not a valid zip file
util_test.go:1473: Expected file package.json does not exist in directory after unzipping
util_test.go:1473: Expected file package-lock.json does not exist in directory after …
```
=> Fix flakey tests

pkg/util/util_test.go
/kind flake
Disables the following:
```sh
ok  	github.com/openshift/odo/pkg/url	1.093s
ok  	github.com/openshift/odo/pkg/url/labels	1.011s
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf5ee8f]
goroutine 174 [running]:
testing.tRunner.func1(0xc0001ac700)
/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/testing/testing.go:830 +0x69d
panic(0x1046320, 0x19e74b0)
/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/panic.go:522 +0x1b5
github.com/openshift/odo/pkg/util.GetGitHubZipURL(0x114ab3b, 0x26, 0x12068ea0, …
```
=> Disables another flakey test with util_test.go

pkg/odo/cli/component/watch.go
which is only valid in devfile mode
/kind bug
```
in devfile mode:
[root@xyimgr77 ftq]# ./odo watch -h
Watch for changes, update component on change.
Usage:
odo watch [component name] [flags]
Examples:
odo watch
odo watch frontend
in s2i mode
Watch for changes, update component on change.
Usage:
odo watch [flags]
Examples:
odo watch
Flags:
```
Fixes #?
=> avoid list component name in s2i mode 

tests/integration/operatorhub/cmd_service_test.go
/kind bug
By default, Eventually will poll every 10 milliseconds for up to 1 second for each ```helper.CmdShouldPass```. In our case we are customizing the max poll time to 10 min to make sure whatever the command we execute should finish before 10 min otherwise test script reports as timeout failure. 
I am surprised how operator test file was infact is running successfully in CI.
Fixes NA
=> Adding eventually duration in operator test file

pkg/machineoutput/services.go, pkg/odo/cli/catalog/list/services.go, tests/integration/operatorhub/cmd_service_test.go
/kind feature
> [skip ci]
add json output for operator backed services.
Fixes https://github.com/openshift/odo/issues/2619
Run CRC, install some operators then 
```
odo catalog list services -o json
```
=> add json output for listing operator backed services

tests/helper/helper_generic.go, tests/helper/kubernetes_utils.go, tests/integration/devfile/cmd_devfile_catalog_test.go, tests/integration/devfile/cmd_devfile_watch_test.go
/kind bug
Avoid racing condition between set and unset KUBECONFIG while running test in parallel.
Fixes #3032 
```make test-cmd-devfile-watch``` should pass on kubernetes cluster
=> Avoid racing condition between set and unset KUBECONFIG

pkg/component/component.go, pkg/envinfo/envinfo.go, pkg/kclient/fake/ingress.go, pkg/kclient/fake/secrets.go, pkg/occlient/occlient.go, pkg/occlient/occlient_test.go, pkg/occlient/volumes_test.go, pkg/odo/cli/url/create.go, pkg/odo/cli/url/describe.go, pkg/odo/cli/url/list.go, pkg/odo/util/cmdutils.go, pkg/testingutil/routes.go, pkg/url/types.go, pkg/url/url.go, pkg/url/url_test.go, tests/integration/devfile/cmd_devfile_url_test.go
/kind feature
It adds the ability of creation of routes for openshift clusters even when experimental mode is on.
Fixes #2727 
Fixes #2816 
- execute `odo url create` on a openshift cluster (with experimental mode off) and a route should be created
- execute `odo url create` on a openshift cluster (with experimental mode on) and a route should be created
- execute `odo url create --ingress` on a openshift cluster (with experimental mode on) and a ingress should be created
- execute `odo url create` on a kubernetes cluster (with experimental mode on) and a ingress should be created
=> Adds route support of URLs for openshift clusters

pkg/debug/info.go, pkg/debug/info_test.go, pkg/odo/cli/debug/info.go, tests/integration/cmd_debug_test.go, tests/integration/debug/cmd_debug_test.go
- Adds machine readable output for `odo debug info -o json`
- Updates the current spec to add ObjectMeta as well as move information
into `Spec`, `ObjectMeta` and `TypeMeta`.
Example:
```json
{
"kind": "OdoDebugInfo",
"apiVersion": "v1",
"metadata": {
"name": "nodejs-nodejs-ex-oguc",
"namespace": "testing",
},
"spec": {
"app": "app",
"debugProcessID": 5902,
"remotePort": 5858,
"localPort": 5858
}
}
```
Fixes https://github.com/openshift/odo/issues/2555
Run:
```sh
odo debug port-forward
odo debug info -o json
```
=> Add debug machine readable output json

.travis.yml, Makefile, pkg/odo/cli/catalog/list/components.go, tests/integration/devfile/docker/cmd_docker_devfile_catalog_test.go
/kind bug
/area devfile
/area local
This PR updates the `odo catalog list component` code to only instantiate an occlient/kclient when the pushtarget is **not** set to Docker. This prevents a bug from occurring if no valid kube context exists and the user is just trying to use odo with Docker
Fixes https://github.com/openshift/odo/issues/3038
Remove or move `~/.kube` and run `odo catalog list components` from master, you should see the following:
```
Johns-MacBook-Pro-3:odo johncollier$ ./odo catalog list components -v4
✗  invalid configuration: no configuration has been …
```
=> Don't list imagestreams when using Docker

pkg/component/component.go, pkg/config/fakeConfig.go, pkg/odo/cli/config/set.go, tests/integration/component.go
/kind bug
This PR fixes two bugs. One is panic when doing `odo describe` for an unpushed component that has more URLs than number of ports it exposes. Another is the incorrect mapping of URL and port. Refer https://github.com/openshift/odo/issues/2776#issuecomment-620040493 for more detail
Fixes #2776 
Create more URLs than the number of exposed ports for a component and run `odo describe`.
=> Fixes odo describe for multiple URLs of unpushed component

pkg/odo/cli/component/delete.go, pkg/odo/cli/component/describe.go, pkg/odo/genericclioptions/context.go, tests/integration/component.go
/kind bug
Fixes #2689 
$ `odo create nodejs component1`
`odo describe <component-name>` should work for not pushed components, provided context is given or running from odo component directory. previously `odo describe` was working but `odo describe <component-name>` was failing.
$ `odo describe component1`
=> Fix `odo component describe <component-name>` for not pushed components 

.travis.yml, Makefile, tests/integration/devfile/docker/cmd_docker_devfile_url_test.go
/kind cleanup
Removing unnecessary ```oc cluster up```
https://github.com/openshift/odo/pull/2921#issuecomment-617240185
Fixes NA
Test job ```docker devfile push command integration tests``` should pass in travis CI
=> Remove oc setup for devfile push docker target

pkg/devfile/adapters/common/command.go, pkg/devfile/adapters/common/utils.go, pkg/devfile/adapters/docker/component/utils.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/exec/devfile.go, tests/examples/source/devfiles/nodejs/devfile-with-restart.yaml, tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/utils/utils.go
/kind feature
There are some applications which do not require restart of `devRun` command with each odo push. for those applications `restart: false` can be specified as command attributes in devfile.yaml. If `restart:false` then odo would  run `devRun` command only for first push, for subsequent push odo would run only if command is in stopped state. 
To handle this, for `restart:false`  we are running only `supervisord ctl start` for devRun command (as opposed to running stop and then start in regular case) , it would not restart the command if running, would start if stopped.
**Which issue(s) this PR fixes**
Fixes #2820 
- Create a odo component with …
=> Add support for command attribute `restart`

tests/integration/cmd_debug_test.go
/kind bug
/kind flake
Fixes test for debug info json output. Using `Expect` won't respect the timeout and exit immediately.
Fixes NA
- debug info json integration test should pass
=> Debug json flake fix

docs/dev/development.adoc
[skip ci]
Updates the development.adoc documentation with regards to having 1 code
reviewer and 1 approver.
N/A
N/A
=> Clarifies 1 code reviewer, 1 approver

docs/public/community.adoc, docs/public/deploying-a-devfile-using-odo.adoc
[skip ci]
This moves the "upstream" documentation that we have here:
https://github.com/openshift/odo/tree/gh-pages/chosen-docs/upstream to
our main `master` branch to we have one central place for documentation
changes.
N/A
N/A
=> Add devfile and community documentation to /public

docs/dev/development.adoc
[skip ci]
Adds documentation with regards to creating a pull request / commit
signing. It is good practice to get into the habit of signing each
commit.
N/A
N/A
=> Add instructions how to do commit signing

pkg/devfile/adapters/common/types.go, pkg/devfile/adapters/docker/component/utils.go, pkg/devfile/adapters/helper.go, pkg/odo/cli/component/devfile.go, pkg/odo/cli/component/push.go, pkg/odo/cli/component/watch.go, tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/cmd_devfile_watch_test.go
/kind feature
/area devfile
This PR adds support for the `--context` flag to `odo push` commands. Before this PR, `--context` didn't do anything, and the devfile and env info file would only be read from the current directory odo is run from.
I've also added an integration test case for the `--context` flag.
Fixes https://github.com/openshift/odo/issues/2744
- Run integration tests
- Manual test:
1) Create a devfile component
2) Change to a different …
=> Support context in `odo push` commands

pkg/occlient/occlient.go, pkg/occlient/volumes.go, pkg/occlient/volumes_test.go
/kind bug
This PR:
- Fixes the common issue of:
`panic: runtime error: slice bounds out of range [2:1]` when going from
`odo create --local` to `odo update --git`
- Adds way more tests for privatized functions
- Fixes a potential issue with removing volume mounts with
Why?
What was happening was that when removing a volume, if the length of volumes was only **ONE** then an `out of bounds` error occurred. This code checks to see if the length is 1 as well as performing the correct array slicing.
Fixes https://github.com/openshift/odo/issues/2646
**How to test …
=> Remedy panic slice-out-bounds error when using `odo update`

pkg/devfile/adapters/docker/component/adapter.go, pkg/devfile/adapters/docker/component/adapter_test.go, pkg/lclient/storage.go, pkg/lclient/storage_test.go, tests/helper/helper_docker.go, tests/integration/devfile/docker/cmd_docker_devfile_delete_test.go
/kind feature
Currently devfile  odo delete's support for deleting docker volumes is limited to the source volume. This PR adds support for deleting the storage volumes as well.
Parent issue: https://github.com/openshift/odo/issues/2581
See #2806 for how to enable a local docker push target and create a component.
=> Add storage volume deletion to 'odo delete' docker devfile deletion

pkg/util/util.go
/kind bug
/area devfile
This PR fixes a fairly intermittent issue seen when we trying to pull down the index.json for a devfile registry (such as during `odo create` or `odo catalog list components`):
```
$ odo create nodejs
Experimental mode is enabled, use at your own risk
✗  Get https://raw.githubusercontent.com/elsony/devfile-registry/master/devfiles/index.json: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
This was highly intermittent, and not easily reproducible. After working …
=> Set ResponseHeaderTimeout for GET requests

docs/dev/development.adoc, docs/dev/machine-output.adoc, docs/proposals/odo-debug.md, pkg/application/application.go, pkg/catalog/catalog.go, pkg/component/component.go, pkg/component/component_full_description.go, pkg/component/component_test.go, pkg/config/config.go, pkg/machineoutput/types.go, pkg/odo/cli/catalog/util/util_test.go, pkg/preference/preference.go, pkg/project/project.go, pkg/service/service.go, pkg/service/service_test.go, pkg/storage/storage.go, pkg/storage/storage_test.go, pkg/url/url.go, tests/integration/cmd_app_test.go, tests/integration/cmd_storage_test.go, tests/integration/cmd_url_test.go, tests/integration/component.go, tests/integration/devfile/cmd_devfile_url_test.go, tests/integration/generic_test.go, tests/integration/project/cmd_project_test.go
Signed-off-by: Tomas Kral <tkral@redhat.com>
/kind api-change
/kind cleanup
- Old API group was OpenShift specific
- now we have our own domain so we can use it to indicate API group
Everything should work as before, only the "ApiVersion" field in the JSON output should be "odo.dev/v1alpha1" everywhere
=> JSON output: use odo.dev instead of odo.openshift.io apigroup

cmd/odo/odo.go, pkg/odo/cli/cli.go, pkg/odo/genericclioptions/runnable.go
/kind bug
Removes the default value of `json` for the `-o` / `--output` flag in odo. Since our default output is not in json, we don't need to be setting the default value for that flag to that.
Previously, it was being set and causing the `ODO_LOG_LEVEL` env var not to work, due to the check here:
https://github.com/openshift/odo/blob/master/cmd/odo/odo.go#L54
See the discussion in https://github.com/openshift/odo/pull/3115
No issue, but I can open one. …
=> Don't set a default value for -o flag and fix `ODO_LOG_LEVEL` check

pkg/odo/cli/url/create.go
/kind bug
/area devfile
/area local
This PR fixes an issue seen when using odo with Docker and no kube config was set up on the user's machine, and `odo url create` would fail. Rather than always initializing an oc client on `odo url create` commands, it will only initialize it if the pushtarget is unset, or set to Kube.
Fixes https://github.com/openshift/odo/issues/3074
1. Move `~/.kube` to another folder if one exists on your machine
2. Set pushtarget …
=> Fix URL create on Docker with no Kube config

docs/public/operator-hub.adoc
[skip ci]
Modifies the current operator hub documentation in the format as some of
the other tutorial documentation
N/A
N/A
=> Add operator hub documentation

scripts/sync.sh
Signed-off-by: Yana Hontyk <yhontyk@redhat.com>
Updates the upstream doc directory name.
While getting rid of "OpenShift Do", I also renamed the directory of the docs sources: https://github.com/openshift/openshift-docs/pull/21982
Fixes #?
=> Update odo docs directory in a docs sync script

.gitignore
Updates the `.gitignore` for html and jekyll information. As I kept
having to `git clean` the dir.
N/A
N/A
=> Add .gitignore files for jekyll / site

pkg/catalog/catalog.go, pkg/catalog/catalog_test.go, pkg/catalog/types.go, pkg/odo/cli/catalog/list/components.go, pkg/odo/util/completion/completionhandlers.go, pkg/util/concurrent.go, pkg/util/util.go
Performance went from more than 4.5 seconds to less than 1.8 seconds on my system.
Also allowed me to fix #3105 as we now also fetch devfiles for completion, which was
previously prohibitively slow. Note that more performance gains could be achieved by caching locally the devfile registry metadata but this current change was a lower-hanging fruit… :)
Fixes #3105
Fixes #2967 
Fixes #3123 
Just run `odo catalog list components` without the fix then with the fix. One noticeable change, though, is that the order in which devfiles are presented is now random.
=> Performance improvement for odo catalog list components when using devfiles

pkg/devfile/adapters/common/utils.go, pkg/devfile/adapters/kubernetes/utils/utils.go, pkg/kclient/generators.go
Fixes utils of k8s adapter for v2 devfile
=> Fixes utils of k8s adapter

pkg/odo/cli/service/list.go, tests/integration/operatorhub/cmd_service_test.go
/kind feature
Adds support for `odo service list -o json` in experimental mode.
Need it because it is required by odo consumers like IDE plugin folks.
Fixes #2790 (2nd acceptance criteria)
- In experimental mode, [start an operator backed service](https://github.com/openshift/odo/blob/master/docs/public/operator-hub.adoc#deploying-etcd-to-a-cluster).
- Execute `odo service list -o json`.
=> JSON output for service list in experimental mode

pkg/devfile/adapters/common/utils.go, pkg/devfile/adapters/docker/component/utils.go, pkg/devfile/adapters/docker/utils/utils.go
=> Fixes utils of docker adapter

pkg/devfile/adapters/common/command.go, pkg/devfile/adapters/common/types.go, pkg/devfile/adapters/common/utils.go, pkg/devfile/adapters/docker/component/utils.go, pkg/devfile/adapters/kubernetes/component/adapter.go
Update adapters to use commands maps, updated logic for common commands.go
Fixes #?
=> Update Docker and Kubernetes adapter to use groups

pkg/occlient/occlient.go, pkg/odo/cli/project/delete.go, pkg/project/project.go, pkg/project/project_test.go, tests/integration/project/cmd_project_test.go
/kind feature
Adds `--wait` parameter. Ex. `odo project delete myproject --wait`
Fixes https://github.com/openshift/odo/issues/1884
```sh
odo project create foobar
odo project delete foobar --wait
```
=> Add --wait to project delete

.travis.yml, Makefile, tests/integration/devfile/docker/cmd_docker_devfile_url_pushtarget_test.go, tests/integration/devfile/docker/cmd_docker_devfile_url_test.go
/kind cleanup
/area devfile
Currently, the Docker `odo url` tests require both a Docker daemon **and** a Kube config to run, because of a couple tests that test switching back and forth from a Kube pushtarget and a Docker pushtarget. This means that [bugs that occur when there's no Kube config, go unnoticed](https://github.com/openshift/odo/issues/3074). 
To fix this, I've separated out those test cases to their own test file (`cmd_docker_devfile_url_pushtarget_test.go`) that will run alongside the devfile Kube tests on Travis (where Docker and …
=> Run devfile docker url tests without kube config

.travis.yml, Dockerfile.rhel, docs/dev/development.adoc, openshift-ci/build-root/Dockerfile
- All golang version references now uniformly updated to 1.12
- Adding all golang version references to development.adoc
Fixes #3023
=> Setting golang version uniformly accross repo and updating docs

pkg/catalog/catalog.go, tests/integration/devfile/cmd_devfile_catalog_test.go, tests/integration/devfile/cmd_devfile_create_test.go
/kind bug
/area devfile
This PR fixes a bug in the `odo catalog list` code, where devfile components with no `devBuild` command were being filtered out. Odo only requires a `devRun` command in the devfile, and so we shouldn't be filtering out devfiles that meet that criteria without having a `devBuild` command.
Fixes https://github.com/openshift/odo/issues/3170
The quarkus devfile that was recently added to https://github.com/elsony/devfile-registry has no `devBuild command, so the following should work with my changes:
- `odo catalog list components` should show the quarkus devfile
- `odo create quarkus` should succeed
=> Support listing devfile components with no devBuild command

pkg/odo/cli/url/create.go
A typo existing in sample file
/kind bug
[skip ci]
no need to CI as it's modify sample output and the real test cases for `secure` is correct using
no need to add additionl test
Fixes #3237 
=> replace secured with secure

docs/proposals/event-notification.md
[skip ci]
Parent issue: https://github.com/openshift/odo/issues/2550
**Proposal as rendered by GitHub markdown**:
https://github.com/jgwest/odo/blob/doc-2550-proposal/docs/proposals/event-notification.md
=> Design proposal: Event notification support for build and application status for IDE integration for devfile scenarios (#2550)

docs/dev/development.adoc
[skip ci]
What does does this PR do / why we need it:
Added documentation for running devfile integration tests on kubernetes cluster.
Which issue(s) this PR fixes:
Fixes #3205 
How to test changes / Special notes to the reviewer:
Manually verify the doc change.
=> Running devfile integration tests on kubernetes cluster

Makefile, scripts/setup-operators.sh, tests/integration/operatorhub/cmd_service_test.go
/kind cleanup
This PR ensures that each test spec for operator hub is run in a
separate namespace. This is needed because these tests were written in a
stringent fashion which tied the hands while writing additional tests
for the feature.
This PR should help take the tests out of the "odo test statistics"
dashboard.
Fixes #3193
* CI should pass. Specially for Operator Hub tests under
`tests/integration/operatorhub`.
* Looks at the review comments I've made for clarification
=> Modify operator hub tests to run in separate namespaces

tests/e2escenarios/e2e_beta_test.go, tests/integration/cmd_pref_config_test.go, tests/integration/cmd_push_test.go, tests/integration/component.go, tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/cmd_devfile_url_test.go, tests/integration/devfile/docker/cmd_docker_devfile_push_test.go, tests/integration/devfile/utils/utils.go, tests/integration/generic_test.go, tests/integration/operatorhub/cmd_service_test.go, tests/integration/servicecatalog/cmd_link_unlink_test.go, tests/integration/servicecatalog/cmd_service_test.go
/kind cleanup
Removes multiple `expect` assert statements throughout the test.
Fixes #3245 
It should check for the parameter passed in `MatchAllInOutput` and `DontMatchAllInOutput`
=> Replace multiple expect statement with MatchAllInOutput and DontMatchAllInOutput

pkg/odo/cli/component/create.go
/kind bug
This PR removes the prompt for the user to enter a namespace when running `odo create` with the pushtarget set to Docker. Since no namespaces are used in odo's Docker support, we don't need to prompt for it.
Fixes https://github.com/openshift/odo/issues/2978
1. Set pushtarget to Docker
2. `odo create`
You should not be prompted to enter a namespace
=> Don't prompt for namespace if pushtarget is Docker

tests/integration/operatorhub/cmd_service_test.go
/kind bug
The purpose of the pr is to make `/tmp` compatible for All supported OS
Fixes #3246 
The changes should work for all the platform.
=> Fix windows incompatibility with /tmp

tests/helper/helper_oc.go
/kind bug
The strings returned from 'CmdShouldPass' contain the char "'" which cause the comparison with target name or tag failed. Then the 'oc.checkForImageStream' returned false all the time. 
Fixes #3051 
With this PR, If there is the target imagestream, the oc.checkForImageStream should return true.
=> Fix checkForImageStream to return correct result.

pkg/occlient/occlient.go, pkg/odo/cli/component/create.go
/kind cleanup
When a user enters an invalid component name to `odo create` when experimental mode is enabled on OpenShift, they see this error:
```
✗  imagestreams.image.openshift.io "dsfdsfd" not found
```
This happens because on OpenShift (with odo's experimental mode enabled), if no valid devfile component with the given name is found, we drop down to checking for s2i/imagestream components instead, rather than erroring out.
This error can be confusing if the user doesn't know what imagestreams are / was only intending to create from a …
=> Don't show imagestreams error on experimental mode

tests/integration/devfile/cmd_devfile_create_test.go
/kind bug
/kind cleanup
It re moves the unnecessary experimental preference set in devfile create test script
Fixes NA, I see the issue and directly sending the pr.
```make test-cmd-devfile-create``` should not print output like 
```
[odo] I0603 09:13:54.826617    4108 preference.go:188] The path for preference file is C:\Users\Admin\AppData\Local\Temp\132378982\config.yaml
[odo] ? Experimental is already set. Do you want to override it in the config (y/N) I0603 09:13:54.876372    4108 common.go:1
7] Encountered an error processing prompt: Incorrect function.
```
=> Remove unnecessary preference set

tests/integration/devfile/cmd_devfile_catalog_test.go, tests/integration/devfile/cmd_devfile_create_test.go, tests/integration/devfile/docker/cmd_docker_devfile_catalog_test.go
/kind bug
/area testing
Updates odo's devfile integration tests to use `java-openliberty` instead of `openLiberty`, as the name of the Open Liberty devfile stack was recently renamed.
I'm putting this change up so that our PRs are unblocked on CI failures. I'm not crazy about an external dependency (a devfile registry in this case) being able to completely break our tests, but given that we need to test `odo create` with devfiles in a registry, I'm not sure what's the best approach here.
Fixes https://github.com/openshift/odo/issues/3316
Run the integration tests that I updated.
=> Fix failing CI tests due to Open Liberty devfile rename

openshift-ci/build-root/Dockerfile
/kind bug
/kind cleanup
Due to new workflow in [pr](https://github.com/openshift/release/pull/9431) `/tmp` dir has encountered permission issue while copying the unnecessary secret to it. So removing the unused secret directory from docker file.
Fixes NA
=> Removing unused secret directory

pkg/odo/cli/component/devfile.go
/kind bug
/kind flake
fixes use of wrong namespace  while pushing a component via `odo url create --now`
Run 
```
$ odo create nodejs mynodejs --project project1`
$ oc project
Using project "project2" on server "https://api.crc.testing:6443".
$ `odo url create url1  --host "myhost.com" --ingress --now`
```
url create --now, pushes the component and create the url, but it pushes the component in current namespace not in the namespace saved in env.yaml or namespace used while creation.
This causes failure in CI if the current set namespace gets terminated before component deployment.
Fixes #3122
Component …
=> Fix namespace issue for url create --now

.travis.yml, scripts/oc-cluster.sh
/kind cleanup
Unnecessarily minikube env variable are being populated for test jobs that runs on ```oc cluster up```. This pr will update the travis global minikube variable to local test job variable so that these variable won't be available for other OpenShift test job. 
To know on which version of docker we are using for cluster up, i adding docker version info. 
Fixes NA
Travis CI should pass
=> Updating travis env variable and adding docker version info

pkg/occlient/occlient.go, pkg/odo/cli/component/create.go, tests/integration/devfile/cmd_devfile_create_test.go
/kind cleanup
see $SUBJECT
experimental mode on
```
$ odo create fake-s
Experimental mode is enabled, use at your own risk
Validation
✗  Checking devfile compatibility [97069ns]
✗  Creating a devfile component from registry:  [92999ns]
Please run `odo catalog list components` for a list of supported devfile component types
✗  component type "fake-s" not found <------ this was just "component before"
```
=> use a more specific error message for when image is not found

.travis.yml, pkg/odo/cli/component/create.go, tests/integration/devfile/cmd_devfile_create_test.go
/kind test
Runs the devfile create integration test on kubernetes cluster.
Fixes #2752
The test should pass on travis with ```make test-cmd-devfile-create``` command.
=> devfile create Interation test on kubernetes cluster using travis CI

pkg/odo/cli/component/push.go, pkg/odo/cli/url/delete.go, tests/integration/devfile/cmd_devfile_url_test.go
/kind feature
>
> [skip ci]
`--now` flag is being implemented for `odo url delete`
Fixes #2804 
1. Have a kubernetes cluster
2. export ODO_EXPERIMENTAL=true 
3. Create a devfile component with a url. Make sure it is pushed
4. odo url delete myurl --now
```
❯ odo url delete nodejs-3000 --now --context <redacted>/nodejs-ex-2
I0511 16:34:33.774340   44748 cert_rotation.go:137] Starting client certificate rotation controller
? Are you sure you want to delete the url nodejs-3000 Yes
Validation
✓  Validating the devfile [62110ns] …
```
=> Updating url delete to apply `--now` on devfile

pkg/exec/exec.go
/kind bug
Fixes a potential flake with regards to when writing to cmdOutput at the
same time that log.ErrorF(...) is reading from it.
Closes https://github.com/openshift/odo/issues/2828
N/A, honestly not too sure
=> Fix unsafe data race in ExecuteCommand

pkg/devfile/adapters/docker/component/adapter.go, pkg/devfile/adapters/docker/component/adapter_test.go, pkg/devfile/adapters/docker/component/utils.go, pkg/devfile/adapters/docker/component/utils_test.go, pkg/devfile/adapters/docker/utils/utils.go, pkg/devfile/adapters/docker/utils/utils_test.go, pkg/lclient/containers.go, pkg/lclient/containers_test.go, pkg/lclient/fakeclient.go, tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
/kind bug
/kind cleanup
Docker adapter uses one supervisord volume for all the odo components. However, if the supervisord volume is not initialized properly(for example, when someone presses Ctrl-C during odo push); future odo push is going to fail because supervisord may not have been copied to the volume
This PR:
- copies the odo-init image to the supervisord volume when component does not exist
- cleans up init container after vol has been initialized
- refactor component project vol logic
- spins up a supervisord vol per odo component instead of one for all odo components
- delete the supervisord vol on odo delete
- updated componentExist logic for …
=> Fix Docker Supervisord Vol Initialization

pkg/util/util.go, tests/helper/helper_generic.go
=> resolved the gosec issue failing unit tests

pkg/odo/cli/component/list.go
/kind bug
--app and --all-apps exist should report error
`odo list --all-apps --app sdaf`
There's a edge case that I can run --all-apps in a folder has .odo subfolder
so --app will be set .. thus we can't prevent run --all-apps in this folder so we have to warn
user about this action but not block it
Fixes #?
=> warn --app and --all-apps coexist

.travis.yml, Makefile, pkg/debug/info.go, pkg/debug/info_test.go, pkg/debug/portforward.go, pkg/devfile/adapters/common/command.go, pkg/devfile/adapters/common/command_test.go, pkg/devfile/adapters/common/types.go, pkg/devfile/adapters/common/utils.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/utils/utils.go, pkg/devfile/adapters/kubernetes/utils/utils_test.go, pkg/devfile/parser/data/1.0.0/components.go, pkg/envinfo/envinfo.go, pkg/exec/devfile.go, pkg/kclient/fakeclient.go, pkg/kclient/generators.go, pkg/kclient/pods.go, pkg/kclient/pods_test.go, pkg/occlient/pods.go, pkg/odo/cli/component/devfile.go, pkg/odo/cli/component/push.go, pkg/odo/cli/debug/info.go, pkg/odo/cli/debug/portforward.go, tests/examples/source/devfiles/nodejs/devfile-with-debugrun.yaml, tests/integration/cmd_debug_test.go, tests/integration/debug/cmd_debug_test.go, tests/integration/devfile/cmd_devfile_debug_test.go, tests/integration/devfile/debug/cmd_devfile_debug_test.go, tests/integration/devfile/debug/debug_suite_test.go
/kind feature
Adds debug commands for devfile components.
Fixes #2701 
Doc here : #3187  
- add a debug step to the working devfile
- `odo push --debug` should execute the the debug step and start the component in debug mode
- `odo debug port-forward`, `odo debug info` should work normally for the devfile component
- `odo push` should close remote debugging for the component
=> Adds debug command for devfiles

pkg/catalog/catalog.go, pkg/catalog/catalog_test.go, pkg/odo/cli/component/create.go, pkg/odo/cli/registry/add.go, pkg/preference/preference.go, tests/integration/devfile/cmd_devfile_catalog_test.go, tests/integration/devfile/cmd_devfile_create_test.go, tests/integration/devfile/docker/cmd_docker_devfile_catalog_test.go
/kind bug
/area devfile
This PR fixes the following issues related with registry
1. Only throw warning for invalid registry and display registry name properly
2. Improve `--registry` flag validation
3. Improve component type existence validation when creating devfile component from registry
4. Add GitHub raw URL conversion support so that user can directly add GirHub regular URL (can be reachable) instead of GitHub raw URL as registry URL
5. Update corresponding help and usage
Fixes https://github.com/openshift/odo/issues/3297
Fixes https://github.com/openshift/odo/issues/3167
Fixes https://github.com/openshift/odo/issues/3382 …
=> Fix multiple registry related issues

pkg/component/component.go, pkg/devfile/adapters/docker/component/adapter.go, pkg/devfile/adapters/docker/component/utils.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/exec/devfile.go, pkg/exec/exec.go, pkg/machineoutput/event_logging.go, pkg/machineoutput/types.go, pkg/machineoutput/types_event_logging.go, pkg/odo/cli/component/devfile.go, pkg/odo/cli/component/push.go, pkg/sync/adapter.go, tests/helper/kubernetes_utils.go, tests/integration/devfile/cmd_devfile_push_test.go, tests/integration/devfile/docker/cmd_docker_devfile_push_test.go, tests/integration/devfile/utils/cmd_devfile_push_test_utils.go
/kind feature
Short answer: This PR enables JSON events to be emitted, on dev file push, when the `-o json` parameter is passed.
Long answer: Design proposal is [here](https://github.com/openshift/odo/blob/parser-v2/docs/proposals/event-notification.md).
**Parent issue**:
https://github.com/openshift/odo/issues/2550
```
export ODO_EXPERIMENTAL=true
git clone https://github.com/odo-devfiles/nodejs-ex.git
cd nodejs-ex
odo push -f -o json
```
**Sample output**:
```
{"devFileCommandExecutionBegin":{"commandId":"devbuild","componentName":"runtime","commandLine":"npm install","groupKind":"build","timestamp":"1591336117.632920"}} …
```
=> Push support: Event notification support for build and application status for IDE integration for devfile scenarios

docs/proposals/secure-registry.md
[skip ci]
Parent issue: https://github.com/openshift/odo/issues/2893
=> Design proposal: secure registry support

docs/proposals/odo-deploy.md
/kind design
[skip ci]
This is a design proposal for adding limited outer-loop capabilities to odo. Additional information non this is captured here:  #3300 
Relates to: #3300 
This is a design proposal, once the design is agreed upon we can submit a PR for the implementation. We might start making some progress on a prototype based on this proposal and then adjust as the design evolves.
=> Proposal for odo deploy

pkg/log/status.go
/kind bug
This PR updates `SpinnerNoSpin` to use the same Windows stdout code as other `Get*` methods in `log/status.go`.
https://github.com/openshift/odo/issues/2851
You MUST use the Windows 'Command Prompt' application, rather than 'Windows Terminal' (including the 'Command Prompt' shell in Windows Terminal) or Powershell (both which handle ANSI escape codes better).
=> Invalid ANSI colouring on Windows when doing devfile push

README.adoc, tests/e2escenarios/e2e_images_test.go
Removes deprecated and nodejs 8 images from e2e tests
Fixes https://github.com/openshift/odo/issues/2641
CI shouldn't fail
=> removed deprecated and nodejs 8 images from e2e tests and README

pkg/log/status.go
/kind bug
This PR truncates the spinner suffix based on the detected terminal width (in cases where the terminal width is available).
https://github.com/openshift/odo/issues/3373
See issue for reproduction steps.
=> Build progress does not show correctly when the command line is too long

pkg/envinfo/envinfo.go, pkg/envinfo/envinfo_test.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/devfile.go, pkg/util/file_indexer.go, pkg/util/util.go, tests/integration/devfile/cmd_devfile_push_test.go
/kind bug
Add .odo/env in the .gitignore file for devfile push
Fixes https://github.com/openshift/odo/issues/3386
Do odo create..odo push component creation 
and then check `.gitignore` for `.odo/env`
=> Ignore .odo/env folder for devfile

pkg/odo/cli/component/watch.go, pkg/odo/genericclioptions/context.go, tests/helper/helper_generic.go, tests/integration/devfile/utils/utils.go
/kind cleanup
`odo watch` commands allows a `[component name]` as 1st arg which is not being used.
Fixes https://github.com/openshift/odo/issues/3440
`odo watch -h` now shouldn't show the `[component name]`
=> update odo watch to remove [component name] arg also resolved bugs in odo watch test utils

pkg/odo/cli/component/create.go
/kind bug
Fixes #3380 
`odo create --help` should mention `odo catalog list components` instead of `odo catalog list`.
=> fix #3380: `odo create --help` should mention `odo catalog list components` instead of `odo catalog list`

pkg/odo/cli/component/watch.go, tests/integration/cmd_watch_test.go, tests/integration/devfile/cmd_devfile_watch_test.go
/kind bug
Informative watch UX
Fixes #3447 
```
$ odo watch -h
Watch for changes, update component on change. Watch doesn't provide support for git component.
Usage:
odo watch [flags]
Examples:
odo watch
Flags:
[...]
```
=> Add unsupported component info in watch help UX

.travis.yml
/kind feature
Update minikube version on travis CI 
Fixes NA
Minikube should get set up on travis successfully.
=> Adding latest minikube version on travis

pkg/config/config.go, pkg/odo/cli/config/set.go
kind bug
Adds Validation on parameters passed with `odo config set ` commands
Fixes #3036
=> Add validation for parameters passed with  command

scripts/configure-installer-tests-cluster.sh, tests/integration/loginlogout/cmd_login_logout_test.go
/kind feature
This pr gives read write permission for kubeconfig file which is blocking us for multi-stage testing. Detailed explanation in [comment](https://github.com/openshift/odo/issues/3270#issuecomment-651838728)
Fixes NA
Copying kubeconfig to tmp file and accessing it should work with template based test too.
=> Copy kubeconfig to temporary file and add permissions

.travis.yml, Dockerfile.rhel, docs/dev/development.adoc, openshift-ci/build-root/Dockerfile, rpms/openshift-odo.spec, scripts/rpm-local-build.sh, scripts/rpm-prepare.sh
We dont need redistributable package building
on multiple architectures as it is happening right
now (case in point internal scratch build)
Eg:
- openshift-odo-redistributable-1.2.3-1.el8.s390x.rpm
- openshift-odo-redistributable-1.2.3-1.el8.ppc64le.rpm
- openshift-odo-redistributable-1.2.3-1.el8.x86_64.rpm
We only need last one as individual rpms for specific architectures
is fine but not the redistributable ones.
Internal build system now supports golang 1.13
/kind cleanup
See above
None, this …
=> Building redistributable only on x86_64 and updating golang version to 1.13

pkg/catalog/catalog.go, pkg/catalog/catalog_test.go, pkg/catalog/types.go
/kind bug
**What does this PR do / why we need it**: 
Undoes the change made/bug added in PR  #2451
Fixes #2707
=> Fix #2707 : `odo catalog list components -o json` does not have `imageStreamRef` in json output after update from v1.0.x to v1.1.0

pkg/devfile/parser/data/1.0.0/components.go, pkg/envinfo/envinfo.go, pkg/odo/cli/component/common_push.go, pkg/odo/cli/component/create.go, pkg/odo/cli/component/devfile.go, pkg/odo/cli/component/push.go, pkg/odo/genericclioptions/context.go, pkg/testingutil/devfile.go, tests/examples/source/devfiles/springboot/devfile-with-metadataname-foobar.yaml, tests/integration/devfile/cmd_devfile_push_test.go
/kind feature
This PR changes:
- Being able to push without an `.odo` directory
- Automatic creation of an `.odo/env/env.yaml` file when pushing
- Safe determination of a devfile's name when pushing
- Code refactoring in order to be able to implement the above features
Fixes https://github.com/openshift/odo/issues/3144
```sh
odo create java-spring-boot # only to initially create it
rm -r .odo
odo push
```
=> Push odo without an .odo directory

tests/integration/devfile/debug/cmd_devfile_debug_test.go
/kind bug
Fixes #3534
```make test-cmd-devfile-debug``` should pass on Windows platform too
=> Fix delete context on Windows

tests/integration/devfile/cmd_devfile_catalog_test.go
/kind bug
$SUBJECT which is breaking CI https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/3523/pull-ci-openshift-odo-master-v4.5-integration-e2e/1281448634201673728#1:build-log.txt%3A567
Fixes NA
It should solve the CI break issue for `odo catalog describe component jave-openliberty`
=> Fixing location field for odo catalog describe component jave-openliberty

docs/public/understanding-odo.adoc
[skip ci]
Since we are doing a future Devfile release of odo that uses Devfile, we
require our "Understanding odo" guide to be located upstream rather than
downstream (from github.com/openshift/openshift-docs).
This adds that documentation.
Closes https://github.com/openshift/odo/issues/3517
N/A
=> Add "Understanding odo" Documentation

pkg/odo/cli/component/create.go
[skip ci]
update help message for --ref to show that its only valid for git components
partly https://github.com/openshift/odo/issues/3498
`odo create --help` should show help for `ref` with mention that its only valid for git components
=> update help message for --ref to show that its only valid for git components

tests/integration/component.go
Uses the standard way to compare json output
Tests should plass
=> use MatchJSON in tests wherever needed

pkg/devfile/adapters/common/interface.go, pkg/devfile/adapters/docker/adapter.go, pkg/devfile/adapters/docker/component/adapter.go, pkg/devfile/adapters/docker/component/adapter_test.go, pkg/devfile/adapters/docker/utils/utils.go, pkg/devfile/adapters/docker/utils/utils_test.go, pkg/devfile/adapters/kubernetes/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter.go, pkg/devfile/adapters/kubernetes/component/adapter_test.go, pkg/devfile/adapters/kubernetes/utils/utils.go, pkg/devfile/adapters/kubernetes/utils/utils_test.go, pkg/kclient/deployments.go, pkg/kclient/deployments_test.go, pkg/odo/cli/component/delete.go, pkg/odo/cli/component/devfile.go, pkg/odo/cli/component/watch.go, pkg/odo/genericclioptions/context.go, tests/integration/devfile/cmd_devfile_delete_test.go, tests/integration/devfile/docker/cmd_docker_devfile_delete_test.go
/kind bug
- `odo delete`/`odo delete -a` does not err out when there is no component to delete. Just shows a message saying there is no component present
- `odo delete -a` now also prompts if user wants to delete the devfile.yaml
Fixes #3104 
See https://github.com/openshift/odo/pull/3405#issuecomment-651913789 for detailed case scenarios
=> Update odo delete for no component and devfile.yaml

pkg/odo/cli/url/create.go, tests/integration/devfile/cmd_devfile_delete_test.go, tests/integration/devfile/cmd_devfile_url_test.go
/kind bug
Adds a error message which is displayed when creation of routes is triggered using a host flag.
Fixes https://github.com/openshift/odo/issues/3354
On a openshift cluster, try to create a route based URL with a host flag
`odo url create example --host`
It should error out with a appropriate message.
=> Adds a error message for creation of routes with host flag

scripts/configure-installer-tests-cluster.sh, scripts/openshiftci-periodic-tests.sh, scripts/openshiftci-presubmit-all-tests.sh, tests/integration/loginlogout/cmd_login_logout_test.go
/kind bug
/kind cleanup
/kind feature
Configuring kubeconfig path and login session for test script running against 4.x cluster
Fixes #3501 
Test script should use the developer login session and pr https://github.com/openshift/release/pull/9431 should not fail.
=> Fixing kubeconfig path and login session for 4.x cluster

pkg/odo/cli/component/update.go
/kind deprecation
added deprecation and error messages for `odo update`
Fixes #3396 
run `odo update` for 1. s2i components (expect a deprecation warning)
2. devfile component (expect an error)
Its a Draft right now
=> added deprecation and error messages for 'odo update`

pkg/odo/cli/preference/view.go, pkg/preference/machine_output.go
/kind feature
see $SUBJECT
Fixes https://github.com/openshift/odo/issues/3094
```
odo preference view -o json
```
Output - 
```
{
"kind": "PreferenceList",
"apiVersion": "odo.dev/v1alpha1",
"items": [
{
"Name": "UpdateNotification",
"Value": null,
"Default": true,
"Type": "bool",
"Description": "Flag to control if an update notification is shown or not (Default: true)"
},
{
"Name": "NamePrefix",
"Value": null,
"Default": "",
"Type": "string",
"Description": "Use this value to set a default name prefix …
```
=> implement machine readable output for odo preference view

tests/integration/cmd_push_test.go
use linux path separator for commands executed on pod instead of platform independent `filepath.Join` as the pod will always be linux but host machine can be windows. Would would join the paths in the commands incorrectly for linux.
Fixes https://github.com/openshift/odo/issues/3328
failing tests mentioned in the above issue should pass on windows
=> use linux path separator for commands executed on pod

pkg/odo/cli/service/list.go
/area UX
It changes the way `odo service list` prints the output.
Fixes #3560
Start a few Operator backed services and execute `odo service list`. Output should be of the format:
```sh
$ odo service list
NAME                          AGE
Cockroachdb/example           3s
EtcdCluster/example           3m22s
EtcdCluster/myawesomeetcd     3s
```
=> Change service list output to make linking easier

tests/integration/generic_test.go, tests/integration/project/cmd_project_test.go
/kind cleanup
Uncomment odo project list json test
Fixes #1708
```make test-cmd-project```
=> Uncomment odo project list json test

pkg/util/util.go, tests/helper/helper_filesystem.go, tests/integration/devfile/cmd_devfile_create_test.go
/kind bug
/area devfile
This PR fixes the empty devfile overriding issue when user run `odo create --devfile ./devfile.yaml` successfully.
Fixes https://github.com/openshift/odo/issues/3542
Fixes https://github.com/openshift/odo/issues/3452
1. Copy existing devfile to your current directory.
2. In you current directory, run `odo create --devfile ./devfile.yaml`
=> Fix empty devfile overriding issue for `odo create --devfile ./devfile.yaml`

pkg/kclient/deployments.go, pkg/kclient/operators.go, pkg/odo/cli/service/delete.go, pkg/service/service.go, tests/integration/operatorhub/cmd_service_test.go
/kind feature
Adds support for deletion of Operator backed service because it's essential to let users be able to delete a service.
Fixes #2792
Create an Operator backed service. Try to delete it with `odo service delete <serviceType>/<serviceName>`. 
For example: `odo service delete EtcdCluster/example`.
**NOTE**: ~This PR is rebased on top of #3561.~ NVM, it's merged.
=> Adds support for deletion of Operator backed service
