redhat-developer/odo

- .travis.yml
- Makefile
- README.md
- scripts/check-gofmt.sh
> enable TravisCI

- .codecov.yml
- .gitignore
- .travis.yml
- Makefile
- README.md
- scripts/generate-coverage.sh
this has to be merged after #9 
related to #2
> add codecov.io

- cmd/version.go
- pkg/occlient/occlient.go
- pkg/occlient/occlient_test.go
#8
create pkg/occlient 
this is wrapper around oc command
use NewOcClient to create new OcClient instance
this is more of a prototype , just wanted to test if this approach will work
> [Work In Progress] First take on OcClient 

- .travis.yml
- Makefile
- scripts/generate-bintray-json.sh
merge after #10 
related to #2
> automatically build master branch and upload to bintray 

- Makefile
- README.md
- scripts/generate-bintray-json.sh
> Fix bintray uploading and add info to readme

- pkg/occlient/occlient.go
This commit modifies occlinet.go file to accept type OcClient as
input. Also adds a utility function to check for the current
project been set by the user.
> Modify occlient structure

- cmd/app.go
- pkg/application/application.go
> app application create

- cmd/app.go
- pkg/application/application.go
- pkg/config/config.go
- pkg/occlient/occlient.go
This commit ties one application to one OpenShift project.
> make applications tied to OpenShift projects

- cmd/component.go
- cmd/root.go
- pkg/component/component.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/occlient/occlient.go
- pkg/occlient/occlient_test.go
> Component create and delete

- cmd/app.go
- pkg/application/application.go
This commit moves the setting defaultApplication logic from
pkg/application/application.go to cmd/app.go. Also, pretty prints
the log messages now.
> Modify application create behavior

- pkg/occlient/occlient.go
Till now we were getting non zero exit codes in case of running
commands like `ocdev component create nodejs --from-dir=...`
because it logged to STDERR as well as to STDOUT, while the
command still exited successfully.
This commit moves over to checking the exit code for the same
instead of relying on STDERR output.
> Refactor running commands to avoid false positives

- README.md
This commit adds some getting started and concepts headings to
the readme. This should help a new user coming to the project in
getting started with ocdev.
> Add some getting started steps to README

- .gitignore
- .travis.yml
- Makefile
- docs/contributing.md
- scripts/generate-bintray-json.sh
- scripts/prepare-release.sh
this automates binary uploading to github release page
it is documented in docs/contributing.md
this is how release draft that is cread by travis looks like:
all that we have to do is provide a description and click publish draft button
I've also created new bot account  www.github.com/ocdev-bot this account is used for uploading to github
> Release automation

- .travis.yml
- Makefile
runs unit tests for all packages
> Add 'make test'

- README.md
prerequisite https://github.com/redhat-developer/ocdev/pull/92 
it refers to packages generated by travis
> README.md - add installation and pre-requisites

- pkg/occlient/occlient.go
This commit adds an `IsServerUp()` function which checks if the
endpoint of the server is reachable before firing requests.
> Check if OpenShift server is running

- README.md
fixing a few errors i found when testing install instructions
> fix few typos and copy/paster errors in README.md

- cmd/application.go
- pkg/application/application.go
- pkg/component/component.go
- pkg/config/config.go
- pkg/config/config_test.go
Saves every application that is created to config. 
This will make sure that we display all created applications in application list (even empty applications)
fixes https://github.com/redhat-developer/ocdev/issues/105
> Show all empty applications in app list

- pkg/notify/notify.go
> Fix nil pointer dereference

- pkg/component/component.go
> 'deactivate' component after it is deleted

- cmd/component.go
fixes https://github.com/redhat-developer/ocdev/issues/137
> fix missing component name when calling push

- cmd/application.go
- pkg/application/application.go
This commit moves the logic of checking if an application exists
outside of SetCurrent()
> Fix application create error

- README.md
- docs/getting-started.md
This commit adds a Getting Started guide for making it easier for
new users to get onboarded. Also updates the references in
README.md to point to the guide.
> Add Getting Started guide

- cmd/application.go
This commit prompts the user before deleting the application when
`ocdev application delete name` command is run.
Also, a "--force/-f" flag has been introduced which skips this
prompt if set.
> Confirm before deleting application

- cmd/application.go
- cmd/component.go
- pkg/application/application.go
- pkg/component/component.go
- pkg/config/config.go
- pkg/config/config_test.go
fixes https://github.com/redhat-developer/ocdev/issues/180
Also, this will make it easier to write unit tests when #232 is done
> decouple Create and SetCurrent for app and component

- cmd/application.go
- cmd/component.go
- cmd/push.go
- cmd/root.go
- cmd/storage.go
- pkg/application/application.go
- pkg/component/component.go
- pkg/occlient/occlient.go
- pkg/storage/storage.go
This commit refactors the code to add a New() function to the
occlient package, and then modifies function signatures to take
client as a parameter.
> Refactor to add initialization to occlient

- cmd/project.go
- pkg/occlient/occlient.go
- pkg/project/project.go
Added the project get command https://github.com/redhat-developer/ocdev/issues/96
> Added the ocdev project get command

- pkg/application/application.go
Fix for https://github.com/redhat-developer/ocdev/issues/244
> Fix of the app list command

- cmd/component.go
The user will be prompted before deletion of a component, unless
overriden using --force/-f.
Fixes #200
> Prompt before deleting component

- cmd/component.go
- cmd/push.go
- tests/e2e/e2e_test.go
> Rename --dir flag to --local and add help messages for component commands.

- cmd/project.go
> Fixed newline issue in `ocdev project get`

- docs/getting-started.md
replacing `--dir` with `--local`, since `--dir` is invalid now
> Fixed getting started guide

- cmd/update.go
- pkg/component/component.go
- pkg/occlient/occlient.go
Added component update command as `ocdev update <component_name_optional> --optional_flags flag_value`
> Added component update command

- cmd/project.go
- cmd/push.go
- pkg/application/application.go
- pkg/component/component.go
- pkg/project/project.go
use `project.GetCurrent` instad of `occlient.GetCurrentProjectName`
> use project abstraction

- pkg/application/application.go
There might be a situation where application is not defined in local config but it is present in OpenShift cluster.
This situation can happen for example if user delted config file.
In this case we need to add application back to the the config  before we set is as active.
> Allow switch to app that is not in config but exists in cluster.

- tests/e2e/e2e_test.go
This commit adds tests for `ocdev storage` operations. Also, the `runCmd` function which runs the ocdev commands will now accept an additional argument of exit status. The exit status value is 0 by default.
> Tests for storage commands

- Makefile
- tests/e2e/e2e_test.go
With this commit, the `runCmd` function has been modified to use GinkgoWriter and gexec.Start.
> Fixing error-handling and logging of errors in e2e tests

- pkg/application/application.go
- pkg/config/config.go
Check it explicitly before trying to add it to the config file.
> Check that new application doesn't exists

- cmd/create.go
- pkg/component/component.go
- pkg/occlient/occlient.go
Issue : https://github.com/redhat-developer/ocdev/issues/264
> Fixed component git build log issue

- pkg/occlient/occlient.go
Updates the error output with (slightly) better information.
> Update the error outout for occlient

- cmd/create.go
- pkg/component/component.go
Second part of #217 
note from @kadel:
https://github.com/redhat-developer/ocdev/pull/301 has to be merged before this
> Adds checks if a component name with same name exists

- cmd/url.go
- pkg/url/url.go
Added a variable in URL struct to fetch the URL schema
Alt the time of printing route URL, let's print a clickable link
in place of just host name
#343
> URL will print full url with protocol

- cmd/create.go
Remove unnecessary if condition
> Remove unnecessary if condition

- cmd/project.go
- pkg/project/project.go
> Fixes the problem of switching to a non-existing project

- cmd/delete.go
This will resolve #389. Instead of printing the output, Now it will be log.debug
> Updated `odo delete` output

- cmd/component.go
> Fixes the issue of switching to a non-existing component using set command

- cmd/delete.go
This change allows the deletion of a component if no arguments are
passed (deletes the default application).
For example:
```sh
github.com/redhat-developer/odo  delete-default ✗                                                                                                                                                                                                                                                                                                                  2h50m ⚑
▶ ./odo list
You have deployed:
nodejs4 using the nodejs component
github.com/redhat-developer/odo  delete-default ✗ …
```
> Deletes the default component if no arguments are passed

- tests/e2e/e2e_test.go
Test for a case fixed as part of PR #360
> Tests for component creation in default app

- cmd/application.go
- cmd/describe.go
- cmd/util.go
Resolves #197
It will give output as following:
```
ocdev application describe batman
Application batman  has:
Component nodejs with source in file:///tmp/nodejs-ex
This Component is externally exposed via nodejs-myproject.192.168.42.231.nip.io
This component uses storage which is mounted at /home
```
> Full description of Application using `describe` subcommand

- tests/e2e/e2e_test.go
`odo component list` --> `odo list`
> Fixing the component list cmd in e2e code

- cmd/component.go
- cmd/create.go
- cmd/delete.go
- cmd/watch.go
This commit refactors some redundant error checking to
checkError()
> Move error checking to checkError()

- docs/development.md
Adds a development document with instructions on how to use glide with
odo
> Add development.md document with instructions for glide

- Makefile
Reverts redhat-developer/odo#409
> Revert "travisci - disable golint"

- cmd/create.go
- cmd/push.go
- pkg/component/component.go
- pkg/occlient/occlient.go
> Adds the binary flag implementation for the create and push command

- cmd/update.go
- pkg/component/component.go
> Adds the implementation of update for binary files

- cmd/application.go
- cmd/describe.go
- cmd/utils.go
- pkg/component/component.go
Renames cmpnt to currentComponent.
> Rename cmpnt to currentComponent

- .travis.yml
- Makefile
- tests/e2e/demo_test.go
- tests/e2e/e2e_test.go
We use --ginkgo.focus to run e2e and demo tests separately.
> Script for running the demo workflow

- cmd/create.go
- cmd/update.go
> Adds checks for checking that a directory or a file exists

- docs/getting-started.md
Updates the getting started guide with a (slightly) improved format.
> Update getting started guide

- scripts/create-packages.sh
> fix release scripts - 'odo version' output changed

- tests/e2e/demo_test.go
Updated tests to include component creation using binary source
> Update katacoda tests:

- cmd/component.go
- cmd/create.go
- cmd/update.go
- cmd/version.go
Updates CLI information / grammar.
> Update CLI information

- pkg/occlient/fakeclient.go
- pkg/occlient/occlient.go
- pkg/occlient/occlient_test.go
- pkg/url/url_test.go
adding tests using fakeClient for testing functions in occlient pkg making API calls
https://github.com/redhat-developer/odo/issues/395
> add test for CreateRoute using fakeClient

- cmd/storage.go
- pkg/storage/storage.go
This will fix the issue of  deleting all storage In spite of that, it will throw error #449
> This will fix the issue of  deleting all storage

- cmd/storage.go
This PR fixes the `storage list` command to display the mounted storages on the active component and also the unmounted storages in the application, which can be mounted.
NOTE : https://github.com/redhat-developer/odo/pull/349 has to be merged first for this to work
>  Fixed the formatting of storage list

- cmd/storage.go
- pkg/storage/storage.go
> Added the storage mount command implementation

- cmd/storage.go
Also fix examples formatting for a couple of storage commands.
> Add missing --component flag to 'odo storage unmount'

- .travis.yml
This is currently blocking releasing v0.0.6
#487
> temporary disable linux install test

- cmd/storage.go
Adds an alias ` umount` for `unmount `
#484
> Adds an alias umount for unmount

- README.md
Update the link to minishift and openshift site to get oc binary.
> Update minishift link and getting oc binary link.

- tests/e2e/e2e_test.go
> Save current project before running tests

- cmd/utils.go
Makes the output description less repetitive by removing "This
Component".
> Update the deletion / component description output

- cmd/storage.go
Issue: https://github.com/redhat-developer/odo/issues/498
> Fixed the problem of storage list when no component is created or selected

- pkg/occlient/occlient.go
> update bootstrap-supervisored-s2i to v0.0.2

- tests/e2e/e2e_test.go
Was failing due to references to old application name in some parts of the code.
> fix e2e tests

- pkg/occlient/occlient_test.go
add unit test for GetPVCFromName
> add unit test for GetPVCFromName

- pkg/url/url_test.go
fix broken TestDelete in url_test.go
> fix broken TestDelete

- pkg/occlient/occlient.go
Removes StartBinaryBuild function as it is no longer used.
> Remove StartBinaryBuild

- pkg/storage/storage.go
- tests/e2e/e2e_test.go
> Fixed the odo storage mount by adding the namespacedOpenshiftObject

- README.md
- scripts/prepare-release.sh
Updates the current installation instuctions. Adds links to the
binaries.
> Update installation instructions, add binaries

- README.md
- docs/getting-started.md
- scripts/oc-cluster.sh
This PR updates the OC Cluster from 3.7.2 to 3.9
> Updating th oc cluster version

- README.md
This adds the public channel, issue and contribution information to the
README.md
> Add public channel, community and contribution info

- scripts/check-vendor.sh
> Replace kompose with odo in check-vendor script

- cmd/storage.go
> Generate storage name if not provided

- pkg/occlient/occlient.go
> Add message for user on `invalid configuration error`

- tests/e2e/README.md
> update e2e coverage

- pkg/occlient/fakeclient.go
- pkg/occlient/occlient_test.go
add TestRemoveVolumeFromDeploymentConfig
> add TestRemoveVolumeFromDeploymentConfig

- tests/e2e/e2e_test.go
> Changes to the url creation test to add checks for correct name

- docs/development.md
Amends the development.md doc with a small note regaring including
descriptions to PR requests.
> Amend development doc with PR decription requirement

- pkg/occlient/occlient_test.go
This fixes the error message in occlient_test.go
> Fixes the error messages in occlient_test.go

- pkg/occlient/occlient_test.go
add test for GetPVCNameFromVolumeMountName
> add test for GetPVCNameFromVolumeMountName

- cmd/cmdutils.go
This adds a new line in getComponent() in cmdutils.go.
> Adds new line in getComponent() in cmdutils.go

- README.md
Hello team! 
This project looks amazing and I cannot wait to see where it goes! 👍 
Just getting started using the binary install and I ran into this permissions error so I am supplying this PR. 
Simple fix for the  issue is `sudo chmod` but it could also be a `sudo sh -c ' curl ...'` if you guys want me to change.
> FIX - sudo permission issue on mac install

- scripts/oc-cluster.sh
Updating the oc client to v3.10.0
> Update oc from v3.9.0 -> v3.10.0

- docs/cli-reference.md
> Update 'odo component list' to 'odo catalog list' in cli reference doc

- scripts/bump-version.sh
Removed grammatical errors and made more semantically correct.
> Corrected semantics and grammatical errors.

- Makefile
- docs/cli-reference.md
This updates the documentation (it's a tad out of date) as well as
modifies the makefile command to actually modify the
docs/cli-reference.md file
> Updates CLI reference Makefile command and doc

- cmd/create.go
Updates the help messages of both binary and git.
Closes https://github.com/redhat-developer/odo/issues/139
> Update the description messages of binary and git flags

- Makefile
- cmd/project.go
- glide.yaml
- pkg/project/project.go
- pkg/project/project_test.go
- pkg/testingutil/projects.go
- tests/e2e/cmp_test.go
- tests/e2e/e2e.go
- tests/e2e/e2e_test.go
- vendor/github.com/bouk/monkey/LICENSE.md
- vendor/github.com/bouk/monkey/README.md
- vendor/github.com/bouk/monkey/circle.yml
- vendor/github.com/bouk/monkey/examples/bleep.go
- vendor/github.com/bouk/monkey/examples/instance_example.go
- vendor/github.com/bouk/monkey/examples/no_http.go
- vendor/github.com/bouk/monkey/monkey.go
- vendor/github.com/bouk/monkey/monkey_386.go
- vendor/github.com/bouk/monkey/monkey_amd64.go
- vendor/github.com/bouk/monkey/monkey_test.go
- vendor/github.com/bouk/monkey/replace.go
- vendor/github.com/bouk/monkey/replace_unix.go
- vendor/github.com/bouk/monkey/replace_windows.go
- vendor/github.com/bouk/monkey/script/test
This PR adds project delete command.
The core implementation is only wrapped around by this PR
and exposed to the outside as a cli command
fixes #646
> Add project delete command

- README.md
- cmd/version.go
- docs/cli-reference.md
- scripts/install.sh
> Bump version to 0.0.11

- .codecov.yml
Disable status checks for commits and enable comment reports.
> Update codecov.io configuration.

- cmd/root.go
> Issue #772 Fix broken odo -h command

- README.md
- cmd/version.go
- docs/cli-reference.md
- scripts/install.sh
> 0.0.13 release

- pkg/occlient/occlient.go
* Removed unused variable `dc`
* define variable `currentProjectName` properly
> Small fix according to golang ci

- cmd/application.go
- cmd/project.go
- pkg/application/application.go
- pkg/component/component.go
- pkg/config/config.go
- pkg/project/project.go
- tests/e2e/e2e_test.go
Add e2e regarding the new command
Refactored list function to make code reusable
Use tabwriter to print everything
Fix typos
Fixes #206
> Add support for odo app list --project name

- README.md
- docs/cli-reference.md
- docs/examples.md
This is a first pass at adding some more information to the README and other docs. I still want to add more content (link, watch, etc.) to https://github.com/redhat-developer/odo/blob/master/docs/getting-started.md so that it is more of a user guide, but I'd like to get feedback on this version before doing more.
> Updates to the README and other docs

- README.md
- docs/cli-reference.md
- docs/development.md
- docs/getting-started.md
- docs/installation.md
The PR makes part of the docs more idiomatic to the English language
> Apply minor doc fixes

- pkg/occlient/occlient_test.go
Adds a small test for IsVolumeAnEmptyDir.
Finishes (part) of https://github.com/redhat-developer/odo/issues/828
> Add a small test for IsVolumeAnEmptyDir

- .travis.yml
- Makefile
- scripts/oc-cluster.sh
- tests/e2e/e2e.go
- tests/e2e/e2e_test.go
- tests/e2e/service_test.go
fixes #725 
This PR setups up service catalog on travis with few examples.
> Set up service-catalog on travis

- cmd/config.go
Fix a minor documentation grammar as per
https://github.com/redhat-developer/odo/pull/741/files#r227419998
> Fix a minor documentation grammar

- tests/e2e/e2e.go
Was added back in by accident here: https://github.com/redhat-developer/odo/pull/625/files#diff-4f9790de0f6fca6246aaffe0ba9a28e9R27
> Remove pingSvc function

- pkg/occlient/occlient.go
- pkg/occlient/occlient_test.go
Adds a test for findContainer.
Closes 1/3 of https://github.com/redhat-developer/odo/issues/828
> Add test for findContainer

- docs/development.md
- tests/e2e/README.md
Adds e2e test instructions to development.md
Closes https://github.com/redhat-developer/odo/issues/788
> Adds e2e test instructions to development.md

- cmd/cmdutils.go
- cmd/service.go
This PR fixes small change which was missed in  https://github.com/redhat-developer/odo/pull/683 and  breaking master
> Fixing service.go

- docs/proposals/odo-config-file.md
@kadel This is an initial proposal to define what's described in issue #800. We can discuss in the PR about this and see how the process would work. If it works fine, I'll be happy to keep pushing more proposals.
> [PROPOSAL] Define configuration and format for a local .odo config file

- cmd/application.go
I fixed the presence of application before confirm to delete it.
#888 
go test -v ./...
> check application existence before confirmation #888

- docs/getting-started.md
Adds some notes on using a custom builder,
Closes: https://github.com/redhat-developer/odo/issues/780
> Add notes on custom builder

- README.md
- docs/getting-started.md
A few things within README.md and the getting-started.md guide were
outdated. I've gone over and quickly updated a few changes.
> Update the README.md

- pkg/occlient/occlient.go
Fix #852
#852
PR #855 also attempted to address the issue, but the tests were failing which lead me to open this PR
It's difficult to actually verify the timeout is working. You could always reduce it (to like 5 second) and test
> Add timeout to pod waiting function

- .travis.yml
This is a very small modification to the Travis configuration that aims to make checking out the test status in the Travis UI easier
Noe
There is nothing here odo related to test :)
> Add names to Travis test stages in order to improve readability in UI

- pkg/occlient/occlient_test.go
Adds a test that covers CreateBuildConfig in occlient.go
Closes https://github.com/redhat-developer/odo/issues/828
> Add CreateBuildConfig test

- _data/menu.yml
- _layouts/default.html
Updates the side-menu for the documentation portion of the website.
> Updates the menu of the website

- pkg/occlient/occlient.go
This fixes an issue reported #950 which resulted in the whole directory
that contained a binary file being copied to the supevisord pod
#950 
```
odo create redhat-openjdk18-openshift:1.4 java --binary some-app.jar
odo push
```
Then looking in `/opt/app-root/src` of the supervisord pod there should only be a single file, the jar file.
For regression testing purposes, also test that a nodejs app where we push an entire source directory still works
> Optimize the case of single file transfer to the supervisord pod

- cmd/cmdutils.go
- cmd/project.go
- cmd/service_test.go
- pkg/odo/util/completion/completion.go
- pkg/odo/util/completion/completionhandlers.go
> Added the project auto completion code

- docs/development.md
> Update release documentation

- pkg/auth/login.go
Fixes `odo login` issues
Solves  #992 
`odo login`
> Fixed odo login

- Makefile
Improve the logs of e2e tests
no
by checking the e2e test logs on travis CI
> Improving logs of e2e test 

- cmd/update.go
fixes #1012 
To test : Try file name completion for `update --local` and `--binary`
> Added file completion support for update command

- pkg/storage/storage_test.go
> Adding unit tests for pkg/storage/storage.go

- _layouts/index.html
Updates the website with the Asciinema Demo as well as updated
instructions as we did not previously add `odo push`
> Update frontpage with demo and updated instructions

- pkg/component/watch.go
- pkg/util/util.go
- pkg/util/util_test.go
> Fixed the problem of Odo not ignoring files that it can't find

- README.md
- docs/getting-started.md
Simple doc change, see: $subject
Fixes: #1044
Nothing to test, only docs affected
> Remove outdated reference to oc being necessary

- cmd/odo/odo.go
- pkg/component/component.go
- pkg/component/watch.go
- pkg/component/watch_test.go
- pkg/config/config.go
- pkg/notify/notify.go
- pkg/occlient/fakeclient.go
- pkg/occlient/occlient.go
- pkg/odo/cli/cli.go
- pkg/odo/cli/component/push.go
- pkg/odo/cli/url/url.go
- pkg/testingutil/fileutils.go
- pkg/url/labels/labels.go
- pkg/url/labels/labels_test.go
- pkg/url/url.go
- pkg/url/url_test.go
- pkg/util/util.go
- pkg/util/util_test.go
- tests/e2e/cmp_test.go
- tests/e2e/e2e_test.go
- tests/e2e/examples/source/dotnet/Startup.cs
Resolved golint errors related to:
- Variable name formating ( Url -> URL )
- Comments incorrectly written ( function name not matching the comment heads )
- redundant `else` for if statements having return at the `end`
Not discussed
changes do not impact functionality
> resolved golint errors for variable names, stale comments and more

- pkg/component/component.go
- pkg/component/component_test.go
- pkg/odo/cli/application/application.go
- pkg/odo/cli/component/describe.go
- pkg/odo/util/cmdutils.go
- tests/e2e/cmp_test.go
This PR enhances describe command for both application and component.
it also has some ground work for machine readable output work.
fixes #853
* `odo describe`
* `odo app describe`
> Enhance describe command

- cmd/cli-doc/cli-doc.go
- cmd/odo/odo.go
- pkg/odo/cli/application/application.go
- pkg/odo/cli/catalog/catalog.go
- pkg/odo/cli/cli.go
- pkg/odo/cli/component/component.go
- pkg/odo/cli/component/create.go
- pkg/odo/cli/component/delete.go
- pkg/odo/cli/component/describe.go
- pkg/odo/cli/component/link.go
- pkg/odo/cli/component/list.go
- pkg/odo/cli/component/log.go
- pkg/odo/cli/component/push.go
- pkg/odo/cli/component/update.go
- pkg/odo/cli/component/watch.go
- pkg/odo/cli/login/login.go
- pkg/odo/cli/logout/logout.go
- pkg/odo/cli/project/project.go
- pkg/odo/cli/service/create.go
- pkg/odo/cli/service/delete.go
- pkg/odo/cli/service/list.go
- pkg/odo/cli/service/service.go
- pkg/odo/cli/service/service_test.go
- pkg/odo/cli/storage/storage.go
- pkg/odo/cli/url/url.go
- pkg/odo/cli/utils/utils.go
- pkg/odo/cli/version/version.go
This work aims to fix #785. I'm creating this PR while the work is still ongoing so that interested parties can comment and decisions can be taken while code is still being written.
#785
If everything goes well, nothing will change externally for `odo` users so tests should work as expected.
> Re-organize code according to kubectl/oc conventions

- pkg/odo/cli/application/application.go
- pkg/odo/cli/component/component.go
- pkg/odo/cli/component/create.go
- pkg/odo/cli/component/delete.go
- pkg/odo/cli/component/describe.go
- pkg/odo/cli/component/link.go
- pkg/odo/cli/component/list.go
- pkg/odo/cli/component/log.go
- pkg/odo/cli/component/push.go
- pkg/odo/cli/component/update.go
- pkg/odo/cli/component/watch.go
- pkg/odo/cli/project/project.go
- pkg/odo/cli/service/create.go
- pkg/odo/cli/service/delete.go
- pkg/odo/cli/service/list.go
- pkg/odo/cli/service/service.go
- pkg/odo/cli/storage/storage.go
- pkg/odo/cli/url/url.go
- pkg/odo/genericclioptions/context_flags.go
- pkg/odo/util/completion/completion.go
- pkg/odo/util/completion/completionhandlers.go
> Added the auto completion for components

- docs/completion-architecture.md
- docs/getting-started.md
Updates getting started documentation for UI changes and adds command completion details.
fixes #1089 
No code changes.
> Completion user doc

- pkg/odo/cli/cli.go
Adds a newline in the help menu to showcase our GitHub link.
> Add newline in help

- docs/getting-started.md
Improve getting started doc experience
fixes #1118
> Add link to command completion index

- pkg/odo/cli/component/component.go
resolve a bug in the docs
fixes #???
No issue
Its a doc change
> solved the ordering in example

- pkg/odo/cli/service/create.go
The command is incorrect and this has been updated to show `odo catalog
list services`.
> Update odo catalog list services

- docs/development.md
Adding workaround for odo repo cloning issue on windows terminal like PowerShell and Command Prompt in doc development.md  
In mattermost channel - https://chat.openshift.io/developers/pl/xtsmdukx4fnojfgexay34frqee
In details - https://chat.openshift.io/developers/channels/odo
Read the added section
> Updating doc for odo cloning issue

- cmd/odo/odo.go
- pkg/odo/cli/application/application.go
- pkg/odo/cli/catalog/catalog.go
- pkg/odo/cli/component/component.go
- pkg/odo/cli/component/create.go
- pkg/odo/cli/component/delete.go
- pkg/odo/cli/component/describe.go
- pkg/odo/cli/component/link.go
- pkg/odo/cli/component/list.go
- pkg/odo/cli/component/log.go
- pkg/odo/cli/component/push.go
- pkg/odo/cli/component/unlink.go
- pkg/odo/cli/component/update.go
- pkg/odo/cli/component/watch.go
- pkg/odo/cli/login/login.go
- pkg/odo/cli/logout/logout.go
- pkg/odo/cli/project/project.go
- pkg/odo/cli/service/create.go
- pkg/odo/cli/service/delete.go
- pkg/odo/cli/service/list.go
- pkg/odo/cli/storage/storage.go
- pkg/odo/cli/url/url.go
- pkg/odo/cli/utils/config.go
- pkg/odo/cli/utils/terminal.go
- pkg/odo/genericclioptions/context.go
- pkg/odo/util/cmdutils.go
Signed-off-by: glefloch <glfloch@gmail.com>
This change renames `CheckError` function name to `LogErrorAndExit`.
fixes #874 
Running tests make sure there are no regressions.
> Rename CheckError to LogErrorAndExit

- pkg/catalog/catalog.go
- pkg/occlient/occlient.go
- pkg/occlient/utils.go
- pkg/occlient/utils_test.go
- pkg/odo/cli/catalog/catalog.go
- tests/e2e/service_test.go
This change checks for `hidden` tag in the services and hides them.
partly https://github.com/redhat-developer/odo/issues/1180
`odo catalog list services`
`odo catalog search service <service>`
> added check in tags for services in catalog

- pkg/occlient/occlient.go
> Fix error code.

- pkg/odo/cli/cli.go
- pkg/odo/util/cmdutils.go
- pkg/odo/util/cmdutils_test.go
see $SUBJECT
No. Trivial change.
No externally visible change.
> Extract full name generation.

- pkg/odo/cli/component/link.go
- pkg/odo/cli/component/unlink.go
see $SUBJECT
No.
No externally visible changes.
> Use name in Use.

- pkg/occlient/occlient.go
Remove unused and functionality duplicating function.
> Remove GetServiceClass

- pkg/secret/secret.go
- tests/e2e/link_test.go
See $SUBJECT
Fixes: #1174
Create a java backend component (which exposes multiple ports).
Create a frontend component.
Try to link the frontend to the backend. The error should now be what #1174 describes
> Improve error message when a port is needed for odo link

- docs/cli-reference.md
- pkg/odo/cli/component/create.go
added an example of `ref` in cli reference
No issue
Doc change
> added a git ref in cli reference

- pkg/odo/cli/service/delete.go
Resolves the long description of `odo service delete` 
No discussion
`odo service delete --help`
> resolved the delete long description

- pkg/odo/cli/cli.go
- pkg/odo/cli/version/version.go
Changing odo version to follow patterns of odo service which
already follows complete-validate-run pattern
fixes #???
#1195
> Fixing #1195: Refactoring odo version to follow complete-validate-run pattern

- pkg/odo/cli/version/version.go
See $SUBJECT.
No
No externally visible changes.
> Fix improper version refactoring missed during review: Run takes no arguments.

- pkg/odo/cli/service/service.go
See $SUBJECT.
No.
No externally visible changes.
> Service command is not using GetFullName.

- pkg/odo/cli/application/application.go
- tests/e2e/link_test.go
See $SUBJECT
Fixes: #1203
Create various component and/or services. 
Make sure that `odo app describe` shows the appropriate output
> Add services to odo app describe

- _config.yml
Updates the year for the Odo website.
> Update the year for the website

- pkg/odo/cli/cli.go
- pkg/odo/cli/url/create.go
- pkg/odo/cli/url/delete.go
- pkg/odo/cli/url/list.go
- pkg/odo/cli/url/url.go
Refactoring url to `complete-validate-run` pattern
fixes #1193 
* Check CI status to :green_heart:  and run all url related commands :smile:
> Refactored URL to complete-validate-run pattern

- pkg/odo/cli/cli.go
- pkg/odo/cli/project/create.go
- pkg/odo/cli/project/delete.go
- pkg/odo/cli/project/get.go
- pkg/odo/cli/project/list.go
- pkg/odo/cli/project/project.go
- pkg/odo/cli/project/set.go
- Refactored the project package to follow complete-validate-run pattern
- Using tabwritter instead of fmt when outputting tables
fixes https://github.com/redhat-developer/odo/issues/1191
`odo project`
> refactored project package to follow complete validate run pattern

- .travis.yml
- Makefile
- pkg/application/types.go
- pkg/component/component.go
- pkg/component/component_test.go
- pkg/component/types.go
- pkg/odo/cli/application/application.go
- pkg/odo/cli/component/describe.go
- pkg/odo/cli/component/list.go
- pkg/odo/cli/storage/list.go
- pkg/odo/cli/storage/mount.go
- pkg/odo/cli/storage/storage.go
- pkg/odo/cli/url/list.go
- pkg/odo/util/cmdutils.go
- pkg/odo/util/completion/completionhandlers.go
- pkg/storage/types.go
- pkg/url/types.go
- tests/e2e/json_test.go
Provide machine readable output (json format) so that other applications can easily consume output generated by odo. for example, vscode plugin
fixes #1062 
* odo app describe <appname> -o json
* odo app list -o json
* odo describe <componentName> -o json
* odo list -o json
* odo url list -o json
* odo storage list -o json
> Machine Readable Output

- .circleci/config.yml
This pr will add circleci config for building odo in circle ci
#1309
proof-read the config and check if the builds are successful for this pr on circle-ci
> add circleci file

- .travis.yml
Since part of the test workload is moved to CircleCI, let's remove these from Travis configuration.
No.
Nothing to do, just less tests should run in Travis, faster.
> Remove tests that are performed in CircleCI.

- pkg/log/status.go
- tests/e2e/component.go
- tests/e2e/e2e.go
- tests/e2e/e2e_test.go
- tests/e2e/java_test.go
- tests/e2e/json_test.go
- tests/e2e/link_test.go
- tests/e2e/login_test.go
- tests/e2e/service_test.go
- tests/e2e/source_test.go
- tests/e2e/utils.go
- tests/e2e/watch_test.go
Error will be reported in ```stderr```
fixes #1205
make test*
Check travis for test execution reference
> Issue #1205 Update test suite to handle stderr

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/odo/cli/utils/config/set.go
- pkg/odo/cli/utils/config/unset.go
- pkg/odo/cli/utils/config/view.go
- tests/e2e/e2e_test.go
added component settings and used reflection for deletion
partly  https://github.com/redhat-developer/odo/issues/1294
```
odo utils config set componentName test
odo utils config set minCPU 0.5
```
> added component settings and used reflection for deletion

- pkg/component/component.go
- pkg/odo/cli/application/application.go
- pkg/odo/cli/component/describe.go
- pkg/odo/cli/url/create.go
- pkg/odo/cli/url/list.go
- pkg/odo/util/cmdutils.go
- pkg/odo/util/completion/completionhandlers.go
- pkg/url/url.go
- pkg/url/url_test.go
- tests/e2e/json_test.go
Refactor `url` portion to use new structs throughtout and remove old url struct and all it's usage
fixes #1288
CI should be :green_heart:  and test all URL related commands
> Modify URL related functions to use new structs

- pkg/component/component.go
- pkg/odo/cli/application/application.go
- pkg/odo/cli/component/describe.go
- pkg/odo/cli/storage/list.go
- pkg/odo/cli/storage/storage.go
- pkg/odo/util/cmdutils.go
- pkg/odo/util/completion/completionhandlers.go
- pkg/storage/storage.go
- pkg/storage/storage_test.go
getMachineReadableFormat() and getMachineReadableFormatForList() were introduced for helping in making machine readable output for storage.
fixes #1289 
How to test:
Test all storage related commands
> Modified storage related functions to use new structs

- README.md
Added a badge to track circle CI build status on master
No issue
Doc change, check the readme for a badge which looks like this [![CircleCI](https://circleci.com/gh/redhat-developer/odo/tree/master.svg?style=svg)](https://circleci.com/gh/redhat-developer/odo/tree/master)
> added circle ci badge

- docs/proposals/odo-config-file.md
> add warning to outdated config file proposal

- pkg/occlient/occlient.go
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
fixes #???
> Fix typo arguement --> argument

- pkg/config/config.go
- pkg/config/config_test.go
- tests/e2e/e2e_test.go
- tests/e2e/utils.go
fixes #1331 
How to test:
1. Create many apps
2. Delete the active one and check app switching
> Added suitable auto app switching in case of application deletion

- pkg/component/component.go
- pkg/component/component_test.go
- pkg/component/types.go
- pkg/odo/cli/application/application.go
- pkg/odo/cli/application/describe.go
- pkg/odo/cli/component/describe.go
- pkg/odo/cli/component/list.go
- pkg/odo/cli/storage/list.go
- pkg/odo/util/cmdutils.go
- pkg/odo/util/completion/completionhandlers.go
- pkg/odo/util/completion/completionhandlers_test.go
- pkg/storage/storage.go
- pkg/url/url.go
Refactor `Component` portion to use new structs throughtout and remove old Component struct and all it's usage
fixes #1291
CI should be :green_heart:  and test all Component related commands
> Modify components according to new structs

- docs/development.md
- docs/getting-started.md
Adds some notes with regards to actually enabling service catalog for
development and getting started.
> Add notes with regards to enabling service catalog

- OWNERS
- pkg/application/OWNERS
- pkg/auth/OWNERS
- pkg/catalog/OWNERS
- pkg/component/OWNERS
- pkg/config/OWNERS
- pkg/log/OWNERS
- pkg/notify/OWNERS
- pkg/occlient/OWNERS
- pkg/odo/OWNERS
- pkg/project/OWNERS
- pkg/secret/OWNERS
- pkg/service/OWNERS
- pkg/storage/OWNERS
- pkg/testingutil/OWNERS
- pkg/url/OWNERS
- pkg/util/OWNERS
- scripts/OWNERS
- tests/OWNERS
This PR adds OWNERS files to enable prow to ping appropriate people
and decide whose PRs warrant automatic merge
fixes #1400 
> Fix #1400 : Adding prow style OWNERS files

- pkg/application/application.go
- pkg/application/application_test.go
- pkg/odo/cli/application/application.go
- pkg/odo/cli/application/describe.go
- pkg/odo/cli/application/list.go
- tests/e2e/json_test.go
odo will return empty struct if there's no app
fixes #1327
validate the output for below commands
`odo app list -o json`
> Fixed odo app list json output

- pkg/component/component.go
- pkg/component/component_test.go
- pkg/odo/cli/component/list.go
Fixed odo list output 
fixes #1326 
```
odo list -o json
```
> Fix odo list -o json

- tests/e2e/source_test.go
Update the test file to run it on all oc supported platform including windows
fixes Part of #1129
make test-source-e2e
> Remove terminal specific command from e2e source test file

- tests/e2e/service_test.go
Update the test file to run it on all oc supported platform including windows 
fixes - Part of #1129
make test-service-e2e
> Remove terminal specific command from e2e service test file

- pkg/odo/cli/component/ui/ui.go
- pkg/odo/cli/url/create.go
- pkg/odo/cli/url/delete.go
- pkg/odo/cli/url/list.go
- pkg/odo/genericclioptions/add_flags.go
- pkg/odo/genericclioptions/context.go
- pkg/odo/genericclioptions/context_flags.go
- pkg/odo/util/cmdutils.go
- pkg/url/types.go
- pkg/url/url.go
- pkg/url/url_test.go
- pkg/util/util.go
- tests/e2e/json_test.go
`odo url create` will provide json output
fixes #1378
`odo url create -o json`
> json output for odo url create

- docs/development.md
Updating our development documentation so that it has necessary information about the prow workflow
> Updating development docs with information on prow.

- docs/development.md
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
fixes #???
> Fix typo in development guide

- openshift-ci/build-root/Dockerfile
- openshift-ci/build-root/README.md
> Adding our own base image to test on Openshift CI

- tests/e2e/e2e_test.go
- tests/e2e/utils.go
Update the test file to run it on all oc supported platform including windows
fixes - Part of #1129
make test-main-e2e
> Remove terminal specific command from e2e test file

- pkg/odo/cli/storage/create.go
- pkg/odo/cli/storage/list.go
- pkg/odo/cli/storage/storage.go
- pkg/odo/util/cmdutils.go
- pkg/storage/storage.go
- pkg/storage/storage_test.go
- pkg/storage/types.go
- pkg/util/util.go
- tests/e2e/json_test.go
fixes #1379 
run `odo storage` ommand with `-o json`
> Added json output for storage create

- tests/e2e/java_test.go
- tests/e2e/utils.go
Update the test file to run it on all oc supported platform including windows
fixes Part of #1129
make test-java-e2e
> Remove terminal specific command from e2e java test file

- scripts/configure-installer-tests-cluster.sh
Fix of issue like https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/redhat-developer_odo/1467/pull-ci-redhat-developer-odo-master-e2e-core/162
Run `make configure-installer-tests-cluster` against any cluster brought up using openshift installer
> Increasing wait time and detecting failure of login as developer

- tests/e2e/component.go
Fix of component test failure in prow - https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_release/3134/rehearse-3134-pull-ci-redhat-developer-odo-master-e2e-core/4
No
> Increasing timeout for accessing health endpoint

- _layouts/index.html
Removes the gifs from the site (http://openshiftdo.org)
> Remove gifs from site

- docs/getting-started.md
Fixes the link to the installation document from the getting started
guide.
Closes: https://github.com/redhat-developer/odo/issues/1496
> Fixes link for installation document

- _config.yml
Updates the site with the new repo
> Update site with new repo

- tests/e2e/e2e.go
- tests/e2e/e2e_test.go
- tests/e2e/utils.go
This allows us to retry commands that can be flaky a few times
before declaring them as failures
This should reduce failures in OpenShift CI
> Adding runCmdShouldPass function with retry and turning off failing test on openshift ci

- pkg/occlient/occlient.go
fix https://github.com/redhat-developer/odo/issues/1231
yes, https://github.com/redhat-developer/odo/issues/1231
```
$ git clone https://github.com/openshift/nodejs-ex.git
$ odo create nodejs:8 customsupvisrodui --app web --local /tmp/nodejs-ex/
$ odo push
$ odo push
```
> bumb supervisord image version

- .travis.yml
group our e2e test into groups, to cut down cluster setup time
> Group TravisCI jobs

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/odo/cli/config/view.go
- tests/e2e/e2e_test.go
Resolves a panic while setting port config
fixes #1523 
```
$ odo config set Ports 8080/TCP - panic out
$ odo config set ports 8080/TCP - panic out
```
shouldn't panic
> resolved panic on port set

- pkg/odo/cli/application/application.go
- pkg/odo/cli/component/component.go
- pkg/odo/cli/project/project.go
see $SUBJECT
fixes https://github.com/openshift/odo/issues/1512
```
odo app delete
odo project delete
odo component delete
```
now shouldn't have extra inconsistent spacing
> removed spacing in delete info prints

- pkg/occlient/occlient.go
- scripts/configure-installer-tests-cluster.sh
- tests/e2e/component.go
- tests/e2e/e2e.go
- tests/e2e/e2e_test.go
- tests/e2e/java_test.go
- tests/e2e/json_test.go
- tests/e2e/service_test.go
- tests/e2e/source_test.go
- tests/e2e/utils.go
- tests/e2e/watch_test.go
fixing e2e tests on OpenShift CI - what was left from #1360
> Various e2e fixes for OpenShiftCI

- docs/development.md
describe our PR review process in develoment.md
> Odo pr review process

- docs/getting-started.md
Adds .gitignore documentation.
Closes https://github.com/redhat-developer/odo/issues/1427
> Add .odoignore documentation

- docs/getting-started.md
Reviewed and modified getting started document.
> Review getting started document

- pkg/odo/cli/project/list.go
- pkg/odo/cli/url/list.go
- pkg/odo/util/completion/completionhandlers.go
- pkg/project/project.go
- pkg/project/types.go
- tests/e2e/json_test.go
fixes #1361
```
odo project list -o json
```
> Added machine readable struct for `odo project list`

- docs/installation.adoc
- docs/installation.md
This PR reviews and modifies the installation doc and converts this doc to asiccdoc format.
> Review of Installation doc

- .github/ISSUE_TEMPLATE/Documentation.md
Fixes the typo in the issue template.
> Typo in documentation issue templates

- docs/ci-reference.adoc
- docs/cli-reference.adoc
- docs/cli-reference.md
- docs/completion-architecture.adoc
- docs/examples.adoc
- docs/logging.adoc
- docs/tdd-workflow.adoc
- docs/validation-architecture.adoc
- This PR converts 7 docs to .adoc format. This takes care off all the docs in the docs folder to enable change in the script for the website.
- It also reviews the Examples file.
- The other 6 docs as discussed with @kadel  and @cdrage , are to be maintained by the developers, are not the first priority for GA and can be revisited later. They have been converted to adoc, and have a very basic sanity check done.
> Converted 7 docs to .adoc

- docs/getting-started.adoc
- This PR converts the GSG to adoc format.
- It also makes changes to the workflow as pointed out by @surajnarwade and @anmolbabu
> Adding the GSG adoc version and changes to the workflow.

- docs/development.adoc
This PR reviews, modifies and converts the Development guide from .md to .adoc
> Development guide review and adoc conversion

- .travis.yml
No issue
Check travis CI to confirm the typo is not present
> typo in travis.yml

- OWNERS
- pkg/catalog/OWNERS
- pkg/occlient/OWNERS
- pkg/odo/OWNERS
- pkg/secret/OWNERS
- pkg/service/OWNERS
remove people that are no longer active in this project from OWNERS file.
In the OWNERS file that would be left with just one person, I randomly added someone 😃
> remove inactive people from OWNERS

- Makefile
- scripts/openshiftci-presubmit-e2e-scenarios.sh
- tests/e2escenarios/core_beta_flow.go
- tests/e2escenarios/e2escenarios_test.go
- tests/e2escenarios/examples/source/openjdk/pom.xml
- tests/e2escenarios/examples/source/openjdk/src/main/java/Application.java
- tests/e2escenarios/examples/source/openjdk/src/main/java/MessageProducer.java
- tests/e2escenarios/helper/helper_filesystem.go
- tests/e2escenarios/helper/helper_generic.go
- tests/e2escenarios/helper/helper_http.go
- tests/e2escenarios/helper/helper_oc.go
- tests/e2escenarios/helper/helper_run.go
The new clean e2e scenario, that tries to simulate basic flow.
This can be a replacement for the "old" template.
This will be required to pass before we release beta version.
Watch test is missing, I'll add that in another PR.
> e2e test: core scenario for beta

- _layouts/index.html
* Language and style improvements
* Consolidation of naming (rid of 'OpenShift Do' in favor of 'odo'; https://github.com/openshift/odo/pull/1467#issuecomment-480935375)
* Change demo to embedded
Apologies it's so last-minute.
> Lang. and other fixes for homepage

- pkg/odo/cli/url/list.go
- tests/e2e/json_test.go
returns empty json object if urls not present
fixes #1515
```
odo url list -o json
```
> Fixed empty `odo url list -o json`

- pkg/occlient/occlient.go
> Fixes the issue of storage unmounting during odo push

- pkg/occlient/occlient.go
- pkg/occlient/templates.go
> Copy over EnvFrom across component updates

- pkg/odo/cli/config/set.go
- tests/e2e/json_test.go
- tests/e2escenarios/core_beta_flow.go
- tests/e2escenarios/helper/helper_oc.go
- tests/e2escenarios/helper/helper_run.go
this also fixes a few minor issues in e2e beta scenario
The test is passing now. After this is merged I'll open PR on openshift/release to run this tests
> inform user to run odo push after odo config

- scripts/oc-cluster.sh
- scripts/travis-check-pods.sh
- tests/e2e/service_test.go
fixes https://github.com/openshift/odo/issues/1491
> uncomment and fix service tests

- pkg/odo/cli/project/list.go
- pkg/odo/util/completion/completionhandlers.go
- pkg/project/project.go
Improves `project.Exist` and `project.List`
fixes #1620
tests should be fast
> Improve project list

- tests/e2e/e2e_test.go
> e2e test namespace cleanup

- docs/getting-started.adoc
few updates about URL in getting started guide
> Updated getting started guide

- README.adoc
- docs/development.adoc
- docs/getting-started.adoc
- docs/installation.adoc
This PR modifies the format of commands in the main guides, Readme, Development, Getting started and Installation and examples.
It also has a change in command in the Readme on line 145 & 146 based on input from @surajnarwade 
I will raise another PR for the rest of the docs.
> Improving format of commands in the main guides.

- tests/e2e/json_test.go
json tests are flaky this should help to resolve it
fixes #1625
> use Gomega matchers for json output

- OWNERS
- pkg/application/OWNERS
- pkg/auth/OWNERS
- pkg/component/OWNERS
- pkg/config/OWNERS
- pkg/odo/OWNERS
- pkg/util/OWNERS
- scripts/OWNERS
- site/OWNERS
> OWNERS files cleanup

- docs/cli-reference.adoc
The CLI reference page wasn't rendering correctly. This fixes it (ran
through pandoc converter...)
> Fix CLI reference page

- pkg/auth/login.go
- pkg/log/status.go
This fixes the issue of `odo login` not working correctly.
In this PR:
- Added logging for before AND after
- Changed stdout / stderror to the correct ones from odolog package
- Fix up success output
- Added Success function to odolog
Closes issue https://github.com/openshift/odo/issues/1643
Closes issue https://github.com/openshift/odo/issues/1664
Closes issue https://github.com/openshift/odo/issues/1662
> Fixes issue of odo login not working correctly

- pkg/occlient/occlient.go
- pkg/occlient/occlient_test.go
- pkg/occlient/templates.go
- pkg/occlient/utils.go
fixes #1633 
This PR prevents the unnecessary roll out of new deployment config.
> Deploy fix

- tests/integration/integration_suite_test.go
resolved a typo I noticed in the tests
no issue
check the CI logs to see if the typo is still present
> resolved typo in the tests

- cmd/cli-doc/cli-doc.go
- docs/cli-reference.adoc
- pkg/odo/cli/cli.go
This updates the CLI reference doc generation script as well as the
current documentation within the help menu (odo not using correct
capitalization).
> Update the CLI reference doc generation script

- OWNERS
Add meself to OWNERS file for reviews.
fixes #???
> Add dharmit to OWNERS file

- docs/development.adoc
see $SUBJECT
No issue
Use the link in development doc
> resolved the broken link to .wwhrd.yml

- tests/integration/generic_test.go
- tests/integration/java_test.go
- tests/integration/json_test.go
fixes - Probably the issue was coming due to the issue in git component deployment. pr #1684 has fixed the issue 
make test-json-format-output
> Uncommenting git component push issue

- README.adoc
- docs/installation.adoc
On README page:
- Removed steps for binary and tarball installation
- Formated the installation section
On Installation page:
- Added bulleted list for quick access to sections
- Added more section headings to support above
- Changed URLs to use latest release so that we don't have to change them for every release. Ref: https://help.github.com/en/articles/linking-to-releases
fixes #1670
Take a look at
- https://github.com/dharmit/odo/blob/fix-1670/README.adoc
- https://github.com/dharmit/odo/blob/fix-1670/docs/installation.adoc
> Format and synchronize README and installation page

- tests/helper/helper_oc.go
- tests/integration/link_test.go
fixes #1616
make test-link-e2e
> Update link test as per new test flow

- tests/integration/generic_test.go
To add more integration test coverage 
fixes - test scenario for issue #1599, however i have created an issue #1752 for full scale catalog command implementation later.
> Adding test spec for catalog list without comp dir

- tests/helper/odo_utils.go
> Added v4 log level to project creation

- pkg/util/util_test.go
fixes #1786 
It sorts the strings before running the comparison
> Modifies TestRemoveDuplicate to remove flake

- pkg/catalog/catalog.go
- pkg/component/component.go
- pkg/config/config.go
- pkg/odo/cli/component/create.go
- pkg/odo/cli/component/push.go
- pkg/odo/cli/url/create.go
- pkg/odo/cli/url/delete.go
This PR:
- Improves the UI / UX of the URL output
- Separates Validation / Creation / Updating of components in the CLI
output
Closes https://github.com/openshift/odo/issues/1648
> Improve URL creation and deletion UX / UI output

- pkg/log/fidget/spinner.go
- pkg/log/status.go
Adds a timer to the UI / UX:
```sh
Validation
✓  Validating component [5s]
✓  Checking component [6s]
Configuration changes
✓  Applying configuration [808ms]
Applying URL changes
✓  URL myurl2 already exists
Pushing to component nodejs-lhov of type local
✓  Waiting for component to start [61ms]
✓  Copying files to component [3s]
✓  Building component [6s]
✓  Changes successfully pushed to component
```
related to https://github.com/openshift/odo/issues/1726
> Adds a timer to UI / UX output

- tests/integration/java_test.go
- tests/integration/service_test.go
- tests/integration/source_test.go
Uncommenting java test as it seems to be fixed in pr #1740
make test-java-e2e
> Uncommenting spec in java test file

- tests/integration/component.go
Due to #1778 and #1782 , the update e2e tests are commented out
> Comments out the update e2e tests

- .travis.yml
- README.adoc
- docs/development.adoc
- pkg/notify/notify.go
after #1802 we need to update the link to the install script.
> Fixes links to the install script

- docs/development.adoc
- docs/proposals/odo-config-file.md
Fixes various types in docs
Thanks to @apupier for opening the original PR (https://github.com/openshift/odo/pull/1649)
fixes #???
> resolved various typos

- .travis.yml
- Makefile
- docs/development.adoc
- scripts/openshiftci-presubmit-e2e.sh
- tests/integration/cmd_app_test.go
- tests/integration/json_test.go
> Run app command test in parallel

- .travis.yml
- Makefile
- docs/development.adoc
- tests/integration/json_test.go
To reduce test time both locally and on CI too.
make test-json-format-output
> Run json format test in parallel

- pkg/odo/cli/component/create.go
Fixes the example link
Closes https://github.com/openshift/odo/issues/1821
> Fix example link

- tests/helper/helper_filesystem.go
> Small typo fix in helper scripts in test

- Makefile
- docs/development.adoc
- tests/integration/cmd_pref_config_test.go
> Run preference and config command test in parallel

- README.adoc
Removed broken links and added adapter links in readme.
fixes https://github.com/openshift/odo/issues/1736
check the readme for the changes
> Removed broken links and added adapter links in readme

- Makefile
- docs/development.adoc
- tests/helper/helper_oc.go
- tests/integration/cmd_link_unlink_test.go
> Run link command test in parallel

- pkg/odo/cli/version/version.go
fixes the incorrect output when a new odo version is available
fixes https://github.com/openshift/odo/issues/1822
download an older version of release from odo's release and that should show the change
> changed config to preference in the new version output

- tests/helper/helper_oc.go
Fixing generic test flake
fixes #1889
> Fix generic test flake

- pkg/component/component.go
- pkg/component/component_test.go
- tests/integration/cmd_app_test.go
- tests/integration/json_test.go
Adds project name to component spec
fixes #1894
```
odo list -o json
odo list --path . -o json
```
> Include project name in component spec

- docs/getting-started.adoc
> Fix broken links in Getting Started guide

- pkg/component/component.go
- pkg/component/types.go
- pkg/odo/cli/component/describe.go
- tests/integration/json_test.go
Adds ports information to `odo describe`
fixes https://github.com/openshift/odo/issues/1481
odo describe -o json
> Add ports information to odo describe

- docs/examples.adoc
Use new wildly s2i repo https://github.com/wildfly/wildfly-s2i/blob/master/README.md
> Update wildfly s2i source location

- tests/e2escenarios/core_beta_flow.go
- tests/integration/cmd_app_test.go
- tests/integration/cmd_storage_test.go
- tests/integration/cmd_watch_test.go
- tests/integration/component.go
- tests/integration/generic_test.go
- tests/integration/login_test.go
- tests/integration/url_test.go
> Fix CmdShouldFail false positive

- docs/development.adoc
Minor updates to docs/developer.adoc to help new odo developers.
No, too minor.
Only doc changes, review developer.adoc
> Added minor notes for new developers.

- .travis.yml
- Makefile
- pkg/odo/cli/component/common_push.go
- pkg/odo/cli/component/push.go
- pkg/odo/cli/version/version.go
- pkg/util/fileIndexer.go
- scripts/openshiftci-presubmit-e2e.sh
- tests/helper/helper_filesystem.go
- tests/integration/cmd_push_test.go
- tests/integration/generic_test.go
fixes #1788 
How to test:
- run `odo push`
- a `odo-file-index.json` will be generate with all the fileNames, sizes and lastModifiedDates
- rerun and check if the build gets started or not
- use `-f` flag to force build
> Implementation of a walker for smart odo push

- docs/cli-reference.adoc
Added a note about GLOBAODOCONFIG in CLI
fixes #1773
> I1773 globalodoconfig docs

- tests/helper/helper_run.go
Add a message like "Running odo with args [odo project create ogotapiklo -w -v4]"
to test output when a command returns an unexpected status code.
No issue, trivial change to make test failures easier to diagnose.
Shut down your test openshift environment and run `make test-cmd-push` to get an error.
> Add message with program and arguments to helper_run.go output

- tests/helper/helper_oc.go
- tests/integration/component.go
https://github.com/openshift/odo/pull/1898#issuecomment-516316166
> Fixing oc describe dc test falke

- pkg/odo/cli/cli.go
see $SUBJECT
No issue
`odo` <- output of this shouldn't change
> removed unnecessary HasAvailableLocalFlag checks from root usage template

- docs/development.adoc
Adds the procedure for setting/unsetting ODO_BOOTSTRAPPER_IMAGE var.
fixes #1311
> odo_bootstrapper_image-docs-small-fixes

- pkg/util/file_indexer.go
resolved a lint error and handled some ignored errors in file_indexer
No issue
just check if the index file is created correctly
> resolved a lint error and handled some ignored errors in file_indexer

- README.adoc
see $SUBJECT
fixes #2005
the readme has the google group
> added the google group in Readme

- tests/benchmark/benchmark_test.go
- tests/helper/reporter/httpMeasurementReporter.go
Adds PR number into the [benchmark results table](https://docs.google.com/spreadsheets/d/1o-GIoYlZoEyW1F25kAwvvEXzbW4tLck0x3EGCC4_L_A/edit#gid=0)
> report PR number to benchmark collector

- OWNERS
- pkg/auth/OWNERS
- pkg/catalog/OWNERS
- pkg/occlient/OWNERS
- pkg/odo/OWNERS
- pkg/secret/OWNERS
- pkg/service/OWNERS
- pkg/util/OWNERS
- site/OWNERS
Adding @dharmit  to @surajnarwade  place 
fixes #2002
> Remove Suraj from OWNERS and replace him with Dharmit

- tests/integration/service_test.go
the test was trying to delete component instead of service
> fix service integration test

- Makefile
- pkg/occlient/occlient.go
- tests/helper/helper_oc.go
- tests/integration/cmd_push_test.go
Updates test so they will work with https://github.com/openshift/odo-supervisord-image/pull/27
all information about this change is in  https://github.com/openshift/odo-supervisord-image/pull/27
> Update test to reflect changes done in odo-supervisord-image#27

- tests/integration/cmd_app_test.go
Typo Fix
No
Check the spelling of ```Successfully``` in file.
> Fix typo in app test file

- tests/integration/cmd_pref_config_test.go
- tests/integration/generic_test.go
- tests/integration/servicecatalog/cmd_service_test.go
fixes #2136
Run ```make test-generic```, ```make test-cmd-pref-config``` and ```make test-cmd-service``` on Win10 platform
> Fixing JustAfterEach error on windows platform

- tests/integration/component.go
fixes #2127 
Run ```make test-cmd-cmp``` on windows platform
> Fix JSON output context path on windows platform

- docs/proposals/odo-debug.md
Proposal for `odo debug` related to #822
> Proposal document: odo debug

- docs/cli-reference.adoc
- pkg/odo/cli/cli.go
Fix the typo in help message
NA
Verify `odo -h` output
> Fix typo to correctly show the purpose of odo

- pkg/occlient/occlient.go
see $SUBJECT
No issue
Comments changed, no difference
> changed all references of odo-supervisord-image to odo-init-image

- docs/development.adoc
Improve the look and feel of integration test portion of the document
No, However when I was going through the unit and integration test doc I found these minor improvements.
Verify it in the doc.
> Improve look and feel of integration test doc

- .travis.yml
- Makefile
- pkg/odo/cli/project/list.go
- pkg/project/project.go
- pkg/project/types.go
- scripts/openshiftci-presubmit-integrationtests.sh
- tests/integration/cmd_project_test.go
fixes #2073 
How to test:
1. Execute `project list` and `project list -o json` and compare speeds with the master branch
> Removes apps from project specs and speeds up the query

- Makefile
Updating Make Comment
No
See the info in Makefile comment
> Fixing wrong info provided for integration test comment

- pkg/occlient/occlient.go
update init-image to 0.13.0 this includes fix https://github.com/openshift/odo-init-image/pull/38
> update init image to 0.13.0

- tests/integration/generic_test.go
- tests/integration/servicecatalog/cmd_service_test.go
Adds tests for odo catalog search failing
Closes https://github.com/openshift/odo/issues/2147
> Add tests for odo catalog search failing

- pkg/odo/cli/debug/portforward.go
$subject
NA
Check output of `odo debug port-forward -h`.
> Fix typo in `odo debug` help output

- pkg/occlient/occlient.go
fixes #2126 
How to test on windows:
1. create a component
2. add a file, push the component
3. delete the file, push and verify if the file is deleted in the container
> Modifies the paths for deletion according to linux containers

- docs/dev/machine-output.md
- pkg/application/application.go
- tests/integration/cmd_app_test.go
Machine readable output for ApplicationList Kind should actually just be
`Kind`.
> Machine output for `odo app list` should be `Kind: List`

- Makefile
Including link and service command test which were somehow misplace 
fixes #2262
make test-cmd-service
make test-cmd-link-unlink
> Include service and link command tests

- pkg/odo/cli/url/create.go
- pkg/odo/cli/url/delete.go
Updates the help usage for odo url create / delete.
Closes https://github.com/openshift/odo/issues/2260
> Updates help for odo url create / delete

- pkg/odo/cli/component/create.go
If the user doesn't opt for advanced options, the ports of the component
remain empty in odo config file. This leads to odo panicking when doing
odo push. This commit fixes that.
fixes #2192 
* Try doing `odo create` for a few different component types. 
* Select 'No' when asked for `Do you wish to set advanced options (y/N)`
* Check output of `odo config view`. Particularly the `Ports` section
I'm not sure how to add tests for interactive mode (cc @kadel @amitkrout)
> Automatically set component's ports in interactive mode

- pkg/project/project.go
- pkg/project/project_test.go
UTs coverage for project create
No
```make test-coverage```
> Adds unit test for project create

- README.adoc
/kind docs
Need to update the current asciinema
Fixes #?
View the asciinema / README :)
> Updates the asciinema tutorial on the README.adoc

- tests/integration/project/cmd_project_test.go
/kind flake
https://github.com/openshift/odo/pull/2356#issuecomment-549794079
CI should not throw project list flake
> Adding sleep to project test flake

- .github/ISSUE_TEMPLATE/Bug.md
- .github/ISSUE_TEMPLATE/Documentation.md
- .github/ISSUE_TEMPLATE/Enhancement.md
/kind cleanup
Cleans up the tmeplates we currently have.
Few things:
- "enhancement" kind does not exist, replaced by "code refactoring"
- minor cleaup of spacing
None, no issue was opened.
Look at the markdown changes :)
> Refactor templates

- Dockerfile.rhel
- pkg/version/version.go
- scripts/installer.sh
- scripts/rpm-prepare.sh
/kind feature
New version of odo (1.0.1)
N/A
N/A
> New release of odo! 1.0.1

- tests/integration/cmd_link_unlink_test.go
/kind test
Verifying the link test with officially supported component
No issue is created for this. While running some test i found it, so directly sending the pr
make test-cmd-link-unlink
> Updating to supported java component test in link test file

- tests/e2escenarios/e2e_beta_test.go
/kind cleanup
Typo fix
Fixes #? No
👀
> Fixing typo in test file

- pkg/component/component.go
- pkg/component/component_test.go
- pkg/config/config.go
- pkg/config/fakeConfig.go
- pkg/odo/cli/url/create.go
- pkg/odo/cli/url/delete.go
- pkg/odo/cli/url/list.go
- pkg/url/types.go
- pkg/url/url.go
- tests/e2escenarios/e2e_beta_test.go
- tests/integration/servicecatalog/cmd_link_unlink_test.go
/kind cleanup
see $SUBJECT
No issue
just internal renaming of variable, tests should pass
> renamed Url to URL to resolve lint warning and consistency

- pkg/odo/cli/component/create.go
- tests/helper/helper_filesystem.go
- tests/integration/component.go
fixes #2282 
How to test:
* create a symlink and try odo create command using it
> Fixes the symlink path for the binary flag

- pkg/util/file_indexer.go
- tests/integration/cmd_push_test.go
Adding odo-file-index.json into .gitignore file
fixes #2223 
make test-cmd-push
> Adding odo file index json to gitignore file

- pkg/component/component.go
- pkg/component/component_test.go
- pkg/config/fakeConfig.go
- pkg/odo/cli/component/describe.go
- pkg/odo/util/cmdutils.go
- tests/integration/component.go
Fixes #2288 
run `odo describe` in non pushed odo component directory
> Fixes odo describe for non pushed components

- pkg/config/config_test.go
https://github.com/openshift/odo/pull/2311/files#r348458747
/kind cleanup
/kind test
It makes the unit tests for deleting odo config directory to be tabular. This is required because we try to follow the tabular approach for our unit tests. There was also bunch of repetitive code in the two tests being executed for the function under test.
Fixes NA but discussed on https://github.com/openshift/odo/pull/2311/files#r348458747
`$ go test github.com/openshift/odo/pkg/config -run ^(TestDeleteConfigDirIfEmpty)$`
> Modify unit tests for deleting odo config dir to be tabular

- README.adoc
/kind docs
Adds a link to our new slack channel
N/A
N/A
> Add link to slack channel

- pkg/catalog/catalog.go
- pkg/occlient/occlient.go
- pkg/occlient/templates.go
/kind bug
This is a combination of https://github.com/openshift/odo/pull/2405 and
the newly updated odo init image PR here: https://github.com/openshift/odo-init-image/pull/43
Fixes #1066
```sh
odo push
```
> Detect component has yet to be built

- Dockerfile.rhel
- pkg/version/version.go
- scripts/bump-version.sh
- scripts/installer.sh
- scripts/rpm-prepare.sh
/kind feature
Releases 1.0.2 + updates the release script
N/A
N/A
> Release 1.0.2

- .github/ISSUE_TEMPLATE/Documentation.md
the label should be documentation not docs
> Update documentation issue template

- pkg/occlient/occlient.go
This mainly helps avoid loop inside a loop and iterating over all items
should be faster than directly seeking the value of a particular key,
no?
NA
Make sure that `odo app list` shows expected output.
> Replace "for" loop with map

- scripts/changelog-script.sh
> /kind bug
Fix up the changelog script by commenting out the summary section since
we do not (yet) summarize releases in issues.
Need to comment this out so the next release goes out smoothly.
N/A
N/A
> Update changelog script

- pkg/odo/genericclioptions/context.go
/kind cleanup
see $SUBJECT
Fixes https://github.com/openshift/odo/issues/1915
add tests should pass
> remove duplicate code from context.go file

- pkg/occlient/occlient.go
/kind cleanup
see $SUBJECT
No issue
Code cleanup
> extracted some common code into a function in occlient for cleanup

- pkg/occlient/occlient.go
/kind feature
Update the odo init image to v1.0.2.
Fixes https://github.com/openshift/odo/issues/2409
> update the odo init image to v1.0.2

- pkg/odo/cli/application/describe.go
- pkg/odo/cli/component/describe.go
/kind cleanup
see $SUBJECT
No issues
odo describe --help shouldn't have `,` in it
> removed , from describe example for app and component

- tests/helper/helper_oc.go
> resolve typo in function comments

- Makefile
path to GITCOMMIT variable in ldflags was incorrect
> fix git commit in odo version

- pkg/occlient/occlient_test.go
/kind bug
More confined Unit test validation in pkg/occlient/occlient_test.go
Fixes NA
```make test``` should pass
> Fixed unit test for GetPVCFromName with extra validation

- Dockerfile.rhel
- pkg/version/version.go
- scripts/installer.sh
- scripts/rpm-prepare.sh
> Bumping version v1.0.3 -> v1.1.0

- tests/examples/source/openjdk/src/main/java/AnotherMessageProducer.java
- tests/helper/helper_oc.go
- tests/integration/cmd_push_test.go
/kind test
Add a test to verify for java component that local file deletions get reflected on the component as well. 
Fixes https://github.com/openshift/odo/issues/2248
The tests should pass
> add test for java component to verify reflection of deleted files

- README.adoc
> Fix README.adoc text about supported versions

- pkg/occlient/occlient.go
- pkg/occlient/occlient_test.go
- pkg/occlient/volumes.go
- pkg/occlient/volumes_test.go
- tests/helper/helper_oc.go
- tests/integration/component.go
This PR deletes storage belonging to a component on component deletion
/kind bug
Fixes storage deletion on `odo delete`
Fixes #2529 
- create a component
- add a storage to it
- delete the component
- push again and check if we face any issues.
> Deletes storage on component deletion

- .travis.yml
king/feature
Run Unit test on macOs
Fixes - Part of #2539 
test should run on macOS in travis CI
> Running Unit test on macOS

- docs/proposals/devfile.md
> /kind design
High-level design and description of [devfile](https://github.com/redhat-developer/devfile/) support in odo.
This is just https://docs.google.com/document/d/16OUCIvuoTPuJfqS32RLNDgJS1ZJ-sY3NDR9ZMP6wQH4/edit# converted into markdwon
Fixes #2290
> add devfile proposal

- OWNERS
Adding  @johnmcollier, @maysunfaisal, @rajivnathan as reviewers.
Are you guys ok with becoming reviewers?
What it means is that you will be able to `/lgtm` PRs.
General info on how reviewers and approvers work can be found at https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#code-review-using-owners-files
> add new reviewers to top level OWNERS

- README.adoc
**What type of PR is this?** 
Inform everyone about our regular calls.
> update README: add info about odo calls

- pkg/component/component.go
- pkg/config/config.go
- pkg/occlient/occlient.go
- pkg/occlient/occlient_test.go
- pkg/odo/cli/url/create.go
- pkg/url/url.go
- pkg/url/url_test.go
- tests/helper/helper_http.go
- tests/helper/odo_utils.go
- tests/integration/cmd_url_test.go
It adds a secure paramater for urls to the config. It indicates if the url is a secure one or not.
/kind feature
It creates a HTTPs secure URL for the component. 
Fixes #2561 
- Create a secure URL `odo url create example --secure`
- check if the URL created is a HTTPs one and is working
> Adds HTTPs support for URL

- tests/helper/helper_run.go
> /kind bug
> /kind design
/kind feature
> /kind flake
added a CmdShouldFail test helper which retries until it fails. This unblocks PR https://github.com/openshift/odo/pull/2491
as discussed here https://github.com/openshift/odo/pull/2491/files#r365660644
No issue
A test helper is added
> added a CmdShouldFail test helper which retries until it fails

- README.adoc
> /kind bug
> /kind design
> /kind flake
Update google groups links for odo.
> Update Google Groups Link

- docs/dev/machine-output.md
- pkg/odo/cli/storage/list.go
- pkg/odo/cli/storage/storage.go
- pkg/odo/util/cmdutils.go
- pkg/storage/storage.go
- pkg/storage/storage_test.go
- pkg/storage/types.go
- tests/integration/cmd_storage_test.go
> /kind bug
> /kind design
> /kind flake
Update storage structure 
`Status.Path moved to Spec.Path`
`State moved to Status`
Fixes #2527 
```
$ odo storage list -o json // should list path under spec.
{                                                         
"kind": "List",                                        …
```
> Update Storage Type

- Dockerfile.rhel
- pkg/version/version.go
- scripts/installer.sh
- scripts/rpm-prepare.sh
> Release 1.1.1 of odo

- scripts/changelog-script.sh
/kind cleanup
Updates the release script to include other kinds / labels that weren't there
N/A
N/A
> Update release script

- docs/dev/development.adoc
Updates the release notes with regards to the changelog script
N/A
N/A
> Updates release notes

- tests/integration/cmd_push_test.go
Some of the hardcoded strings are removed from cmd_push_test.go file and replaced with env variables.
Fixes #2639
- make test-cmd-push should pass
> Fixes hardcoded directory strings with env variables

- pkg/devfile/adapters/common/utils.go
/kind feature
Updates the odo-init-image to 1.1.2
N/A
N/A
> Update bootstrap image to 1.1.2

- OWNERS
/kind cleanup
Removing yusuf from owners
> Remove yusuf from OWNERS file

- README.adoc
- scripts/changelog-script.sh
We need it to keep the docs updated.
NA
> Update documentation links from 4.2 to 4.3

- .travis.yml
/kind feature
Checks the OS version details which is used in travis.
Fixes NA
OS version should get reflected on respective travis jobs.
> OS version details used in travis CI

- OWNERS
- docs/OWNERS
- openshift-ci/build-root/OWNERS
- pkg/catalog/OWNERS
- pkg/debug/OWNERS
- pkg/devfile/OWNERS
- pkg/devfile/adapters/docker/OWNERS
- pkg/lclient/OWNERS
- pkg/odo/cli/catalog/OWNERS
- pkg/odo/cli/service/OWNERS
- pkg/service/OWNERS
- tests/OWNERS
Add more OWNERS files.
Some of the people are focusing more on a specific area of odo I've tried to reflect this.
Everyone is encouraged to open PR and add themself to any OWNERS file, or create a new OWNERS file for directory where there is no OWNERS file yet.
> add more OWNERS files

- pkg/odo/cli/project/project.go
> Remove -q param in odo project command

- Makefile
- docs/dev/development.adoc
/kind feature
Optimize total test time in CI by increasing ginkgo test node
Fixes NA
The test should run parallely on 4 nodes.
> Optimize total test time in CI

- Dockerfile.rhel
- pkg/version/version.go
- scripts/installer.sh
- scripts/rpm-prepare.sh
/kind feature
Releasing odo cli binary with version 1.1.3
Fixes NA
> Odo cli binary release version 1.1.3

- README.md
- chosen-docs/upstream/deploying-a-devfile-using-odo.md
- docs/deploying-a-devfile-using-odo.md
- index.md
[skip ci]
Updates the documentation on the site, adds Devfile documentation as well.
N/A
N/A
> Add Devfile documentation to site

- chosen-docs/upstream/deploying-a-devfile-using-odo.md
Left this in by accident when commiting
> Remove uneeded documentation regarding devfile

- docs/deploying-a-devfile-using-odo.md
Runs the synchronization script between `/docs/chosen-docs` and `/docs`
> Run synchronization script

- pkg/sync/sync.go
- pkg/util/file_indexer.go
> Revert "Update some recursive logs to V(5)"

- _config.yml
- docs/deploying-a-devfile-using-odo.md
- docs/installing-odo.md
- index.md
> Remove capitalization of odo

- Makefile
- docs/dev/development.adoc
/kind feature
Just to revert a plan which went horribly wrong. The plan was, we need to increase the total test node to 4 (Current was 2) to optimize the CI test run time and then fixes the flake if it encounters against each pr. Now there are so many flakes are coming, even its hard to find out the reason for failure (What i suspect 70% test script failure and 30% may be due to limited resource in CI or feature failure). TBH its really frustrating because most of the job has been re triggered due to these unknown flake..
We will still stick to our original plan but plan execution will be in a better way
1. This pr will revert back the changes, i mean we will back to 2 test node.
2. Once this pr goes in, i will …
> Run test on two ginkgo test node

- Dockerfile.rhel
- pkg/version/version.go
- scripts/installer.sh
- scripts/rpm-prepare.sh
/kind feature
Releases 1.2.0 of odo!
N/A
N/A
> Release 1.2.0 of odo

- tests/helper/kubernetes_utils.go
- tests/integration/devfile/cmd_devfile_catalog_test.go
- tests/integration/devfile/cmd_devfile_watch_test.go
/kind bug
It supports parallel test run on kubernetes cluster.
Fixes #2954 
Kubernetes job should pass on travis.
> Fix parallel test run failure for devfile integration test 

- README.adoc
> /kind bug
> /kind design
> /kind flake
>
> [skip ci]
Fixes #?
> Fix naming to match future direction with starting with k8s

- docs/dev/development.adoc
- rpms/openshift-odo.spec
- scripts/rpm-prepare.sh
- Updated rpm spec and rpm-prepare script to template golang version
- Docs now contain a warning about golang version update
/kind feature
> Adding messaging and script updates to ensure smoother golang updates

- scripts/openshiftci-presubmit-integration-tests.sh
/kind cleanup
Currently we have high volume of test running for each pr which consumes almost 3hrs. So the plan here is to distribute the test in different types run. For example in nightly run all the test script will run periodically on master branch over a period of time. The pr test will be validated against integration test only.
Fixes - part of #2931
Each pr will be validated against integration test only on OpenShift CI
> Integration test only for pr validation

- README.md
[skip ci]
Updates the README.md to note that pandoc is required.
Will eventually create a Dockerfile / better script to run all of this.
N/A
N/A
> Update notes regarding pandoc

- docs/dev/machine-output.adoc
- pkg/component/component_full_description.go
- pkg/odo/cli/component/describe.go
- tests/integration/component.go
- created new struct
- structurally similar to component but url is no longer list of strings
but URLList
/kind bug
Fixes #2778 
**Testing**
- Build odo from this 
- Create a component
- do a `odo describe` with and without json output
- add URLs, storages, with various combinations of pushed and unpushed
- try describe again
**NOTE**: Not yet implemented for devfile
> Fixing component description to consider local config and cluster

- pkg/kclient/fake/ingress.go
- pkg/url/url.go
- pkg/url/url_test.go
- tests/integration/devfile/cmd_devfile_push_test.go
- tests/integration/devfile/cmd_devfile_url_test.go
/kind bug
Fixes second push after URL creation 
Fixes #3048 
Fixes #2980 
- create a URL and push two times
- both pushes should pass
> Fixes second push after creating and pushing URL

- pkg/devfile/adapters/common/utils.go
/kind feature
>
> [skip ci]
Updates the bootstrap image to 1.1.3
N/A
N/A
> Update bootstrap odo-init-image to 1.1.3

- docs/installing-odo.md
Synchronization needed for documentation / installation page
> Synchronizes docs to the site

- docs/public/deploying-a-devfile-using-odo.adoc
[skip ci]
Improves the documentation regarding using devfiles.
> fix: improve documentation

- Dockerfile.rhel
- pkg/version/version.go
- scripts/installer.sh
- scripts/rpm-prepare.sh
/kind feature
Releases 1.2.1 of odo
N/A
N/A
> Release 1.2.1 of odo

- pkg/occlient/occlient.go
- pkg/odo/cli/component/create.go
Signed-off-by: adisky <adsharma@redhat.com>
/kind bug
Do not execute  S2I related code on k8s cluster for .`odo component create` 
Fixes  #2888 
> Fix odo fake component create on kubernetes cluster

- OWNERS
Adding @mik-dass and @dharmit  as top-level approves
[skip-ci]
> add mik-dass and dharmit as top level approvers

- pkg/devfile/adapters/common/command.go
- pkg/devfile/adapters/common/command_test.go
- pkg/devfile/adapters/common/utils.go
- pkg/devfile/adapters/kubernetes/component/adapter.go
- pkg/devfile/parser/data/common/types.go
- pkg/exec/devfile.go
Fixes command.go for parser v2
**Note: for branch parser-v2**
> V2 command

- pkg/devfile/adapters/common/command.go
update common adapter to use groups
**NOTE : PR for parser-v2 branch**
> Update Command Logic to use groups

- pkg/odo/cli/component/create.go
Updates the create logic to use v2 based common
> Updates create logic to v2

- docs/public/debugging-using-devfile.adoc
[skip ci]
This adds a document for debugging applications using devfiles.
Fixes NA
> Adds a document for debugging applications using devfiles

- pkg/devfile/adapters/common/command.go
- pkg/devfile/adapters/common/utils.go
- pkg/devfile/parser/data/2.0.0/components.go
Update logs as per v2, and fix interface implementation
Fixes #?
> Updated Logs for V2 and Fix Interface Implementation

- pkg/devfile/adapters/docker/utils/utils.go
- pkg/devfile/adapters/kubernetes/utils/utils.go
- pkg/devfile/parser/data/1.0.0/components.go
- pkg/devfile/parser/data/1.0.0/types.go
- pkg/devfile/parser/data/common/types.go
- pkg/exec/devfile.go
- pkg/odo/cli/component/create.go
- pkg/sync/adapter.go
While converting v1 structs to v2, to avoid potential null pointer errors while dereferencing string pointers. Updated struct fields to use strings.
**NOTE: PR for parser-v2 branch**
> Avoid Using String Pointers

- pkg/devfile/parser/data/1.0.0/components.go
Fixes upper and lower case for devfile commands.
> Fixes lower and upper case for commands

- pkg/devfile/parser/data/1.0.0/components.go
- pkg/devfile/parser/data/2.0.0/types.go
- pkg/devfile/validate/components.go
- pkg/odo/cli/component/create.go
Fixes type of project and components for v1
> Fixes type of project and components for devfile v1

- pkg/devfile/adapters/common/command.go
- pkg/devfile/adapters/common/command_test.go
- pkg/devfile/adapters/common/utils.go
- pkg/devfile/adapters/common/utils_test.go
- pkg/devfile/adapters/docker/component/utils.go
- pkg/devfile/adapters/docker/utils/utils.go
- pkg/devfile/adapters/kubernetes/component/adapter_test.go
- pkg/devfile/adapters/kubernetes/utils/utils.go
- pkg/devfile/parser/data/1.0.0/components.go
- pkg/devfile/parser/data/common/types.go
- pkg/devfile/parser/writer_test.go
- pkg/devfile/validate/components_test.go
- pkg/testingutil/devfile.go
- vendor/k8s.io/api/go.sum
Fixes # fixing unit tests of adpaters/common after update to devfile V2
**NOTE: PR for parser-v2 branch**
> Update testing utils

- pkg/devfile/adapters/common/command.go
- pkg/devfile/adapters/common/types.go
- pkg/devfile/adapters/common/utils.go
- pkg/devfile/adapters/docker/component/utils.go
- pkg/devfile/adapters/docker/storage/utils.go
- pkg/devfile/adapters/docker/utils/utils.go
- pkg/devfile/adapters/kubernetes/component/adapter.go
- pkg/devfile/adapters/kubernetes/storage/utils.go
- pkg/devfile/adapters/kubernetes/utils/utils.go
- pkg/devfile/parser/data/1.0.0/components.go
- pkg/devfile/parser/data/common/types.go
- pkg/kclient/generators.go
- pkg/kclient/volumes.go
- tests/integration/devfile/utils/utils.go
Fixes #?
**Note: PR for parser-v2 branch**
> Fix Integration tests for devfile v2

- pkg/devfile/adapters/docker/component/adapter_test.go
- pkg/devfile/adapters/docker/component/utils_test.go
- pkg/devfile/adapters/docker/storage/adapter_test.go
- pkg/devfile/adapters/docker/storage/utils_test.go
- pkg/devfile/adapters/docker/utils/utils_test.go
- pkg/devfile/adapters/helper_test.go
- pkg/devfile/adapters/kubernetes/storage/utils_test.go
- pkg/devfile/adapters/kubernetes/utils/utils_test.go
- pkg/devfile/validate/components_test.go
- pkg/kclient/volumes_test.go
- pkg/sync/adapter_test.go
- pkg/testingutil/devfile.go
> Fixes unit tests

- docs/dev/development.adoc
[skip ci]
Fixes #3213 
Verify manually the doc changes.
> Run test locally against 4.* Cluster

- pkg/devfile/parser/data/1.0.0/components.go
- pkg/devfile/parser/data/1.0.0/types.go
- pkg/odo/cli/component/create.go
fix regression caused by rebase to master.
Also add github, zip as supported project types.
Fixes #?
**for parser-v2 branch**
> Fix regression by sparse checkout dir PR on devfile V2

- pkg/devfile/adapters/common/command.go
- pkg/devfile/adapters/common/types.go
- pkg/devfile/adapters/kubernetes/component/adapter.go
- pkg/devfile/parser/data/common/types.go
Address review comments for devfile V2 PR. 
Fixes #?
**NOTE: for parser-v2 branch**
> Address review comments for devfile V2 PR

- pkg/devfile/adapters/common/command.go
- pkg/devfile/adapters/common/command_test.go
- pkg/devfile/adapters/common/utils_test.go
- pkg/devfile/adapters/docker/storage/utils.go
- pkg/devfile/parser/data/1.0.0/components.go
- pkg/devfile/validate/components.go
- tests/integration/devfile/utils/utils.go
Fixes #?
**NOTE: PR for parser-v2 branch**
> Address review comments for devfile V2 PR: Part 2

- Dockerfile.rhel
- pkg/version/version.go
- scripts/installer.sh
- scripts/rpm-prepare.sh
/kind feature
Releases 1.2.1 of odo
N/A
N/A
> Release 1.2.2 of odo

- pkg/url/url.go
- tests/integration/cmd_url_test.go
/kind bug
Fixes list and describe of secure URLs for not pushed components
Fixes #3060 
```
odo url create example --secure
odo url list                   // secure should be true for the not pushed URL
odo url list -o json       // secure should be true for the not pushed URL
odo describe -o json   // secure should be true for the not pushed URL
odo push
odo url list                     // secure should be true for the pushed URL
odo url list -o json         // secure should be true for the pushed URL
odo describe -o json     // secure should be true for the pushed URL
```
> Fixes list and describe of secure URLs for not pushed components

- pkg/odo/cli/component/watch.go
- tests/integration/cmd_watch_test.go
/kind bug
`odo watch --app adsf` failed to find adsf is invalid
Fixes #2883 
> return error if app not found

- openshift-ci/build-root/Dockerfile
/kind feature
Add oc binary to bin path for multi stage testing
Fixes NA
👀
> Adding oc to bin path for multistage testing

- openshift-ci/build-root/Dockerfile
> Revert "Adding oc to bin path for multistage testing"

- tests/integration/generic_test.go
/kind bug
Correct the regex to match all possible kinds of Server URL
Fixes #3325 
> Fix 'odo version' integration test.

- pkg/odo/cli/application/describe.go
- tests/integration/cmd_app_test.go
/kind bug
Fixes #3348
`odo app describe t --project myproject` can be used to do test
> Validate application exist before describe it

- pkg/devfile/adapters/docker/component/adapter_test.go
- pkg/devfile/adapters/docker/component/utils_test.go
- pkg/devfile/adapters/docker/storage/adapter_test.go
- pkg/devfile/adapters/docker/utils/utils_test.go
- pkg/devfile/adapters/helper_test.go
- pkg/devfile/parser/data/2.0.0/devfileJsonSchema200.go
- pkg/devfile/parser/data/2.0.0/types.go
- pkg/devfile/parser/data/common/types.go
- pkg/devfile/validate/components_test.go
- pkg/sync/adapter_test.go
It updates the v2 schema  to the latest : https://github.com/devfile/kubernetes-api/blob/master/schemas/devfile.json
Fixes: NA
Required for adding parent support
Tests should pass.
> Updates the v2 schema to the latest

- tests/helper/helper_oc.go
- tests/integration/generic_test.go
Fixes #3342
/kind bug
See related issue.
Fixes #3342
> fix: properly check that odo version contains the server URL

- scripts/openshiftci-periodic-tests.sh
/kind feature
https://github.com/openshift/release/pull/9427#discussion_r441493057
Fixes NA
Current test structure in CI should pass
> Create periodic script for odo periodic job

- tests/e2escenarios/e2e_images_test.go
/kind feature
Added few supported container images to e2e image test. See list supported container images in https://github.com/openshift/odo-init-image/blob/master/language-scripts/image-mappings.json 
Fixes NA, I am sending the pr directly.
```make test-e2e-images```
> Added few supported container images to e2e image test

- pkg/devfile/adapters/common/command.go
- pkg/devfile/adapters/docker/component/utils.go
- pkg/devfile/adapters/docker/storage/utils.go
- pkg/devfile/adapters/kubernetes/component/adapter.go
- pkg/devfile/adapters/kubernetes/storage/utils.go
- pkg/devfile/adapters/kubernetes/utils/utils.go
/kind cleanup
Updates the devfile log level from 3 to 4 to be consistent with the rest of the code base
N/A
`odo push -v 4` should show more logs now
> Update devfile log levels from 3 to 4 to be consistent

- openshift-ci/build-root/multistage/Dockerfile
/kind feature
Updating script path in Dockerfile for multistage migration without breaking master.
Fixes NA
Multistage migration pr https://github.com/openshift/release/pull/9431 in release repo should pass
> Updating script path in Dockerfile for multistage test

- Dockerfile.rhel
- pkg/version/version.go
- scripts/rpm-prepare.sh
/kind feature
Release 1.2.3 of odo
N/A
N/A
> Release 1.2.3

- tests/helper/helper_generic.go
- tests/helper/helper_kubectl.go
- tests/helper/helper_oc.go
> fix 'Timeout out' typo and fix formatting

- pkg/catalog/types.go
- pkg/machineoutput/services.go
- pkg/machineoutput/types.go
- pkg/odo/cli/catalog/util/util.go
- pkg/odo/cli/catalog/util/util_test.go
- pkg/service/service.go
- pkg/service/types.go
- pkg/url/types.go
- tests/integration/servicecatalog/cmd_service_test.go
> Corrected 'List' type struct definitions

- pkg/odo/cli/service/list.go
- tests/integration/operatorhub/cmd_service_test.go
/kind bug
Fixes #3241 
odo service list -o json
> Add odo service list -o json message

- pkg/debug/info_test.go
- pkg/devfile/parser/data/2.0.0/types.go
- pkg/devfile/parser/data/common/types.go
- pkg/kclient/deployments.go
- pkg/odo/cli/debug/portforward.go
- pkg/odo/cli/url/describe.go
- pkg/project/types.go
- pkg/storage/types.go
- pkg/testingutil/deployments.go
- pkg/url/url.go
- pkg/util/concurrent.go
- pkg/util/util.go
- pkg/util/util_test.go
- tests/integration/cmd_debug_test.go
- tests/integration/devfile/cmd_devfile_debug_test.go
- tests/integration/devfile/docker/cmd_docker_devfile_url_test.go
/kind cleanup
see $SUBJECT
No issue
tests should pass - there is no code change in the PR, just code comments changed.
> resolved some incorrect comments

- docs/community.md
- docs/creating-an-application-with-a-database.md
- docs/deploying-a-devfile-using-odo.md
- docs/odo-cli-reference.md
Synchronize the documentation from master to gh-pages
> Synchronize documentation

- pkg/odo/cli/component/common_push.go
- pkg/sync/adapter.go
- pkg/util/file_indexer.go
/kind bug
Fixes #2728 
**How to test changes **:
follow the way describe in the bug #2728
> Make write odo-file-index.json after push success

- pkg/kclient/operators.go
- pkg/odo/cli/catalog/search/service.go
- pkg/odo/cli/catalog/util/util.go
- tests/integration/operatorhub/cmd_service_test.go
Fixes #3355
`odo catalog search service <>`
> catalog search service honor experiment flag

- .github/PULL_REQUEST_TEMPLATE.md
[skip ci]
New field added for pr acceptance criteria
Fixes NA
👀
> PR acceptance criteria template
